Fixed bugs.
* clang/jamfile:
Fixed bugs.

* icu4c/jamfile:
Added save of `objdir` for ICU4C in case of build failure.

* template/x86_64-unknown-linux-gnu/clang++-wrapper:
From Clang 3.2, the name of compiler front-end binaries has been
prefixed by arch triplet (e.g. `x86_64-unknown-linux-gnu-clang++`).
Added support of that change.

* template/x86_64-unknown-linux-gnu/clang-wrapper:
Likewise.

diff --git a/clang/jamfile b/clang/jamfile
--- a/clang/jamfile
+++ b/clang/jamfile
@@ -712,14 +712,14 @@ actions make-install
   mkdir -p '$(INCLUDEDIR)' || exit 1
 
   if [ '$(BINDIR)' != '$(COMPILER_PREFIX)/bin' ]; then
-    ( cd '$(COMPILER_PREFIX)/bin' && find . -mindepth 1 -maxdepth 1 -newer before-make-install -execdir [ '{}' -ot after-make-install ] \; -execdir mv '{}' '$(BINDIR)' \; ) || exit 1
+    ( cd '$(COMPILER_PREFIX)/bin' && find . -mindepth 1 -maxdepth 1 -newer before-make-install -execdir [ '{}' -ot after-make-install ] \; -execdir mv -f '{}' '$(BINDIR)' \; ) || exit 1
   fi
   if [ '$(LIBDIR)' != '$(COMPILER_PREFIX)/lib' ]; then
-    ( cd '$(COMPILER_PREFIX)/lib' && find . -mindepth 1 -maxdepth 1 -newer before-make-install -execdir [ '{}' -ot after-make-install ] \; -execdir mv '{}' '$(LIBDIR)' \; ) || exit 1
+    ( cd '$(COMPILER_PREFIX)/lib' && find . -mindepth 1 -maxdepth 1 -newer before-make-install -execdir [ '{}' -ot after-make-install ] \; -execdir mv -f '{}' '$(LIBDIR)' \; ) || exit 1
     ( cd '$(COMPILER_PREFIX)/lib' && ln -sfT '$(LIBDIR)/clang' clang ) || exit 1
   fi
   if [ '$(INCLUDEDIR)' != '$(COMPILER_PREFIX)/include' ]; then
-    ( cd '$(COMPILER_PREFIX)/include' && find . -mindepth 1 -maxdepth 1 -newer before-make-install -execdir [ '{}' -ot after-make-install ] \; -execdir mv '{}' '$(INCLUDEDIR)' \; ) || exit 1
+    ( cd '$(COMPILER_PREFIX)/include' && find . -mindepth 1 -maxdepth 1 -newer before-make-install -execdir [ '{}' -ot after-make-install ] \; -execdir mv -f '{}' '$(INCLUDEDIR)' \; ) || exit 1
   fi
 
   rm -f '$(COMPILER_PREFIX)/bin/before-make-install' '$(COMPILER_PREFIX)/bin/after-make-install' || exit 1
@@ -729,22 +729,22 @@ actions make-install
   # LLVM gold plugin should be placed in `lib'.
   ( cd '$(COMPILER_PREFIX)/lib' && ln -sf '$(LIBDIR)/LLVMgold.so' . )
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to create a symlink to `LLVMgold.so' in `lib' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to create a symlink to `LLVMgold.so' in `lib' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." | $(AWACS)
+    echo    "ERROR: failed to create a symlink to \`LLVMgold.so' in \`lib' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to create a symlink to \`LLVMgold.so' in \`lib' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
   # LLVM plugin for binutils tools (`ar' and `nm'). See http://llvm.org/docs/GoldPlugin.html.
   ( cd '$(COMPILER_PREFIX)/lib' && mkdir -p bfd-plugins )
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to create `bfd-plugins' subdirectory in `lib' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to create `bfd-plugins' subdirectory in `lib' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." | $(AWACS)
+    echo    "ERROR: failed to create \`bfd-plugins' subdirectory in \`lib' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to create \`bfd-plugins' subdirectory in \`lib' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
   ( cd '$(COMPILER_PREFIX)/lib/bfd-plugins' && ln -sf '$(LIBDIR)/LLVMgold.so' . )
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to create a symlink to `LLVMgold.so' in `lib/bfd-plugins' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to create a symlink to `LLVMgold.so' in `lib/bfd-plugins' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." | $(AWACS)
+    echo    "ERROR: failed to create a symlink to \`LLVMgold.so' in \`lib/bfd-plugins' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to create a symlink to \`LLVMgold.so' in \`lib/bfd-plugins' for LLVM & Clang $version ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
diff --git a/icu4c/jamfile b/icu4c/jamfile
--- a/icu4c/jamfile
+++ b/icu4c/jamfile
@@ -332,8 +332,9 @@ actions make-install
     ( cd '$(OBJDIR)' && '$(SRCDIR)/source/runConfigureICU' $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
+    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
+    echo    "ERROR:$$: failed to \`runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR:$$: failed to \`runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -346,8 +347,9 @@ actions make-install
     ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
+    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
+    echo    "ERROR:$$: failed to \`make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR:$$: failed to \`make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -363,8 +365,9 @@ actions make-install
       echo    "WARNING: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
       echo -n "WARNING: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     else
-      echo    "ERROR: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-      echo -n "ERROR: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
+      mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
+      echo    "ERROR:$$: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+      echo -n "ERROR:$$: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
       exit 1
     fi
   fi
@@ -375,8 +378,9 @@ actions make-install
     ( cd '$(OBJDIR)' && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
+    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
+    echo    "ERROR:$$: failed to \`make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR:$$: failed to \`make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
diff --git a/template/x86_64-unknown-linux-gnu/clang++-wrapper b/template/x86_64-unknown-linux-gnu/clang++-wrapper
--- a/template/x86_64-unknown-linux-gnu/clang++-wrapper
+++ b/template/x86_64-unknown-linux-gnu/clang++-wrapper
@@ -65,21 +65,25 @@ if [ ! -x "${bindir}/gcc" ]; then
   exit 1
 fi
 
-if [ ! -x "${bindir}/clang++" ]; then
-  echo "${0}: error: \`${bindir}/clang++': not found" 1>&2
-  exit 1
+if [ -x "${bindir}/clang++" ]; then
+    compiler_path="${bindir}/clang++"
+elif [ -x "${bindir}/x86_64-unknown-linux-gnu-clang++" ]; then
+    compiler_path="${bindir}/x86_64-unknown-linux-gnu-clang++"
+else
+    echo "${0}: error: \`clang++': not found" 1>&2
+    exit 1
 fi
 
 ulimit -S -t 300
 ulimit -S -m 2097152
 
 if [ ${is_link} -eq 0 ]; then
-    exec "${bindir}/clang++" "$@"
+    exec "$compiler_path" "$@"
 elif [ ${is_link} -eq 1 ]; then
     if [ ${bits} -eq 64 ]; then
-	exec "${bindir}/clang++" "$@" -Wl,"-rpath=${prefix}/lib64" -Wl,"-rpath=${prefix}/lib" -Wl,--enable-new-dtags
+	exec "$compiler_path" "$@" -Wl,"-rpath=${prefix}/lib64" -Wl,"-rpath=${prefix}/lib" -Wl,--enable-new-dtags
     elif [ ${bits} -eq 32 ]; then
-	exec "${bindir}/clang++" "$@" -Wl,"-rpath=${prefix}/lib32" -Wl,"-rpath=${prefix}/lib" -Wl,--enable-new-dtags
+	exec "$compiler_path" "$@" -Wl,"-rpath=${prefix}/lib32" -Wl,"-rpath=${prefix}/lib" -Wl,--enable-new-dtags
     else
 	echo "${0}: error: an internal error" 1>&2
 	exit 1
