Fixed messages, and fixed configure options on Cygwin.

diff --git a/clang/jamfile b/clang/jamfile
--- a/clang/jamfile
+++ b/clang/jamfile
@@ -119,7 +119,9 @@ rule make-clang ( targets * : sources * : properties * )
     OPTIONS on $(targets) += "--with-c-include-dirs=\"$(PREFIX)/$(gcc)/lib/gcc/$(triplet)/$(gcc)/include:/usr/local/include:$(PREFIX)/$(gcc)/include:$(PREFIX)/$(gcc)/lib/gcc/$(triplet)/$(gcc)/include-fixed:/usr/include\"" ;
     OPTIONS on $(targets) += "--with-cxx-include-root=\"$(PREFIX)/$(gcc)/include/c++/$(gcc)\"" ;
     OPTIONS on $(targets) += --with-cxx-include-arch=$(triplet) ;
-    OPTIONS on $(targets) += --with-cxx-include-32bit-dir=32 ;
+    if $(triplet) = x86_64-unknown-linux-gnu || $(triplet) = x86_64-w64-mingw32 {
+      OPTIONS on $(targets) += --with-cxx-include-32bit-dir=32 ;
+    }
   }
 
   OPTIONS on $(targets) += CC="\"$(PREFIX)/$(gcc)/bin/gcc\"" ;
@@ -127,15 +129,12 @@ rule make-clang ( targets * : sources * : properties * )
   OPTIONS on $(targets) += CXX="\"$(PREFIX)/$(gcc)/bin/g++\"" ;
 
   SET_RUN_VARS on $(targets) = ;
-  UNSET_RUN_VARS on $(targets) = ;
   if $(gcc) != $(GCC_BUILTIN) {
     if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
-      SET_RUN_VARS on $(targets) = "OLD_PATH=\"$PATH\"; PATH=\"$(PREFIX)/$(gcc)/bin:$PATH\"; export PATH" ;
-      UNSET_RUN_VARS on $(targets) = "PATH=\"$OLD_PATH\"; export PATH; unset OLD_PATH" ;
+      SET_RUN_VARS on $(targets) = "OLD_PATH=\"$PATH\"; PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"; export PATH" ;
     }
     else {
-      SET_RUN_VARS on $(targets) = "OLD_LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\"; LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib:$LD_LIBRARY_PATH\"; export LD_LIBRARY_PATH" ;
-      UNSET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$OLD_LD_LIBRARY_PATH\"; export LD_LIBRARY_PATH; unset OLD_LD_LIBRARY_PATH" ;
+      SET_RUN_VARS on $(targets) = "OLD_LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\"; LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
     }
   }
 
@@ -161,7 +160,10 @@ actions make-clang
   if [ ! -d "$(LLVM_DIR)" ]; then
     ( cd "$(INTRO_ROOT_DIR)" && svn checkout http://llvm.org/svn/llvm-project/llvm/trunk llvm )
     if [ $? -ne 0 ]; then
-      ( cd "$(INTRO_ROOT_DIR)" && rm -rf llvm )
+      if [ -d "$(LLVM_DIR)" ]; then
+        ( cd "$(LLVM_DIR)" && rm -rf * ) || exit $?
+        rmdir "$(LLVM_DIR)" || exit $?
+      fi
       echo "ERROR: failed to 'svn checkout' the LLVM repository." 1>&2
       /bin/echo -n "ERROR: failed to 'svn checkout' the LLVM repository." | $(AWACS)
       exit 1
@@ -174,7 +176,10 @@ actions make-clang
   if [ ! -d "$(CLANG_DIR)" ]; then
     ( cd "$(INTRO_ROOT_DIR)/llvm/tools" && svn checkout http://llvm.org/svn/llvm-project/cfe/trunk clang )
     if [ $? -ne 0 ]; then
-      ( cd "$(INTRO_ROOT_DIR)/llvm/tools" && rm -rf clang )
+      if [ -d "$(CLANG_DIR)" ]; then
+        ( cd "$(CLANG_DIR)" && rm -rf * )
+        rmdir "$(CLANG_DIR)"
+      fi
       echo "ERROR: failed to 'svn checkout' the Clang repository." 1>&2
       /bin/echo -n "ERROR: failed to 'svn checkout' the Clang repository." | $(AWACS)
       exit 1
@@ -199,42 +204,36 @@ actions make-clang
   $(SET_RUN_VARS)
   ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
     echo "ERROR: failed to 'configure' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
     /bin/echo -n "ERROR: failed to 'configure' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || { $(UNSET_RUN_VARS); exit 1; }
+  [ -f "$(<:D)/build/Makefile" ] || exit $?
   ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
     echo "ERROR: failed to 'make' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
     /bin/echo -n "ERROR: failed to 'make' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)/build" && make check )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
     echo "WARNING: failed to 'make check' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
     /bin/echo -n "WARNING: failed to 'make check' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
   fi
   ( cd "$(<:D)/build" && make install )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
     echo "ERROR: failed to 'make install' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
     /bin/echo -n "ERROR: failed to 'make install' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)/build" && rm -rf * )
-  $(UNSET_RUN_VARS)
   cp -f "$(CLANGPP_WRAPPER)" "$(CLANGPP_TLIMIT)" "$(VERSION_PREFIX)/bin"
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to create the wrapper script for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to create the wrapper script for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to create wrapper scripts for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to create wrapper scripts for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  chmod +x "$(VERSION_PREFIX)/bin/clang++-wrapper" || exit $?
-  chmod +x "$(VERSION_PREFIX)/bin/clang++-tlimit" || exit $?
+  chmod +x "$(VERSION_PREFIX)/bin/clang++-wrapper" "$(VERSION_PREFIX)/bin/clang++-tlimit" || exit $?
   [ -e "$(<)" ] && exit 1
   /bin/echo -n "LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
   touch "$(<)"
diff --git a/gmp/jamfile b/gmp/jamfile
--- a/gmp/jamfile
+++ b/gmp/jamfile
@@ -90,8 +90,12 @@ actions download-gmp
 {
   rm -f "$(<)" || exit $?
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
-    ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' ) \
-      || { echo "ERROR: failed to download the GMP tarball." 1>&2; exit 1; }
+    ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' )
+    if [ $? -ne 0 ]; then
+      echo "ERROR: failed to download the GMP tarball." 1>&2
+      /bin/echo -n "ERROR: failed to download the GMP tarball." | $(AWACS)
+      exit 1
+    fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
   fi
   [ -e "$(<)" ] && exit 1
@@ -139,7 +143,12 @@ actions expand-gmp
   rm -f "$(<)" || exit $?
   [ -f "$(>)" ] || exit $?
   if [ ! -x "$(DEST_DIR)/configure" ]; then
-    rm -rf "$(DEST_DIR)" || exit $?
+    if [ -f "$(DEST_DIR)" ]; then
+      rm -f "$(DEST_DIR)" || exit $?
+    elif [ -d "$(DEST_DIR)" ]; then
+      ( cd "$(DEST_DIR)" && rm -rf * ) || exit $?
+      rmdir "$(DEST_DIR)" || exit $?
+    fi
     if [ -f "$(TARBALL_GZ)" ]; then
       tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
         || { echo "ERROR: failed to expand the GMP tarball." 1>&2; exit 1; }
@@ -188,6 +197,7 @@ rule make-gmp ( targets * : sources * : properties * )
   OPTIONS on $(targets) = ;
 
   local version = [ feature.get-values <gmp> : $(properties) ] ;
+  VERSION on $(targets) = $(version) ;
 
   # Set the path to the 'configure' file.
   local configure = $(INTRO_ROOT_DIR)/gmp-$(version)/configure ;
@@ -201,6 +211,7 @@ rule make-gmp ( targets * : sources * : properties * )
 
   # Set the '--prefix' option for the 'configure' script.
   local gcc-raw = [ feature.get-values <gcc> : $(properties) ] ;
+  GCC_RAW on $(targets) = $(gcc-raw) ;
   local gcc = [ regex.replace "$(gcc-raw)" "-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]" ".0" ] ;
   OPTIONS on $(targets) += --prefix=\"$(PREFIX)/$(gcc)\" ;
 
@@ -218,21 +229,11 @@ rule make-gmp ( targets * : sources * : properties * )
   OPTIONS on $(targets) += CXX=\"$(PREFIX)/$(gcc)/bin/g++\" ;
 
   SET_RUN_VARS on $(targets) = ;
-  UNSET_RUN_VARS on $(targets) = ;
   if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
-    SET_RUN_VARS on $(targets) = "OLD_PATH=\"$PATH\"; PATH=\"$(PREFIX)/$(gcc)/bin:$PATH\"; export PATH" ;
-    UNSET_RUN_VARS on $(targets) = "PATH=\"$OLD_PATH\"; export PATH; unset OLD_PATH" ;
+    SET_RUN_VARS on $(targets) = "OLD_PATH=\"$PATH\"; PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"; export PATH" ;
   }
   else {
-    SET_RUN_VARS on $(targets) = "OLD_LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\"; LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib:$LD_LIBRARY_PATH\"; export LD_LIBRARY_PATH" ;
-    UNSET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$OLD_LD_LIBRARY_PATH\"; export LD_LIBRARY_PATH; unset OLD_LD_LIBRARY_PATH" ;
-  }
-
-  AWACS_ON_SUCCESS on $(targets) = ;
-  AWACS_ON_FAILURE on $(targets) = ;
-  if $(AWACS) {
-    AWACS_ON_SUCCESS on $(targets) = "/bin/echo -n \"GMP $(version) ($(triplet)-gcc-$(gcc-raw)) was successfully built.\" | $(AWACS)" ;
-    AWACS_ON_FAILURE on $(targets) = "/bin/echo -n \"GMP $(version) ($(triplet)-gcc-$(gcc-raw)) failed to build.\" | $(AWACS)" ;
+    SET_RUN_VARS on $(targets) = "OLD_LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\"; LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
   }
 }
 actions make-gmp
@@ -244,37 +245,32 @@ actions make-gmp
   $(SET_RUN_VARS)
   ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
-    echo "ERROR: failed to 'configure' for the GMP build." 1>&2
-    $(AWACS_ON_FAILURE)
+    echo "ERROR: failed to 'configure' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to 'configure' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || { $(UNSET_RUN_VARS); exit 1; }
+  [ -f "$(<:D)/build/Makefile" ] || exit $?
   ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
-    echo "ERROR: failed to 'make' for the GMP build." 1>&2
-    $(AWACS_ON_FAILURE)
+    echo "ERROR: failed to 'make' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to 'make' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
-    echo "ERROR: failed to 'make check' for the GMP build." 1>&2
-    $(AWACS_ON_FAILURE)
+    echo "ERROR: failed to 'make check' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to 'make check' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)/build" && make install )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
-    echo "ERROR: failed to 'make install' for the GMP build." 1>&2
-    $(AWACS_ON_FAILURE)
+    echo "ERROR: failed to 'make install' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to 'make install' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)/build" && rm -rf * )
-  $(UNSET_RUN_VARS)
+  /bin/echo -n "GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
-  $(AWACS_ON_SUCCESS)
   touch "$(<)"
 }
 
diff --git a/openmpi/jamfile b/openmpi/jamfile
--- a/openmpi/jamfile
+++ b/openmpi/jamfile
@@ -11,7 +11,7 @@ rule assert-specified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) = unspecified {
-    errors.error $(feature) is not specified for the OpenMPI build. ;
+    errors.error $(feature) is not specified for the Open MPI build. ;
   }
 }
 
@@ -19,7 +19,7 @@ rule assert-unspecified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) != unspecified {
-    errors.error $(feature) is not valid for the OpenMPI build. ;
+    errors.error $(feature) is not valid for the Open MPI build. ;
   }
 }
 
@@ -94,8 +94,12 @@ actions download-openmpi
 {
   rm -f "$(<)" || exit $?
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
-    ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' ) \
-      || { echo "ERROR: failed to download the OpenMPI tarball." 1>&2; exit 1; }
+    ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' )
+    if [ $? -ne 0 ]; then
+      echo "ERROR: failed to download the Open MPI tarball." 1>&2
+      /bin/echo -n "ERROR: failed to download the Open MPI tarball." | $(AWACS)
+      exit 1
+    fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
   fi
   [ -e "$(<)" ] && exit 1
@@ -143,13 +147,18 @@ actions expand-openmpi
   rm -f "$(<)" || exit $?
   [ -f "$(>)" ] || exit $?
   if [ ! -x "$(DEST_DIR)/configure" ]; then
-    rm -rf "$(DEST_DIR)" || exit $?
+    if [ -f "$(DEST_DIR)" ]; then
+      rm -f "$(DEST_DIR)" || exit $?
+    elif [ -d "$(DEST_DIR)" ]; then
+      ( cd "$(DEST_DIR)" && rm -rf * ) || exit $?
+      rmdir "$(DEST_DIR)" || exit $?
+    fi
     if [ -f "$(TARBALL_GZ)" ]; then
       tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the OpenMPI tarball." 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the Open MPI tarball." 1>&2; exit 1; }
     elif [ -f "$(TARBALL_BZ2)" ]; then
       tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the OpenMPI tarball." 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the Open MPI tarball." 1>&2; exit 1; }
     else
       exit 1
     fi
@@ -192,6 +201,7 @@ rule make-openmpi ( targets * : sources * : properties * )
   OPTIONS on $(targets) = ;
 
   local version = [ feature.get-values <openmpi> : $(properties) ] ;
+  VERSION on $(targets) = $(version) ;
 
   # Set the path to the 'configure' file.
   local configure = $(INTRO_ROOT_DIR)/openmpi-$(version)/configure ;
@@ -205,6 +215,7 @@ rule make-openmpi ( targets * : sources * : properties * )
 
   # Set the '--prefix' option for the 'configure' script.
   local gcc-raw = [ feature.get-values <gcc> : $(properties) ] ;
+  GCC_RAW on $(targets) = $(gcc-raw) ;
   local gcc = [ regex.replace "$(gcc-raw)" "-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]" ".0" ] ;
   OPTIONS on $(targets) += --prefix=\"$(PREFIX)/$(gcc)\" ;
 
@@ -222,21 +233,11 @@ rule make-openmpi ( targets * : sources * : properties * )
   OPTIONS on $(targets) += CXX=\"$(PREFIX)/$(gcc)/bin/g++\" ;
 
   SET_RUN_VARS on $(targets) = ;
-  UNSET_RUN_VARS on $(targets) = ;
   if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
-    SET_RUN_VARS on $(targets) = "OLD_PATH=\"$PATH\"; PATH=\"$(PREFIX)/$(gcc)/bin:$PATH\"; export PATH" ;
-    UNSET_RUN_VARS on $(targets) = "PATH=\"$OLD_PATH\"; export PATH; unset OLD_PATH" ;
+    SET_RUN_VARS on $(targets) = "OLD_PATH=\"$PATH\"; PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"; export PATH" ;
   }
   else {
-    SET_RUN_VARS on $(targets) = "OLD_LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\"; LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib:$LD_LIBRARY_PATH\"; export LD_LIBRARY_PATH" ;
-    UNSET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$OLD_LD_LIBRARY_PATH\"; export LD_LIBRARY_PATH; unset OLD_LD_LIBRARY_PATH" ;
-  }
-
-  AWACS_ON_SUCCESS on $(targets) = ;
-  AWACS_ON_FAILURE on $(targets) = ;
-  if $(AWACS) {
-    AWACS_ON_SUCCESS on $(targets) = "/bin/echo -n \"Open MPI $(version) ($(triplet)-gcc-$(gcc-raw)) was successfully built.\" | $(AWACS)" ;
-    AWACS_ON_FAILURE on $(targets) = "/bin/echo -n \"Open MPI $(version) ($(triplet)-gcc-$(gcc-raw)) failed to build.\" | $(AWACS)" ;
+    SET_RUN_VARS on $(targets) = "OLD_LD_LIBRARY_PATH=\"$LD_LIBRARY_PATH\"; LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
   }
 }
 actions make-openmpi
@@ -248,37 +249,32 @@ actions make-openmpi
   $(SET_RUN_VARS)
   ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
-    echo "ERROR: failed to 'configure' for the OpenMPI build." 1>&2
-    $(AWACS_ON_FAILURE)
+    echo "ERROR: failed to 'configure' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to 'configure' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || { $(UNSET_RUN_VARS); exit 1; }
+  [ -f "$(<:D)/build/Makefile" ] || exit $?
   ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
-    echo "ERROR: failed to 'make' for the OpenMPI build." 1>&2
-    $(AWACS_ON_FAILURE)
+    echo "ERROR: failed to 'make' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to 'make' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
-    echo "ERROR: failed to 'make check' for the OpenMPI build." 1>&2
-    $(AWACS_ON_FAILURE)
+    echo "ERROR: failed to 'make check' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to 'make check' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)/build" && make install )
   if [ $? -ne 0 ]; then
-    $(UNSET_RUN_VARS)
-    echo "ERROR: failed to 'make install' for the OpenMPI build." 1>&2
-    $(AWACS_ON_FAILURE)
+    echo "ERROR: failed to 'make install' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to 'make install' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)/build" && rm -rf * )
-  $(UNSET_RUN_VARS)
+  /bin/echo -n "Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
-  $(AWACS_ON_SUCCESS)
   touch "$(<)"
 }
 
