Added support of #10.
Added the build scripts for PPL and CLooG. GCC build is now configured to
use PPL/CLooG.

diff --git a/clang/jamfile b/clang/jamfile
--- a/clang/jamfile
+++ b/clang/jamfile
@@ -27,8 +27,8 @@ rule assert-unspecified ( feature : properties * )
 rule gcc-dep-req ( properties * )
 {
   assert-specified   <triplet>         : $(properties) ;
-  assert-specified   <multilib>        : $(properties) ;
-  assert-unspecified <multilib-hidden> : $(properties) ;
+  assert-unspecified <multilib>        : $(properties) ;
+  assert-specified   <multilib-hidden> : $(properties) ;
   assert-specified   <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
@@ -37,6 +37,10 @@ rule gcc-dep-req ( properties * )
   assert-specified   <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
   assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <ppl>             : $(properties) ;
+  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <cloog>           : $(properties) ;
+  assert-specified   <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -48,12 +52,18 @@ rule gcc-dep-req ( properties * )
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
   local result = <source>../gcc//install ;
+  local multilib = [ feature.get-values <multilib-hidden> : $(properties) ] ;
+  result = $(result)/<multilib>$(multilib)/<multilib-hidden>unspecified ;
   local gmp = [ feature.get-values <gmp-hidden> : $(properties) ] ;
   result = $(result)/<gmp>$(gmp)/<gmp-hidden>unspecified ;
   local mpfr = [ feature.get-values <mpfr-hidden> : $(properties) ] ;
   result = $(result)/<mpfr>$(mpfr)/<mpfr-hidden>unspecified ;
   local mpc = [ feature.get-values <mpc-hidden> : $(properties) ] ;
   result = $(result)/<mpc>$(mpc)/<mpc-hidden>unspecified ;
+  local ppl = [ feature.get-values <ppl-hidden> : $(properties) ] ;
+  result = $(result)/<ppl>$(ppl)/<ppl-hidden>unspecified ;
+  local cloog = [ feature.get-values <cloog-hidden> : $(properties) ] ;
+  result = $(result)/<cloog>$(cloog)/<cloog-hidden>unspecified ;
   return $(result) ;
 }
 
@@ -71,8 +81,8 @@ always make ;
 rule make-clang ( targets * : sources * : properties * )
 {
   assert-specified   <triplet>         : $(properties) ;
-  assert-specified   <multilib>        : $(properties) ;
-  assert-unspecified <multilib-hidden> : $(properties) ;
+  assert-unspecified <multilib>        : $(properties) ;
+  assert-specified   <multilib-hidden> : $(properties) ;
   assert-specified   <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
@@ -81,6 +91,10 @@ rule make-clang ( targets * : sources * : properties * )
   assert-specified   <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
   assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <ppl>             : $(properties) ;
+  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <cloog>           : $(properties) ;
+  assert-specified   <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -141,8 +155,8 @@ rule make-clang ( targets * : sources * : properties * )
   }
 
   if $(gcc) != $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += CC="\"$(PREFIX)/$(gcc)/bin/gcc\"" ;
-    OPTIONS on $(targets) += CXX="\"$(PREFIX)/$(gcc)/bin/g++\"" ;
+    OPTIONS on $(targets) += CC="\"$(PREFIX)/$(gcc)/bin/gcc-wrapper\"" ;
+    OPTIONS on $(targets) += CXX="\"$(PREFIX)/$(gcc)/bin/g++-wrapper\"" ;
   }
 
   SET_RUN_VARS on $(targets) = ;
@@ -163,13 +177,22 @@ rule make-clang ( targets * : sources * : properties * )
     GCC_RAW on $(targets) = $(gcc-raw) ;
   }
 
-  local clangpp-wrapper = "$(INTRO_ROOT_DIR)/clang/clang++-wrapper" ;
-  CLANGPP_WRAPPER on $(targets) = "$(clangpp-wrapper)" ;
-  local clangpp-tlimit = "$(INTRO_ROOT_DIR)/clang/clang++-tlimit" ;
-  CLANGPP_TLIMIT on $(targets) = "$(clangpp-tlimit)" ;
-
   local version-prefix = "$(PREFIX)/$(gcc)" ;
   VERSION_PREFIX on $(targets) = $(version-prefix) ;
+
+  ENV_DYN_LINK_VARS on $(targets) = ;
+  if $(gcc) != $(GCC_BUILTIN) {
+    if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
+      if $(gcc) != $(GCC_BUILTIN) {
+        ENV_DYN_LINK_VARS on $(targets) = "/usr/bin/env PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"" ;
+      }
+    }
+    else {
+      if $(version) != $(GCC_BUILTIN) {
+        ENV_DYN_LINK_VARS on $(targets) = "/usr/bin/env LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"" ;
+      }
+    }
+  }
 }
 actions make-clang
 {
@@ -227,9 +250,7 @@ actions make-clang
   fi
   llvm_rev=`( cd "$(LLVM_DIR)" && { LANG=C svn info || exit 1; } | { grep -E '^Revision: [[:digit:]]+$' || exit 1; } | { grep -oE '[[:digit:]]+$' || exit 1; } )`
   [ $? -eq 0 ] || $?
-  #{ mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit 1
   mkdir -p "$(<:D)/build" || exit $?
-  $(SET_RUN_VARS)
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
@@ -252,13 +273,14 @@ actions make-clang
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
-    ( cd "$(<:D)/build" && make check >> "$(STREAM)" 2>&1 )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) make check >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$(<:D)/build" && make check )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) make check )
   fi
   if [ $? -ne 0 ]; then
-    echo "WARNING: failed to 'make check' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "WARNING: failed to 'make check' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make check' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to 'make check' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    exit 1
   fi
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && make install >> "$(STREAM)" 2>&1 )
@@ -270,14 +292,12 @@ actions make-clang
     /bin/echo -n "ERROR: failed to 'make install' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  #( cd "$(<:D)" && rm -rf build )
-  cp -f "$(CLANGPP_WRAPPER)" "$(CLANGPP_TLIMIT)" "$(VERSION_PREFIX)/bin"
+  install --mode=755 "$(INTRO_ROOT_DIR)/clang/clang++-wrapper" "$(VERSION_PREFIX)/bin"
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to create wrapper scripts for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to create wrapper scripts for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to install the wrapper script for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: failed to install the wrapper script for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  chmod +x "$(VERSION_PREFIX)/bin/clang++-wrapper" "$(VERSION_PREFIX)/bin/clang++-tlimit" || exit $?
   /bin/echo -n "LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -287,8 +307,8 @@ actions make-clang
 rule install-req ( properties * )
 {
   assert-specified   <triplet>         : $(properties) ;
-  assert-specified   <multilib>        : $(properties) ;
-  assert-unspecified <multilib-hidden> : $(properties) ;
+  assert-unspecified <multilib>        : $(properties) ;
+  assert-specified   <multilib-hidden> : $(properties) ;
   assert-specified   <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
@@ -297,6 +317,10 @@ rule install-req ( properties * )
   assert-specified   <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
   assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <ppl>             : $(properties) ;
+  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <cloog>           : $(properties) ;
+  assert-specified   <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
diff --git a/gcc/jamfile b/gcc/jamfile
--- a/gcc/jamfile
+++ b/gcc/jamfile
@@ -40,6 +40,10 @@ rule download-gcc ( targets * : sources * : properties * )
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
+  assert-unspecified <ppl>             : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
+  assert-unspecified <cloog>           : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -110,6 +114,10 @@ rule expand-gcc ( targets * : sources * : properties * )
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
+  assert-unspecified <ppl>             : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
+  assert-unspecified <cloog>           : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -166,10 +174,12 @@ actions expand-gcc
 
 
 make configure
-  : ../binutils//install/<multilib>unspecified/<gmp>unspecified/<mpfr>unspecified/<mpc>unspecified/<gcc>unspecified
-    # `../prerequisites//static-mpc' depends on `../prerequisites//static-gmp' and `../prerequisites//static-mpfr'.
-    ../prerequisites//static-mpc/<multilib>unspecified/<gcc>unspecified
-    expand/<triplet>unspecified/<multilib>unspecified/<binutils>unspecified/<gmp>unspecified/<mpfr>unspecified/<mpc>unspecified
+  : ../binutils//install/<multilib>unspecified/<gmp>unspecified/<mpfr>unspecified/<mpc>unspecified/<ppl>unspecified/<cloog>unspecified/<gcc>unspecified
+    # `../prerequisites//mpc' depends on `../prerequisites//gmp' and `../prerequisites//mpfr'.
+    ../prerequisites//mpc/<multilib>unspecified/<ppl>unspecified/<cloog>unspecified/<gcc>unspecified
+    ../prerequisites/ppl//install/<multilib>unspecified/<mpfr>unspecified/<mpc>unspecified/<cloog>unspecified/<gcc>unspecified
+    ../prerequisites/cloog//install/<multilib>unspecified/<mpfr>unspecified/<mpc>unspecified/<ppl>unspecified/<gcc>unspecified
+    expand/<triplet>unspecified/<multilib>unspecified/<binutils>unspecified/<gmp>unspecified/<mpfr>unspecified/<mpc>unspecified/<ppl>unspecified/<cloog>unspecified
   : @configure-gcc
   ;
 explicit configure ;
@@ -187,6 +197,10 @@ rule configure-gcc ( targets * : sources * : properties * )
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-specified   <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
+  assert-specified   <ppl>             : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
+  assert-specified   <cloog>           : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -301,15 +315,19 @@ rule configure-gcc ( targets * : sources * : properties * )
     OPTIONS on $(targets) += --disable-win32-registry ;
   }
 
-  OPTIONS on $(targets) += --enable-nls ;
+  OPTIONS on $(targets) += --disable-nls ;
 
   if $(triplet) = i686-pc-cygwin {
     OPTIONS on $(targets) += --enable-graphite ;
   }
 
-  OPTIONS on $(targets) += --with-gmp=\"$(INTRO_ROOT_DIR)/prerequisites\" ;
-  OPTIONS on $(targets) += --with-mpfr=\"$(INTRO_ROOT_DIR)/prerequisites\" ;
-  OPTIONS on $(targets) += --with-mpc=\"$(INTRO_ROOT_DIR)/prerequisites\" ;
+  OPTIONS on $(targets) += --with-gmp=\"$(PREFIX)\" ;
+  OPTIONS on $(targets) += --with-mpfr=\"$(PREFIX)\" ;
+  OPTIONS on $(targets) += --with-mpc=\"$(PREFIX)\" ;
+  OPTIONS on $(targets) += --with-ppl=\"$(PREFIX)\" ;
+  OPTIONS on $(targets) += --with-cloog=\"$(PREFIX)\" ;
+
+  OPTIONS on $(targets) += --enable-cloog-backend=isl ;
 
   OPTIONS on $(targets) += --enable-linker-build-id ;
 
@@ -320,8 +338,6 @@ rule configure-gcc ( targets * : sources * : properties * )
   OPTIONS on $(targets) += --enable-libstdcxx-time=yes ;
 
   OPTIONS on $(targets) += --enable-libstdcxx-debug ;
-
-  OPTIONS on $(targets) += --disable-libstdcxx-pch ;
 
   SET_PREFIX_SYMLINK on $(targets) = ;
   if $(triplet) = x86_64-unknown-linux-gnu || $(triplet) = x86_64-w64-mingw32 {
@@ -367,6 +383,10 @@ rule make-gcc ( targets * : sources * : properties * )
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-specified   <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
+  assert-specified   <ppl>             : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
+  assert-specified   <cloog>           : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -399,20 +419,31 @@ rule make-gcc ( targets * : sources * : properties * )
     errors.error "ERROR: an invalid GCC version." ;
   }
 
-  local gpp-tlimit = "$(INTRO_ROOT_DIR)/gcc/g++-tlimit" ;
-  GPP_TLIMIT on $(targets) = "$(gpp-tlimit)" ;
-
   local version-prefix = "$(PREFIX)/$(version)" ;
   VERSION_PREFIX on $(targets) = $(version-prefix) ;
+
+  ENV_DYN_LINK_VARS on $(targets) = ;
+  if $(gmp) != system || $(mpfr) != system || $(mpc) != system || $(ppl) != system || $(cloog) != system {
+    if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
+      if $(gcc) != $(GCC_BUILTIN) {
+        ENV_DYN_LINK_VARS on $(targets) = "/usr/bin/env PATH=\"$(PREFIX)/bin${PATH:+:$PATH}\"" ;
+      }
+    }
+    else {
+      if $(version) != $(GCC_BUILTIN) {
+        ENV_DYN_LINK_VARS on $(targets) = "/usr/bin/env LD_LIBRARY_PATH=\"$(PREFIX)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"" ;
+      }
+    }
+  }
 }
 actions make-gcc
 {
   rm -f "$(<)" || exit $?
   [ -f "$(<:D)/build/Makefile" ] || exit 1
   if [ -n "$(STREAM)" ]; then
-    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'make' GCC $(VER_RAW) ($(TRIPLET))." 1>&2
@@ -430,13 +461,12 @@ actions make-gcc
     exit 1
   fi
   ( cd "$(<:D)" && rm -rf build )
-  cp -f "$(GPP_TLIMIT)" "$(VERSION_PREFIX)/bin"
+  install --mode=755 "$(INTRO_ROOT_DIR)/gcc/gcc-wrapper" "$(INTRO_ROOT_DIR)/gcc/g++-wrapper" "$(VERSION_PREFIX)/bin"
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to create the wrapper script for GCC $(VER_RAW) ($(TRIPLET))." 1>&2
-    /bin/echo -n "ERROR: failed to create the wrapper script for GCC $(VER_RAW) ($(TRIPLET))." | $(AWACS)
+    echo "ERROR: failed to install the wrapper scripts for GCC $(VER_RAW) ($(TRIPLET))." 1>&2
+    /bin/echo -n "ERROR: failed to install the wrapper scripts for GCC $(VER_RAW) ($(TRIPLET))." | $(AWACS)
     exit 1
   fi
-  chmod +x "$(VERSION_PREFIX)/bin/g++-tlimit" || exit $?
   /bin/echo -n "GCC $(VER_RAW) ($(TRIPLET)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -456,6 +486,10 @@ rule install-req ( properties * )
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-specified   <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
+  assert-specified   <ppl>             : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
+  assert-specified   <cloog>           : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -472,9 +506,7 @@ rule install-req ( properties * )
   local gcc = [ feature.get-values <gcc> : $(properties) ] ;
   if $(gcc) = $(GCC_BUILTIN) {
     # Skips the build of GCC.
-    result = <source>../binutils//install/<multilib>unspecified/<gmp>unspecified/<mpfr>unspecified/<mpc>unspecified/<gcc>unspecified ;
-    # `../prerequisites//static-mpc' depends on `../prerequisites//static-gmp' and `../prerequisites//static-mpfr'.
-    result += <source>../prerequisites//static-mpc/<multilib>unspecified/<gcc>unspecified ;
+    result = <source>../binutils//install/<multilib>unspecified/<gmp>unspecified/<mpfr>unspecified/<mpc>unspecified/<ppl>unspecified/<cloog>unspecified/<gcc>unspecified ;
   }
   else {
     local triplet = [ feature.get-values <triplet> : $(properties) ] ;
diff --git a/prerequisites/ppl/jamfile b/prerequisites/ppl/jamfile
--- a/prerequisites/ppl/jamfile
+++ b/prerequisites/ppl/jamfile
@@ -1,6 +1,5 @@
-project intro/binutils ;
+project intro/prerequisites/ppl ;
 
-import alias ;
 import errors ;
 import feature ;
 import make ;
@@ -10,7 +9,7 @@ rule assert-specified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) = unspecified {
-    errors.error $(feature) is not specified for binutils build. ;
+    errors.error $(feature) is not specified for PPL build. ;
   }
 }
 
@@ -18,20 +17,20 @@ rule assert-unspecified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) != unspecified {
-    errors.error $(feature) is not valid for binutils build. ;
+    errors.error $(feature) is not valid for PPL build. ;
   }
 }
 
 
-make download : : @download-binutils ;
-explicit download ;
+make tarball : : @download ;
+explicit tarball ;
 
-rule download-binutils ( targets * : sources * : properties * )
+rule download ( targets * : sources * : properties * )
 {
   assert-unspecified <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-unspecified <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
@@ -39,7 +38,7 @@ rule download-binutils ( targets * : sources * : properties * )
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
-  assert-unspecified <ppl>             : $(properties) ;
+  assert-specified   <ppl>             : $(properties) ;
   assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
   assert-unspecified <cloog-hidden>    : $(properties) ;
@@ -53,13 +52,13 @@ rule download-binutils ( targets * : sources * : properties * )
   assert-unspecified <openmpi-hidden>  : $(properties) ;
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
-  local version = [ feature.get-values <binutils> : $(properties) ] ;
-  URL on $(targets) = http://ftp.tsukuba.wide.ad.jp/software/binutils/binutils-$(version).tar.bz2 ;
-  #URL on $(targets) = http://core.ring.gr.jp/pub/GNU/binutils/binutils-$(version).tar.bz2 ;
-  TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/binutils-$(version).tar.gz ;
-  TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/binutils-$(version).tar.bz2 ;
+  local version = [ feature.get-values <ppl> : $(properties) ] ;
+  URL on $(targets) = http://bugseng.com/products/ppl/download/ftp/releases/$(version)/ppl-$(version).tar.bz2 ;
+  #URL on $(targets) = http://ftp.tsukuba.wide.ad.jp/software/gcc/infrastructure/ppl-$(version).tar.gz ;
+  TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/ppl-$(version).tar.gz ;
+  TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/ppl-$(version).tar.bz2 ;
 }
-actions download-binutils
+actions download
 {
   rm -f "$(<)" || exit $?
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
@@ -69,8 +68,8 @@ actions download-binutils
       ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' )
     fi
     if [ $? -ne 0 ]; then
-      echo "ERROR: failed to download binutils tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download binutils tarball." | $(AWACS)
+      echo "ERROR: failed to download PPL tarball." 1>&2
+      /bin/echo -n "ERROR: failed to download PPL tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
@@ -80,10 +79,10 @@ actions download-binutils
 }
 
 
-make expand : download : @expand-binutils ;
-explicit expand ;
+make srcdir : tarball : @expand ;
+explicit srcdir ;
 
-rule expand-binutils ( targets * : sources * : properties * )
+rule expand ( targets * : sources * : properties * )
 {
   if ! $(sources[1]) {
     errors.error "ERROR: wrong number of sources." ;
@@ -94,7 +93,7 @@ rule expand-binutils ( targets * : sources * : properties * )
   assert-unspecified <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-unspecified <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
@@ -102,7 +101,7 @@ rule expand-binutils ( targets * : sources * : properties * )
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
-  assert-unspecified <ppl>             : $(properties) ;
+  assert-specified   <ppl>             : $(properties) ;
   assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
   assert-unspecified <cloog-hidden>    : $(properties) ;
@@ -116,18 +115,18 @@ rule expand-binutils ( targets * : sources * : properties * )
   assert-unspecified <openmpi-hidden>  : $(properties) ;
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
-  local version = [ feature.get-values <binutils> : $(properties) ] ;
+  local version = [ feature.get-values <ppl> : $(properties) ] ;
   VERSION on $(targets) = $(version) ;
-  TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/binutils-$(version).tar.gz ;
-  TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/binutils-$(version).tar.bz2 ;
-  DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/binutils-$(version) ;
+  TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/ppl-$(version).tar.gz ;
+  TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/ppl-$(version).tar.bz2 ;
+  DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/ppl-$(version) ;
 }
-actions expand-binutils
+actions expand
 {
   rm -f "$(<)" || exit $?
   [ -f "$(>)" ] || exit 1
-  ( cd "$(INTRO_ROOT_DIR)" && rm -rf binutils-$(VERSION) ) || exit 1
-  [ -e "$(INTRO_ROOT_DIR)/binutils-$(VERSION)" ] && exit 1
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf ppl-$(VERSION) ) || exit 1
+  [ -e "$(INTRO_ROOT_DIR)/ppl-$(VERSION)" ] && exit 1
   if [ -f "$(TARBALL_GZ)" ]; then
     if [ -n "$(STREAM)" ]; then
       tar xzvf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" >> "$(STREAM)" 2>&1
@@ -144,8 +143,8 @@ actions expand-binutils
     exit 1
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to expand binutils tarball." 1>&2
-    /bin/echo -n "ERROR: failed to expand binutils tarball." | $(AWACS)
+    echo "ERROR: failed to expand PPL tarball." 1>&2
+    /bin/echo -n "ERROR: failed to expand PPL tarball." | $(AWACS)
     exit 1
   fi
   [ -d "$(DEST_DIR)" ] || exit 1
@@ -155,26 +154,28 @@ actions expand-binutils
 }
 
 
-make make
-  : expand/<triplet>unspecified
-  : @make-binutils
+make install
+  : ../../binutils//install/<gmp>unspecified/<ppl>unspecified
+    ..//gmp/<ppl>unspecified
+    srcdir/<triplet>unspecified/<binutils>unspecified/<gmp>unspecified
+  : @make-install
   ;
-explicit make ;
+explicit install ;
 
-rule make-binutils ( targets * : sources * : properties * )
+rule make-install ( targets * : sources * : properties * )
 {
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-unspecified <multilib-hidden> : $(properties) ;
   assert-specified   <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
-  assert-unspecified <gmp>             : $(properties) ;
+  assert-specified   <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
-  assert-unspecified <ppl>             : $(properties) ;
+  assert-specified   <ppl>             : $(properties) ;
   assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
   assert-unspecified <cloog-hidden>    : $(properties) ;
@@ -191,34 +192,29 @@ rule make-binutils ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) = ;
 
-  local version = [ feature.get-values <binutils> : $(properties) ] ;
+  local version = [ feature.get-values <ppl> : $(properties) ] ;
   VERSION on $(targets) = $(version) ;
 
   # Set the path to the 'configure' file.
-  local configure = $(INTRO_ROOT_DIR)/binutils-$(version)/configure ;
+  local configure = $(INTRO_ROOT_DIR)/ppl-$(version)/configure ;
   CONFIGURE on $(targets) = $(configure) ;
 
-  # Set the '--build', '--host' and '--target' options for the 'configure' script.
+  # Set the '--build' and '--host' options for the 'configure' script.
   local triplet = [ feature.get-values <triplet> : $(properties) ] ;
   TRIPLET on $(targets) = $(triplet) ;
   OPTIONS on $(targets) += --build=$(triplet) ;
   OPTIONS on $(targets) += --host=$(triplet) ;
-  OPTIONS on $(targets) += --target=$(triplet) ;
 
   # Set the '--prefix' option for the 'configure' script.
   OPTIONS on $(targets) += --prefix=\"$(PREFIX)\" ;
 
-  OPTIONS on $(targets) += --enable-ld=default ;
+  # Set the link variants for the 'configure' script.
+  OPTIONS on $(targets) += --enable-static ;
+  OPTIONS on $(targets) += --enable-shared ;
 
-  OPTIONS on $(targets) += --enable-gold ;
-
-  OPTIONS on $(targets) += --enable-libssp ;
-
-  OPTIONS on $(targets) += --enable-lto ;
-
-  OPTIONS on $(targets) += --enable-plugins ;
+  OPTIONS on $(targets) += --with-gmp=\"$(PREFIX)\" ;
 }
-actions make-binutils
+actions make-install
 {
   rm -f "$(<)" || exit $?
   [ -x "$(CONFIGURE)" ] || exit 1
@@ -230,8 +226,8 @@ actions make-binutils
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'configure' binutils $(VERSION) ($(TRIPLET)-gcc)." 1>&2
-    /bin/echo -n "ERROR: failed to 'configure' binutils $(VERSION) ($(TRIPLET)-gcc)." | $(AWACS)
+    echo "ERROR: failed to 'configure' PPL $(VERSION) (as prerequisites)." 1>&2
+    /bin/echo -n "ERROR: failed to 'configure' PPL $(VERSION) (as prerequisites)." | $(AWACS)
     exit 1
   fi
   [ -f "$(<:D)/build/Makefile" ] || exit 1
@@ -241,18 +237,20 @@ actions make-binutils
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make' binutils $(VERSION) ($(TRIPLET)-gcc)." 1>&2
-    /bin/echo -n "ERROR: failed to 'make' binutils $(VERSION) ($(TRIPLET)-gcc)." | $(AWACS)
+    echo "ERROR: failed to 'make' PPL $(VERSION) (as prerequisites)." 1>&2
+    /bin/echo -n "ERROR: failed to 'make' PPL $(VERSION) (as prerequisites)." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
-    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check >> "$(STREAM)" 2>&1 )
+    echo 'Skip check'
+    #( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
+    echo 'Skip check'
+    #( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make check' binutils $(VERSION) ($(TRIPLET)-gcc)." 1>&2
-    /bin/echo -n "ERROR: failed to 'make check' binutils $(VERSION) ($(TRIPLET)-gcc)." | $(AWACS)
+    echo "ERROR: failed to 'make check' PPL $(VERSION) (as prerequisites)." 1>&2
+    /bin/echo -n "ERROR: failed to 'make check' PPL $(VERSION) (as prerequisites)." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -261,45 +259,12 @@ actions make-binutils
     ( cd "$(<:D)/build" && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make install' binutils $(VERSION) ($(TRIPLET)-gcc)." 1>&2
-    /bin/echo -n "ERROR: failed to 'make install' binutils $(VERSION) ($(TRIPLET)-gcc)." | $(AWACS)
+    echo "ERROR: failed to 'make install' PPL $(VERSION) (as prerequisites)." 1>&2
+    /bin/echo -n "ERROR: failed to 'make install' PPL $(VERSION) (as prerequisites)." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)" && rm -rf build )
-  /bin/echo -n "binutils $(VERSION) ($(TRIPLET)-gcc) was successfully built." | $(AWACS)
+  /bin/echo -n "PPL $(VERSION) (as prerequisites) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
-
-
-rule install-req ( properties * )
-{
-  assert-specified   <triplet>         : $(properties) ;
-  assert-unspecified <multilib>        : $(properties) ;
-  assert-unspecified <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
-  assert-unspecified <binutils-hidden> : $(properties) ;
-  assert-unspecified <gmp>             : $(properties) ;
-  assert-unspecified <gmp-hidden>      : $(properties) ;
-  assert-unspecified <mpfr>            : $(properties) ;
-  assert-unspecified <mpfr-hidden>     : $(properties) ;
-  assert-unspecified <mpc>             : $(properties) ;
-  assert-unspecified <mpc-hidden>      : $(properties) ;
-  assert-unspecified <ppl>             : $(properties) ;
-  assert-unspecified <ppl-hidden>      : $(properties) ;
-  assert-unspecified <cloog>           : $(properties) ;
-  assert-unspecified <cloog-hidden>    : $(properties) ;
-  assert-unspecified <gcc>             : $(properties) ;
-  assert-unspecified <gcc-hidden>      : $(properties) ;
-  assert-unspecified <icu4c>           : $(properties) ;
-  assert-unspecified <icu4c-hidden>    : $(properties) ;
-  assert-unspecified <mpi>             : $(properties) ;
-  assert-unspecified <mpi-hidden>      : $(properties) ;
-  assert-unspecified <openmpi>         : $(properties) ;
-  assert-unspecified <openmpi-hidden>  : $(properties) ;
-  assert-unspecified <boost>           : $(properties) ;
-  assert-unspecified <boost-hidden>    : $(properties) ;
-}
-
-alias install : make : <conditional>@install-req ;
-explicit install ;
