Fixed messages.

diff --git a/clang/jamfile b/clang/jamfile
--- a/clang/jamfile
+++ b/clang/jamfile
@@ -160,12 +160,9 @@ actions make-clang
   if [ ! -d "$(LLVM_DIR)" ]; then
     ( cd "$(INTRO_ROOT_DIR)" && svn checkout http://llvm.org/svn/llvm-project/llvm/trunk llvm )
     if [ $? -ne 0 ]; then
-      if [ -d "$(LLVM_DIR)" ]; then
-        ( cd "$(LLVM_DIR)" && rm -rf * ) || exit $?
-        rmdir "$(LLVM_DIR)" || exit $?
-      fi
-      echo "ERROR: failed to 'svn checkout' the LLVM repository." 1>&2
-      /bin/echo -n "ERROR: failed to 'svn checkout' the LLVM repository." | $(AWACS)
+      ( cd "$(INTRO_ROOT_DIR)" && rm -rf llvm )
+      echo "ERROR: failed to 'svn checkout' LLVM repository." 1>&2
+      /bin/echo -n "ERROR: failed to 'svn checkout' LLVM repository." | $(AWACS)
       exit 1
     fi
     [ -d "$(LLVM_DIR)" ] || exit $?
@@ -176,26 +173,23 @@ actions make-clang
   if [ ! -d "$(CLANG_DIR)" ]; then
     ( cd "$(INTRO_ROOT_DIR)/llvm/tools" && svn checkout http://llvm.org/svn/llvm-project/cfe/trunk clang )
     if [ $? -ne 0 ]; then
-      if [ -d "$(CLANG_DIR)" ]; then
-        ( cd "$(CLANG_DIR)" && rm -rf * )
-        rmdir "$(CLANG_DIR)"
-      fi
-      echo "ERROR: failed to 'svn checkout' the Clang repository." 1>&2
-      /bin/echo -n "ERROR: failed to 'svn checkout' the Clang repository." | $(AWACS)
+      ( cd "$(INTRO_ROOT_DIR)/llvm/tools" && rm -rf clang )
+      echo "ERROR: failed to 'svn checkout' Clang repository." 1>&2
+      /bin/echo -n "ERROR: failed to 'svn checkout' Clang repository." | $(AWACS)
       exit 1
     fi
     [ -d "$(CLANG_DIR)" ] || exit $?
   fi
   ( cd "$(LLVM_DIR)" && svn update )
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'svn update' the LLVM repository." 1>&2
-    /bin/echo -n "ERROR: failed to 'svn update' the LLVM repository." | $(AWACS)
+    echo "ERROR: failed to 'svn update' LLVM repository." 1>&2
+    /bin/echo -n "ERROR: failed to 'svn update' LLVM repository." | $(AWACS)
     exit 1
   fi
   ( cd "$(CLANG_DIR)" && svn update )
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'svn update' the Clang repository." 1>&2
-    /bin/echo -n "ERROR: failed to 'svn update' the Clang repository." | $(AWACS)
+    echo "ERROR: failed to 'svn update' Clang repository." 1>&2
+    /bin/echo -n "ERROR: failed to 'svn update' Clang repository." | $(AWACS)
     exit 1
   fi
   llvm_rev=`( cd "$(LLVM_DIR)" && { LANG=C svn info || exit 1; } | { grep -E '^Revision: [[:digit:]]+$' || exit 1; } | { grep -oE '[[:digit:]]+$' || exit 1; } )`
@@ -226,7 +220,7 @@ actions make-clang
     /bin/echo -n "ERROR: failed to 'make install' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  ( cd "$(<:D)/build" && rm -rf * )
+  ( cd "$(<:D)" && rm -rf build )
   cp -f "$(CLANGPP_WRAPPER)" "$(CLANGPP_TLIMIT)" "$(VERSION_PREFIX)/bin"
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to create wrapper scripts for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
@@ -234,8 +228,8 @@ actions make-clang
     exit 1
   fi
   chmod +x "$(VERSION_PREFIX)/bin/clang++-wrapper" "$(VERSION_PREFIX)/bin/clang++-tlimit" || exit $?
-  [ -e "$(<)" ] && exit 1
   /bin/echo -n "LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
+  [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
 
diff --git a/gcc/jamfile b/gcc/jamfile
--- a/gcc/jamfile
+++ b/gcc/jamfile
@@ -11,7 +11,7 @@ rule assert-specified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) = unspecified {
-    errors.error $(feature) is not specified for the GCC build. ;
+    errors.error $(feature) is not specified for GCC build. ;
   }
 }
 
@@ -19,7 +19,7 @@ rule assert-unspecified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) != unspecified {
-    errors.error $(feature) is not valid for the GCC build. ;
+    errors.error $(feature) is not valid for GCC build. ;
   }
 }
 
@@ -64,8 +64,8 @@ actions download-gcc
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
     ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' )
     if [ $? -ne 0 ]; then
-      echo "ERROR: failed to download the GCC tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download the GCC tarball." | $(AWACS)
+      echo "ERROR: failed to download GCC tarball." 1>&2
+      /bin/echo -n "ERROR: failed to download GCC tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
@@ -106,6 +106,7 @@ rule expand-gcc ( targets * : sources * : properties * )
     errors.error "ERROR: wrong number of sources." ;
   }
   local version = [ feature.get-values <gcc> : $(properties) ] ;
+  VERSION on $(targets) = $(version) ;
   TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/gcc-$(version).tar.gz ;
   TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/gcc-$(version).tar.bz2 ;
   DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/gcc-$(version) ;
@@ -114,24 +115,17 @@ actions expand-gcc
 {
   rm -f "$(<)" || exit $?
   [ -f "$(>)" ] || exit $?
-  if [ ! -x "$(DEST_DIR)/configure" ]; then
-    if [ -f "$(DEST_DIR)" ]; then
-      rm -f "$(DEST_DIR)" || exit $?
-    elif [ -d "$(DEST_DIR)" ]; then
-      ( cd "$(DEST_DIR)" && rm -rf * ) || exit $?
-      rmdir "$(DEST_DIR)" || exit $?
-    fi
-    if [ -f "$(TARBALL_GZ)" ]; then
-      tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the tarball for the GCC build." 1>&2; exit 1; }
-    elif [ -f "$(TARBALL_BZ2)" ]; then
-      tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the tarball for the GCC build." 1>&2; exit 1; }
-    else
-      exit 1
-    fi
-    [ -x "$(DEST_DIR)/configure" ] || exit $?
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf gcc-$(VERSION) ) || exit $?
+  [ -e "$(INTRO_ROOT_DIR)/gcc-$(VERSION)" ] && exit 1
+  if [ -f "$(TARBALL_GZ)" ]; then
+    tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" || { echo "ERROR: failed to expand GCC tarball." 1>&2; exit 1; }
+  elif [ -f "$(TARBALL_BZ2)" ]; then
+    tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" || { echo "ERROR: failed to expand GCC tarball." 1>&2; exit 1; }
+  else
+    exit 1
   fi
+  [ -d "$(DEST_DIR)" ] || exit $?
+  [ -x "$(DEST_DIR)/configure" ] || exit $?
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -409,7 +403,7 @@ actions make-gcc
     /bin/echo -n "ERROR: failed to 'make install' GCC $(VER_RAW) ($(TRIPLET))." | $(AWACS)
     exit 1
   fi
-  ( cd "$(<:D)/build" && rm -rf * )
+  ( cd "$(<:D)" && rm -rf build )
   $(UNSET_MPC_SYMLINK)
   $(UNSET_MPFR_SYMLINK)
   $(UNSET_GMP_SYMLINK)
diff --git a/gmp/jamfile b/gmp/jamfile
--- a/gmp/jamfile
+++ b/gmp/jamfile
@@ -11,7 +11,7 @@ rule assert-specified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) = unspecified {
-    errors.error $(feature) is not specified for the GMP build. ;
+    errors.error $(feature) is not specified for GMP build. ;
   }
 }
 
@@ -19,7 +19,7 @@ rule assert-unspecified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) != unspecified {
-    errors.error $(feature) is not valid for the GMP build. ;
+    errors.error $(feature) is not valid for GMP build. ;
   }
 }
 
@@ -92,8 +92,8 @@ actions download-gmp
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
     ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' )
     if [ $? -ne 0 ]; then
-      echo "ERROR: failed to download the GMP tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download the GMP tarball." | $(AWACS)
+      echo "ERROR: failed to download GMP tarball." 1>&2
+      /bin/echo -n "ERROR: failed to download GMP tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
@@ -134,6 +134,7 @@ rule expand-gmp ( targets * : sources * : properties * )
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
   local version = [ feature.get-values <gmp> : $(properties) ] ;
+  VERSION on $(targets) = $(version) ;
   TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/gmp-$(version).tar.gz ;
   TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/gmp-$(version).tar.bz2 ;
   DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/gmp-$(version) ;
@@ -142,24 +143,17 @@ actions expand-gmp
 {
   rm -f "$(<)" || exit $?
   [ -f "$(>)" ] || exit $?
-  if [ ! -x "$(DEST_DIR)/configure" ]; then
-    if [ -f "$(DEST_DIR)" ]; then
-      rm -f "$(DEST_DIR)" || exit $?
-    elif [ -d "$(DEST_DIR)" ]; then
-      ( cd "$(DEST_DIR)" && rm -rf * ) || exit $?
-      rmdir "$(DEST_DIR)" || exit $?
-    fi
-    if [ -f "$(TARBALL_GZ)" ]; then
-      tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the GMP tarball." 1>&2; exit 1; }
-    elif [ -f "$(TARBALL_BZ2)" ]; then
-      tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the GMP tarball." 1>&2; exit 1; }
-    else
-      exit 1
-    fi
-    [ -x "$(DEST_DIR)/configure" ] || exit $?
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf gmp-$(VERSION) ) || exit $?
+  [ -e "$(INTRO_ROOT_DIR)/gmp-$(VERSION)" ] && exit 1
+  if [ -f "$(TARBALL_GZ)" ]; then
+    tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" || { echo "ERROR: failed to expand GMP tarball." 1>&2; exit 1; }
+  elif [ -f "$(TARBALL_BZ2)" ]; then
+    tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" || { echo "ERROR: failed to expand GMP tarball." 1>&2; exit 1; }
+  else
+    exit 1
   fi
+  [ -d "$(DEST_DIR)" ] || exit $?
+  [ -x "$(DEST_DIR)/configure" ] || exit $?
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -268,7 +262,7 @@ actions make-gmp
     /bin/echo -n "ERROR: failed to 'make install' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  ( cd "$(<:D)/build" && rm -rf * )
+  ( cd "$(<:D)" && rm -rf build )
   /bin/echo -n "GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
diff --git a/icu4c/jamfile b/icu4c/jamfile
--- a/icu4c/jamfile
+++ b/icu4c/jamfile
@@ -11,7 +11,7 @@ rule assert-specified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) = unspecified {
-    errors.error $(feature) is not specified for the ICU4C build. ;
+    errors.error $(feature) is not specified for ICU4C build. ;
   }
 }
 
@@ -19,7 +19,7 @@ rule assert-unspecified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) != unspecified {
-    errors.error $(feature) is not valid for the ICU4C build. ;
+    errors.error $(feature) is not valid for ICU4C build. ;
   }
 }
 
@@ -97,8 +97,8 @@ actions download-icu4c
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_TGZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
     ( cd "$(TARBALL_TGZ:D)" && wget --quiet -- '$(URL)' )
     if [ $? -ne 0 ]; then
-      echo "ERROR: failed to download the ICU4C tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download the ICU4C tarball." | $(AWACS)
+      echo "ERROR: failed to download ICU4C tarball." 1>&2
+      /bin/echo -n "ERROR: failed to download ICU4C tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_TGZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
@@ -149,27 +149,19 @@ actions expand-icu4c
 {
   rm -f "$(<)" || exit $?
   [ -f "$(>)" ] || exit $?
-  if [ ! -x "$(DEST_DIR)/source/runConfigureICU" ]; then
-    if [ -f "$(DEST_DIR)" ]; then
-      rm -f "$(DEST_DIR)" || exit $?
-    elif [ -d "$(DEST_DIR)" ]; then
-      ( cd "$(DEST_DIR)" && rm -rf * ) || exit $?
-      rmdir "$(DEST_DIR)" || exit $?
-    fi
-    if [ -f "$(TARBALL_GZ)" ]; then
-      tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the ICU4C tarball." 1>&2; exit 1; }
-    elif [ -f "$(TARBALL_TGZ)" ]; then
-      tar xzf "$(TARBALL_TGZ)" -C "$(TARBALL_TGZ:D)" \
-        || { echo "ERROR: failed to expand the ICU4C tarball." 1>&2; exit 1; }
-    elif [ -f "$(TARBALL_BZ2)" ]; then
-      tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the ICU4C tarball." 1>&2; exit 1; }
-    else
-      exit 1
-    fi
-    [ -x "$(DEST_DIR)/source/runConfigureICU" ] || exit $?
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf icu ) || exit $?
+  [ -e "$(INTRO_ROOT_DIR)/icu" ] && exit 1
+  if [ -f "$(TARBALL_GZ)" ]; then
+    tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" || { echo "ERROR: failed to expand ICU4C tarball." 1>&2; exit 1; }
+  elif [ -f "$(TARBALL_TGZ)" ]; then
+    tar xzf "$(TARBALL_TGZ)" -C "$(TARBALL_TGZ:D)" || { echo "ERROR: failed to expand ICU4C tarball." 1>&2; exit 1; }
+  elif [ -f "$(TARBALL_BZ2)" ]; then
+    tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" || { echo "ERROR: failed to expand ICU4C tarball." 1>&2; exit 1; }
+  else
+    exit 1
   fi
+  [ -d "$(DEST_DIR)" ] || exit $?
+  [ -x "$(DEST_DIR)/source/runConfigureICU" ] || exit $?
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -296,7 +288,7 @@ actions make-icu4c
     /bin/echo -n "ERROR: failed to 'make install' ICU4C $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  ( cd "$(<:D)/build" && rm -rf * )
+  ( cd "$(<:D)" && rm -rf build )
   /bin/echo -n "ICU4C $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
diff --git a/mpc/jamfile b/mpc/jamfile
--- a/mpc/jamfile
+++ b/mpc/jamfile
@@ -11,7 +11,7 @@ rule assert-specified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) = unspecified {
-    errors.error $(feature) is not specified for the MPC build. ;
+    errors.error $(feature) is not specified for MPC build. ;
   }
 }
 
@@ -19,7 +19,7 @@ rule assert-unspecified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) != unspecified {
-    errors.error $(feature) is not valid for the MPC build. ;
+    errors.error $(feature) is not valid for MPC build. ;
   }
 }
 
@@ -90,8 +90,8 @@ actions download-mpc
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
     ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' )
     if [ $? -ne 0 ]; then
-      echo "ERROR: failed to download the MPC tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download the MPC tarball." | $(AWACS)
+      echo "ERROR: failed to download MPC tarball." 1>&2
+      /bin/echo -n "ERROR: failed to download MPC tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
@@ -132,6 +132,7 @@ rule expand-mpc ( targets * : sources * : properties * )
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
   local version = [ feature.get-values <mpc> : $(properties) ] ;
+  VERSION on $(targets) = $(version) ;
   TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/mpc-$(version).tar.gz ;
   TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/mpc-$(version).tar.bz2 ;
   DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/mpc-$(version) ;
@@ -140,24 +141,17 @@ actions expand-mpc
 {
   rm -f "$(<)" || exit $?
   [ -f "$(>)" ] || exit $?
-  if [ ! -x "$(DEST_DIR)/configure" ]; then
-    if [ -f "$(DEST_DIR)" ]; then
-      rm -f "$(DEST_DIR)" || exit $?
-    elif [ -d "$(DEST_DIR)" ]; then
-      ( cd "$(DEST_DIR)" && rm -rf * ) || exit $?
-      rmdir "$(DEST_DIR)" || exit $?
-    fi
-    if [ -f "$(TARBALL_GZ)" ]; then
-      tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the MPC tarball." 1>&2; exit 1; }
-    elif [ -f "$(TARBALL_BZ2)" ]; then
-      tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the MPC tarball." 1>&2; exit 1; }
-    else
-      exit 1
-    fi
-    [ -x "$(DEST_DIR)/configure" ] || exit $?
+  ( rm -rf "$(INTRO_ROOT_DIR)" && rm -rf mpc-$(VERSION) ) || exit $?
+  [ -e "$(INTRO_ROOT_DIR)/mpc-$(VERSION)" ] && exit 1
+  if [ -f "$(TARBALL_GZ)" ]; then
+    tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" || { echo "ERROR: failed to expand MPC tarball." 1>&2; exit 1; }
+  elif [ -f "$(TARBALL_BZ2)" ]; then
+    tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" || { echo "ERROR: failed to expand MPC tarball." 1>&2; exit 1; }
+  else
+    exit 1
   fi
+  [ -d "$(DEST_DIR)" ] || exit $?
+  [ -x "$(DEST_DIR)/configure" ] || exit $?
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -266,7 +260,7 @@ actions make-mpc
     /bin/echo -n "ERROR: failed to 'make install' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  ( cd "$(<:D)/build" && rm -rf * )
+  ( cd "$(<:D)" && rm -rf build )
   /bin/echo -n "MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
diff --git a/openmpi/jamfile b/openmpi/jamfile
--- a/openmpi/jamfile
+++ b/openmpi/jamfile
@@ -11,7 +11,7 @@ rule assert-specified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) = unspecified {
-    errors.error $(feature) is not specified for the Open MPI build. ;
+    errors.error $(feature) is not specified for Open MPI build. ;
   }
 }
 
@@ -19,7 +19,7 @@ rule assert-unspecified ( feature : properties * )
 {
   local val = [ feature.get-values $(feature) : $(properties) ] ;
   if $(val) != unspecified {
-    errors.error $(feature) is not valid for the Open MPI build. ;
+    errors.error $(feature) is not valid for Open MPI build. ;
   }
 }
 
@@ -96,8 +96,8 @@ actions download-openmpi
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
     ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' )
     if [ $? -ne 0 ]; then
-      echo "ERROR: failed to download the Open MPI tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download the Open MPI tarball." | $(AWACS)
+      echo "ERROR: failed to download Open MPI tarball." 1>&2
+      /bin/echo -n "ERROR: failed to download Open MPI tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
@@ -138,6 +138,7 @@ rule expand-openmpi ( targets * : sources * : properties * )
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
   local version = [ feature.get-values <openmpi> : $(properties) ] ;
+  VERSION on $(targets) = $(version) ;
   TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/openmpi-$(version).tar.gz ;
   TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/openmpi-$(version).tar.bz2 ;
   DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/openmpi-$(version) ;
@@ -146,24 +147,17 @@ actions expand-openmpi
 {
   rm -f "$(<)" || exit $?
   [ -f "$(>)" ] || exit $?
-  if [ ! -x "$(DEST_DIR)/configure" ]; then
-    if [ -f "$(DEST_DIR)" ]; then
-      rm -f "$(DEST_DIR)" || exit $?
-    elif [ -d "$(DEST_DIR)" ]; then
-      ( cd "$(DEST_DIR)" && rm -rf * ) || exit $?
-      rmdir "$(DEST_DIR)" || exit $?
-    fi
-    if [ -f "$(TARBALL_GZ)" ]; then
-      tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the Open MPI tarball." 1>&2; exit 1; }
-    elif [ -f "$(TARBALL_BZ2)" ]; then
-      tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the Open MPI tarball." 1>&2; exit 1; }
-    else
-      exit 1
-    fi
-    [ -x "$(DEST_DIR)/configure" ] || exit $?
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf openmpi-$(VERSION) ) || exit $?
+  [ -e "$(INTRO_ROOT_DIR)/openmpi-$(VERSION)" ] && exit 1
+  if [ -f "$(TARBALL_GZ)" ]; then
+    tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" || { echo "ERROR: failed to expand Open MPI tarball." 1>&2; exit 1; }
+  elif [ -f "$(TARBALL_BZ2)" ]; then
+    tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" || { echo "ERROR: failed to expand Open MPI tarball." 1>&2; exit 1; }
+  else
+    exit 1
   fi
+  [ -d "$(DEST_DIR)" ] || exit $?
+  [ -x "$(DEST_DIR)/configure" ] || exit $?
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -272,7 +266,7 @@ actions make-openmpi
     /bin/echo -n "ERROR: failed to 'make install' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  ( cd "$(<:D)/build" && rm -rf * )
+  ( cd "$(<:D)" && rm -rf build )
   /bin/echo -n "Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
