Fixed #96.
* bootstrap:
  * Modified to dereference `latest` value of `--with-lcov` command-line
    option into concrete version numbers before invoking `bjam`.
  * Modified to prepare LCOV source trees before invoking `bjam`.
* jamroot: Removed support for `latest` value of `--enable-lcov`
           command-line option.
* lcov/checkout.sh: Newly added.
* lcov/latest.sh: Fixed to use git repository.
* lcov/download.sh: Newly added.
* lcov/jamfile:
  * Removed downloading and expanding actions.
  * Switched dependency on LCOV source trees from `lcov-$VERSION/README`
    to timestamp files `lcov-$VERSION/e2c10538-d490-4c93-8e19-3fb74e470174`.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -567,7 +567,16 @@ no)
 esac
 
 if [ -n "$lcov" ]; then
-  delegated_opts=("${delegated_opts[@]}" --enable-lcov="$lcov")
+    if [ "$lcov" = latest ]; then
+        lcov="$("$intro_root/lcov/latest.sh")"
+    fi
+    if echo "$lcov" | grep -Eq '^[[:digit:]]+\.[[:digit:]]+$'; then
+        "$intro_root/lcov/download.sh" "$lcov"
+    else
+        echo "error: an invalid value \`$lcov' for \`--enable-lcov'" >&2
+        exit 1
+    fi
+    delegated_opts=("${delegated_opts[@]}" --enable-lcov="$lcov")
 fi
 
 if [ -n "$gcovr" ]; then
