Added support for Binutils trunk.
Removed downloading and expanding actions from build procedure. These
actions now run before build procedure is invoked.
* bootstrap: Changed to invoke downloading/expanding or cloning scripts.
* download.sh: Newly added.
* checkout.sh: Newly added.
* jamroot: Added support for `trunk` argument of `with-binutils` option.
* binutils/jamfile: Removed downloading and expanding actions.
* gcc/jamfile: Added dependency on the timestamp file of Binutils source
  tree to GCC build target.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -582,6 +582,19 @@ fi
 
 intro_root=`(cd \`dirname "$0"\`; pwd)`
 
+if [ "$binutils" = latest ]; then
+  "$intro_root/binutils/download.sh" latest
+elif echo "$binutils" | grep -Eq '^[[:digit:]]+(\.[[:digit:]]+(\.[[:digit:]]+)?)?$'; then
+  "$intro_root/binutils/download.sh" "$binutils"
+elif [ "$binutils" = trunk ]; then
+  "$intro_root/binutils/checkout.sh"
+elif [ "$binutils" != system ]; then
+  :
+else
+  echo "error: an invalid value \`$binutils' for \`--with-binutils'." >&2
+  exit 1
+fi
+
 boost_latest=`"$intro_root/boost/latest.sh"`
 
 if [ ! -d "$prefix/boost/$boost_latest" ]; then
