Fixed #86
* .gitignore: Told to ignore downloaded GDB tarballs.
* bootstrap:
  * Modified to dereference `latest` value of `--enable-gdb` command-line
    option into concrete version numbers before invoking `bjam`.
* gdb/download.sh: Newly added.
* jamroot: Removed support for `latest` value of `--enable-gdb` command-line
  option.
* gdb/jamfile:
  * Removed downloading and expanding actions.
  * Switched dependency on GDB source trees from `gdb-$VERSION/README`
    to timestamp files `gdb-$VERSION/f4f591f6-9a1d-4ac3-ae2f-ba6463d79680`.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -575,7 +575,17 @@ if [ -n "$gcovr" ]; then
 fi
 
 if [ -n "$gdb" ]; then
-  delegated_opts=("${delegated_opts[@]}" --enable-gdb="$gdb")
+    if [ "$gdb" = latest ]; then
+        gdb="$("$intro_root/gdb/latest.sh")"
+    fi
+    # GDB version strings might include non-digit suffixes like `7.3a`.
+    if echo "$gdb" | grep -Eq '^[[:digit:]]+(\.[[:digit:]]+){1,2}a?$'; then
+        "$intro_root/gdb/download.sh" "$gdb"
+    else
+        echo "error: an invalid value \`$gdb' for \`--enable-gdb'" >&2
+        exit 1
+    fi
+    delegated_opts=("${delegated_opts[@]}" --enable-gdb="$gdb")
 fi
 
 case "$gdb_check" in
