Fixed #109.
* bootstrap:
  * Modified to dereference `latest` value of `--with-gcovr` command-line
    option into concrete version numbers before invoking `bjam`.
  * Modified to prepare gcovr source trees before invoking `bjam`.
* jamroot: Removed support for `latest` value of `--enable-gcovr`
           command-line option.
* gcovr/checkout.sh: Newly added.
* gcovr/latest.sh: Fixed to use git repository.
* gcovr/download.sh: Newly added.
* gcovr/jamfile:
  * Removed downloading and expanding actions.
  * Switched dependency on gcovr source trees from
    `gcovr-$VERSION/README.txt` to timestamp files
    `gcovr-$VERSION/fb301e39-8f74-4e35-8428-9b3b48a324bc`.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -592,7 +592,16 @@ if [ -n "$lcov" ]; then
 fi
 
 if [ -n "$gcovr" ]; then
-  delegated_opts=("${delegated_opts[@]}" --enable-gcovr="$gcovr")
+    if [ "$gcovr" = latest ]; then
+        gcovr="$("$intro_root/gcovr/latest.sh")"
+    fi
+    if echo "$gcovr" | grep -Eq '^[[:digit:]]+\.[[:digit:]]+$'; then
+        "$intro_root/gcovr/download.sh" "$gcovr"
+    else
+        echo "error: an invalid value \`$gcovr' for \`--enable-gcovr'" >&2
+        exit 1
+    fi
+    delegated_opts=("${delegated_opts[@]}" --enable-gcovr="$gcovr")
 fi
 
 if [ -n "$gdb" ]; then
