Added multi-target/multi-binary support for ICU4C.

diff --git a/icu4c/jamfile b/icu4c/jamfile
--- a/icu4c/jamfile
+++ b/icu4c/jamfile
@@ -6,7 +6,20 @@ import feature ;
 import make ;
 import path ;
 import regex ;
-import "$(INTRO_ROOT_DIR)/compilers" ;
+import "$(INTRO_ROOT_DIR)/compilers"
+  : is-gcc
+    is-clang
+    get-compiler-description
+    get-compiler-prefix
+    get-bindir
+    get-libdir
+    get-includedir
+    get-cc
+    get-cflags
+    get-cxx
+    get-cxxflags
+    get-environment-commands
+  ;
 
 
 rule assert-specified ( feature : properties * )
@@ -40,11 +53,11 @@ rule compiler-dep-req ( properties * )
   local multitarget = [ feature.get-values <multitarget-hidden> : $(properties) ] ;
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
   local result ;
-  if [ "$(INTRO_ROOT_DIR)/compilers.is-gcc" $(compiler) ]
+  if [ is-gcc $(compiler) ]
   {
     result = <source>../gcc//install/<multitarget>$(multitarget)/<multitarget-hidden>unspecified ;
   }
-  else if [ "$(INTRO_ROOT_DIR)/compilers.is-clang" $(compiler) ]
+  else if [ is-clang $(compiler) ]
   {
     result = <source>../clang//install ;
   }
@@ -88,19 +101,19 @@ rule download ( targets * : sources * : properties * )
 }
 actions download
 {
-  rm -rf "$(<)" || exit 1
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(<:D)" && wget -- '$(URL)' >> "$(STREAM)" 2>&1 )
+  rm -rf '$(<)' || exit 1
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(<:D)' && wget -- '$(URL)' >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(<:D)" && wget --quiet -- '$(URL)' )
+    ( cd '$(<:D)' && wget --quiet -- '$(URL)' )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to download ICU4C $(VERSION) tarball." 1>&2
-    echo -n "ERROR: failed to download ICU4C $(VERSION) tarball." | $(AWACS)
-    rm -rf "$(<)"
+    echo    'ERROR: failed to download ICU4C $(VERSION) tarball.' 1>&2
+    echo -n 'ERROR: failed to download ICU4C $(VERSION) tarball.' | $(AWACS)
+    rm -rf '$(<)'
     exit 1
   fi
-  [ -f "$(<)" ] || exit 1
+  [ -f '$(<)' ] || exit 1
   exit 0
 }
 
@@ -147,29 +160,29 @@ rule expand ( targets * : sources * : properties * )
 }
 actions expand
 {
-  rm -rf "$(<:D)" || exit 1
-  rm -rf "$(INTRO_ROOT_DIR)/icu" || exit 1
-  [ -f "$(>)" ] || exit 1
-  if [ -n "$(STREAM)" ]; then
-    tar xzvf "$(>)" --directory="$(INTRO_ROOT_DIR)" >> "$(STREAM)" 2>&1
+  rm -rf '$(<:D)' || exit 1
+  rm -rf '$(INTRO_ROOT_DIR)/icu' || exit 1
+  [ -f '$(>)' ] || exit 1
+  if [ -n '$(STREAM)' ]; then
+    tar xzvf '$(>)' --directory='$(INTRO_ROOT_DIR)' >> '$(STREAM)' 2>&1
   else
-    tar xzf "$(>)" --directory="$(INTRO_ROOT_DIR)"
+    tar xzf '$(>)' --directory='$(INTRO_ROOT_DIR)'
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to expand ICU4C $(VERSION) tarball." 1>&2
-    echo -n "ERROR: failed to expand ICU4C $(VERSION) tarball." | $(AWACS)
-    rm -rf "$(<:D)"
-    rm -rf "$(INTRO_ROOT_DIR)/icu"
+    echo    'ERROR: failed to expand ICU4C $(VERSION) tarball.' 1>&2
+    echo -n 'ERROR: failed to expand ICU4C $(VERSION) tarball.' | $(AWACS)
+    rm -rf '$(<:D)'
+    rm -rf '$(INTRO_ROOT_DIR)/icu'
     exit 1
   fi
-  [ -d "$(INTRO_ROOT_DIR)/icu" ] || exit 1
-  mv "$(INTRO_ROOT_DIR)/icu" "$(<:D)" || exit 1
+  [ -d '$(INTRO_ROOT_DIR)/icu' ] || exit 1
+  mv '$(INTRO_ROOT_DIR)/icu' '$(<:D)' || exit 1
   # If the timestamp of the tarball's contents is restored, the modification
   # time of the source directory could be older than the one of the tarball.
   # Such behavior is not desirable because the decompression always happens.
   # Therefore, `touch' is required.
-  touch --no-create "$(<)"
-  [ -f "$(<)" ] || exit 1
+  touch --no-create '$(<)'
+  [ -f '$(<)' ] || exit 1
   exit 0
 }
 
@@ -194,18 +207,20 @@ explicit srcdir ;
 
 
 
-for local compiler in $(COMPILERS)
+rule location-conditional ( properties * )
 {
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  make "$(compiler-prefix)/include/unicode/uchar.h"
-    : compiler-dep
-      srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified
-    : @make-install
-    : $(USE_ICU4C)
-    ;
-  explicit "$(compiler-prefix)/include/unicode/uchar.h" ;
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  return "<location>$(includedir)" ;
 }
+
+make unicode/uchar.h
+  : compiler-dep
+    srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified
+  : @make-install
+  : $(USE_ICU4C)
+    <conditional>@location-conditional
+  ;
+explicit unicode/uchar.h ;
 
 rule make-install ( targets * : sources * : properties * )
 {
@@ -218,7 +233,7 @@ rule make-install ( targets * : sources * : properties * )
   assert-specified   <icu4c-hidden>       : $(properties) ;
 
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local compiler-description = [ "$(INTRO_ROOT_DIR)/compilers.get-compiler-description" $(compiler) ] ;
+  local compiler-description = [ get-compiler-description $(compiler) ] ;
   COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <icu4c> : $(properties) ] ;
@@ -233,7 +248,12 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) = ;
 
-  OPTIONS on $(targets) += --enable-debug ;
+  local variant = [ feature.get-values <variant> : $(properties) ] ;
+  if $(variant) = debug
+  {
+    OPTIONS on $(targets) += --enable-debug ;
+    OPTIONS on $(targets) += --disable-release ;
+  }
 
   local triplet = [ feature.get-values <triplet> : $(properties) ] ;
   if $(triplet) = i686-pc-cygwin
@@ -253,22 +273,33 @@ rule make-install ( targets * : sources * : properties * )
     errors.error "an internal error." ;
   }
 
-  # Set the '--build' and '--host' options for the 'configure' script.
+  # Set `--prefix' option for `configure' script.
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
+  OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
+
+  # Set `--bindir' option for `configure' script.
+  local bindir = [ get-bindir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  local bindir-native = [ path.native "$(bindir)" ] ;
+  OPTIONS on $(targets) += "--bindir='$(bindir-native)'" ;
+
+  # Set `--libdir' option for `configure' script.
+  local libdir = [ get-libdir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  local libdir-native = [ path.native "$(libdir)" ] ;
+  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
+
+  # Set `--includedir' option for `configure' script.
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  local includedir-native = [ path.native "$(includedir)" ] ;
+  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
+
+  # Set `--build' and `--host' options for `configure' script.
   TRIPLET on $(targets) = $(triplet) ;
   OPTIONS on $(targets) += --build=$(triplet) ;
   OPTIONS on $(targets) += --host=$(triplet) ;
 
-  # Set the '--prefix' option for the 'configure' script.
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  OPTIONS on $(targets) += "--prefix=\"$(compiler-prefix)\"" ;
-
-  OPTIONS on $(targets) += --enable-release ;
-
-  OPTIONS on $(targets) += --enable-static ;
   OPTIONS on $(targets) += --enable-shared ;
-
-  OPTIONS on $(targets) += --enable-threads ;
+  OPTIONS on $(targets) += --enable-static ;
 
   if $(triplet) = i686-pc-linux-gnu || $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32
   {
@@ -283,105 +314,104 @@ rule make-install ( targets * : sources * : properties * )
     errors.error "an internal error." ;
   }
 
-  local cc = [ "$(INTRO_ROOT_DIR)/compilers.cc" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
-  OPTIONS on $(targets) += "CC=\"$(cc)\"" ;
+  local cc = [ get-cc "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  cc = [ path.native "$(cc)" ] ;
+  OPTIONS on $(targets) += "CC='$(cc)'" ;
 
-  local cxx = [ "$(INTRO_ROOT_DIR)/compilers.cxx" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
-  OPTIONS on $(targets) += "CXX=\"$(cxx)\"" ;
+  local cflags = [ get-cflags $(properties) ] ;
+  if $(cflags)
+  {
+    CFLAGS on $(targets) = "$(cflags)" ;
+  }
 
-  PREPEND_SHARED_LIBRARY_PATH_VARIABLE_COMMAND on $(targets) = [ "$(INTRO_ROOT_DIR)/compilers.prepend-shared-library-path-variable-command" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  local cxx = [ get-cxx "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  cxx = [ path.native "$(cxx)" ] ;
+  OPTIONS on $(targets) += "CXX='$(cxx)'" ;
+
+  local cxxflags = [ get-cxxflags $(properties) ] ;
+  if $(cxxflags)
+  {
+    CXXFLAGS on $(targets) = "$(cxxflags)" ;
+  }
+
+  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 }
 actions make-install
 {
-  [ -x "$(SRCDIR)/source/runConfigureICU" ] || exit 1
-  chmod +x "$(SRCDIR)/source/config.sub" || exit 1
-  [ `"$(SRCDIR)/source/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  [ -x '$(SRCDIR)/source/runConfigureICU' ] || exit 1
+  chmod +x '$(SRCDIR)/source/config.sub' || exit 1
+  [ `'$(SRCDIR)/source/config.sub' $(TRIPLET)` = $(TRIPLET) ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
-  { mkdir -p "$(OBJDIR)" && ( cd "$(OBJDIR)" && rm -rf * ); } || exit 1
+  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
 
-  $(PREPEND_SHARED_LIBRARY_PATH_VARIABLE_COMMAND)
+  $(ENVIRONMENT_COMMANDS)
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && "$(SRCDIR)/source/runConfigureICU" $(OPTIONS) >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && CFLAGS='$(CFLAGS)' CXXFLAGS='$(CXXFLAGS)' '$(SRCDIR)/source/runConfigureICU' $(OPTIONS) >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && "$(SRCDIR)/source/runConfigureICU" $(OPTIONS) )
+    ( cd '$(OBJDIR)' && CFLAGS='$(CFLAGS)' CXXFLAGS='$(CXXFLAGS)' '$(SRCDIR)/source/runConfigureICU' $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to \`runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
 
   # Check the creation of `Makefile'.
-  [ -f "$(OBJDIR)/Makefile" ] || exit 1
+  [ -f '$(OBJDIR)/Makefile' ] || exit 1
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) )
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to \`make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
 
-  if [ -n "$(STREAM)" ]; then
+  if [ -n '$(STREAM)' ]; then
     # `make check' of ICU4C does not support parallel build.
-    ( cd "$(OBJDIR)" && make check >> "$(STREAM)" 2>&1 )
+    ( cd '$(OBJDIR)' && make check >> '$(STREAM)' 2>&1 )
   else
     # `make check' of ICU4C does not support parallel build.
-    ( cd "$(OBJDIR)" && make check )
+    ( cd '$(OBJDIR)' && make check )
   fi
   if [ $? -ne 0 ]; then
     if uname | grep -Fq 'CYGWIN' && [ `echo $(VERSION) `x = 49.1.1x ]; then
-      echo "WARNING: failed to 'make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-      echo -n "WARNING: failed to 'make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+      echo    "WARNING: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+      echo -n "WARNING: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
     else
-      echo "ERROR: failed to 'make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-      echo -n "ERROR: failed to 'make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+      echo    "ERROR: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+      echo -n "ERROR: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
       exit 1
     fi
   fi
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && make install >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && make install >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && make install )
+    ( cd '$(OBJDIR)' && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to \`make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
 
-  [ -f "$(<)" ] || exit 1
+  [ -f '$(<)' ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
-  rm -rf "$(OBJDIR)" || exit 1
+  rm -rf '$(OBJDIR)' || exit 1
 
-  echo -n "ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built." | $(AWACS)
+  echo -n 'ICU4C $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built.' | $(AWACS)
   exit 0
 }
 
 
 
-rule install-req ( properties * )
-{
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-  assert-unspecified <icu4c>              : $(properties) ;
-  assert-specified   <icu4c-hidden>       : $(properties) ;
-
-  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  return <source>"$(compiler-prefix)/include/unicode/uchar.h" ;
-}
-
-alias install : : <conditional>@install-req ;
+alias install : unicode/uchar.h ;
 explicit install ;
