GCC build now uses `gmp/', `mpfr/' and `mpc/' subdirectories. Fixed bugs.

diff --git a/stage1/binutils/jamfile b/stage1/binutils/jamfile
--- a/stage1/binutils/jamfile
+++ b/stage1/binutils/jamfile
@@ -30,7 +30,8 @@ rule gcc-dep-req ( properties * )
     result = $(result)/<mpc-version>$(mpc-version) ;
     result = $(result)/<mpc-version-hidden>unspecified ;
     # `<gcc-version>' is automatically propagated.
-    # `<gcc-default>yes' is automatically propagated. ;
+    # `<enable-cross-crt>' is automatically propagated.
+    # `<enable-cross-binutils>yes' is automatically propagated.
   }
   return $(result) ;
 }
@@ -56,7 +57,7 @@ actions download-binutils
       || { echo "ERROR: failed to download the Binutils tarball." 2>>"$(STDOUT_)" 1>&2; exit 1; }
     [ -f "$(TARBALL_BZ2)" ] || exit 1
   fi
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -94,7 +95,7 @@ actions expand-binutils
     fi
     [ -x "$(DEST_DIR)/configure" ] || exit 1
   fi
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -224,7 +225,11 @@ actions make-binutils
     echo "ERROR: failed to 'configure' for the Binutils build." 2>>"$(STDERR_)" 1>&2
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || { $(UNSET_RUN_VARS); $(UNSET_RUNTIME_SYMLINK); exit 1; }
+  if [ ! -f "$(<:D)/build/Makefile" ]; then
+    $(UNSET_RUN_VARS)
+    $(UNSET_RUNTIME_SYMLINK)
+    exit 1
+  fi
   ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) 1>>"$(STDOUT_)" 2>>"$(STDERR_)" )
   if [ $? -ne 0 ]; then
     $(UNSET_RUN_VARS)
@@ -250,7 +255,7 @@ actions make-binutils
   fi
   $(UNSET_RUN_VARS)
   $(UNSET_RUNTIME_SYMLINK)
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -310,17 +315,17 @@ rule test-binutils ( targets * : sources * : properties * )
 }
 actions test-binutils
 {
-  rm -f "$(<)" || exit $?
+  rm -f "$(<)" || { rm -f "$(<:D)/make"; exit 1; }
   [ -e "$(LD)" ] || { rm -f "$(<:D)/make"; exit 1; }
   if [ $(TEST) = yes ]; then
     $(SET_RUN_VARS)
-    { "$(LD)" -v || exit $?; } | grep -Fq "$(VERSION)"
+    { ( LC_ALL=C "$(LD)" -v ) || { rm -f "$(<:D)/make"; exit 1; }; } | grep -Fq "$(VERSION)"
     result=$?
     $(UNSET_RUN_VARS)
     [ $result -eq 0 ] || { rm -f "$(<:D)/make"; exit 1; }
   fi
   [ ! -e "$(<)" ] || { rm -f "$(<:D)/make"; exit 1; }
-  touch "$(<)"
+  touch "$(<)" || { rm -f "$(<:D)/make"; exit 1; }
 }
 
 
@@ -423,12 +428,17 @@ rule install-req ( properties * )
     errors.error "ERROR: `<gcc-version>' is not specified for the Binutils stage 3 build." ;
   }
 
-  local gcc-default = [ feature.get-values <gcc-default> : $(properties) ] ;
-  if $(stage) = 2 && $(gcc-default) != unspecified {
-    errors.error "ERROR: `<gcc-default>$(gcc-default)' is not valid for the Binutils stage 2 build." ;
+  local enable-cross-crt = [ feature.get-values <enable-cross-crt> : $(properties) ] ;
+  if $(stage) = 2 && $(enable-cross-crt) != unspecified {
+    errors.error "ERROR: `<enable-cross-crt>$(enable-cross-crt)' is not valid for the Binutils stage 2 build." ;
   }
-  if $(stage) = 3 && $(gcc-default) != yes {
-    errors.error "ERROR: `<gcc-default>no' is not valid for the Binutils stage 3 build." ;
+  if $(stage) = 3 && $(enable-cross-crt) = unspecified {
+    errors.error "ERROR: `<enable-cross-crt>' is not specified for the Binutils stage 3 build." ;
+  }
+
+  local enable-cross-binutils = [ feature.get-values <enable-cross-binutils> : $(properties) ] ;
+  if $(enable-cross-binutils) != yes {
+    errors.error "ERROR: `<enable-cross-binutils>$(enable-cross-binutils)' is not valid for the Binutils build." ;
   }
 
   return $(result) ;
diff --git a/stage1/gmp/jamfile b/stage1/gmp/jamfile
--- a/stage1/gmp/jamfile
+++ b/stage1/gmp/jamfile
@@ -32,7 +32,8 @@ rule gcc-dep-req ( properties * )
     result = $(result)/<mpc-version>$(mpc-version) ;
     result = $(result)/<mpc-version-hidden>unspecified ;
     # `<gcc-version>' is automatically propagated.
-    result = $(result)/<gcc-default>yes ;
+    # `<enable-cross-crt>' is automatically propagated.
+    # `<enable-cross-binutils>' is automatically propagated.
   }
   return $(result) ;
 }
@@ -46,25 +47,29 @@ rule crt-dep-req ( properties * )
   local result ;
   local stage = [ feature.get-values <intro-stage> : $(properties) ] ;
   local host = [ feature.get-values <intro-host> : $(properties) ] ;
+  local enable-cross-crt = [ feature.get-values <enable-cross-crt> : $(properties) ] ;
   if $(stage) = 3 && [ regex.match "(-w64-mingw32)$" : $(host) : 1 ] {
-    result = <source>../../stage3//mingw-w64-crt//install ;
-    # `<intro-stage>3' is automatically propagated.
-    # `<intro-host>' is automatically propagated.
-    result = $(result)/<intro-link>unspecified ;
-    local multilib = [ feature.get-values <intro-multilib-hidden> : $(properties) ] ;
-    result = $(result)/<intro-multilib>$(multilib) ;
-    result = $(result)/<intro-multilib-hidden>unspecified ;
-    # `<binutils-version>' is automatically propagated.
-    # `<binutils-version-hidden>unspecified' is automatically propagated.
-    local gmp-version = [ feature.get-values <gmp-version> : $(properties) ] ;
-    result = $(result)/<gmp-version>unspecified ;
-    result = $(result)/<gmp-version-hidden>$(gmp-version) ;
-    # `<mpfr-version>unspecified' is automatically propagated.
-    # `<mpfr-version-hidden>' is automatically propagated.
-    # `<mpc-version>unspecified' is automatically propagated.
-    # `<mpc-version-hidden>' is automatically propagated.
-    # `<gcc-version>' is automatically propagated.
-    result = $(result)/<gcc-default>yes ;
+    if $(enable-cross-crt) = yes {
+      result = <source>../../stage3//mingw-w64-crt//install ;
+      # `<intro-stage>3' is automatically propagated.
+      # `<intro-host>' is automatically propagated.
+      result = $(result)/<intro-link>unspecified ;
+      local multilib = [ feature.get-values <intro-multilib-hidden> : $(properties) ] ;
+      result = $(result)/<intro-multilib>$(multilib) ;
+      result = $(result)/<intro-multilib-hidden>unspecified ;
+      # `<binutils-version>' is automatically propagated.
+      # `<binutils-version-hidden>unspecified' is automatically propagated.
+      local gmp-version = [ feature.get-values <gmp-version> : $(properties) ] ;
+      result = $(result)/<gmp-version>unspecified ;
+      result = $(result)/<gmp-version-hidden>$(gmp-version) ;
+      # `<mpfr-version>unspecified' is automatically propagated.
+      # `<mpfr-version-hidden>' is automatically propagated.
+      # `<mpc-version>unspecified' is automatically propagated.
+      # `<mpc-version-hidden>' is automatically propagated.
+      # `<gcc-version>' is automatically propagated.
+      # `<enable-cross-crt>yes' is automatically propagated.
+      # `<enable-cross-binutils>' is automatically propagated.
+    }
   }
   return $(result) ;
 }
@@ -91,7 +96,7 @@ actions download-gmp
       || { echo "ERROR: failed to download the GMP tarball." 2>>"$(STDOUT_)" 1>&2; exit 1; }
     [ -f "$(TARBALL_BZ2)" ] || exit 1
   fi
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -107,10 +112,78 @@ rule expand-gmp ( targets * : sources * : properties * )
   if $(sources[2]) {
     errors.error "ERROR: wrong number of sources." ;
   }
+
   local version = [ feature.get-values <gmp-version> : $(properties) ] ;
   TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/gmp-$(version).tar.gz ;
   TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/gmp-$(version).tar.bz2 ;
   DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/gmp-$(version) ;
+
+  local stage = [ feature.get-values <intro-stage> : $(properties) ] ;
+  if $(stage) != 1 {
+    errors.error "ERROR: `<intro-stage>$(stage)' is not valid for the GMP `expand' target." ;
+  }
+
+  local host = [ feature.get-values <intro-host> : $(properties) ] ;
+  if $(host) != unspecified {
+    errors.error "ERROR: `<intro-host>$(host)' is not valid for the GMP `expand' target." ;
+  }
+
+  local link = [ feature.get-values <intro-link> : $(properties) ] ;
+  if $(link) != unspecified {
+    errors.error "ERROR: `<intro-link>$(link)' is not valid for the GMP `expand' target." ;
+  }
+
+  local multilib = [ feature.get-values <intro-multilib> : $(properties) ] ;
+  if $(multilib) != unspecified {
+    errors.error "ERROR: `<intro-multilib>$(multilib)' is not valid for the GMP `expand' target." ;
+  }
+
+  local binutils-version = [ feature.get-values <binutils-version> : $(properties) ] ;
+  if $(binutils-version) != unspecified {
+    errors.error "ERROR: `<binutils-version>$(binutils-version)' is not valid for the GMP `expand' target." ;
+  }
+  binutils-version = [ feature.get-values <binutils-version-hidden> : $(properties) ] ;
+  if $(binutils-version) != unspecified {
+    errors.error "ERROR: `<binutils-version-hidden>$(binutils-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local gmp-version = [ feature.get-values <gmp-version-hidden> : $(properties) ] ;
+  if $(gmp-version) != unspecified {
+    errors.error "ERROR: `<gmp-version-hidden>$(gmp-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local mpfr-version = [ feature.get-values <mpfr-version> : $(properties) ] ;
+  if $(mpfr-version) != unspecified {
+    errors.error "ERROR: `<mpfr-version>$(mpfr-version)' is not valid for the GMP `expand' target." ;
+  }
+  mpfr-version = [ feature.get-values <mpfr-version-hidden> : $(properties) ] ;
+  if $(mpfr-version) != unspecified {
+    errors.error "ERROR: `<mpfr-version-hidden>$(mpfr-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local mpc-version = [ feature.get-values <mpc-version> : $(properties) ] ;
+  if $(mpc-version) != unspecified {
+    errors.error "ERROR: `<mpc-version>$(mpc-version)' is not valid for the GMP `expand' target." ;
+  }
+  mpc-version = [ feature.get-values <mpc-version-hidden> : $(properties) ] ;
+  if $(mpc-version) != unspecified {
+    errors.error "ERROR: `<mpc-version-hidden>$(mpc-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local gcc-version = [ feature.get-values <gcc-version> : $(properties) ] ;
+  if $(gcc-version) != unspecified {
+    errors.error "ERROR: `<gcc-version>$(gcc-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local enable-cross-binutils = [ feature.get-values <enable-cross-binutils> : $(properties) ] ;
+  if $(enable-cross-binutils) != unspecified {
+    errors.error "ERROR: `<enable-cross-binutils>$(enable-cross-binutils)' is not valid for the GMP `expand' target." ;
+  }
+
+  local enable-cross-crt = [ feature.get-values <enable-cross-crt> : $(properties) ] ;
+  if $(enable-cross-crt) != unspecified {
+    errors.error "ERROR: `<enable-cross-crt>$(enable-cross-crt)' is not valid for the GMP `expand' target." ;
+  }
 }
 actions expand-gmp
 {
@@ -129,7 +202,7 @@ actions expand-gmp
     fi
     [ -x "$(DEST_DIR)/configure" ] || exit 1
   fi
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -262,7 +335,7 @@ actions make-gmp
   fi
   $(UNSET_RUN_VARS)
   $(UNSET_RUNTIME_SYMLINK)
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -488,9 +561,28 @@ rule install-req ( properties * )
     errors.error "ERROR: '<gcc-version>' is not specified for the GMP stage 2 or 3 build." ;
   }
 
-  local gcc-default = [ feature.get-values <gcc-default> : $(properties) ] ;
-  if $(gcc-default) != unspecified {
-    errors.error "ERROR: '<gcc-default>$(gcc-default)' is not valid for the GMP build." ;
+  local enable-cross-crt = [ feature.get-values <enable-cross-crt> : $(properties) ] ;
+  if $(stage) = 1 {
+    if $(enable-cross-crt) != unspecified {
+      errors.error "ERROR: `<enable-cross-crt>$(enable-cross-crt)' is not valid for the GMP stage 1 build." ;
+    }
+  }
+  else {
+    if $(enable-cross-crt) = unspecified {
+      errors.error "ERROR: `<enable-cross-crt>' is not specified for the GMP stage 2 or 3 build." ;
+    }
+  }
+
+  local enable-cross-binutils = [ feature.get-values <enable-cross-binutils> : $(properties) ] ;
+  if $(stage) = 1 {
+    if $(enable-cross-binutils) != unspecified {
+      errors.error "ERROR: `<enable-cross-binutils>$(enable-cross-binutils)' is not valid for the GMP stage 1 build." ;
+    }
+  }
+  else {
+    if $(enable-cross-binutils) = unspecified {
+      errors.error "ERROR: `<enable-cross-binutils>' is not specified for the GMP stage 2 or 3 build." ;
+    }
   }
 
   return $(result) ;
diff --git a/stage1/mingw-w64-crt/jamfile b/stage1/mingw-w64-crt/jamfile
--- a/stage1/mingw-w64-crt/jamfile
+++ b/stage1/mingw-w64-crt/jamfile
@@ -9,31 +9,24 @@ import regex ;
 
 rule mingw-w64-headers-dep-req ( properties * )
 {
-  local result ;
-  local stage = [ feature.get-values <intro-stage> : $(properties) ] ;
-  if $(stage) = 3 {
-    if [ regex.match "(-w64-mingw32)$" : $(HOST) : 1 ] {
-      result = <source>../mingw-w64-headers//install ;
-      # `<intro-stage>3' is automatically propagated.
-      # `<intro-host>' is automatically propagated.
-      # `<intro-link>unspecified' is automatically propagated.
-      result = $(result)/<intro-multilib>unspecified ;
-      # `<intro-multilib-hidden>unspecified' is automatically propagated.
-      result = $(result)/<binutils-version>unspecified ;
-      # `<binutils-version-hidden>unspecified' is automatically propagated.
-      # `<gmp-version>unspecified' is automatically propagated.
-      result = $(result)/<gmp-version-hidden>unspecified ;
-      # `<mpfr-version>unspecified' is automatically propagated.
-      result = $(result)/<mpfr-version-hidden>unspecified ;
-      # `<mpc-version>unspecified' is automatically propagated.
-      result = $(result)/<mpc-version-hidden>unspecified ;
-      result = $(result)/<gcc-version>unspecified ;
-      result = $(result)/<gcc-default>unspecified ;
-    }
-    else {
-      errors.error "ERROR: unknown cross target." ;
-    }
-  }
+  # For stage 2 and 3.
+  local result = <source>../mingw-w64-headers//install ;
+  # `<intro-stage>' is automatically propagated.
+  # `<intro-host>' is automatically propagated.
+  # `<intro-link>unspecified' is automatically propagated.
+  result = $(result)/<intro-multilib>unspecified ;
+  # `<intro-multilib-hidden>unspecified' is automatically propagated.
+  result = $(result)/<binutils-version>unspecified ;
+  # `<binutils-version-hidden>unspecified' is automatically propagated.
+  # `<gmp-version>unspecified' is automatically propagated.
+  result = $(result)/<gmp-version-hidden>unspecified ;
+  # `<mpfr-version>unspecified' is automatically propagated.
+  result = $(result)/<mpfr-version-hidden>unspecified ;
+  # `<mpc-version>unspecified' is automatically propagated.
+  result = $(result)/<mpc-version-hidden>unspecified ;
+  result = $(result)/<gcc-version>unspecified ;
+  result = $(result)/<enable-cross-binutils>unspecified ;
+  # `<enable-cross-crt>yes' is automatically propagated.
   return $(result) ;
 }
 alias mingw-w64-headers-dep : : <conditional>@mingw-w64-headers-dep-req ;
@@ -42,29 +35,27 @@ explicit mingw-w64-headers-dep ;
 
 rule gcc-stage1-dep-req ( properties * )
 {
-  local result ;
-  local stage = [ feature.get-values <intro-stage> : $(properties) ] ;
-  if $(stage) = 2 || $(stage) = 3 {
-    result = <source>../../stage2/gcc//mingw32-stage1.make ;
-    result = $(result)/<intro-stage>2 ;
-    # `<intro-host>' is automatically propagated.
-    # `<intro-link>unspecified' is automatically propagated.
-    # `<intro-multilib>' is automatically propagated.
-    # `<intro-multilib-hidden>unspecified' is automatically propagated.
-    # `<binutils-version>' is automatically propagated.
-    # `<binutils-version-hidden>unspecified' is automatically propagated.
-    local gmp-version = [ feature.get-values <gmp-version-hidden> : $(properties) ] ;
-    result = $(result)/<gmp-version>$(gmp-version) ;
-    result = $(result)/<gmp-version-hidden>unspecified ;
-    local mpfr-version = [ feature.get-values <mpfr-version-hidden> : $(properties) ] ;
-    result = $(result)/<mpfr-version>$(mpfr-version) ;
-    result = $(result)/<mpfr-version-hidden>unspecified ;
-    local mpc-version = [ feature.get-values <mpc-version-hidden> : $(properties) ] ;
-    result = $(result)/<mpc-version>$(mpc-version) ;
-    result = $(result)/<mpc-version-hidden>unspecified ;
-    # `<gcc-version>' is automatically propagated.
-    # `<gcc-default>yes' is automatically propagated.
-  }
+  # For stage 2 and 3.
+  local result = <source>../../stage2/gcc//mingw32-stage1.make ;
+  result = $(result)/<intro-stage>2 ;
+  # `<intro-host>' is automatically propagated.
+  # `<intro-link>unspecified' is automatically propagated.
+  # `<intro-multilib>' is automatically propagated.
+  # `<intro-multilib-hidden>unspecified' is automatically propagated.
+  # `<binutils-version>' is automatically propagated.
+  # `<binutils-version-hidden>unspecified' is automatically propagated.
+  local gmp-version = [ feature.get-values <gmp-version-hidden> : $(properties) ] ;
+  result = $(result)/<gmp-version>$(gmp-version) ;
+  result = $(result)/<gmp-version-hidden>unspecified ;
+  local mpfr-version = [ feature.get-values <mpfr-version-hidden> : $(properties) ] ;
+  result = $(result)/<mpfr-version>$(mpfr-version) ;
+  result = $(result)/<mpfr-version-hidden>unspecified ;
+  local mpc-version = [ feature.get-values <mpc-version-hidden> : $(properties) ] ;
+  result = $(result)/<mpc-version>$(mpc-version) ;
+  result = $(result)/<mpc-version-hidden>unspecified ;
+  # `<gcc-version>' is automatically propagated.
+  # `<enable-cross-binutils>' is automatically propagated.
+  # `<enable-cross-crt>yes' is automatically propagated.
   return $(result) ;
 }
 alias gcc-stage1-dep : : <conditional>@gcc-stage1-dep-req ;
@@ -168,7 +159,10 @@ actions make-mingw-w64-crt
     echo "ERROR: failed to 'configure' for the mingw-w64-crt build." 2>>"$(STDERR_)" 1>&2
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || { $(UNSET_RUN_VARS); exit 1; }
+  if [ ! -f "$(<:D)/build/Makefile" ]; then
+    $(UNSET_RUN_VARS)
+    exit 1
+  fi
   ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) 1>>"$(STDOUT_)" 2>>"$(STDERR_)" )
   if [ $? -ne 0 ]; then
     $(UNSET_RUN_VARS)
@@ -190,7 +184,7 @@ actions make-mingw-w64-crt
     exit 1
   fi
   $(UNSET_RUN_VARS)
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -276,9 +270,14 @@ rule install-req ( properties * )
     errors.error "ERROR: `<gcc-version>' is not specified for the mingw-w64-crt build." ;
   }
 
-  local gcc-default = [ feature.get-values <gcc-default> : $(properties) ] ;
-  if $(gcc-default) != yes {
-    errors.error "ERROR: `<gcc-default>$(gcc-default)' is not valid for the mingw-w64-crt build." ;
+  local enable-cross-binutils = [ feature.get-values <enable-cross-binutils> : $(properties) ] ;
+  if $(enable-cross-binutils) = unspecified {
+    errors.error "ERROR: `<enable-cross-binutils>' is not specified for the mingw-w64-crt build." ;
+  }
+
+  local enable-cross-crt = [ feature.get-values <enable-cross-crt> : $(properties) ] ;
+  if $(enable-cross-crt) != yes {
+    errors.error "ERROR: `<enable-cross-crt>$(enable-cross-crt)' is not valid for the mingw-w64-crt build." ;
   }
 
   return $(result) ;
diff --git a/stage1/mingw-w64-headers/jamfile b/stage1/mingw-w64-headers/jamfile
--- a/stage1/mingw-w64-headers/jamfile
+++ b/stage1/mingw-w64-headers/jamfile
@@ -12,8 +12,8 @@ explicit download ;
 
 rule download-mingw-w64 ( targets * : sources * : properties * )
 {
-  URL on $(targets) = "http://downloads.sourceforge.net/project/mingw-w64/mingw-w64/mingw-w64-snapshot/mingw-w64-v1.0-snapshot-20110428.tar.bz2" ;
-  TARBALL on $(targets) = "$(INTRO_ROOT_DIR)/mingw-w64-v1.0-snapshot-20110428.tar.bz2" ;
+  URL on $(targets) = "http://downloads.sourceforge.net/project/mingw-w64/mingw-w64/mingw-w64-snapshot/mingw-w64-v1.0-snapshot-20110523.tar.bz2" ;
+  TARBALL on $(targets) = "$(INTRO_ROOT_DIR)/mingw-w64-v1.0-snapshot-20110523.tar.bz2" ;
 }
 actions download-mingw-w64
 {
@@ -23,7 +23,7 @@ actions download-mingw-w64
       || { echo "ERROR: failed to download the MinGW-w64 tarball." 2>>"$(STDOUT_)" 1>&2; exit 1; }
     [ -f "$(TARBALL)" ] || exit 1
   fi
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -39,8 +39,8 @@ rule expand-mingw-w64 ( targets * : sources * : properties * )
   if $(sources[2]) {
     errors.error "ERROR: wrong number of sources." ;
   }
-  TARBALL on $(targets) = $(INTRO_ROOT_DIR)/mingw-w64-v1.0-snapshot-20110428.tar.bz2 ;
-  DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/mingw-w64-v1.0-20110428 ;
+  TARBALL on $(targets) = $(INTRO_ROOT_DIR)/mingw-w64-v1.0-snapshot-20110523.tar.bz2 ;
+  DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/mingw-w64-v1.0-20110523 ;
 }
 actions expand-mingw-w64
 {
@@ -53,7 +53,7 @@ actions expand-mingw-w64
       || { echo "ERROR: failed to expand the tarball for the MinGW-w64 build." 2>>"$(STDERR_)" 1>&2; exit 1; }
     [ -x "$(DEST_DIR)/mingw-w64-headers/configure" ] || exit 1
   fi
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -69,7 +69,7 @@ rule make-mingw-w64-headers ( targets * : sources * : properties * )
   OPTIONS on $(targets) = ;
 
   # Set the path to the 'configure' file.
-  local configure = $(INTRO_ROOT_DIR)/mingw-w64-v1.0-20110428/mingw-w64-headers/configure ;
+  local configure = $(INTRO_ROOT_DIR)/mingw-w64-v1.0-20110523/mingw-w64-headers/configure ;
   CONFIGURE on $(targets) = $(configure) ;
 
   # Set the '--build' and '--host' options for the 'configure' script.
@@ -130,7 +130,7 @@ actions make-mingw-w64-headers
     ln -sf "$(PREFIX)/$(HOST)/lib" "$(PREFIX)/$(HOST)/lib64" || exit $?
   fi
   $(UNSET_RUN_VARS)
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -204,9 +204,14 @@ rule install-req ( properties * )
     errors.error "ERROR: `<gcc-version>$(gcc-version)' is not valid for the mingw-w64-headers build." ;
   }
 
-  local gcc-default = [ feature.get-values <gcc-default> : $(properties) ] ;
-  if $(gcc-default) != unspecified {
-    errors.error "ERROR: `<gcc-default>$(gcc-default)' is not valid for the mingw-w64-headers build." ;
+  local enable-cross-binutils = [ feature.get-values <enable-cross-binutils> : $(properties) ] ;
+  if $(enable-cross-binutils) != unspecified {
+    errors.error "ERROR: `<enable-cross-binutils>$(enable-cross-binutils)' is not valid for the mingw-w64-headers build." ;
+  }
+
+  local enable-cross-crt = [ feature.get-values <enable-cross-crt> : $(properties) ] ;
+  if $(enable-cross-crt) != yes {
+    errors.error "ERROR: `<enable-cross-crt>$(enable-cross-crt)' is not valid for the mingw-w64-headers build." ;
   }
 
   return $(result) ;
diff --git a/stage1/mpc/jamfile b/stage1/mpc/jamfile
--- a/stage1/mpc/jamfile
+++ b/stage1/mpc/jamfile
@@ -37,7 +37,8 @@ rule mpfr-dep-req ( properties * )
     result = $(result)/<mpc-version-hidden>$(mpc-version) ;
   }
   # `<gcc-version>' is automatically propagated.
-  # `<gcc-default>unspecified' is automatically propagated.
+  # `<enable-cross-crt>' is automatically propagated.
+  # `<enable-cross-binutils>' is automatically propagated.
   return $(result) ;
 }
 
@@ -63,7 +64,7 @@ actions download-mpc
       || { echo "ERROR: failed to download the MPC tarball." 2>>"$(STDOUT_)" 1>&2; exit 1; }
     [ -f "$(TARBALL_GZ)" ] || exit 1
   fi
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -83,6 +84,73 @@ rule expand-mpc ( targets * : sources * : properties * )
   TARBALL_GZ on $(targets) = $(INTRO_ROOT_DIR)/mpc-$(version).tar.gz ;
   TARBALL_BZ2 on $(targets) = $(INTRO_ROOT_DIR)/mpc-$(version).tar.bz2 ;
   DEST_DIR on $(targets) = $(INTRO_ROOT_DIR)/mpc-$(version) ;
+
+  local stage = [ feature.get-values <intro-stage> : $(properties) ] ;
+  if $(stage) != 1 {
+    errors.error "ERROR: `<intro-stage>$(stage)' is not valid for the GMP `expand' target." ;
+  }
+
+  local host = [ feature.get-values <intro-host> : $(properties) ] ;
+  if $(host) != unspecified {
+    errors.error "ERROR: `<intro-host>$(host)' is not valid for the GMP `expand' target." ;
+  }
+
+  local link = [ feature.get-values <intro-link> : $(properties) ] ;
+  if $(link) != unspecified {
+    errors.error "ERROR: `<intro-link>$(link)' is not valid for the GMP `expand' target." ;
+  }
+
+  local multilib = [ feature.get-values <intro-multilib> : $(properties) ] ;
+  if $(multilib) != unspecified {
+    errors.error "ERROR: `<intro-multilib>$(multilib)' is not valid for the GMP `expand' target." ;
+  }
+
+  local binutils-version = [ feature.get-values <binutils-version> : $(properties) ] ;
+  if $(binutils-version) != unspecified {
+    errors.error "ERROR: `<binutils-version>$(binutils-version)' is not valid for the GMP `expand' target." ;
+  }
+  binutils-version = [ feature.get-values <binutils-version-hidden> : $(properties) ] ;
+  if $(binutils-version) != unspecified {
+    errors.error "ERROR: `<binutils-version-hidden>$(binutils-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local gmp-version = [ feature.get-values <gmp-version> : $(properties) ] ;
+  if $(gmp-version) != unspecified {
+    errors.error "ERROR: `<gmp-version>$(gmp-version)' is not valid for the GMP `expand' target." ;
+  }
+  gmp-version = [ feature.get-values <gmp-version-hidden> : $(properties) ] ;
+  if $(gmp-version) != unspecified {
+    errors.error "ERROR: `<gmp-version-hidden>$(gmp-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local mpfr-version = [ feature.get-values <mpfr-version> : $(properties) ] ;
+  if $(mpfr-version) != unspecified {
+    errors.error "ERROR: `<mpfr-version>$(mpfr-version)' is not valid for the GMP `expand' target." ;
+  }
+  mpfr-version = [ feature.get-values <mpfr-version-hidden> : $(properties) ] ;
+  if $(mpfr-version) != unspecified {
+    errors.error "ERROR: `<mpfr-version-hidden>$(mpfr-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local mpc-version = [ feature.get-values <mpc-version-hidden> : $(properties) ] ;
+  if $(mpc-version) != unspecified {
+    errors.error "ERROR: `<mpc-version-hidden>$(mpc-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local gcc-version = [ feature.get-values <gcc-version> : $(properties) ] ;
+  if $(gcc-version) != unspecified {
+    errors.error "ERROR: `<gcc-version>$(gcc-version)' is not valid for the GMP `expand' target." ;
+  }
+
+  local enable-cross-binutils = [ feature.get-values <enable-cross-binutils> : $(properties) ] ;
+  if $(enable-cross-binutils) != unspecified {
+    errors.error "ERROR: `<enable-cross-binutils>$(enable-cross-binutils)' is not valid for the GMP `expand' target." ;
+  }
+
+  local enable-cross-crt = [ feature.get-values <enable-cross-crt> : $(properties) ] ;
+  if $(enable-cross-crt) != unspecified {
+    errors.error "ERROR: `<enable-cross-crt>$(enable-cross-crt)' is not valid for the GMP `expand' target." ;
+  }
 }
 actions expand-mpc
 {
@@ -101,7 +169,7 @@ actions expand-mpc
     fi
     [ -x "$(DEST_DIR)/configure" ] || exit 1
   fi
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -256,7 +324,7 @@ actions make-mpc
   fi
   $(UNSET_RUN_VARS)
   $(UNSET_RUNTIME_SYMLINK)
-  [ -e "$(<)" ] && exit 1
+  [ ! -e "$(<)" ] || exit 1
   touch "$(<)"
 }
 
@@ -483,9 +551,28 @@ rule install-req ( properties * )
     errors.error "ERROR: '<gcc-version>' is not specified for the MPFR stage 2 or 3 build." ;
   }
 
-  local gcc-default = [ feature.get-values <gcc-default> : $(properties) ] ;
-  if $(gcc-default) != unspecified {
-    errors.error "ERROR: '<gcc-default>$(gcc-default)' is not valid for the MPFR build." ;
+  local enable-cross-crt = [ feature.get-values <enable-cross-crt> : $(properties) ] ;
+  if $(stage) = 1 {
+    if $(enable-cross-crt) != unspecified {
+      errors.error "ERROR: `<enable-cross-crt>$(enable-cross-crt)' is not valid for the GMP stage 1 build." ;
+    }
+  }
+  else {
+    if $(enable-cross-crt) = unspecified {
+      errors.error "ERROR: `<enable-cross-crt>' is not specified for the GMP stage 2 or 3 build." ;
+    }
+  }
+
+  local enable-cross-binutils = [ feature.get-values <enable-cross-binutils> : $(properties) ] ;
+  if $(stage) = 1 {
+    if $(enable-cross-binutils) != unspecified {
+      errors.error "ERROR: `<enable-cross-binutils>$(enable-cross-binutils)' is not valid for the GMP stage 1 build." ;
+    }
+  }
+  else {
+    if $(enable-cross-binutils) = unspecified {
+      errors.error "ERROR: `<enable-cross-binutils>' is not specified for the GMP stage 2 or 3 build." ;
+    }
   }
 
   return $(result) ;
