Changed to use `@file` option format for MPC.

diff --git a/mpc/jamfile b/mpc/jamfile
--- a/mpc/jamfile
+++ b/mpc/jamfile
@@ -190,7 +190,8 @@ rule make-install ( targets * : sources * : properties * )
   SRCDIR on $(targets) = [ path.native "$(srcdir)" ] ;
 
   local objdir = "$(INTRO_ROOT_DIR)/objdir" ;
-  OBJDIR on $(targets) = [ path.native "$(objdir)" ] ;
+  local objdir-native = [ path.native "$(objdir)" ] ;
+  OBJDIR on $(targets) = "$(objdir-native)" ;
 
   OPTIONS on $(targets) = ;
 
@@ -259,27 +260,29 @@ rule make-install ( targets * : sources * : properties * )
     #else {
     #  errors.error "an internal error." ;
     #}
-    OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
+    CFLAGS on $(targets) = "$(cflags)" ;
+    OPTIONS on $(targets) += "CFLAGS='@$(objdir-native)/cflags'" ;
   }
 
   # `CXX' and `CXXFLAGS' are not used for MPFR build.
-  #local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
-  #local cxx-native = [ path.native "$(cxx)" ] ;
-  #OPTIONS on $(targets) += "CXX='$(cxx-native)'" ;
-  #
-  #local cxxflags = [ get-cxxflags $(properties) ] ;
-  #if "$(cxxflags)" {
-  #  #if "$(lto)" = "off" {
-  #  #  cxxflags = "$(cxxflags) -g" ;
-  #  #}
-  #  #else if "$(lto)" = "on" {
-  #  #  # Do nothing.
-  #  #}
-  #  #else {
-  #  #  errors.error "an internal error" ;
-  #  #}
-  #  OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
-  #}
+  local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
+  local cxx-native = [ path.native "$(cxx)" ] ;
+  OPTIONS on $(targets) += "CXX='$(cxx-native)'" ;
+
+  local cxxflags = [ get-cxxflags $(properties) ] ;
+  if "$(cxxflags)" {
+    #if "$(lto)" = "off" {
+    #  cxxflags = "$(cxxflags) -g" ;
+    #}
+    #else if "$(lto)" = "on" {
+    #  # Do nothing.
+    #}
+    #else {
+    #  errors.error "an internal error" ;
+    #}
+    CXXFLAGS on $(targets) = "$(cxxflags)" ;
+    OPTIONS on $(targets) += "CXXFLAGS='@$(objdir-native)/cxxflags'" ;
+  }
 
   local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
@@ -299,6 +302,9 @@ actions make-install
   { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
 
   $(ENVIRONMENT_COMMANDS)
+
+  ( cd '$(OBJDIR)' && echo -n '$(CFLAGS)' > cflags ) || exit 1
+  ( cd '$(OBJDIR)' && echo -n '$(CXXFLAGS)' > cxxflags ) || exit 1
 
   if [ -n '$(STREAM)' ]; then
     ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(STREAM)' 2>&1 )
