Added multi-target/multi-binary support for isl.

diff --git a/isl/jamfile b/isl/jamfile
--- a/isl/jamfile
+++ b/isl/jamfile
@@ -5,7 +5,19 @@ import errors ;
 import feature ;
 import make ;
 import path ;
-import "$(INTRO_ROOT_DIR)/compilers" ;
+import "$(INTRO_ROOT_DIR)/compilers"
+  : is-gcc
+    is-clang
+    get-compiler-description
+    get-compiler-prefix
+    get-libdir
+    get-includedir
+    get-cc
+    get-cflags
+    get-cxx
+    get-cxxflags
+    get-environment-commands
+  ;
 
 
 rule assert-specified ( feature : properties * )
@@ -41,11 +53,11 @@ rule compiler-dep-req ( properties * )
   local multitarget = [ feature.get-values <multitarget-hidden> : $(properties) ] ;
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
   local result ;
-  if [ "$(INTRO_ROOT_DIR)/compilers.is-gcc" $(compiler) ]
+  if [ is-gcc $(compiler) ]
   {
     result = <source>../gcc//install/<multitarget>$(multitarget)/<multitarget-hidden>unspecified ;
   }
-  else if [ "$(INTRO_ROOT_DIR)/compilers.is-clang" $(compiler) ]
+  else if [ is-clang $(compiler) ]
   {
     result = <source>../clang//install ;
   }
@@ -195,20 +207,22 @@ explicit srcdir ;
 
 
 
-for local compiler in $(COMPILERS)
+rule location-conditional ( properties * )
 {
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  make "$(compiler-prefix)/include/isl/version.h"
-    : compiler-dep
-      ../gmp//install
-      srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified
-    : @make-install
-    : $(USE_GMP)
-      $(USE_ISL)
-    ;
-  explicit "$(compiler-prefix)/include/isl/version.h" ;
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  return <location>"$(includedir)" ;
 }
+
+make isl/version.h
+  : compiler-dep
+    ../gmp//install
+    srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified
+  : @make-install
+  : $(USE_GMP)
+    $(USE_ISL)
+    <conditional>@location-conditional
+  ;
+explicit isl/version.h ;
 
 rule make-install ( targets * : sources * : properties * )
 {
@@ -223,7 +237,7 @@ rule make-install ( targets * : sources * : properties * )
   assert-unspecified <compiler-hidden>    : $(properties) ;
 
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local compiler-description = [ "$(INTRO_ROOT_DIR)/compilers.get-compiler-description" $(compiler) ] ;
+  local compiler-description = [ get-compiler-description $(compiler) ] ;
   COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <isl> : $(properties) ] ;
@@ -238,12 +252,22 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) = ;
 
-  # Set the '--prefix' option for the 'configure' script.
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  OPTIONS on $(targets) += "--prefix=\"$(compiler-prefix)\"" ;
+  # Set the `--prefix' option for the `configure' script.
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
+  OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
 
-  # Set the '--build' and '--host' options for the 'configure' script.
+  # Set the `--libdir' option for the `configure' script.
+  local libdir = [ get-libdir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  local libdir-native = [ path.native "$(libdir)" ] ;
+  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
+
+  # Set the `--includedir' option for the `configure' script.
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  local includedir-native = [ path.native "$(includedir)" ] ;
+  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
+
+  # Set the `--build' and `--host' options for the `configure' script.
   local triplet = [ feature.get-values <triplet> : $(properties) ] ;
   TRIPLET on $(targets) = $(triplet) ;
   OPTIONS on $(targets) += --build=$(triplet) ;
@@ -252,43 +276,68 @@ rule make-install ( targets * : sources * : properties * )
   # Set the link variants for the 'configure' script.
   if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32
   {
-    OPTIONS on $(targets) += --disable-static ;
     OPTIONS on $(targets) += --enable-shared ;
+    OPTIONS on $(targets) += --disable-static ;
   }
   else
   {
-    OPTIONS on $(targets) += --enable-static ;
     OPTIONS on $(targets) += --enable-shared ;
+    OPTIONS on $(targets) += --enable-static ;
   }
 
-  OPTIONS on $(targets) += --with-gmp=system ;
+  if [ is-clang $(compiler) ]
+  {
+    OPTIONS on $(targets) += "--with-clang=system" ;
+  }
 
-  OPTIONS on $(targets) += --with-gmp-prefix=\"$(compiler-prefix)\" ;
+  # Default `CC' seems `-O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math'.
+  local cc = [ get-cc "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  cc = [ path.native "$(cc)" ] ;
+  OPTIONS on $(targets) += "CC='$(cc)'" ;
 
-  local cc = [ "$(INTRO_ROOT_DIR)/compilers.cc" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
-  OPTIONS on $(targets) += "CC=\"$(cc)\"" ;
+  local cflags = [ get-cflags $(properties) ] ;
+  if $(cflags)
+  {
+    if [ feature.get-values <variant> : $(properties) ] != debug
+    {
+      cflags = "$(cflags) -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math" ;
+    }
+    OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
+  }
 
-  local cxx = [ "$(INTRO_ROOT_DIR)/compilers.cxx" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
-  OPTIONS on $(targets) += "CXX=\"$(cxx)\"" ;
+  local cxx = [ get-cxx "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  cxx = [ path.native "$(cxx)" ] ;
+  OPTIONS on $(targets) += "CXX='$(cxx)'" ;
 
-  PREPEND_SHARED_LIBRARY_PATH_VARIABLE_COMMAND on $(targets) = [ "$(INTRO_ROOT_DIR)/compilers.prepend-shared-library-path-variable-command" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  local cxxflags = [ get-cxxflags $(properties) ] ;
+  if $(cxxflags)
+  {
+    if [ feature.get-values <variant> : $(properties) ] != debug
+    {
+      cxxflags = "$(cxxflags) -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math" ;
+    }
+    OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
+  }
+
+  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 }
 actions make-install
 {
   # Restore the hacked configure script. See also `../gcc/jamfile'.
-  if [ -e "$(SRCDIR)/real-configure" ]; then
-    [ ! -x "$(SRCDIR)/real-configure" ] && exit 1
-    mv -f "$(SRCDIR)/real-configure" "$(SRCDIR)/configure" || exit 1
+  if [ -e '$(SRCDIR)/real-configure' ]; then
+    [ ! -x '$(SRCDIR)/real-configure' ] && exit 1
+    mv -f '$(SRCDIR)/real-configure' '$(SRCDIR)/configure' || exit 1
   fi
 
   [ -x '$(SRCDIR)/configure' ] || exit 1
   [ -x '$(SRCDIR)/config.sub' ] || exit 1
   [ `'$(SRCDIR)/config.sub' $(TRIPLET)` = $(TRIPLET) ] || exit 1
 
-  # Clean up objdir `OBJDIR'.
+  # Clean up objdir `$(OBJDIR)'.
   { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
 
-  $(PREPEND_SHARED_LIBRARY_PATH_VARIABLE_COMMAND)
+  $(ENVIRONMENT_COMMANDS)
 
   if [ -n '$(STREAM)' ]; then
     ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(STREAM)' 2>&1 )
@@ -343,7 +392,7 @@ actions make-install
 
   [ -f '$(<)' ] || exit 1
 
-  # Clean up objdir `OBJDIR'.
+  # Clean up objdir `$(OBJDIR)'.
   rm -rf '$(OBJDIR)' || exit 1
 
   echo -n 'isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built.' | $(AWACS)
@@ -352,23 +401,5 @@ actions make-install
 
 
 
-rule install-req ( properties * )
-{
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-unspecified <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <isl>                : $(properties) ;
-  assert-specified   <isl-hidden>         : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
-  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  return <source>"$(compiler-prefix)/include/isl/version.h" ;
-}
-
-alias install : : <conditional>@install-req ;
+alias install : isl/version.h ;
 explicit install ;
