Added AWACS stream output.
Added AWACS stream output when failing to expand a tarball.

diff --git a/binutils/jamfile b/binutils/jamfile
--- a/binutils/jamfile
+++ b/binutils/jamfile
@@ -69,7 +69,7 @@ actions download-binutils
       /bin/echo -n "ERROR: failed to download binutils tarball." | $(AWACS)
       exit 1
     fi
-    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
+    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
   fi
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -117,8 +117,8 @@ rule expand-binutils ( targets * : sources * : properties * )
 actions expand-binutils
 {
   rm -f "$(<)" || exit $?
-  [ -f "$(>)" ] || exit $?
-  ( cd "$(INTRO_ROOT_DIR)" && rm -rf binutils-$(VERSION) ) || exit $?
+  [ -f "$(>)" ] || exit 1
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf binutils-$(VERSION) ) || exit 1
   [ -e "$(INTRO_ROOT_DIR)/binutils-$(VERSION)" ] && exit 1
   if [ -f "$(TARBALL_GZ)" ]; then
     if [ -n "$(STREAM)" ]; then
@@ -135,9 +135,13 @@ actions expand-binutils
   else
     exit 1
   fi
-  [ $? -ne 0 ] && { echo "ERROR: failed to expand binutils tarball." 1>&2; exit 1; }
-  [ -d "$(DEST_DIR)" ] || exit $?
-  [ -x "$(DEST_DIR)/configure" ] || exit $?
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to expand binutils tarball." 1>&2
+    /bin/echo -n "ERROR: failed to expand binutils tarball." | $(AWACS)
+    exit 1
+  fi
+  [ -d "$(DEST_DIR)" ] || exit 1
+  [ -x "$(DEST_DIR)/configure" ] || exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -205,9 +209,9 @@ rule make-binutils ( targets * : sources * : properties * )
 actions make-binutils
 {
   rm -f "$(<)" || exit $?
-  [ -x "$(CONFIGURE)" ] || exit $?
-  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit $?
-  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit $?
+  [ -x "$(CONFIGURE)" ] || exit 1
+  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit 1
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
@@ -218,7 +222,7 @@ actions make-binutils
     /bin/echo -n "ERROR: failed to 'configure' binutils $(VERSION) ($(TRIPLET)-gcc)." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || exit $?
+  [ -f "$(<:D)/build/Makefile" ] || exit 1
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
diff --git a/gcc/jamfile b/gcc/jamfile
--- a/gcc/jamfile
+++ b/gcc/jamfile
@@ -87,7 +87,7 @@ actions download-gcc
       /bin/echo -n "ERROR: failed to download GCC tarball." | $(AWACS)
       exit 1
     fi
-    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
+    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
   fi
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -135,8 +135,8 @@ rule expand-gcc ( targets * : sources * : properties * )
 actions expand-gcc
 {
   rm -f "$(<)" || exit $?
-  [ -f "$(>)" ] || exit $?
-  ( cd "$(INTRO_ROOT_DIR)" && rm -rf gcc-$(VERSION) ) || exit $?
+  [ -f "$(>)" ] || exit 1
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf gcc-$(VERSION) ) || exit 1
   [ -e "$(INTRO_ROOT_DIR)/gcc-$(VERSION)" ] && exit 1
   if [ -f "$(TARBALL_GZ)" ]; then
     if [ -n "$(STREAM)" ]; then
@@ -153,9 +153,13 @@ actions expand-gcc
   else
     exit 1
   fi
-  [ $? -ne 0 ] && { echo "ERROR: failed to expand GCC tarball." 1>&2; exit 1; }
-  [ -d "$(DEST_DIR)" ] || exit $?
-  [ -x "$(DEST_DIR)/configure" ] || exit $?
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to expand GCC tarball." 1>&2
+    /bin/echo -n "ERROR: failed to expand GCC tarball." | $(AWACS)
+    exit 1
+  fi
+  [ -d "$(DEST_DIR)" ] || exit 1
+  [ -x "$(DEST_DIR)/configure" ] || exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -321,16 +325,16 @@ rule configure-gcc ( targets * : sources * : properties * )
 
   SET_PREFIX_SYMLINK on $(targets) = ;
   if $(triplet) = x86_64-unknown-linux-gnu || $(triplet) = x86_64-w64-mingw32 {
-    SET_PREFIX_SYMLINK on $(targets) = "{ mkdir -p \"$(PREFIX)/$(version)/lib\" && ( cd \"$(PREFIX)/$(version)\" && ln -sf lib lib64 ); } || exit $?" ;
+    SET_PREFIX_SYMLINK on $(targets) = "{ mkdir -p \"$(PREFIX)/$(version)/lib\" && ( cd \"$(PREFIX)/$(version)\" && ln -sf lib lib64 ); } || exit 1" ;
   }
 }
 actions configure-gcc
 {
   rm -f "$(<)" || exit $?
-  [ -x "$(CONFIGURE)" ] || exit $?
+  [ -x "$(CONFIGURE)" ] || exit 1
   $(SET_PREFIX_SYMLINK)
-  [ `$(CONFIGURE:D)/config.sub $(TRIPLET)` = $(TRIPLET) ] || exit $?
-  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit $?
+  [ `$(CONFIGURE:D)/config.sub $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit 1
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
@@ -341,7 +345,7 @@ actions configure-gcc
     /bin/echo -n "ERROR: failed to 'configure' GCC $(VER_RAW) ($(TRIPLET))." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || exit $?
+  [ -f "$(<:D)/build/Makefile" ] || exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -404,7 +408,7 @@ rule make-gcc ( targets * : sources * : properties * )
 actions make-gcc
 {
   rm -f "$(<)" || exit $?
-  [ -f "$(<:D)/build/Makefile" ] || exit $?
+  [ -f "$(<:D)/build/Makefile" ] || exit 1
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
diff --git a/gmp/jamfile b/gmp/jamfile
--- a/gmp/jamfile
+++ b/gmp/jamfile
@@ -105,7 +105,7 @@ actions download-gmp
       /bin/echo -n "ERROR: failed to download GMP tarball." | $(AWACS)
       exit 1
     fi
-    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
+    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
   fi
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -153,8 +153,8 @@ rule expand-gmp ( targets * : sources * : properties * )
 actions expand-gmp
 {
   rm -f "$(<)" || exit $?
-  [ -f "$(>)" ] || exit $?
-  ( cd "$(INTRO_ROOT_DIR)" && rm -rf gmp-$(VERSION) ) || exit $?
+  [ -f "$(>)" ] || exit 1
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf gmp-$(VERSION) ) || exit 1
   [ -e "$(INTRO_ROOT_DIR)/gmp-$(VERSION)" ] && exit 1
   if [ -f "$(TARBALL_GZ)" ]; then
     if [ -n "$(STREAM)" ]; then
@@ -171,9 +171,13 @@ actions expand-gmp
   else
     exit 1
   fi
-  [ $? -ne 0 ] && { echo "ERROR: failed to expand GMP tarball." 1>&2; exit 1; }
-  [ -d "$(DEST_DIR)" ] || exit $?
-  [ -x "$(DEST_DIR)/configure" ] || exit $?
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to expand GMP tarball." 1>&2
+    /bin/echo -n "ERROR: failed to expand GMP tarball." | $(AWACS)
+    exit 1
+  fi
+  [ -d "$(DEST_DIR)" ] || exit 1
+  [ -x "$(DEST_DIR)/configure" ] || exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -284,9 +288,9 @@ rule make-gmp ( targets * : sources * : properties * )
 actions make-gmp
 {
   rm -f "$(<)" || exit $?
-  [ -x "$(CONFIGURE)" ] || exit $?
-  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit $?
-  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit $?
+  [ -x "$(CONFIGURE)" ] || exit 1
+  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit 1
   $(SET_RUN_VARS)
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
@@ -298,7 +302,7 @@ actions make-gmp
     /bin/echo -n "ERROR: failed to 'configure' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || exit $?
+  [ -f "$(<:D)/build/Makefile" ] || exit 1
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
diff --git a/icu4c/jamfile b/icu4c/jamfile
--- a/icu4c/jamfile
+++ b/icu4c/jamfile
@@ -109,7 +109,7 @@ actions download-icu4c
       /bin/echo -n "ERROR: failed to download ICU4C tarball." | $(AWACS)
       exit 1
     fi
-    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_TGZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
+    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_TGZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
   fi
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -158,8 +158,8 @@ rule expand-icu4c ( targets * : sources * : properties * )
 actions expand-icu4c
 {
   rm -f "$(<)" || exit $?
-  [ -f "$(>)" ] || exit $?
-  ( cd "$(INTRO_ROOT_DIR)" && rm -rf icu ) || exit $?
+  [ -f "$(>)" ] || exit 1
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf icu ) || exit 1
   [ -e "$(INTRO_ROOT_DIR)/icu" ] && exit 1
   if [ -f "$(TARBALL_GZ)" ]; then
     if [ -n "$(STREAM)" ]; then
@@ -182,9 +182,13 @@ actions expand-icu4c
   else
     exit 1
   fi
-  [ $? -ne 0 ] && { echo "ERROR: failed to expand ICU4C tarball." 1>&2; exit 1; }
-  [ -d "$(DEST_DIR)" ] || exit $?
-  [ -x "$(DEST_DIR)/source/runConfigureICU" ] || exit $?
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to expand ICU4C tarball." 1>&2
+    /bin/echo -n "ERROR: failed to expand ICU4C tarball." | $(AWACS)
+    exit 1
+  fi
+  [ -d "$(DEST_DIR)" ] || exit 1
+  [ -x "$(DEST_DIR)/source/runConfigureICU" ] || exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -311,10 +315,10 @@ rule make-icu4c ( targets * : sources * : properties * )
 actions make-icu4c
 {
   rm -f "$(<)" || exit $?
-  [ -x "$(CONFIGURE)" ] || exit $?
+  [ -x "$(CONFIGURE)" ] || exit 1
   chmod +x "$(CONFIGURE:D)/config.sub" || exit $?
-  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit $?
-  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit $?
+  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit 1
   $(SET_RUN_VARS)
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
@@ -326,7 +330,7 @@ actions make-icu4c
     /bin/echo -n "ERROR: failed to 'runConfigureICU' ICU4C $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || exit $?
+  [ -f "$(<:D)/build/Makefile" ] || exit 1
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
diff --git a/mpc/jamfile b/mpc/jamfile
--- a/mpc/jamfile
+++ b/mpc/jamfile
@@ -103,7 +103,7 @@ actions download-mpc
       /bin/echo -n "ERROR: failed to download MPC tarball." | $(AWACS)
       exit 1
     fi
-    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
+    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
   fi
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -151,8 +151,8 @@ rule expand-mpc ( targets * : sources * : properties * )
 actions expand-mpc
 {
   rm -f "$(<)" || exit $?
-  [ -f "$(>)" ] || exit $?
-  ( cd "$(INTRO_ROOT_DIR)" && rm -rf mpc-$(VERSION) ) || exit $?
+  [ -f "$(>)" ] || exit 1
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf mpc-$(VERSION) ) || exit 1
   [ -e "$(INTRO_ROOT_DIR)/mpc-$(VERSION)" ] && exit 1
   if [ -f "$(TARBALL_GZ)" ]; then
     if [ -n "$(STREAM)" ]; then
@@ -169,9 +169,13 @@ actions expand-mpc
   else
     exit 1
   fi
-  [ $? -ne 0 ] && { echo "ERROR: failed to expand MPC tarball." 1>&2; exit 1; }
-  [ -d "$(DEST_DIR)" ] || exit $?
-  [ -x "$(DEST_DIR)/configure" ] || exit $?
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to expand MPC tarball." 1>&2
+    /bin/echo -n "ERROR: failed to expand MPC tarball." | $(AWACS)
+    exit 1
+  fi
+  [ -d "$(DEST_DIR)" ] || exit 1
+  [ -x "$(DEST_DIR)/configure" ] || exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -291,9 +295,9 @@ rule make-mpc ( targets * : sources * : properties * )
 actions make-mpc
 {
   rm -f "$(<)" || exit $?
-  [ -x "$(CONFIGURE)" ] || exit $?
-  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit $?
-  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit $?
+  [ -x "$(CONFIGURE)" ] || exit 1
+  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit 1
   $(SET_RUN_VARS)
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
@@ -305,7 +309,7 @@ actions make-mpc
     /bin/echo -n "ERROR: failed to 'configure' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || exit $?
+  [ -f "$(<:D)/build/Makefile" ] || exit 1
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
diff --git a/mpfr/jamfile b/mpfr/jamfile
--- a/mpfr/jamfile
+++ b/mpfr/jamfile
@@ -103,7 +103,7 @@ actions download-mpfr
       /bin/echo -n "ERROR: failed to download MPFR tarball." | $(AWACS)
       exit 1
     fi
-    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
+    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
   fi
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -151,8 +151,8 @@ rule expand-mpfr ( targets * : sources * : properties * )
 actions expand-mpfr
 {
   rm -f "$(<)" || exit $?
-  [ -f "$(>)" ] || exit $?
-  ( cd "$(INTRO_ROOT_DIR)" && rm -rf mpfr-$(VERSION) ) || exit $?
+  [ -f "$(>)" ] || exit 1
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf mpfr-$(VERSION) ) || exit 1
   [ -e "$(INTRO_ROOT_DIR)/mpfr-$(VERSION)" ] && exit 1
   if [ -f "$(TARBALL_GZ)" ]; then
     if [ -n "$(STREAM)" ]; then
@@ -169,9 +169,13 @@ actions expand-mpfr
   else
     exit 1
   fi
-  [ $? -ne 0 ] && { echo "ERROR: failed to expand MPFR tarball." 1>&2; exit 1; }
-  [ -d "$(DEST_DIR)" ] || exit $?
-  [ -x "$(DEST_DIR)/configure" ] || exit $?
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to expand MPFR tarball." 1>&2
+    /bin/echo -n "ERROR: failed to expand MPFR tarball." | $(AWACS)
+    exit 1
+  fi
+  [ -d "$(DEST_DIR)" ] || exit 1
+  [ -x "$(DEST_DIR)/configure" ] || exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -289,9 +293,9 @@ rule make-mpfr ( targets * : sources * : properties * )
 actions make-mpfr
 {
   rm -f "$(<)" || exit $?
-  [ -x "$(CONFIGURE)" ] || exit $?
-  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit $?
-  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit $?
+  [ -x "$(CONFIGURE)" ] || exit 1
+  [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit 1
   $(SET_RUN_VARS)
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
@@ -303,7 +307,7 @@ actions make-mpfr
     /bin/echo -n "ERROR: failed to 'configure' MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || exit $?
+  [ -f "$(<:D)/build/Makefile" ] || exit 1
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
diff --git a/openmpi/jamfile b/openmpi/jamfile
--- a/openmpi/jamfile
+++ b/openmpi/jamfile
@@ -108,7 +108,7 @@ actions download-openmpi
       /bin/echo -n "ERROR: failed to download Open MPI tarball." | $(AWACS)
       exit 1
     fi
-    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit $?
+    [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
   fi
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -156,8 +156,8 @@ rule expand-openmpi ( targets * : sources * : properties * )
 actions expand-openmpi
 {
   rm -f "$(<)" || exit $?
-  [ -f "$(>)" ] || exit $?
-  ( cd "$(INTRO_ROOT_DIR)" && rm -rf openmpi-$(VERSION) ) || exit $?
+  [ -f "$(>)" ] || exit 1
+  ( cd "$(INTRO_ROOT_DIR)" && rm -rf openmpi-$(VERSION) ) || exit 1
   [ -e "$(INTRO_ROOT_DIR)/openmpi-$(VERSION)" ] && exit 1
   if [ -f "$(TARBALL_GZ)" ]; then
     if [ -n "$(STREAM)" ]; then
@@ -174,9 +174,13 @@ actions expand-openmpi
   else
     exit 1
   fi
-  [ $? -ne 0 ] && { echo "ERROR: failed to expand Open MPI tarball." 1>&2; exit 1; }
-  [ -d "$(DEST_DIR)" ] || exit $?
-  [ -x "$(DEST_DIR)/configure" ] || exit $?
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to expand Open MPI tarball." 1>&2
+    /bin/echo -n "ERROR: failed to expand Open MPI tarball." | $(AWACS)
+    exit 1
+  fi
+  [ -d "$(DEST_DIR)" ] || exit 1
+  [ -x "$(DEST_DIR)/configure" ] || exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -286,9 +290,9 @@ rule make-openmpi ( targets * : sources * : properties * )
 actions make-openmpi
 {
   rm -f "$(<)" || exit $?
-  [ -x "$(CONFIGURE)" ] || exit $?
-  [ `"$(CONFIGURE:D)/config/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit $?
-  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit $?
+  [ -x "$(CONFIGURE)" ] || exit 1
+  [ `"$(CONFIGURE:D)/config/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit 1
   $(SET_RUN_VARS)
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
@@ -300,7 +304,7 @@ actions make-openmpi
     /bin/echo -n "ERROR: failed to 'configure' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  [ -f "$(<:D)/build/Makefile" ] || exit $?
+  [ -f "$(<:D)/build/Makefile" ] || exit 1
   if [ -n "$(STREAM)" ]; then
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
