Use hard-coded dynamic link path.

diff --git a/binutils/jamfile b/binutils/jamfile
--- a/binutils/jamfile
+++ b/binutils/jamfile
@@ -307,17 +307,18 @@ rule make-install ( targets * : sources * : properties * )
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
 
-  OPTIONS on $(targets) = ;
+  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
+  local compiler-description = [ "$(INTRO_ROOT_DIR)/compilers.get-compiler-description" $(compiler) ] ;
+  COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <binutils> : $(properties) ] ;
   VERSION on $(targets) = $(version) ;
 
-  local compiler-description = [ "$(INTRO_ROOT_DIR)/compilers.get-compiler-description" $(compiler) ] ;
-  COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
-
   # Set the path to the source directory.
   local srcdir = "$(INTRO_ROOT_DIR)/binutils-$(version)" ;
   SRCDIR on $(targets) = $(srcdir) ;
+
+  OPTIONS on $(targets) = ;
 
   # Set the '--build', '--host' and '--target' options for the 'configure' script.
   local triplet = [ feature.get-values <triplet> : $(properties) ] ;
@@ -327,7 +328,9 @@ rule make-install ( targets * : sources * : properties * )
   OPTIONS on $(targets) += --target=$(triplet) ;
 
   # Set the '--prefix' option for the 'configure' script.
-  OPTIONS on $(targets) += --prefix=\"$(PREFIX)\" ;
+  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
+  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
+  OPTIONS on $(targets) += --prefix=\"$(compiler-prefix)\" ;
 
   OPTIONS on $(targets) += --enable-ld ;
   OPTIONS on $(targets) += --enable-gold=default ;
@@ -336,6 +339,30 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) += --enable-lto ;
   OPTIONS on $(targets) += --enable-plugins ;
+
+  if ! [ "$(INTRO_ROOT_DIR)/compilers.is-builtin-gcc" $(compiler) ]
+  {
+    if [ "$(INTRO_ROOT_DIR)/compilers.is-gcc" $(compiler) ]
+    {
+      OPTIONS on $(targets) += CC=\"$(compiler-prefix)/bin/gcc-wrapper\" ;
+      OPTIONS on $(targets) += CXX=\"$(compiler-prefix)/bin/g++-wrapper\" ;
+    }
+    else if [ "$(INTRO_ROOT_DIR)/compilers.is-clang" $(compiler) ]
+    {
+      OPTIONS on $(targets) += CC=\"$(compiler-prefix)/bin/clang-wrapper\" ;
+      OPTIONS on $(targets) += CXX=\"$(compiler-prefix)/bin/clang++-wrapper\" ;
+    }
+    else
+    {
+      errors.error "an internal error." ;
+    }
+  }
+
+  ENV_RUN_VARS on $(targets) = ;
+  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32
+  {
+    ENV_RUN_VARS on $(targets) = "env PATH=\"$(compiler-prefix)/bin${PATH:+:$PATH}\"" ;
+  }
 }
 actions make-install
 {
@@ -350,9 +377,9 @@ actions make-install
   { mkdir -p "$objdir" && ( cd "$objdir" && rm -rf * ); } || exit 1
 
   if [ -n "$(STREAM)" ]; then
-    ( cd "$objdir" && "$(SRCDIR)/configure" $(OPTIONS) >> "$(STREAM)" 2>&1 )
+    ( cd "$objdir" && $(ENV_RUN_VARS) "$(SRCDIR)/configure" $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$objdir" && "$(SRCDIR)/configure" $(OPTIONS) )
+    ( cd "$objdir" && $(ENV_RUN_VARS) "$(SRCDIR)/configure" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'configure' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
@@ -364,9 +391,9 @@ actions make-install
   [ -f "${objdir}/Makefile" ] || exit 1
 
   if [ -n "$(STREAM)" ]; then
-    ( cd "$objdir" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+    ( cd "$objdir" && $(ENV_RUN_VARS) make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$objdir" && make --jobs=$(CONCURRENCY) )
+    ( cd "$objdir" && $(ENV_RUN_VARS) make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'make' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
@@ -375,9 +402,9 @@ actions make-install
   fi
 
   if [ -n "$(STREAM)" ]; then
-    ( cd "$objdir" && make --jobs=$(CONCURRENCY) check >> "$(STREAM)" 2>&1 )
+    ( cd "$objdir" && $(ENV_RUN_VARS) make --jobs=$(CONCURRENCY) check >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$objdir" && make --jobs=$(CONCURRENCY) check )
+    ( cd "$objdir" && $(ENV_RUN_VARS) make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'make check' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
@@ -386,9 +413,9 @@ actions make-install
   fi
 
   if [ -n "$(STREAM)" ]; then
-    ( cd "$objdir" && make install >> "$(STREAM)" 2>&1 )
+    ( cd "$objdir" && $(ENV_RUN_VARS) make install >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$objdir" && make install )
+    ( cd "$objdir" && $(ENV_RUN_VARS) make install )
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'make install' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
diff --git a/gcc/jamfile b/gcc/jamfile
--- a/gcc/jamfile
+++ b/gcc/jamfile
@@ -269,8 +269,6 @@ rule make-install ( targets * : sources * : properties * )
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
 
-  OPTIONS on $(targets) = ;
-
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
   if ! [ "$(INTRO_ROOT_DIR)/compilers.is-gcc" "$(compiler)" ]
   {
@@ -284,17 +282,25 @@ rule make-install ( targets * : sources * : properties * )
   local srcdir = "$(INTRO_ROOT_DIR)/gcc-$(version)" ;
   SRCDIR on $(targets) = "$(srcdir)" ;
 
+  local objdir = "$(INTRO_ROOT_DIR)/objdir" ;
+  OBJDIR on $(targets) = "$(objdir)" ;
+
+  # Set the compiler-specific prefix.
+  local compiler-prefix = "$(PREFIX)/$(compiler)" ;
+  COMPILER_PREFIX on $(targets) = "$(compiler-prefix)" ;
+
+  local libdir = "$(compiler-prefix)/lib" ;
+  LIBDIR on $(targets) = "$(libdir)" ;
+
   local triplet = [ feature.get-values <triplet> : $(properties) ] ;
   TRIPLET on $(targets) = $(triplet) ;
+
+  OPTIONS on $(targets) = ;
 
   # Set the '--build', '--host' and '--target' options for the 'configure' script.
   OPTIONS on $(targets) += --build=$(triplet) ;
   OPTIONS on $(targets) += --host=$(triplet) ;
   OPTIONS on $(targets) += --target=$(triplet) ;
-
-  # Set the compiler-specific prefix.
-  local compiler-prefix = "$(PREFIX)/$(compiler)" ;
-  COMPILER_PREFIX on $(targets) = "$(compiler-prefix)" ;
 
   # Set the '--prefix' option for the 'configure' script.
   OPTIONS on $(targets) += "--prefix=\"$(compiler-prefix)\"" ;
@@ -412,14 +418,16 @@ rule make-install ( targets * : sources * : properties * )
   {
     SET_PREFIX_SYMLINK on $(targets) = "{ mkdir -p \"$(compiler-prefix)/lib\" && ( cd \"$(compiler-prefix)\" && ln -sfT lib lib64 ); } || exit 1" ;
   }
+
+  ENV_FOR_MAKE on $(targets) = env ;
+  ENV_FOR_MAKE on $(targets) += "CPATH=\"$(objdir)/gmp:$(srcdir)/gmp${CPATH:+:$CPATH}\"" ;
+  ENV_FOR_MAKE on $(targets) += "LIBRARY_PATH=\"$(objdir)/gmp/.libs:$(objdir)/$(triplet)/libstdc++-v3/src/.libs${LIBRARY_PATH:+:$LIBRARY_PATH}\"" ;
+  ENV_FOR_MAKE on $(targets) += "LD_RUN_PATH=\"$(libdir):${LD_RUN_PATH:+:$LD_RUN_PATH}\"" ;
 }
 actions make-install
 {
-  # The absolute path to the objdir.
-  objdir="$(INTRO_ROOT_DIR)/objdir"
-
-  # Clean-up the objdir.
-  { mkdir -p "$objdir" && ( cd "$objdir" && rm -rf * ); } || exit 1
+  # Clean-up the OBJDIR.
+  { mkdir -p "$(OBJDIR)" && ( cd "$(OBJDIR)" && rm -rf * ); } || exit 1
 
 
   # Create the symlinks to the source directories to GNU Binutils
@@ -473,8 +481,8 @@ actions make-install
   echo ""                                                                       >> "$(SRCDIR)/ppl/configure"
   echo "echo original options for PPL configure script: \$@"                    >> "$(SRCDIR)/ppl/configure"
   echo "dir=\`dirname \"\$0\"\`"                                                >> "$(SRCDIR)/ppl/configure"
-  #echo "\"\${dir}/real-configure\" --with-gmp-build=\"${objdir}/gmp\" \"\$@\"" >> "$(SRCDIR)/ppl/configure"
-  echo  "\"\${dir}/real-configure\" --srcdir="$(SRCDIR)/ppl" --build=$(TRIPLET) --host=$(TRIPLET) --disable-coverage --enable-static --disable-shared --with-gmp-build=\"${objdir}/gmp\"" >> "$(SRCDIR)/ppl/configure"
+  #echo "\"\${dir}/real-configure\" --with-gmp-build=\"$(OBJDIR)/gmp\" \"\$@\"" >> "$(SRCDIR)/ppl/configure"
+  echo  "\"\${dir}/real-configure\" --srcdir="$(SRCDIR)/ppl" --build=$(TRIPLET) --host=$(TRIPLET) --disable-coverage --enable-static --disable-shared --with-gmp-build=\"$(OBJDIR)/gmp\"" >> "$(SRCDIR)/ppl/configure"
   chmod +x "$(SRCDIR)/ppl/configure"
 
 
@@ -491,8 +499,8 @@ actions make-install
   echo ""                                                                         >> "$(SRCDIR)/cloog/configure"
   echo "echo original options for CLooG configure script: \$@"                    >> "$(SRCDIR)/cloog/configure"
   echo "dir=\`dirname \"\$0\"\`"                                                  >> "$(SRCDIR)/cloog/configure"
-  #echo "\"\${dir}/real-configure\" --with-gmp-builddir=\"${objdir}/gmp\" \"\$@\"" >> "$(SRCDIR)/cloog/configure"
-  echo "\"\${dir}/real-configure\" --srcdir=$(SRCDIR)/cloog --build=$(TRIPLET) --host=$(TRIPLET) --enable-static --disable-shared --with-gnu-ld --with-gmp-builddir=\"${objdir}/gmp\"" >> "$(SRCDIR)/cloog/configure"
+  #echo "\"\${dir}/real-configure\" --with-gmp-builddir=\"$(OBJDIR)/gmp\" \"\$@\"" >> "$(SRCDIR)/cloog/configure"
+  echo "\"\${dir}/real-configure\" --srcdir=$(SRCDIR)/cloog --build=$(TRIPLET) --host=$(TRIPLET) --enable-static --disable-shared --with-gnu-ld --with-gmp-builddir=\"$(OBJDIR)/gmp\"" >> "$(SRCDIR)/cloog/configure"
   chmod +x "$(SRCDIR)/cloog/configure"
 
 
@@ -505,9 +513,9 @@ actions make-install
 
   # `configure'.
   if [ -n "$(STREAM)" ]; then
-    ( cd "$objdir" && "$(SRCDIR)/configure" $(OPTIONS) >> "$(STREAM)" 2>&1 )
+    ( cd "$(OBJDIR)" && env LD_RUN_PATH="$(LIBDIR):${LD_RUN_PATH:+:$LD_RUN_PATH}" "$(SRCDIR)/configure" $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$objdir" && "$(SRCDIR)/configure" $(OPTIONS) )
+    ( cd "$(OBJDIR)" && env LD_RUN_PATH="$(LIBDIR):${LD_RUN_PATH:+:$LD_RUN_PATH}" "$(SRCDIR)/configure" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'configure' $(COMPILER_DESCRIPTION) ($(TRIPLET))." 1>&2
@@ -516,34 +524,28 @@ actions make-install
   fi
 
   # Check the creation of `Makefile'.
-  [ -f "${objdir}/Makefile" ] || exit 1
+  [ -f "$(OBJDIR)/Makefile" ] || exit 1
 
 
   # PPL and CLooG requires GMP. However, they will fail to find the GMP
   # header files, `<gmp.h>' and `<gmpxx.h>'. `<gmp.h>' will be created in
-  # `${objdir}/gmp' during the bootstrap procedure, whereas `<gmpxx.h>'
+  # `$(OBJDIR)/gmp' during the bootstrap procedure, whereas `<gmpxx.h>'
   # resides in `$(SRCDIR)/gmp'. So, `CPATH' environment variable is set
   # to include the paths to those header files.
   if [ -n "$(STREAM)" ]; then
-    ( cd "$objdir" \
-        && env CPATH="${objdir}/gmp:$(SRCDIR)/gmp${CPATH:+:$CPATH}" LIBRARY_PATH="${objdir}/gmp/.libs:${objdir}/$(TRIPLET)/libstdc++-v3/src/.libs${LIBRARY_PATH:+:$LIBRARY_PATH}" make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+    ( cd "$(OBJDIR)" && $(ENV_FOR_MAKE) make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
     if [ $? -ne 0 ]; then
-      ( cd "$objdir" \
-          && env CPATH="${objdir}/gmp:$(SRCDIR)/gmp${CPATH:+:$CPATH}" LIBRARY_PATH="${objdir}/gmp/.libs:${objdir}/$(TRIPLET)/libstdc++-v3/src/.libs${LIBRARY_PATH:+:$LIBRARY_PATH}" make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+      ( cd "$(OBJDIR)" && $(ENV_FOR_MAKE) make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
       if [ $? -ne 0 ]; then
-        ( cd "$objdir" \
-            && env CPATH="${objdir}/gmp:$(SRCDIR)/gmp${CPATH:+:$CPATH}" LIBRARY_PATH="${objdir}/gmp/.libs:${objdir}/$(TRIPLET)/libstdc++-v3/src/.libs${LIBRARY_PATH:+:$LIBRARY_PATH}" make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+        ( cd "$(OBJDIR)" && $(ENV_FOR_MAKE) make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
       fi
     fi
   else
-    ( cd "$objdir" \
-        && env CPATH="${objdir}/gmp:$(SRCDIR)/gmp${CPATH:+:$CPATH}" LIBRARY_PATH="${objdir}/gmp/.libs:${objdir}/$(TRIPLET)/libstdc++-v3/src/.libs${LIBRARY_PATH:+:$LIBRARY_PATH}" make --jobs=$(CONCURRENCY) )
+    ( cd "$(OBJDIR)" && $(ENV_FOR_MAKE) make --jobs=$(CONCURRENCY) )
     if [ $? -ne 0 ]; then
-      ( cd "$objdir" \
-          && env CPATH="${objdir}/gmp:$(SRCDIR)/gmp${CPATH:+:$CPATH}" LIBRARY_PATH="${objdir}/gmp/.libs:${objdir}/$(TRIPLET)/libstdc++-v3/src/.libs${LIBRARY_PATH:+:$LIBRARY_PATH}" make --jobs=$(CONCURRENCY) )
+      ( cd "$(OBJDIR)" && $(ENV_FOR_MAKE) make --jobs=$(CONCURRENCY) )
       if [ $? -ne 0 ]; then
-        ( cd "$objdir" \
-            && env CPATH="${objdir}/gmp:$(SRCDIR)/gmp${CPATH:+:$CPATH}" LIBRARY_PATH="${objdir}/gmp/.libs:${objdir}/$(TRIPLET)/libstdc++-v3/src/.libs${LIBRARY_PATH:+:$LIBRARY_PATH}" make --jobs=$(CONCURRENCY) )
+        ( cd "$(OBJDIR)" && $(ENV_FOR_MAKE) make --jobs=$(CONCURRENCY) )
       fi
     fi
   fi
@@ -556,9 +558,9 @@ actions make-install
 
   # `make install'.
   if [ -n "$(STREAM)" ]; then
-    ( cd "$objdir" && make install >> "$(STREAM)" 2>&1 )
+    ( cd "$(OBJDIR)" && env LD_RUN_PATH="$(LIBDIR):${LD_RUN_PATH:+:$LD_RUN_PATH}" make install >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$objdir" && make install )
+    ( cd "$(OBJDIR)" && env LD_RUN_PATH="$(LIBDIR):${LD_RUN_PATH:+:$LD_RUN_PATH}" make install )
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'make install' $(COMPILER_DESCRIPTION) ($(TRIPLET))." 1>&2
@@ -575,13 +577,29 @@ actions make-install
     echo -n "ERROR: failed to create the workaround symlink to the linker for $(COMPILER_DESCRIPTION) ($(TRIPLET))." | $(AWACS)
     exit 1
   fi
+  # Some configure scripts (e.g. MPC's) require `ld' instead of `real-ld'.
+  ( cd "$(COMPILER_PREFIX)"/libexec/gcc/$(TRIPLET)/`"$(COMPILER_PREFIX)/bin/gcc" -dumpversion` && ln -sf ../../../../bin/ld ld )
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to create the workaround symlink to the linker for $(COMPILER_DESCRIPTION) ($(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to create the workaround symlink to the linker for $(COMPILER_DESCRIPTION) ($(TRIPLET))." | $(AWACS)
+    exit 1
+  fi
+
+
+  # Install the wrapper scripts.
+  install --mode=755 "$(INTRO_ROOT_DIR)/gcc/gcc-wrapper" "$(INTRO_ROOT_DIR)/gcc/g++-wrapper" "$(<:D)"
+  if [ $? -ne 0 ]; then
+    echo "ERROR: failed to install the wrapper scripts for $(COMPILER_DESCRIPTION) ($(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to install the wrapper scripts for $(COMPILER_DESCRIPTION) ($(TRIPLET))." | $(AWACS)
+    exit 1
+  fi
 
 
   # Check the creation of `g++'.
   [ -x "$(<)" ] || exit 1
 
-  # Clean-up the objdir.
-  rm -rf "$objdir" || exit 1
+  # Clean-up the OBJDIR.
+  rm -rf "$(OBJDIR)" || exit 1
 
   echo -n "$(COMPILER_DESCRIPTION) ($(TRIPLET)) was successfully built." | $(AWACS)
   echo -n "NOTE: Binutils $(BINUTILS_FOR_GCC), GMP $(GMP_FOR_GCC), MPFR $(MPFR_FOR_GCC), MPC $(MPC_FOR_GCC), PPL $(PPL_FOR_GCC), CLooG $(CLOOG_FOR_GCC) were bootstrapped alongside." | $(AWACS)
