Added multi-binary support.

diff --git a/binutils/jamfile b/binutils/jamfile
--- a/binutils/jamfile
+++ b/binutils/jamfile
@@ -5,49 +5,39 @@ import errors ;
 import feature ;
 import make ;
 import path ;
-import "$(INTRO_ROOT_DIR)/compilers" ;
-
-
-rule assert-specified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) = unspecified {
-    errors.error $(feature) is not specified for binutils build. ;
-  }
-}
-
-rule assert-unspecified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) != unspecified {
-    errors.error $(feature) is not valid for binutils build. ;
-  }
-}
-
+import "$(INTRO_ROOT_DIR)/compilers"
+  : is-gcc
+    is-clang
+    get-compiler-description
+    get-compiler-prefix
+    get-default-bindir
+    get-default-libdir
+    get-default-includedir
+    get-compiler-triplets
+    get-cc
+    get-cflags
+    get-cxx
+    get-cxxflags
+    get-environment-commands
+    get-rpath-commands
+    get-property-dump-commands
+  ;
 
 
 rule compiler-dep-req ( properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-specified   <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  assert-unspecified <binutils>           : $(properties) ;
-  assert-specified   <binutils-hidden>    : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
   local result ;
-  if [ "$(INTRO_ROOT_DIR)/compilers.is-gcc" $(compiler) ]
-  {
+  if [ is-gcc $(compiler) ] {
     result = <source>../gcc//install ;
   }
-  else if [ "$(INTRO_ROOT_DIR)/compilers.is-clang" $(compiler) ]
-  {
+  else if [ is-clang $(compiler) ] {
     result = <source>../clang//install ;
   }
-  else
-  {
+  else if [ is-icc $(compiler) ] {
+    result = <source>../icc//install ;
+  }
+  else {
     errors.error "an internal error." ;
   }
   return $(result) ;
@@ -63,27 +53,18 @@ explicit "$(INTRO_ROOT_DIR)/binutils-$(BINUTILS).tar.bz2" ;
 
 rule download ( targets * : sources * : properties * )
 {
-  if $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  assert-unspecified <binutils>           : $(properties) ;
-  assert-specified   <binutils-hidden>    : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <binutils-hidden> : $(properties) ] ;
   VERSION on $(targets) = $(version) ;
   URLS on $(targets) = "'http://ftp.nara.wide.ad.jp/pub/GNU/gnu/binutils/binutils-$(version).tar.bz2' \\
                         'http://ftp.tsukuba.wide.ad.jp/software/binutils/binutils-$(version).tar.bz2' \\
                         'http://ftp.jaist.ac.jp/pub/GNU/binutils/binutils-$(version).tar.bz2'         \\
                         'ftp://sourceware.org/pub/binutils/snapshots/binutils-$(version).tar.bz2'"    ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions download
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   rm -rf '$(<)' || exit 1
 
   for url in $(URLS) ; do
@@ -125,46 +106,33 @@ explicit "$(INTRO_ROOT_DIR)/binutils-$(BINUTILS)/README" ;
 
 rule expand ( targets * : sources * : properties * )
 {
-  if ! $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  if $(sources[2])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  assert-unspecified <binutils>           : $(properties) ;
-  assert-specified   <binutils-hidden>    : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <binutils-hidden> : $(properties) ] ;
   VERSION on $(targets) = $(version) ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions expand
 {
-  rm -rf "$(<:D)" || exit 1
-  [ -f "$(>)" ] || exit 1
-  if [ -n "$(STREAM)" ]; then
-    tar xjvf "$(>)" --directory="$(INTRO_ROOT_DIR)" >> "$(STREAM)" 2>&1
+  $(PROPERTY_DUMP_COMMANDS)
+
+  rm -rf '$(<:D)' || exit 1
+  [ -f '$(>)' ] || exit 1
+  if [ -n '$(STREAM)' ]; then
+    tar xjvf '$(>)' --directory='$(INTRO_ROOT_DIR)' >> '$(STREAM)' 2>&1
   else
-    tar xjf "$(>)" --directory="$(INTRO_ROOT_DIR)"
+    tar xjf '$(>)' --directory='$(INTRO_ROOT_DIR)'
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to expand Binutils $(VERSION) tarball." 1>&2
-    echo -n "ERROR: failed to expand Binutils $(VERSION) tarball." | $(AWACS)
-    rm -rf "$(<:D)"
+    echo    'ERROR: failed to expand Binutils $(VERSION) tarball.' 1>&2
+    echo -n 'ERROR: failed to expand Binutils $(VERSION) tarball.' | $(AWACS)
+    rm -rf '$(<:D)'
     exit 1
   fi
   # If the timestamp of the tarball's contents is restored, the modification
   # time of the source directory could be older than the one of the tarball.
   # Such behavior is not desirable because the decompression always happens.
   # Therefore, `touch' is required.
-  touch --no-create "$(<)"
-  [ -f "$(<)" ] || exit 1
+  touch --no-create '$(<)'
+  [ -f '$(<)' ] || exit 1
   exit 0
 }
 
@@ -172,16 +140,8 @@ actions expand
 
 rule srcdir-req ( properties * )
 {
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  assert-unspecified <binutils>           : $(properties) ;
-  assert-specified   <binutils-hidden>    : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <binutils-hidden> : $(properties) ] ;
-  return <source>"$(INTRO_ROOT_DIR)/binutils-$(version)/README/$(DEFAULT_PROPERTIES)" ;
+  return "<source>$(INTRO_ROOT_DIR)/binutils-$(version)/README/$(DEFAULT_PROPERTIES)" ;
 }
 
 alias srcdir : : <conditional>@srcdir-req ;
@@ -189,31 +149,27 @@ explicit srcdir ;
 
 
 
-for local compiler in $(COMPILERS)
+rule location-conditional ( properties * )
 {
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  make "$(compiler-prefix)/bin/ld.gold"
-    : compiler-dep
-      srcdir/<triplet>unspecified/<multitarget>unspecified/<compiler>unspecified
-    : @make-install
-    : $(USE_BINUTILS)
-    ;
-  explicit "$(compiler-prefix)/bin/ld.gold" ;
+  local bindir = [ get-default-bindir "$(PREFIX)" : $(properties) ] ;
+  return "<location>$(bindir)" ;
 }
+
+make ld.gold
+  : compiler-dep
+    srcdir
+  : @make-install
+  : <conditional>@location-conditional
+    $(USE_COMPILER)
+    $(USE_MULTITARGET)
+    $(USE_BINUTILS)
+  ;
+explicit ld.gold ;
 
 rule make-install ( targets * : sources * : properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-specified   <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  assert-specified   <binutils>           : $(properties) ;
-  assert-specified   <binutils-hidden>    : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local compiler-description = [ "$(INTRO_ROOT_DIR)/compilers.get-compiler-description" $(compiler) ] ;
+  local compiler-description = [ get-compiler-description $(compiler) ] ;
   COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <binutils> : $(properties) ] ;
@@ -228,136 +184,150 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) = ;
 
-  # Set the '--build', '--host' and '--target' options for the 'configure' script.
-  local triplet = [ feature.get-values <triplet> : $(properties) ] ;
-  TRIPLET on $(targets) = $(triplet) ;
-  OPTIONS on $(targets) += --build=$(triplet) ;
-  OPTIONS on $(targets) += --host=$(triplet) ;
-  OPTIONS on $(targets) += --target=$(triplet) ;
+  # Set `--prefix' option for `configure' script.
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
+  local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
+  OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
 
-  # Set the '--prefix' option for the 'configure' script.
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  OPTIONS on $(targets) += "--prefix=\"$(compiler-prefix)\"" ;
+  local bindir = [ get-default-bindir "$(PREFIX)" : $(properties) ] ;
+  local bindir-native = [ path.native "$(bindir)" ] ;
+  OPTIONS on $(targets) += "--bindir='$(bindir-native)'" ;
 
-  OPTIONS on $(targets) += --enable-ld=default ;
-  OPTIONS on $(targets) += --enable-gold ;
+  local libdir = [ get-default-libdir "$(PREFIX)" : $(properties) ] ;
+  local libdir-native = [ path.native "$(libdir)" ] ;
+  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
 
-  OPTIONS on $(targets) += --enable-libquadmath ;
+  local includedir = [ get-default-includedir "$(PREFIX)" : $(properties) ] ;
+  local includedir-native = [ path.native "$(includedir)" ] ;
+  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
 
-  OPTIONS on $(targets) += --enable-libssp ;
+  # Set `--build', `--host' and `--target' options for `configure' script.
+  local triplets = [ get-compiler-triplets $(properties) ] ;
+  local build-triplet = "$(triplets[1])" ;
+  local host-triplet = "$(triplets[2])" ;
+  local target-triplet = "$(triplets[3])" ;
+  local enabeld-targets = "$(triplets[4])" ;
+  BUILD_TRIPLET on $(targets) = "$(build-triplet)" ;
+  HOST_TRIPLET on $(targets) = "$(host-triplet)" ;
+  TARGET_TRIPLET on $(targets) = "$(target-triplet)" ;
+  OPTIONS on $(targets) += "--build=$(build-triplet)" ;
+  OPTIONS on $(targets) += "--host=$(host-triplet)" ;
+  OPTIONS on $(targets) += "--target=$(target-triplet)" ;
 
-  OPTIONS on $(targets) += --enable-bootstrap ;
+  OPTIONS on $(targets) += "--enable-ld=default" ;
+  OPTIONS on $(targets) += "--enable-gold" ;
 
-  OPTIONS on $(targets) += --enable-build-with-cxx ;
+  OPTIONS on $(targets) += "--enable-libquadmath" ;
 
-  local multitarget = [ feature.get-values <multitarget> : $(properties) ] ;
-  if $(triplet) = x86_64-unknown-linux-gnu && $(multitarget) = yes
-  {
-    OPTIONS on $(targets) += --enable-targets=x86_64-unknown-linux-gnu,i686-pc-linux-gnu ;
-  }
-  else if $(triplet) = x86_64-w64-mingw32 && $(multitarget) = yes
-  {
-    OPTIONS on $(targets) += --enable-targets=x86_64-w64-mingw32,i686-w64-mingw32 ;
-  }
+  OPTIONS on $(targets) += "--enable-libssp" ;
 
-  OPTIONS on $(targets) += --enable-cloog-backend=isl ;
+  OPTIONS on $(targets) += "--enable-bootstrap" ;
 
-  OPTIONS on $(targets) += --enable-lto ;
-  OPTIONS on $(targets) += --enable-plugins ;
+  OPTIONS on $(targets) += "--enable-build-with-cxx" ;
 
-  local cc = [ "$(INTRO_ROOT_DIR)/compilers.cc" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
-  OPTIONS on $(targets) += "CC=\"$(cc)\"" ;
+  OPTIONS on $(targets) += "--enable-targets=$(enabled-targets)" ;
 
-  local cxx = [ "$(INTRO_ROOT_DIR)/compilers.cxx" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
-  OPTIONS on $(targets) += "CXX=\"$(cxx)\"" ;
+  OPTIONS on $(targets) += "--enable-cloog-backend=isl" ;
 
-  PREPEND_SHARED_LIBRARY_PATH_VARIABLE_COMMAND on $(targets) = [ "$(INTRO_ROOT_DIR)/compilers.prepend-shared-library-path-variable-command" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  OPTIONS on $(targets) += "--enable-lto" ;
+  OPTIONS on $(targets) += "--enable-plugins" ;
+
+  local cc = [ get-cc "$(PREFIX)" : $(properties) ] ;
+  local cc-native = [ path.native "$(cc)" ] ;
+  OPTIONS on $(targets) += "CC='$(cc-native)'" ;
+
+  local cflags = [ get-cflags $(properties) ] ;
+  OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
+
+  local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
+  local cxx-native = [ path.native "$(cxx)" ] ;
+  OPTIONS on $(targets) += "CXX='$(cxx-native)'" ;
+
+  local cxxflags = [ get-cxxflags $(properties) ] ;
+  OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
+
+  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
+  ENVIRONMENT_COMMANDS on $(targets) = $(environment-commands) ;
+
+  local rpath-commands = [ get-rpath-commands "$(PREFIX)" : $(properties) ] ;
+  RPATH_COMMANDS on $(targets) = "$(rpath-commands)" ;
+
+  local property-dump-commands = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = $(property-dump-commands) ;
 }
 actions make-install
 {
-  [ -x "$(SRCDIR)/configure" ] || exit 1
-  [ -x "$(SRCDIR)/config.sub" ] || exit 1
-  [ `"$(SRCDIR)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  $(PROPERTY_DUMP_COMMANDS)
+
+  [ -x '$(SRCDIR)/configure' ] || exit 1
+  [ -x '$(SRCDIR)/config.sub' ] || exit 1
+  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
+  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
+  [ `'$(SRCDIR)/config.sub' $(TARGET_TRIPLET)` = $(TARGET_TRIPLET) ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
-  { mkdir -p "$(OBJDIR)" && ( cd "$(OBJDIR)" && rm -rf * ); } || exit 1
+  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
 
-  $(PREPEND_SHARED_LIBRARY_PATH_VARIABLE_COMMAND)
+  $(ENVIRONMENT_COMMANDS)
+  $(RPATH_COMMANDS)
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && "$(SRCDIR)/configure" $(OPTIONS) >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && "$(SRCDIR)/configure" $(OPTIONS) )
+    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'configure' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'configure' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`configure' Binutils $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`configure' Binutils $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
   # Check the creation of `Makefile'.
-  [ -f "$(OBJDIR)/Makefile" ] || exit 1
+  [ -f '$(OBJDIR)/Makefile' ] || exit 1
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) )
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'make' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make' Binutils $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make' Binutils $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) check >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) check )
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make check' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'make check' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make check' Binutils $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make check' Binutils $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && make install >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && make install >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && make install )
+    ( cd '$(OBJDIR)' && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make install' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'make install' Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make install' Binutils $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make install' Binutils $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
-  [ -x "$(<)" ] || exit 1
+  [ -x '$(<)' ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
-  rm -rf "$(OBJDIR)" || exit 1
+  rm -rf '$(OBJDIR)' || exit 1
 
-  echo -n "Binutils $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built." | $(AWACS)
+  echo -n 'Binutils $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
   exit 0
 }
 
 
 
-rule install-req ( properties * )
-{
-  assert-specified   <triplet>            : $(properties) ;
-  assert-specified   <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  assert-unspecified <binutils>           : $(properties) ;
-  assert-specified   <binutils-hidden>    : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
-  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  return <source>"$(compiler-prefix)/bin/ld.gold" ;
-}
-
-alias install : : <conditional>@install-req ;
+alias install : "ld.gold/$(DEFAULT_COMPILER_PROPERTIES)" ;
 explicit install ;
diff --git a/cloog/jamfile b/cloog/jamfile
--- a/cloog/jamfile
+++ b/cloog/jamfile
@@ -8,64 +8,38 @@ import path ;
 import "$(INTRO_ROOT_DIR)/compilers"
   : is-gcc
     is-clang
+    is-icc
     get-compiler-description
     get-compiler-prefix
     get-bindir
     get-libdir
     get-includedir
+    get-triplets
     get-cc
     get-cflags
     get-cxx
     get-cxxflags
     get-environment-commands
+    get-property-dump-commands
   ;
-
-
-rule assert-specified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) = unspecified {
-    errors.error $(feature) is not specified for CLooG build. ;
-  }
-}
-
-rule assert-unspecified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) != unspecified {
-    errors.error $(feature) is not valid for CLooG build. ;
-  }
-}
-
 
 
 rule compiler-dep-req ( properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-unspecified <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <isl>                : $(properties) ;
-  assert-specified   <isl-hidden>         : $(properties) ;
-  assert-unspecified <cloog>              : $(properties) ;
-  assert-specified   <cloog-hidden>       : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
-  local multitarget = [ feature.get-values <multitarget-hidden> : $(properties) ] ;
-  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
+  local compiler = [ feature.get-values <compiler-hidden> : $(properties) ] ;
   local result ;
-  if [ is-gcc $(compiler) ]
-  {
-    result = <source>../gcc//install/<multitarget>$(multitarget)/<multitarget-hidden>unspecified ;
+  if [ is-gcc "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
   }
-  else if [ is-clang $(compiler) ]
-  {
-    result = <source>../clang//install ;
+  else if [ is-clang "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
+    result += "<source>../clang//install" ;
   }
-  else
-  {
+  else if [ is-icc "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
+    result += "<source>../icc//install" ;
+  }
+  else {
     errors.error "an internal error." ;
   }
   return $(result) ;
@@ -76,36 +50,22 @@ explicit compiler-dep ;
 
 
 
-for local version in $(CLOOG_VERSIONS)
-{
+for local version in $(CLOOG_VERSIONS) {
   make "$(INTRO_ROOT_DIR)/cloog-$(version).tar.gz" : : @download ;
   explicit "$(INTRO_ROOT_DIR)/cloog-$(version).tar.gz" ;
 }
 
 rule download ( targets * : sources * : properties * )
 {
-  if $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  #assert-unspecified <gmp>                : $(properties) ;
-  #assert-specified   <gmp-hidden>         : $(properties) ;
-  #assert-unspecified <isl>                : $(properties) ;
-  #assert-specified   <isl-hidden>         : $(properties) ;
-  assert-unspecified <cloog>              : $(properties) ;
-  assert-specified   <cloog-hidden>       : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <cloog-hidden> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
   URL on $(targets) = http://www.bastoul.net/cloog/pages/download/cloog-$(version).tar.gz ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions download
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   rm -rf '$(<)' || exit 1
   if [ -n '$(STREAM)' ]; then
     ( cd '$(<:D)' && wget -- '$(URL)' >> '$(STREAM)' 2>&1 )
@@ -124,8 +84,7 @@ actions download
 
 
 
-for local version in $(CLOOG_VERSIONS)
-{
+for local version in $(CLOOG_VERSIONS) {
   # Use `README' file as a target representing the completion of
   # decompression action. It is suitable for the purpose because of the
   # following reasons;
@@ -143,31 +102,14 @@ for local version in $(CLOOG_VERSIONS)
 
 rule expand ( targets * : sources * : properties * )
 {
-  if ! $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  if $(sources[2])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  #assert-unspecified <gmp>                : $(properties) ;
-  #assert-specified   <gmp-hidden>         : $(properties) ;
-  #assert-unspecified <isl>                : $(properties) ;
-  #assert-specified   <isl-hidden>         : $(properties) ;
-  assert-unspecified <cloog>              : $(properties) ;
-  assert-specified   <cloog-hidden>       : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <cloog-hidden> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions expand
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   rm -rf '$(<:D)' || exit 1
   [ -f '$(>)' ] || exit 1
   if [ -n '$(STREAM)' ]; then
@@ -194,20 +136,8 @@ actions expand
 
 rule srcdir-req ( properties * )
 {
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  #assert-unspecified <gmp>                : $(properties) ;
-  #assert-specified   <gmp-hidden>         : $(properties) ;
-  #assert-unspecified <isl>                : $(properties) ;
-  #assert-specified   <isl-hidden>         : $(properties) ;
-  assert-unspecified <cloog>              : $(properties) ;
-  assert-specified   <cloog-hidden>       : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <cloog-hidden> : $(properties) ] ;
-  return <source>"$(INTRO_ROOT_DIR)/cloog-$(version)/README/$(DEFAULT_PROPERTIES)" ;
+  return "<source>$(INTRO_ROOT_DIR)/cloog-$(version)/README/$(DEFAULT_PROPERTIES)" ;
 }
 
 alias srcdir : : <conditional>@srcdir-req ;
@@ -217,43 +147,35 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  return <location>"$(includedir)" ;
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
+  return "<location>$(includedir)" ;
 }
 
 make cloog/cloog.h
   : compiler-dep
     ../gmp//install
     ../isl//install
-    srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified
+    srcdir
   : @make-install
-  : $(USE_GMP)
+  : $(USE_COMPILER)
+    $(USE_MULTITARGET)
+    $(USE_GMP)
     $(USE_ISL)
     $(USE_CLOOG)
+    $(USE_ADDRESS_MODEL)
+    $(USE_INSTRUCTION_SET)
     <conditional>@location-conditional
   ;
 explicit cloog/cloog.h ;
 
 rule make-install ( targets * : sources * : properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-specified   <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-specified   <isl>                : $(properties) ;
-  assert-specified   <isl-hidden>         : $(properties) ;
-  assert-specified   <cloog>              : $(properties) ;
-  assert-specified   <cloog-hidden>       : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local compiler-description = [ get-compiler-description $(compiler) ] ;
+  local compiler-description = [ get-compiler-description "$(compiler)" ] ;
   COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <cloog> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
 
   # Set the path to the source directory.
   local srcdir = "$(INTRO_ROOT_DIR)/cloog-$(version)" ;
@@ -264,82 +186,91 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) = ;
 
-  # Set the `--prefix' option for the `configure' script.
-  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  # Set `--prefix' option for `configure' script.
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
   local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
   OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
 
   # Set `--bindir' option for `configure' script.
-  local bindir = [ get-bindir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  local bindir = [ get-bindir "$(PREFIX)" : $(properties) ] ;
   local bindir-native = [ path.native "$(bindir)" ] ;
   OPTIONS on $(targets) += "--bindir='$(bindir-native)'" ;
 
-  # Set the `--libdir' option for the `configure' script.
-  local libdir = [ get-libdir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  # Set `--libdir' option for `configure' script.
+  local libdir = [ get-libdir "$(PREFIX)" : $(properties) ] ;
   local libdir-native = [ path.native "$(libdir)" ] ;
   OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
 
-  # Set the `--includedir' option for the `configure' script.
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  # Set `--includedir' option for `configure' script.
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
   local includedir-native = [ path.native "$(includedir)" ] ;
   OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
 
-  # Set the `--build' and `--host' options for the `configure' script.
-  local triplet = [ feature.get-values <triplet> : $(properties) ] ;
-  TRIPLET on $(targets) = $(triplet) ;
-  OPTIONS on $(targets) += --build=$(triplet) ;
-  OPTIONS on $(targets) += --host=$(triplet) ;
+  # Set `--build' and `--host' options for `configure' script.
+  local triplets = [ get-triplets $(properties) ] ;
+  local build-triplet = "$(triplets[1])" ;
+  local host-triplet = "$(triplets[2])" ;
+  BUILD_TRIPLET on $(targets) = "$(build-triplet)" ;
+  HOST_TRIPLET on $(targets) = "$(host-triplet)" ;
+  OPTIONS on $(targets) += "--build=$(build-triplet)" ;
+  OPTIONS on $(targets) += "--host=$(host-triplet)" ;
 
-  # Set the link variants for the 'configure' script.
-  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32
-  {
-    OPTIONS on $(targets) += --enable-shared ;
-    OPTIONS on $(targets) += --disable-static ;
+  # Set the link variants for `configure' script.
+  if "$(host-triplet)" = "x86_64-w64-mingw32" || "$(host-triplet)" = "i686-w64-mingw32" || "$(host-triplet)" = "i686-pc-cygwin" {
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--disable-static" ;
   }
-  else
-  {
-    OPTIONS on $(targets) += --enable-shared ;
-    OPTIONS on $(targets) += --enable-static ;
+  else {
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--enable-static" ;
   }
+
+  OPTIONS on $(targets) += --with-isl=system ;
+
+  OPTIONS on $(targets) += --with-gmp=system ;
 
   OPTIONS on $(targets) += --with-osl=no ;
 
   OPTIONS on $(targets) += --with-bits=gmp ;
 
-  local cc = [ get-cc "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  cc = [ path.native "$(cc)" ] ;
-  OPTIONS on $(targets) += "CC='$(cc)'" ;
+  local cc = [ get-cc "$(PREFIX)" : $(properties) ] ;
+  local cc-native = [ path.native "$(cc)" ] ;
+  OPTIONS on $(targets) += "CC='$(cc-native)'" ;
+
+  local variant = [ feature.get-values <variant> : $(properties) ] ;
 
   # Default `CFLAGS' seems `-O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math'.
   local cflags = [ get-cflags $(properties) ] ;
-  if $(cflags)
-  {
-    if [ feature.get-values <variant> : $(properties) ] != debug
-    {
+  if "$(cflags)" {
+    if "$(variant)" != "debug" {
       cflags = "$(cflags) -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math" ;
     }
     OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
   }
 
-  local cxx = [ get-cxx "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  cxx = [ path.native "$(cxx)" ] ;
-  OPTIONS on $(targets) += "CXX='$(cxx)'" ;
+  local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
+  local cxx-native = [ path.native "$(cxx)" ] ;
+  OPTIONS on $(targets) += "CXX='$(cxx-native)'" ;
 
   local cxxflags = [ get-cxxflags $(properties) ] ;
-  if $(cxxflags)
-  {
-    if [ feature.get-values <variant> : $(properties) ] != debug
-    {
+  if "$(cxxflags)" {
+    if "$(variant)" != "debug" {
       cxxflags = "$(cxxflags) -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math" ;
     }
     OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
   }
 
-  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  OPTIONS on $(targets) += "LDFLAGS='-Wl,--enable-new-dtags'" ;
+
+  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions make-install
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   # Restore the hacked configure script. See also `../gcc/jamfile'.
   if [ -e '$(SRCDIR)/real-configure' ]; then
     [ ! -x '$(SRCDIR)/real-configure' ] && exit 1
@@ -359,8 +290,8 @@ actions make-install
     ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`configure' CLooG $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`configure' CLooG $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`configure' CLooG $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`configure' CLooG $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -373,8 +304,8 @@ actions make-install
     ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make' CLooG $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`make' CLooG $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make' CLooG $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make' CLooG $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -384,8 +315,8 @@ actions make-install
     ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make check' CLooG $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`make check' CLooG $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make check' CLooG $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make check' CLooG $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -395,17 +326,17 @@ actions make-install
     ( cd '$(OBJDIR)' && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make install' CLooG $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`make install' CLooG $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make install' CLooG $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make install' CLooG $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
-
-  [ -f '$(<)' ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
   rm -rf '$(OBJDIR)' || exit 1
 
-  echo -n 'CLooG $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built.' | $(AWACS)
+  [ -f '$(<)' ] || exit 1
+
+  echo -n 'CLooG $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
   exit 0
 }
 
diff --git a/isl/jamfile b/isl/jamfile
--- a/isl/jamfile
+++ b/isl/jamfile
@@ -8,61 +8,37 @@ import path ;
 import "$(INTRO_ROOT_DIR)/compilers"
   : is-gcc
     is-clang
+    is-icc
     get-compiler-description
     get-compiler-prefix
     get-libdir
     get-includedir
+    get-triplets
     get-cc
     get-cflags
     get-cxx
     get-cxxflags
     get-environment-commands
+    get-property-dump-commands
   ;
-
-
-rule assert-specified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) = unspecified {
-    errors.error $(feature) is not specified for isl build. ;
-  }
-}
-
-rule assert-unspecified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) != unspecified {
-    errors.error $(feature) is not valid for isl build. ;
-  }
-}
-
 
 
 rule compiler-dep-req ( properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-unspecified <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <isl>                : $(properties) ;
-  assert-specified   <isl-hidden>         : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
-  local multitarget = [ feature.get-values <multitarget-hidden> : $(properties) ] ;
-  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
+  local compiler = [ feature.get-values <compiler-hidden> : $(properties) ] ;
   local result ;
-  if [ is-gcc $(compiler) ]
-  {
-    result = <source>../gcc//install/<multitarget>$(multitarget)/<multitarget-hidden>unspecified ;
+  if [ is-gcc "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
   }
-  else if [ is-clang $(compiler) ]
-  {
-    result = <source>../clang//install ;
+  else if [ is-clang "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
+    result += "<source>../clang//install" ;
   }
-  else
-  {
+  else if [ is-icc "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
+    result += "<source>../icc//install" ;
+  }
+  else {
     errors.error "an internal error." ;
   }
   return $(result) ;
@@ -73,35 +49,23 @@ explicit compiler-dep ;
 
 
 
-for local version in $(ISL_VERSIONS)
-{
+for local version in $(ISL_VERSIONS) {
   make "$(INTRO_ROOT_DIR)/isl-$(version).tar.bz2" : : @download ;
   explicit "$(INTRO_ROOT_DIR)/isl-$(version).tar.bz2" ;
 }
 
 rule download ( targets * : sources * : properties * )
 {
-  if $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  #assert-unspecified <gmp>                : $(properties) ;
-  #assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <isl>                : $(properties) ;
-  assert-specified   <isl-hidden>         : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <isl-hidden> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
   URL on $(targets) = "http://ftp.tsukuba.wide.ad.jp/software/gcc/infrastructure/isl-$(version).tar.bz2" ;
   #URL on $(targets) = "http://www.ring.gr.jp/archives/lang/egcs/infrastructure/isl-$(version).tar.bz2" ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions download
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   rm -rf '$(<)' || exit 1
   if [ -n '$(STREAM)' ]; then
     ( cd '$(<:D)' && wget -- '$(URL)' >> '$(STREAM)' 2>&1 )
@@ -120,8 +84,7 @@ actions download
 
 
 
-for local version in $(ISL_VERSIONS)
-{
+for local version in $(ISL_VERSIONS) {
   # Use `ChangeLog' file as a target representing the completion of
   # decompression action. It is suitable for the purpose because of the
   # following reasons;
@@ -139,29 +102,14 @@ for local version in $(ISL_VERSIONS)
 
 rule expand ( targets * : sources * : properties * )
 {
-  if ! $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  if $(sources[2])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  #assert-unspecified <gmp>                : $(properties) ;
-  #assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <isl>                : $(properties) ;
-  assert-specified   <isl-hidden>         : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <isl-hidden> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions expand
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   rm -rf '$(<:D)' || exit 1
   [ -f '$(>)' ] || exit 1
   if [ -n '$(STREAM)' ]; then
@@ -188,18 +136,8 @@ actions expand
 
 rule srcdir-req ( properties * )
 {
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  #assert-unspecified <gmp>                : $(properties) ;
-  #assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <isl>                : $(properties) ;
-  assert-specified   <isl-hidden>         : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <isl-hidden> : $(properties) ] ;
-  return <source>"$(INTRO_ROOT_DIR)/isl-$(version)/ChangeLog/$(DEFAULT_PROPERTIES)" ;
+  return "<source>$(INTRO_ROOT_DIR)/isl-$(version)/ChangeLog/$(DEFAULT_PROPERTIES)" ;
 }
 
 alias srcdir : : <conditional>@srcdir-req ;
@@ -209,39 +147,33 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  return <location>"$(includedir)" ;
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
+  return "<location>$(includedir)" ;
 }
 
 make isl/version.h
   : compiler-dep
     ../gmp//install
-    srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified
+    srcdir
   : @make-install
-  : $(USE_GMP)
+  : $(USE_COMPILER)
+    $(USE_MULTITARGET)
+    $(USE_GMP)
     $(USE_ISL)
+    $(USE_ADDRESS_MODEL)
+    $(USE_INSTRUCTION_SET)
     <conditional>@location-conditional
   ;
 explicit isl/version.h ;
 
 rule make-install ( targets * : sources * : properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-specified   <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-specified   <isl>                : $(properties) ;
-  assert-specified   <isl-hidden>         : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local compiler-description = [ get-compiler-description $(compiler) ] ;
+  local compiler-description = [ get-compiler-description "$(compiler)" ] ;
   COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <isl> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
 
   # Set the path to the source directory.
   local srcdir = "$(INTRO_ROOT_DIR)/isl-$(version)" ;
@@ -252,78 +184,82 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) = ;
 
-  # Set the `--prefix' option for the `configure' script.
-  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  # Set `--prefix' option for `configure' script.
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
   local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
   OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
 
-  # Set the `--libdir' option for the `configure' script.
-  local libdir = [ get-libdir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  # Set `--libdir' option for `configure' script.
+  local libdir = [ get-libdir "$(PREFIX)" : $(properties) ] ;
   local libdir-native = [ path.native "$(libdir)" ] ;
   OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
 
-  # Set the `--includedir' option for the `configure' script.
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  # Set `--includedir' option for `configure' script.
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
   local includedir-native = [ path.native "$(includedir)" ] ;
   OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
 
-  # Set the `--build' and `--host' options for the `configure' script.
-  local triplet = [ feature.get-values <triplet> : $(properties) ] ;
-  TRIPLET on $(targets) = $(triplet) ;
-  OPTIONS on $(targets) += --build=$(triplet) ;
-  OPTIONS on $(targets) += --host=$(triplet) ;
+  # Set `--build' and `--host' options for `configure' script.
+  local triplets = [ get-triplets $(properties) ] ;
+  local build-triplet = "$(triplets[1])" ;
+  local host-triplet = "$(triplets[2])" ;
+  BUILD_TRIPLET on $(targets) = "$(build-triplet)" ;
+  HOST_TRIPLET on $(targets) = "$(host-triplet)" ;
+  OPTIONS on $(targets) += "--build=$(build-triplet)" ;
+  OPTIONS on $(targets) += "--host=$(host-triplet)" ;
 
-  # Set the link variants for the 'configure' script.
-  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32
-  {
-    OPTIONS on $(targets) += --enable-shared ;
-    OPTIONS on $(targets) += --disable-static ;
+  # Set the link variants for `configure' script.
+  if "$(host-triplet)" = "x86_64-w64-mingw32" || "$(host-triplet)" = "i686-w64-mingw32" || "$(host-triplet)" = "i686-pc-cygwin" {
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--disable-static" ;
   }
-  else
-  {
-    OPTIONS on $(targets) += --enable-shared ;
-    OPTIONS on $(targets) += --enable-static ;
-  }
-
-  if [ is-clang $(compiler) ]
-  {
-    OPTIONS on $(targets) += "--with-clang=system" ;
+  else {
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--enable-static" ;
   }
 
-  local cc = [ get-cc "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  cc = [ path.native "$(cc)" ] ;
-  OPTIONS on $(targets) += "CC='$(cc)'" ;
+  #if [ is-clang "$(compiler)" ] {
+  #  OPTIONS on $(targets) += "--with-clang=system" ;
+  #}
+
+  local cc = [ get-cc "$(PREFIX)" : $(properties) ] ;
+  local cc-native = [ path.native "$(cc)" ] ;
+  OPTIONS on $(targets) += "CC='$(cc-native)'" ;
+
+  local variant = [ feature.get-values <variant> : $(properties) ] ;
 
   # Default `CFLAGS' seems `-O3 -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math'.
   local cflags = [ get-cflags $(properties) ] ;
-  if $(cflags)
-  {
-    if [ feature.get-values <variant> : $(properties) ] != debug
-    {
+  if "$(cflags)" {
+    if "$(variant)" != "debug" {
       cflags = "$(cflags) -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math" ;
     }
     OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
   }
 
-  local cxx = [ get-cxx "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  cxx = [ path.native "$(cxx)" ] ;
-  OPTIONS on $(targets) += "CXX='$(cxx)'" ;
+  local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
+  local cxx-native = [ path.native "$(cxx)" ] ;
+  OPTIONS on $(targets) += "CXX='$(cxx-native)'" ;
 
   local cxxflags = [ get-cxxflags $(properties) ] ;
-  if $(cxxflags)
-  {
-    if [ feature.get-values <variant> : $(properties) ] != debug
-    {
+  if "$(cxxflags)" {
+    if "$(variant)" != "debug" {
       cxxflags = "$(cxxflags) -fomit-frame-pointer -malign-double -fstrict-aliasing -ffast-math" ;
     }
     OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
   }
 
-  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  OPTIONS on $(targets) += "LDFLAGS='-Wl,--enable-new-dtags'" ;
+
+  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions make-install
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   # Restore the hacked configure script. See also `../gcc/jamfile'.
   if [ -e '$(SRCDIR)/real-configure' ]; then
     [ ! -x '$(SRCDIR)/real-configure' ] && exit 1
@@ -332,7 +268,8 @@ actions make-install
 
   [ -x '$(SRCDIR)/configure' ] || exit 1
   [ -x '$(SRCDIR)/config.sub' ] || exit 1
-  [ `'$(SRCDIR)/config.sub' $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
+  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
   { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
@@ -346,8 +283,8 @@ actions make-install
   fi
   if [ $? -ne 0 ]; then
     mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`configure' isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR:$$: failed to \`configure' isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR:$$: failed to \`configure' isl $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR:$$: failed to \`configure' isl $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -361,8 +298,8 @@ actions make-install
   fi
   if [ $? -ne 0 ]; then
     mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`make' isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR:$$: failed to \`make' isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR:$$: failed to \`make' isl $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR:$$: failed to \`make' isl $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -373,8 +310,8 @@ actions make-install
   fi
   if [ $? -ne 0 ]; then
     mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`make check' isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR:$$: failed to \`make check' isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR:$$: failed to \`make check' isl $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR:$$: failed to \`make check' isl $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -385,17 +322,17 @@ actions make-install
   fi
   if [ $? -ne 0 ]; then
     mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`make install' isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR:$$: failed to \`make install' isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR:$$: failed to \`make install' isl $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR:$$: failed to \`make install' isl $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
-
-  [ -f '$(<)' ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
   rm -rf '$(OBJDIR)' || exit 1
 
-  echo -n 'isl $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built.' | $(AWACS)
+  [ -f '$(<)' ] || exit 1
+
+  echo -n 'isl $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
   exit 0
 }
 
diff --git a/mpfr/jamfile b/mpfr/jamfile
--- a/mpfr/jamfile
+++ b/mpfr/jamfile
@@ -8,61 +8,37 @@ import path ;
 import "$(INTRO_ROOT_DIR)/compilers"
   : is-gcc
     is-clang
+    is-icc
     get-compiler-description
     get-compiler-prefix
     get-libdir
     get-includedir
+    get-triplets
     get-cc
     get-cflags
     get-cxx
     get-cxxflags
     get-environment-commands
+    get-property-dump-commands
   ;
-
-
-rule assert-specified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) = unspecified {
-    errors.error $(feature) is not specified for MPFR build. ;
-  }
-}
-
-rule assert-unspecified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) != unspecified {
-    errors.error $(feature) is not valid for MPFR build. ;
-  }
-}
-
 
 
 rule compiler-dep-req ( properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-unspecified <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <mpfr>               : $(properties) ;
-  assert-specified   <mpfr-hidden>        : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
-  local multitarget = [ feature.get-values <multitarget-hidden> : $(properties) ] ;
-  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
+  local compiler = [ feature.get-values <compiler-hidden> : $(properties) ] ;
   local result ;
-  if [ is-gcc $(compiler) ]
-  {
-    result = <source>../gcc//install/<multitarget>$(multitarget)/<multitarget-hidden>unspecified ;
+  if [ is-gcc "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
   }
-  else if [ is-clang $(compiler) ]
-  {
-    result = <source>../clang//install ;
+  else if [ is-clang "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
+    result += "<source>../clang//install" ;
   }
-  else
-  {
+  else if [ is-icc "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
+    result += "<source>../icc//install" ;
+  }
+  else {
     errors.error "an internal error." ;
   }
   return $(result) ;
@@ -73,35 +49,23 @@ explicit compiler-dep ;
 
 
 
-for local version in $(MPFR_VERSIONS)
-{
+for local version in $(MPFR_VERSIONS) {
   make "$(INTRO_ROOT_DIR)/mpfr-$(version).tar.bz2" : : @download ;
   explicit "$(INTRO_ROOT_DIR)/mpfr-$(version).tar.bz2" ;
 }
 
 rule download ( targets * : sources * : properties * )
 {
-  if $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  #assert-unspecified <gmp>                : $(properties) ;
-  #assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <mpfr>               : $(properties) ;
-  assert-specified   <mpfr-hidden>        : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <mpfr-hidden> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
   URL on $(targets) = http://ftp.tsukuba.wide.ad.jp/software/mpfr/mpfr-$(version).tar.bz2 ;
   #URL on $(targets) = http://core.ring.gr.jp/pub/GNU/mpfr/mpfr-$(version).tar.bz2 ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions download
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   rm -rf '$(<)' || exit 1
   if [ -n '$(STREAM)' ]; then
     ( cd '$(<:D)' && wget -- '$(URL)' >> '$(STREAM)' 2>&1 )
@@ -120,8 +84,7 @@ actions download
 
 
 
-for local version in $(MPFR_VERSIONS)
-{
+for local version in $(MPFR_VERSIONS) {
   # Use `README' file as a target representing the completion of
   # decompression action. It is suitable for the purpose because of the
   # following reasons;
@@ -139,29 +102,14 @@ for local version in $(MPFR_VERSIONS)
 
 rule expand ( targets * : sources * : properties * )
 {
-  if ! $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  if $(sources[2])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  #assert-unspecified <gmp>                : $(properties) ;
-  #assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <mpfr>               : $(properties) ;
-  assert-specified   <mpfr-hidden>        : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <mpfr-hidden> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions expand
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   rm -rf '$(<:D)' || exit 1
   [ -f '$(>)' ] || exit 1
   if [ -n '$(STREAM)' ]; then
@@ -188,18 +136,8 @@ actions expand
 
 rule srcdir-req ( properties * )
 {
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  #assert-unspecified <gmp>                : $(properties) ;
-  #assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <mpfr>               : $(properties) ;
-  assert-specified   <mpfr-hidden>        : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <mpfr-hidden> : $(properties) ] ;
-  return <source>"$(INTRO_ROOT_DIR)/mpfr-$(version)/README/$(DEFAULT_PROPERTIES)" ;
+  return "<source>$(INTRO_ROOT_DIR)/mpfr-$(version)/README/$(DEFAULT_PROPERTIES)" ;
 }
 
 alias srcdir : : <conditional>@srcdir-req ;
@@ -209,39 +147,33 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  return <location>"$(includedir)" ;
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
+  return "<location>$(includedir)" ;
 }
 
 make mpfr.h
   : compiler-dep
     ../gmp//install
-    srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified
+    srcdir
   : @make-install
-  : $(USE_GMP)
+  : $(USE_COMPILER)
+    $(USE_MULTITARGET)
+    $(USE_GMP)
     $(USE_MPFR)
+    $(USE_ADDRESS_MODEL)
+    $(USE_INSTRUCTION_SET)
     <conditional>@location-conditional
   ;
 explicit mpfr.h ;
 
 rule make-install ( targets * : sources * : properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-specified   <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-specified   <mpfr>               : $(properties) ;
-  assert-specified   <mpfr-hidden>        : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local compiler-description = [ get-compiler-description $(compiler) ] ;
+  local compiler-description = [ get-compiler-description "$(compiler)" ] ;
   COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <mpfr> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
 
   # Set the path to the source directory.
   local srcdir = "$(INTRO_ROOT_DIR)/mpfr-$(version)" ;
@@ -252,87 +184,101 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) = ;
 
-  # Set the `--prefix' option for the `configure' script.
-  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  # Set `--prefix' option for `configure' script.
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
   local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
   OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
 
-  # Set the `--libdir' option for the `configure' script.
-  local libdir = [ get-libdir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  # Set `--libdir' option for `configure' script.
+  local libdir = [ get-libdir "$(PREFIX)" : $(properties) ] ;
   local libdir-native = [ path.native "$(libdir)" ] ;
   OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
 
-  # Set the `--includedir' option for the `configure' script.
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  # Set `--includedir' option for `configure' script.
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
   local includedir-native = [ path.native "$(includedir)" ] ;
   OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
 
-  # Set the `--build' and `--host' options for the `configure' script.
-  local triplet = [ feature.get-values <triplet> : $(properties) ] ;
-  TRIPLET on $(targets) = $(triplet) ;
-  OPTIONS on $(targets) += --build=$(triplet) ;
-  OPTIONS on $(targets) += --host=$(triplet) ;
+  # Set `--build' and `--host' options for `configure' script.
+  local triplets = [ get-triplets $(properties) ] ;
+  local build-triplet = "$(triplets[1])" ;
+  local host-triplet = "$(triplets[2])" ;
+  BUILD_TRIPLET on $(targets) = "$(build-triplet)" ;
+  HOST_TRIPLET on $(targets) = "$(host-triplet)" ;
+  OPTIONS on $(targets) += "--build=$(build-triplet)" ;
+  OPTIONS on $(targets) += "--host=$(host-triplet)" ;
 
-  if [ feature.get-values <variant> : $(properties) ] = debug
-  {
-    OPTIONS on $(targets) += --enable-assert ;
+  local variant = [ feature.get-values <variant> : $(properties) ] ;
+  if "$(variant)" = "debug" {
+    OPTIONS on $(targets) += "--enable-assert" ;
   }
 
-  # Set the link variants for the 'configure' script.
-  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32
-  {
-    OPTIONS on $(targets) += --enable-shared ;
-    OPTIONS on $(targets) += --disable-static ;
+  # Set the link variants for `configure' script.
+  if "$(host-triplet)" = "x86_64-w64-mingw32" || "$(host-triplet)" = "i686-w64-mingw32" || "$(host-triplet)" = "i686-pc-cygwin" {
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--disable-static" ;
   }
-  else
-  {
-    OPTIONS on $(targets) += --enable-shared ;
-    OPTIONS on $(targets) += --enable-static ;
+  else {
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--enable-static" ;
   }
 
-  local cc = [ get-cc "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  cc = [ path.native "$(cc)" ] ;
-  OPTIONS on $(targets) += "CC='$(cc)'" ;
+  local cc = [ get-cc "$(PREFIX)" : $(properties) ] ;
+  local cc-native = [ path.native "$(cc)" ] ;
+  OPTIONS on $(targets) += "CC='$(cc-native)'" ;
+
+  local lto = [ feature.get-values <lto> : $(properties) ] ;
 
   # Default `CFLAGS' seems `-Wall -Wmissing-prototypes -Wpointer-arith -g -O2'.
   local cflags = [ get-cflags $(properties) ] ;
-  if $(cflags)
-  {
-    if [ feature.get-values <variant> : $(properties) ] = lto
-    {
-      OPTIONS on $(targets) += "CFLAGS='$(cflags) -Wall -Wmissing-prototypes -Wpointer-arith'" ;
+  if "$(cflags)" {
+    cflags = "$(cflags) -Wall -Wmissing-prototypes -Wpointer-arith" ;
+    if "$(lto)" = "off" {
+      cflags = "$(cflags) -g" ;
     }
-    else
-    {
-      OPTIONS on $(targets) += "CFLAGS='$(cflags) -Wall -Wmissing-prototypes -Wpointer-arith -g'" ;
+    else if "$(lto)" = "on" {
+      # Do nothing.
     }
+    else {
+      errors.error "an internal error." ;
+    }
+    OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
   }
 
-  local cxx = [ get-cxx "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  cxx = [ path.native "$(cxx)" ] ;
-  OPTIONS on $(targets) += "CXX='$(cxx)'" ;
+  local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
+  local cxx-native = [ path.native "$(cxx)" ] ;
+  OPTIONS on $(targets) += "CXX='$(cxx-native)'" ;
 
   local cxxflags = [ get-cxxflags $(properties) ] ;
-  if $(cxxflags)
-  {
-    if [ feature.get-values <variant> : $(properties) ] = lto
-    {
-      OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags) -Wall -Wpointer-arith'" ;
+  if "$(cxxflags)" {
+    cxxflags = "$(cxxflags) -Wall -Wpointer-arith" ;
+    if "$(lto)" = "off" {
+      cxxflags = "$(cxxflags) -g" ;
     }
-    else
-    {
-      OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags) -Wall -Wpointer-arith -g'" ;
+    else if "$(lto)" = "on" {
+      # Do nothing.
     }
+    else {
+      errors.error "an internal error." ;
+    }
+    OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
   }
 
-  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  OPTIONS on $(targets) += "LDFLAGS='-Wl,--enable-new-dtags'" ;
+
+  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions make-install
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   [ -x '$(SRCDIR)/configure' ] || exit 1
   [ -x '$(SRCDIR)/config.sub' ] || exit 1
-  [ `'$(SRCDIR)/config.sub' $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
+  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
   { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
@@ -345,8 +291,8 @@ actions make-install
     ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`configure' MPFR $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`configure' MPFR $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`configure' MPFR $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`configure' MPFR $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -359,8 +305,8 @@ actions make-install
     ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make' MPFR $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`make' MPFR $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make' MPFR $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make' MPFR $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -370,8 +316,8 @@ actions make-install
     ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make check' MPFR $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`make check' MPFR $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make check' MPFR $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make check' MPFR $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -381,17 +327,17 @@ actions make-install
     ( cd '$(OBJDIR)' && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make install' MPFR $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`make install' MPFR $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make install' MPFR $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make install' MPFR $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
-
-  [ -f '$(<)' ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
   rm -rf '$(OBJDIR)' || exit 1
 
-  echo -n 'MPFR $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built.' | $(AWACS)
+  [ -f '$(<)' ] || exit 1
+
+  echo -n 'MPFR $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
   exit 0
 }
 
diff --git a/ppl/jamfile b/ppl/jamfile
--- a/ppl/jamfile
+++ b/ppl/jamfile
@@ -8,61 +8,37 @@ import path ;
 import "$(INTRO_ROOT_DIR)/compilers"
   : is-gcc
     is-clang
+    is-icc
     get-compiler-description
     get-compiler-prefix
     get-libdir
     get-includedir
+    get-triplets
     get-cc
     get-cflags
     get-cxx
     get-cxxflags
     get-environment-commands
+    get-property-dump-commands
   ;
-
-
-rule assert-specified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) = unspecified {
-    errors.error $(feature) is not specified for PPL build. ;
-  }
-}
-
-rule assert-unspecified ( feature : properties * )
-{
-  local val = [ feature.get-values $(feature) : $(properties) ] ;
-  if $(val) != unspecified {
-    errors.error $(feature) is not valid for PPL build. ;
-  }
-}
-
 
 
 rule compiler-dep-req ( properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-unspecified <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <ppl>                : $(properties) ;
-  assert-specified   <ppl-hidden>         : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
-  local multitarget = [ feature.get-values <multitarget-hidden> : $(properties) ] ;
-  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
+  local compiler = [ feature.get-values <compiler-hidden> : $(properties) ] ;
   local result ;
-  if [ is-gcc $(compiler) ]
-  {
-    result = <source>../gcc//install/<multitarget>$(multitarget)/<multitarget-hidden>unspecified ;
+  if [ is-gcc "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
   }
-  else if [ is-clang $(compiler) ]
-  {
-    result = <source>../clang//install ;
+  else if [ is-clang "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
+    result += "<source>../clang//install" ;
   }
-  else
-  {
+  else if [ is-icc "$(compiler)" ] {
+    result += "<source>../gcc//install" ;
+    result += "<source>../icc//install" ;
+  }
+  else {
     errors.error "an internal error." ;
   }
   return $(result) ;
@@ -73,34 +49,22 @@ explicit compiler-dep ;
 
 
 
-for local version in $(PPL_VERSIONS)
-{
+for local version in $(PPL_VERSIONS) {
   make "$(INTRO_ROOT_DIR)/ppl-$(version).tar.bz2" : : @download ;
   explicit "$(INTRO_ROOT_DIR)/ppl-$(version).tar.bz2" ;
 }
 
 rule download ( targets * : sources * : properties * )
 {
-  if $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  assert-unspecified <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <ppl>                : $(properties) ;
-  assert-specified   <ppl-hidden>         : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <ppl-hidden> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
   URL on $(targets) = http://bugseng.com/products/ppl/download/ftp/releases/$(version)/ppl-$(version).tar.bz2 ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions download
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   rm -rf '$(<)' || exit 1
   if [ -n '$(STREAM)' ]; then
     ( cd '$(<:D)' && wget -- '$(URL)' >> '$(STREAM)' 2>&1 )
@@ -119,8 +83,7 @@ actions download
 
 
 
-for local version in $(PPL_VERSIONS)
-{
+for local version in $(PPL_VERSIONS) {
   # Use `README' file as a target representing the completion of
   # decompression action. It is suitable for the purpose because of the
   # following reasons;
@@ -138,29 +101,14 @@ for local version in $(PPL_VERSIONS)
 
 rule expand ( targets * : sources * : properties * )
 {
-  if ! $(sources[1])
-  {
-    errors.error "an internal error." ;
-  }
-  if $(sources[2])
-  {
-    errors.error "an internal error." ;
-  }
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  assert-unspecified <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <ppl>                : $(properties) ;
-  assert-specified   <ppl-hidden>         : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <ppl-hidden> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions expand
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   rm -rf '$(<:D)' || exit 1
   [ -f '$(>)' ] || exit 1
   if [ -n '$(STREAM)' ]; then
@@ -187,18 +135,8 @@ actions expand
 
 rule srcdir-req ( properties * )
 {
-  assert-unspecified <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-unspecified <multitarget-hidden> : $(properties) ;
-  assert-unspecified <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-unspecified <ppl>                : $(properties) ;
-  assert-specified   <ppl-hidden>         : $(properties) ;
-  assert-unspecified <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local version = [ feature.get-values <ppl-hidden> : $(properties) ] ;
-  return <source>"$(INTRO_ROOT_DIR)/ppl-$(version)/README/$(DEFAULT_PROPERTIES)" ;
+  return "<source>$(INTRO_ROOT_DIR)/ppl-$(version)/README/$(DEFAULT_PROPERTIES)" ;
 }
 
 alias srcdir : : <conditional>@srcdir-req ;
@@ -208,39 +146,33 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  return <location>"$(includedir)" ;
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
+  return "<location>$(includedir)" ;
 }
 
 make ppl.hh
   : compiler-dep
     ../gmp//install
-    srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified
+    srcdir
   : @make-install
-  : $(USE_GMP)
+  : $(USE_COMPILER)
+    $(USE_MULTITARGET)
+    $(USE_GMP)
     $(USE_PPL)
+    $(USE_ADDRESS_MODEL)
+    $(USE_INSTRUCTION_SET)
     <conditional>@location-conditional
   ;
 explicit ppl.hh ;
 
 rule make-install ( targets * : sources * : properties * )
 {
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-specified   <gmp>                : $(properties) ;
-  assert-specified   <gmp-hidden>         : $(properties) ;
-  assert-specified   <ppl>                : $(properties) ;
-  assert-specified   <ppl-hidden>         : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local compiler-description = [ get-compiler-description $(compiler) ] ;
+  local compiler-description = [ get-compiler-description "$(compiler)" ] ;
   COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <ppl> : $(properties) ] ;
-  VERSION on $(targets) = $(version) ;
+  VERSION on $(targets) = "$(version)" ;
 
   # Set the path to the source directory.
   local srcdir = "$(INTRO_ROOT_DIR)/ppl-$(version)" ;
@@ -251,111 +183,127 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) = ;
 
-  # Set the `--prefix' option for the `configure' script.
-  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  # Set `--prefix' option for `configure' script.
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
   local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
   OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
 
-  # Set the `--libdir' option for the `configure' script.
-  local libdir = [ get-libdir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  # Set `--libdir' option for `configure' script.
+  local libdir = [ get-libdir "$(PREFIX)" : $(properties) ] ;
   local libdir-native = [ path.native "$(libdir)" ] ;
   OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
 
-  # Set the `--includedir' option for the `configure' script.
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  # Set `--includedir' option for `configure' script.
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
   local includedir-native = [ path.native "$(includedir)" ] ;
   OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
 
-  # Set the `--build' and `--host' options for the `configure' script.
-  local triplet = [ feature.get-values <triplet> : $(properties) ] ;
-  TRIPLET on $(targets) = $(triplet) ;
-  OPTIONS on $(targets) += --build=$(triplet) ;
-  OPTIONS on $(targets) += --host=$(triplet) ;
+  # Set `--build' and `--host' options for `configure' script.
+  local triplets = [ get-triplets $(properties) ] ;
+  local build-triplet = "$(triplets[1])" ;
+  local host-triplet = "$(triplets[2])" ;
+  BUILD_TRIPLET on $(targets) = "$(build-triplet)" ;
+  HOST_TRIPLET on $(targets) = "$(host-triplet)" ;
+  OPTIONS on $(targets) += "--build=$(build-triplet)" ;
+  OPTIONS on $(targets) += "--host=$(host-triplet)" ;
 
   local variant = [ feature.get-values <variant> : $(properties) ] ;
-  if $(variant) = debug
-  {
-    OPTIONS on $(targets) += --enable-debugging ;
-    OPTIONS on $(targets) += --enable-assertions ;
-    OPTIONS on $(targets) += --enable-more-assertions ;
+  if "$(variant)" = "debug" {
+    OPTIONS on $(targets) += "--enable-debugging" ;
+    OPTIONS on $(targets) += "--enable-assertions" ;
+    #OPTIONS on $(targets) += "--enable-more-assertions" ;
   }
-  else if $(variant) = profile
-  {
-    OPTIONS on $(targets) += --enable-profiling ;
+  else if "$(variant)" = "release" {
+    # Do nothing.
   }
-
-  OPTIONS on $(targets) += --enable-pch ;
-
-  # Set the link variants for the 'configure' script.
-  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32
-  {
-    OPTIONS on $(targets) += --enable-shared ;
-    OPTIONS on $(targets) += --disable-static ;
+  else if "$(variant)" = "profile" {
+    OPTIONS on $(targets) += "--enable-profiling" ;
   }
-  else
-  {
-    OPTIONS on $(targets) += --enable-shared ;
-    OPTIONS on $(targets) += --enable-static ;
+  else {
+    errors.error "an internal error." ;
   }
 
-  local cc = [ get-cc "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  cc = [ path.native "$(cc)" ] ;
-  OPTIONS on $(targets) += "--with-cc='$(cc)'" ;
+  #OPTIONS on $(targets) += "--enable-pch" ;
+
+  # Set the link variants for `configure' script.
+  if "$(host-triplet)" = "x86_64-w64-mingw32" || "$(host-triplet)" = "i686-w64-mingw32" || "$(host-triplet)" = "i686-pc-cygwin" {
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--disable-static" ;
+  }
+  else {
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--enable-static" ;
+  }
+
+  local cc = [ get-cc "$(PREFIX)" : $(properties) ] ;
+  local cc-native = [ path.native "$(cc)" ] ;
+  OPTIONS on $(targets) += "--with-cc='$(cc-native)'" ;
+
+  local lto = [ feature.get-values <lto> : $(properties) ] ;
 
   local cflags = [ get-cflags $(properties) ] ;
-  if $(cflags)
-  {
-    if [ feature.get-values <variant> : $(properties) ] = lto
-    {
-      OPTIONS on $(targets) += "CFLAGS='$(cflags) -frounding-math -Wall'" ;
+  if "$(cflags)" {
+    if "$(lto)" = "off" {
+      cflags = "$(cflags) -g" ;
     }
-    else
-    {
-      OPTIONS on $(targets) += "CFLAGS='$(cflags) -g -frounding-math -Wall'" ;
+    else if "$(lto)" = "on" {
+      # Do nothing.
     }
+    else {
+      errors.error "an internal error." ;
+    }
+    cflags = "$(cflags) -frounding-math -Wall" ;
+    OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
   }
 
-  local cxx = [ get-cxx "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
-  cxx = [ path.native "$(cxx)" ] ;
-  OPTIONS on $(targets) += "--with-cxx='$(cxx)'" ;
+  local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
+  local cxx-native = [ path.native "$(cxx)" ] ;
+  OPTIONS on $(targets) += "--with-cxx='$(cxx-native)'" ;
 
   # Default `CXXFLAGS' seems `-g -O2 -frounding-math -W -Wall'.
   # When `--enable-profiling' is specified, `-pg -DPPL_PROFILING=1' is added to `CXXFLAGS'.
   local cxxflags = [ get-cxxflags $(properties) ] ;
-  if $(cxxflags)
-  {
+  if "$(cxxflags)" {
     # The build of PPL requires GNU extensions.
     local std = [ feature.get-values <std> : $(properties) ] ;
-    if $(std) = c++03
-    {
-      cxxflags = "$(cxxflags) -std=gnu++03" ;
+    if "$(std)" = "c++03" {
+      if [ is-clang "$(compiler)" ] {
+        # Clang does not support `-std=gnu++03'.
+        cxxflags = "$(cxxflags) -std=gnu++98" ;
+      }
+      else {
+        cxxflags = "$(cxxflags) -std=gnu++03" ;
+      }
     }
-    else if $(std) = c++11
-    {
+    else if "$(std)" = "c++11" {
       cxxflags = "$(cxxflags) -std=gnu++0x" ;
     }
-    else
-    {
+    else {
       error "`<std>$(std)' is not valid" ;
     }
-    if $(variant) != lto
-    {
-      # `-g' is default but it is not compatible with `-flto'.
+    #cxxflags = "$(cxxflags) -pg -DPPL_PROFILING=1" ;
+    if "$(lto)" = "off" {
       cxxflags = "$(cxxflags) -g" ;
     }
-    if $(variant) = profile
-    {
-      cxxflags = "$(cxxflags) -pg -DPPL_PROFILING=1" ;
+    else if "$(lto)" = "on" {
+      # Do nothing.
+    }
+    else {
+      errors.error "an internal error." ;
     }
     cxxflags = "$(cxxflags) -frounding-math -Wall" ;
     OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
   }
 
-  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
 }
 actions make-install
 {
+  $(PROPERTY_DUMP_COMMANDS)
+
   # Restore the hacked configure script. See also `../gcc/jamfile'.
   if [ -e '$(SRCDIR)/real-configure' ]; then
     [ ! -x '$(SRCDIR)/real-configure' ] && exit 1
@@ -364,7 +312,8 @@ actions make-install
 
   [ -x '$(SRCDIR)/configure' ] || exit 1
   [ -x '$(SRCDIR)/config.sub' ] || exit 1
-  [ `'$(SRCDIR)/config.sub' $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
+  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
   { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
@@ -377,8 +326,8 @@ actions make-install
     ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`configure' PPL $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`configure' PPL $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`configure' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`configure' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -391,8 +340,8 @@ actions make-install
     ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make' PPL $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`make' PPL $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -408,8 +357,8 @@ actions make-install
     fi
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make check' PPL $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`make check' PPL $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make check' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make check' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
 
@@ -419,17 +368,17 @@ actions make-install
     ( cd '$(OBJDIR)' && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make install' PPL $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to \`make install' PPL $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make install' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
+    echo -n "ERROR: failed to \`make install' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
     exit 1
   fi
-
-  [ -f '$(<)' ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
   rm -rf '$(OBJDIR)' || exit 1
 
-  echo -n 'PPL $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built.' | $(AWACS)
+  [ -f '$(<)' ] || exit 1
+
+  echo -n 'PPL $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
   exit 0
 }
 
