Added build scripts for `Biutils', `mingw-w64-headers' and `mingw-w64-crt'.

diff --git a/binutils/jamfile b/binutils/jamfile
--- a/binutils/jamfile
+++ b/binutils/jamfile
@@ -1,74 +1,70 @@
-project gmp ;
+project binutils ;
 
 import alias ;
 import errors ;
 import feature ;
 import make ;
+import regex ;
 
 path-constant THIS_DIR : . ;
 
 
-rule gcc-dep-conditional-req ( properties * )
+rule gcc-dep-req ( properties * )
 {
-  local results = ;
   local build = [ feature.get-values <intro-build> : $(properties) ] ;
   local host = [ feature.get-values <intro-host> : $(properties) ] ;
   if $(host) != $(build) {
-    local gcc-target = ;
-    gcc-target = <source>../gcc//install ;
-    gcc-target = $(gcc-target)/<intro-build>unspecified ;
-    gcc-target = $(gcc-target)/<intro-host>unspecified ;
-    gcc-target = $(gcc-target)/<intro-target>$(host) ;
-    # `<intro-abi>' is automatically propagated.
-    local prefix = [ feature.get-values <intro-prefix> : $(properties) ] ;
-    if ! [ regex.match "^(/.+/$(host))$" : $(prefix) : 1 ] {
-      errors.error "ERROR: the property '<prefix>$(prefix)' is not valid." ;
+    local result = <source>../gcc//install ;
+    result = $(result)/<intro-build>unspecified ;
+    result = $(result)/<intro-host>unspecified ;
+    if $(host) = $(build) {
+      result = $(result)/<intro-target>unspecified ;
     }
-    local gcc-prefix = [ regex.match "^(/.+)/$(host)$" : $(prefix) : 1 ] ;
-    gcc-target = $(gcc-target)/<intro-prefix>$(gcc-prefix) ;
-    gcc-target = $(gcc-target)/<intro-link>unspecified ;
-    gcc-target = $(gcc-target)/<intro-check>yes ;
+    else {
+      result = $(result)/<intro-target>$(host) ;
+    }
+    # `<intro-abi>' is automatically propagated.
+    # `<intro-prefix>' is automatically propagated.
+    # `<intro-link>' is automatically propagated.
+    # `<intro-check>' is automatically propagated.
     # `<intro-stdour>' is automatically propagated.
     # `<intro-stderr>' is automatically propagated.
-    local gcc-version-cross-default = [ feature.get-values <gcc-version-cross-default> : $(properties) ] ;
-    gcc-target = $(gcc-target)/<gcc-version>$(gcc-version-cross-default) ;
-    gcc-target = $(gcc-target)/<gcc-version-cross-default>unspecified ;
-    errors.error $(gcc-target) ;
-    results += $(gcc-target) ;
+    local gcc-version = [ feature.get-values <gcc-version-cross-default> : $(properties) ] ;
+    result = $(result)/<gcc-version>$(gcc-version) ;
+    # `<binutils-version>' is automatically propagated.
+    #errors.error $(result) ;
+    return $(result) ;
   }
-  return $(results) ;
 }
 
-alias gcc-dep-conditional
-  : # `../gcc//install' is added as a source by the indirect conditional requirements.
-  : <conditional>@gcc-dep-conditional-req
+alias gcc-dep
+  : # `../gcc//install' is added by the indirect conditional requirements.
+  : <conditional>@gcc-dep-req
   ;
-explicit gcc-dep-conditional ;
+explicit gcc-dep ;
 
 
-make gmp.download
+make binutils.download
   : # No sources.
-  : @download-gmp
+  : @download-binutils
   ;
-explicit gmp.download ;
+explicit binutils.download ;
 
-rule download-gmp ( targets * : sources * : properties * )
+rule download-binutils ( targets * : sources * : properties * )
 {
-  local version = [ feature.get-values <gmp-version> : $(properties) ] ;
-  local host = [ feature.get-values <intro-host> : $(properties) ] ;
-  local link = [ feature.get-values <intro-link> : $(properties) ] ;
-  URL on $(targets) = http://core.ring.gr.jp/pub/GNU/gmp/gmp-$(version).tar.bz2 ;
-  TARBALL_GZ on $(targets) = $(THIS_DIR)/gmp-$(version).tar.gz ;
-  TARBALL_BZ2 on $(targets) = $(THIS_DIR)/gmp-$(version).tar.bz2 ;
+  local version = [ feature.get-values <binutils-version> : $(properties) ] ;
+  URL on $(targets) = http://core.ring.gr.jp/pub/GNU/binutils/binutils-$(version).tar.bz2 ;
+  TARBALL_GZ on $(targets) = $(THIS_DIR)/binutils-$(version).tar.gz ;
+  TARBALL_BZ2 on $(targets) = $(THIS_DIR)/binutils-$(version).tar.bz2 ;
   STDOUT_ on $(targets) = [ feature.get-values <intro-stdout> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
 }
-actions download-gmp
+actions download-binutils
 {
   rm -f "$(<)" || exit $?
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
     ( cd "$(TARBALL_BZ2:D)" && wget --quiet --timestamping -- '$(URL)' ) \
-      || { echo "ERROR: failed to download the GMP tarball." 2>>"$(STDOUT_)" 1>&2; exit 1; }
+      || { echo "ERROR: failed to download the Binutils tarball." 2>>"$(STDOUT_)" 1>&2; exit 1; }
     [ ! -f "$(TARBALL_BZ2)" ] && exit 1
   fi
   [ -e "$(<)" ] && exit 1
@@ -76,13 +72,13 @@ actions download-gmp
 }
 
 
-make gmp.expand
-  : gmp.download
-  : @expand-gmp
+make binutils.expand
+  : binutils.download
+  : @expand-binutils
   ;
-explicit gmp.expand ;
+explicit binutils.expand ;
 
-rule expand-gmp ( targets * : sources * : properties * )
+rule expand-binutils ( targets * : sources * : properties * )
 {
   if ! $(sources[1]) {
     errors.error "ERROR: wrong number of sources." ;
@@ -90,14 +86,14 @@ rule expand-gmp ( targets * : sources * : properties * )
   if $(sources[2]) {
     errors.error "ERROR: wrong number of sources." ;
   }
-  local version = [ feature.get-values <gmp-version> : $(properties) ] ;
-  TARBALL_GZ on $(targets) = $(THIS_DIR)/gmp-$(version).tar.gz ;
-  TARBALL_BZ2 on $(targets) = $(THIS_DIR)/gmp-$(version).tar.bz2 ;
-  DEST_DIR on $(targets) = $(THIS_DIR)/gmp-$(version) ;
+  local version = [ feature.get-values <binutils-version> : $(properties) ] ;
+  TARBALL_GZ on $(targets) = $(THIS_DIR)/binutils-$(version).tar.gz ;
+  TARBALL_BZ2 on $(targets) =  $(THIS_DIR)/binutils-$(version).tar.bz2 ;
+  DEST_DIR on $(targets) = $(THIS_DIR)/binutils-$(version) ;
   STDOUT_ on $(targets) = [ feature.get-values <intro-stdout> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
 }
-actions expand-gmp
+actions expand-binutils
 {
   rm -f "$(<)" || exit $?
   [ ! -f "$(>[1])" ] && exit 1
@@ -105,10 +101,10 @@ actions expand-gmp
     rm -rf "$(DEST_DIR)" || exit $?
     if [ -f "$(TARBALL_GZ)" ]; then
       tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the GMP tarball." 2>>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the tarball for the Binutils build." 2>>"$(STDERR_)" 1>&2; exit 1; }
     elif [ -f "$(TARBALL_BZ2)" ]; then
       tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the GMP tarball." 2>>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the tarball for the Binutils build." 2>>"$(STDERR_)" 1>&2; exit 1; }
     else
       exit 1
     fi
@@ -119,21 +115,21 @@ actions expand-gmp
 }
 
 
-make gmp.configure
-  : gcc-dep-conditional
-    gmp.expand/<intro-host>unspecified/<intro-target>unspecified/<intro-link>unspecified/<gcc-version-cross-default>unspecified
-  : @configure-gmp
+make binutils.configure
+  : gcc-dep
+    binutils.expand/<intro-host>unspecified/<intro-target>unspecified/<intro-abi>unspecified/<intro-link>unspecified/<gcc-version-cross-default>unspecified
+  : @configure-binutils
   ;
-explicit gmp.configure ;
+explicit binutils.configure ;
 
-rule configure-gmp ( targets * : sources * : properties * )
+rule configure-binutils ( targets * : sources * : properties * )
 {
   OPTIONS on $(targets) = ;
 
-  local version = [ feature.get-values <gmp-version> : $(properties) ] ;
+  local version = [ feature.get-values <binutils-version> : $(properties) ] ;
 
   # Set the path to the 'configure' file.
-  local configure = $(THIS_DIR)/gmp-$(version)/configure ;
+  local configure = $(THIS_DIR)/binutils-$(version)/configure ;
   CONFIGURE on $(targets) = $(configure) ;
 
   # Set the 'build' option for the 'configure' script.
@@ -144,55 +140,58 @@ rule configure-gmp ( targets * : sources * : properties * )
   local host = [ feature.get-values <intro-host> : $(properties) ] ;
   OPTIONS on $(targets) += --host=$(host) ;
 
-  # Set the 'ABI' option for the 'configure' script.
+  local target = [ feature.get-values <intro-target> : $(properties) ] ;
+  OPTIONS on $(targets) += --target=$(target) ;
+
+  # Set the 'CC' option for the 'configure' script.
   local abi = [ feature.get-values <intro-abi> : $(properties) ] ;
-  ABI on $(targets) = ;
-  if $(abi) != unspecified {
-    ABI on $(targets) = ABI=$(abi) ;
+  local cc = [ SHELL "\"$(THIS_DIR)/../cc.sh\" $(build) $(host) $(abi) || /bin/echo -n 'error'" ] ;
+  if $(cc) = error {
+    errors.error "ERROR: cannot determine the 'CC' option for the Binutils build." ;
+  }
+  CC on $(targets) = ;
+  if $(cc) {
+    CC on $(targets) = "CC='$(cc)'" ;
   }
 
   # Set the 'prefix' option for the 'configure' script.
   local prefix = [ feature.get-values <intro-prefix> : $(properties) ] ;
+  if $(host) != $(build) {
+    prefix = $(prefix)/$(host) ;
+  }
   OPTIONS on $(targets) += --prefix=\"$(prefix)\" ;
 
-  # Set the link variants for the 'configure' script.
-  local link = [ feature.get-values <intro-link> : $(properties) ] ;
-  if $(link) = static || $(link) = both {
-    OPTIONS on $(targets) += --enable-static ;
+  if [ regex.match "(-w64-mingw32)$" : $(target) : 1 ] {
+    OPTIONS on $(targets) += --enable-targets=x86_64-w64-mingw32,i686-w64-mingw32 ;
   }
-  else {
-    OPTIONS on $(targets) += --disable-static ;
-  }
-  if $(link) = shared || $(link) = both {
-    OPTIONS on $(targets) += --enable-shared ;
-  }
-  else {
-    OPTIONS on $(targets) += --disable-shared ;
+
+  if $(target) != $(host) {
+    OPTIONS on $(targets) += --with-sysroot=\"$(prefix)\" ;
   }
 
   STDOUT_ on $(targets) = [ feature.get-values <intro-stdout> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
 }
-actions configure-gmp
+actions configure-binutils
 {
   rm -f "$(<)" || exit $?
   ( mkdir -p "$(<:D)/build" && { cd "$(<:D)/build" && rm -rf *; } ) || exit $?
   [ ! -f "$(CONFIGURE)" ] && exit 1
-  ( cd "$(<:D)/build" && $(ABI) "$(CONFIGURE)" $(OPTIONS) 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'configure' for the GMP build." 2>>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(CC) "$(CONFIGURE)" $(OPTIONS) 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'configure' for the Binutils build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   [ ! -f "$(<:D)/build/Makefile" ] && exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
 
 
-make gmp.make
-  : gmp.configure
-  : @make-gmp
+make binutils.make
+  : binutils.configure
+  : @make-binutils
   ;
-explicit gmp.make ;
+explicit binutils.make ;
 
-rule make-gmp ( targets * : sources * : properties * )
+rule make-binutils ( targets * : sources * : properties * )
 {
   if ! $(sources[1]) {
     errors.error "ERROR: wrong number of sources." ;
@@ -204,31 +203,31 @@ rule make-gmp ( targets * : sources * : properties * )
   STDOUT_ on $(targets) = [ feature.get-values <intro-stdout> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
 }
-actions make-gmp
+actions make-binutils
 {
   rm -f "$(<)" || exit $?
   [ ! -f "$(>[1])" ] && exit 1
   [ ! -f "$(>[1]:D)/build/Makefile" ] && exit 1
   ( cd "$(<:D)/build" && make 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make' for the GMP build." 2>>"$(STDERR_)" 1>&2; exit 1; }
+    || { echo "ERROR: failed to 'make' for the Binutils build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   if [ $(CHECK) = yes ]; then
     ( cd "$(<:D)/build" && make check 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
-      || { echo "ERROR: failed to 'make check' for the GMP build." 2>>"$(STDERR_)" 1>&2; exit 1; }
+      || { echo "ERROR: failed to 'make check' for the Binutils build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   fi
   ( cd "$(<:D)/build" && make install 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make install' for the GMP build." 2>>"$(STDERR_)" 1>&2; exit 1; }
+    || { echo "ERROR: failed to 'make install' for the Bintuils build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
 
 
-make gmp.test
-  : gmp.make
-  : @test-gmp
+make binutils.test
+  : binutils.make
+  : @test-binutils
   ;
-explicit gmp.test ;
+explicit binutils.test ;
 
-rule test-gmp ( targets * : sources * : properties * )
+rule test-binutils ( targets * : sources * : properties * )
 {
   if ! $(sources[1]) {
     errors.error "ERROR: wrong number of sources." ;
@@ -237,7 +236,7 @@ rule test-gmp ( targets * : sources * : properties * )
     errors.error "ERROR: wrong number of sources." ;
   }
   COMMAND on $(targets) = $(THIS_DIR)/test.sh ;
-  VERSION on $(targets) = [ feature.get-values <gmp-version> : $(properties) ] ;
+  VERSION on $(targets) = [ feature.get-values <binutils-version> : $(properties) ] ;
   BUILD on $(targets) = [ feature.get-values <intro-build> : $(properties) ] ;
   HOST on $(targets) = [ feature.get-values <intro-host> : $(properties) ] ;
   ABI on $(targets) = [ feature.get-values <intro-abi> : $(properties) ] ;
@@ -246,17 +245,17 @@ rule test-gmp ( targets * : sources * : properties * )
   CHECK on $(targets) = [ feature.get-values <intro-check> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
 }
-actions test-gmp
+actions test-binutils
 {
   rm -f "$(<)" || exit $?
   [ ! -f "$(>[1])" ] && exit 1
-  result=`"$(COMMAND)" $(VERSION) $(BUILD) $(HOST) $(ABI) "$(PREFIX)" $(CHECK)`
-  if [ $? -ne 0 ]; then
-    /bin/echo 'ERROR: post-installation test failed for the GMP build.' 2>>"$(STDERR_)" 1>&2
-    exit 1
-  fi
-  [ $(LINK) = static -a $result = shared ] && exit 1
-  [ $(LINK) = shared -a $result = static ] && exit 1
+  # result=`"$(COMMAND)" $(VERSION) $(BUILD) $(HOST) $(ABI) "$(PREFIX)" $(CHECK)`
+  # if [ $? -ne 0 ]; then
+  #   /bin/echo 'ERROR: post-installation test failed for the Binutils build.' 2>>"$(STDERR_)" 1>&2
+  #   exit 1
+  # fi
+  # [ $(LINK) = static -a $result = shared ] && exit 1
+  # [ $(LINK) = shared -a $result = static ] && exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -264,13 +263,13 @@ actions test-gmp
 
 rule install-req ( properties * )
 {
-  local result = <source>gmp.test ;
+  local result = <source>binutils.test ;
 
   local tmp = ;
 
-  local version = [ feature.get-values <gmp-version> : $(properties) ] ;
+  local version = [ feature.get-values <binutils-version> : $(properties) ] ;
   if $(version) = unspecified {
-    errors.error "ERROR: the property '<gmp-version>' is not specified for the GMP build.." ;
+    errors.error "ERROR: the property '<binutils-version>' is not specified for the Binutils build." ;
   }
 
   local build = [ feature.get-values <intro-build> : $(properties) ] ;
@@ -283,7 +282,7 @@ rule install-req ( properties * )
   }
   tmp = [ SHELL "\"$(THIS_DIR)/config.sub\" $(build) | tr --delete '\n'" ] ;
   if $(tmp) != $(build) {
-    errors.error "ERROR: the property '<intro-build>$(build)' is not canonical." ;
+    errors.error "ERROR: the given property '<intro-build>$(build)' is not canonical." ;
   }
   result = $(result)/<intro-build>$(build) ;
 
@@ -298,13 +297,18 @@ rule install-req ( properties * )
   result = $(result)/<intro-host>$(host) ;
 
   local target = [ feature.get-values <intro-target> : $(properties) ] ;
-  if $(target) != unspecified {
-    errors.error "ERROR: the property '<intro-target>$(target)' is specified for GMP build." ;
+  if $(target) = unspecified {
+    target = $(host) ;
   }
+  tmp = [ SHELL "\"$(THIS_DIR)/config.sub\" $(target) | tr --delete '\n'" ] ;
+  if $(tmp) != $(target) {
+    errors.error "ERROR: the property '<intro-target>$(target)' is not canonical." ;
+  }
+  result = $(result)/<intro-target>$(target) ;
 
   local link = [ feature.get-values <intro-link> : $(properties) ] ;
-  if $(link) = unspecified {
-    errors.error "ERROR: '<intro-link>' is not specified for the GMP build." ;
+  if $(link) != unspecified {
+    errors.error "ERROR: the property '<intro-link>$(link)' is not valid for the Binutils build." ;
   }
 
   local check = [ feature.get-values <intro-check> : $(properties) ] ;
@@ -324,7 +328,7 @@ rule install-req ( properties * )
 }
 
 alias install
-  : # The source 'install-normalized' is introduced by the following indirect requirements.
+  : # 'binutils.test' is added by the indirect conditional requirements.
   : <conditional>@install-req
   ;
 explicit install ;
diff --git a/gcc/jamfile b/gcc/jamfile
--- a/gcc/jamfile
+++ b/gcc/jamfile
@@ -12,7 +12,7 @@ path-constant THIS_DIR : . ;
 rule mpc-dep-req ( properties * )
 {
   local result = <source>../mpc//install ;
-  result = $(result)/<intro-build>unspecified ;
+  results = $(results)/<intro-build>unspecified ;
   local build = [ feature.get-values <intro-build> : $(properties) ] ;
   local host = [ feature.get-values <intro-host> : $(properties) ] ;
   if $(host) = $(build) {
@@ -55,7 +55,7 @@ rule binutils-dep-req ( properties * )
   local target = [ feature.get-values <intro-target> : $(properties) ] ;
   if $(target) != $(build) {
     result = <source>../binutils//install ;
-    result = $(result)/<intro-build>unspecified ;
+    results = $(results)/<intro-build>unspecified ;
     # `<intro-host>' is automatically propagated.
     # `<intro-target>' is automatically propagated.
     # `<intro-abi>' is automatically propagated.
@@ -68,19 +68,53 @@ rule binutils-dep-req ( properties * )
     result = $(result)/<mpfr-version>unspecified ;
     result = $(result)/<mpc-version>unspecified ;
   }
+  #errors.error $(result) ;
   return $(result) ;
 }
 
-alias binutils-dep-conditional
+alias binutils-dep
   : # The source `../binutils//install' is specified by the indirect conditional requirements.
   : <conditional>@binutils-dep-req
   ;
-explicit binutils-dep-conditional ;
+explicit binutils-dep ;
+
+
+rule mingw-w64-headers-dep-req ( properties * )
+{
+  local result = ;
+  local host = [ feature.get-values <intro-host> : $(properties) ] ;
+  local target = [ feature.get-values <intro-target> : $(properties) ] ;
+  if $(target) != $(host) {
+    if [ regex.match "(-w64-mingw32)$" : $(target) : 1 ] {
+      result = <source>../mingw-w64-headers//install ;
+      result = $(result)/<intro-host>$(target) ;
+      result = $(result)/<intro-target>unspecified ;
+      result = $(result)/<intro-abi>unspecified ;
+      # `<intro-prefix>' is automatically propagated.
+      # `<intro-link>' is automatically propagated.
+      # `<intro-check>' is automatically propagated.
+      # `<intro-stdout>' is automatically propagated.
+      # `<intro-stderr>' is automatically propagated.
+      result = $(result)/<gmp-version>unspecified ;
+      result = $(result)/<mpfr-version>unspecified ;
+      result = $(result)/<mpc-version>unspecified ;
+      result = $(result)/<binutils-version>unspecified ;
+      #errors.error $(result) ;
+    }
+  }
+  return $(result) ;
+}
+
+alias mingw-w64-headers-dep
+  : # The source `../mingw-w64-headers//install' might be introduced by the requirements.
+  : <conditional>@mingw-w64-headers-dep-req
+  ;
+explicit mingw-w64-headers-dep ;
 
 
 rule deps-req ( properties * )
 {
-  local results = mpc-dep binutils-dep-conditional ;
+  local results = mpc-dep binutils-dep mingw-w64-headers-dep ;
   results = <source>$(results) ;
   local gmp-version = [ feature.get-values <gmp-version> : $(properties) ] ;
   results = $(results)/<gmp-version-hidden>$(gmp-version) ;
@@ -95,7 +129,7 @@ rule deps-req ( properties * )
 }
 
 alias deps
-  : # `mpc-dep' and `binutils-dep-conditional' are added by the requirements.
+  : # `mpc-dep', `binutils-dep' and `mingw-w64-headers-dep' are added by the requirements.
   : <conditional>@deps-req
   ;
 explicit deps ;
@@ -121,7 +155,7 @@ actions download-gcc
   rm -f "$(<)" || exit $?
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
     ( cd "$(TARBALL_BZ2:D)" && wget --quiet --timestamping -- '$(URL)' ) \
-      || { echo "ERROR: failed to download the GCC tarball." 2>"$(STDOUT_)" 1>&2; exit 1; }
+      || { echo "ERROR: failed to download the GCC tarball." 2>>"$(STDOUT_)" 1>&2; exit 1; }
     [ ! -f "$(TARBALL_BZ2)" ] && exit 1
   fi
   [ -e "$(<)" ] && exit 1
@@ -158,10 +192,10 @@ actions expand-gcc
     rm -rf "$(DEST_DIR)" || exit $?
     if [ -f "$(TARBALL_GZ)" ]; then
       tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the tarball for the GCC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the tarball for the GCC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
     elif [ -f "$(TARBALL_BZ2)" ]; then
       tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the tarball for the GCC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the tarball for the GCC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
     else
       exit 1
     fi
@@ -250,14 +284,11 @@ rule configure-gcc ( targets * : sources * : properties * )
 
   # Set the 'prefix' option for the 'configure' script.
   local prefix = [ feature.get-values <intro-prefix> : $(properties) ] ;
+  if $(host) != $(build) {
+    prefix = $(prefix)/$(host) ;
+  }
   PREFIX on $(targets) = $(prefix) ;
   OPTIONS on $(targets) += --prefix=\"$(prefix)\" ;
-
-  if $(host) != $(build) {
-    if ! [ regex.match "^(/.+/$(host))$" : $(prefix) : 1 ] {
-      errors.error "ERROR: the property '<prefix>$(prefix)' is not valid." ;
-    }
-  }
 
   OPTIONS on $(targets) += --program-suffix=-$(version) ;
 
@@ -278,9 +309,10 @@ rule configure-gcc ( targets * : sources * : properties * )
     OPTIONS on $(targets) += --enable-libgomp ;
   }
 
-  if $(mingw32_target) = 1 {
-    OPTIONS on $(targets) += --with-dwarf2 ;
-  }
+  # dwarf2 is not supported on 64-bit MinGW-w64.
+  # if $(mingw32_target) = 1 {
+  #   OPTIONS on $(targets) += --with-dwarf2 ;
+  # }
 
   OPTIONS on $(targets) += --enable-targets=all ;
 
@@ -297,9 +329,14 @@ rule configure-gcc ( targets * : sources * : properties * )
   # Set the 'with-mpc' options for the 'configure' script.
   OPTIONS on $(targets) += --with-mpc=\"$(prefix)\" ;
 
-  if $(mingw32_target) = 1 {
-    OPTIONS on $(targets) += --disable-sjlj-exceptions ;
+  # Set the '--with-sysroot' option for the 'configure' script.
+  if $(mingw32_cross_target) = 1 {
+    OPTIONS on $(targets) += --with-sysroot=\"$(prefix)\" ;
   }
+
+  # if $(mingw32_target) = 1 {
+  #   OPTIONS on $(targets) += --disable-sjlj-exceptions ;
+  # }
 
   RUN_VAR on $(targets) = [ run-var $(properties) ] ;
 
@@ -313,8 +350,8 @@ actions configure-gcc
   [ ! -f "$(CONFIGURE)" ] && exit 1
   [ $(MINGW32_CROSS_TARGET) -ne 0 ] \
     && { rm -f "$(PREFIX)/mingw"; ln -s "$(PREFIX)/$(TARGET)" "$(PREFIX)/mingw" || exit $?; }
-  ( cd "$(<:D)/build" && $(CC) $(RUN_VAR) "$(CONFIGURE)" $(OPTIONS) 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'configure' for the GCC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(CC) $(RUN_VAR) "$(CONFIGURE)" $(OPTIONS) 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'configure' for the GCC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   [ $(MINGW32_CROSS_TARGET) -ne 0 ] && { rm "$(PREFIX)/mingw" || exit $?; }
   [ ! -f "$(<:D)/build/Makefile" ] && exit 1
   [ -e "$(<)" ] && exit 1
@@ -322,13 +359,13 @@ actions configure-gcc
 }
 
 
-make gcc-mingw32-cross-target-stage1.make
+make gcc-mingw32-target-cross-stage1.make
   : gcc.configure
-  : @make-gcc-mingw32-cross-target-stage1
+  : @make-gcc-mingw32-target-cross-stage1
   ;
-explicit gcc-mingw32-cross-target-stage1.make ;
+explicit gcc-mingw32-target-cross-stage1.make ;
 
-rule make-gcc-mingw32-cross-target-stage1 ( targets * : sources * : properties * )
+rule make-gcc-mingw32-target-cross-stage1 ( targets * : sources * : properties * )
 {
   if ! $(sources[1]) {
     errors.error "ERROR: wrong number of sources." ;
@@ -337,31 +374,25 @@ rule make-gcc-mingw32-cross-target-stage1 ( targets * : sources * : properties *
     errors.error "ERROR: wrong number of sources." ;
   }
   local prefix = [ feature.get-values <intro-prefix> : $(properties) ] ;
-  local build = [ feature.get-values <intro-build> : $(properties) ] ;
-  if [ regex.match "(-mingw32)$" : $(build) : 1 ] {
-    RUN_VAR on $(targets) = "PATH=$(prefix)/bin:$PATH" ;
-  }
-  else if [ regex.match "(-cygwin)$" : $(build) : 1 ] {
-    RUN_VAR on $(targets) = "PATH=$(prefix)/bin:$PATH" ;
-  }
-  else {
-    RUN_VAR on $(targets) = "LD_LIBRARY_PATH=$(prefix)/lib:$LD_LIBRARY_PATH" ;
-  }
+  local target = [ feature.get-values <intro-target> : $(properties) ] ;
+  PREFIX on $(targets) = $(prefix) ;
+  TARGET on $(targets) = $(target) ;
   STDOUT_ on $(targets) = [ feature.get-values <intro-stdout> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
+  RUN_VAR on $(targets) = [ run-var $(properties) ] ;
 }
-actions make-gcc-mingw32-cross-target-stage1
+actions make-gcc-mingw32-target-cross-stage1
 {
   rm -f "$(<)" || exit $?
   [ ! -f "$(>[1])" ] && exit 1
   [ ! -f "$(>[1]:D)/build/Makefile" ] && exit 1
-  [ $(MINGW32_CROSS_TARGET) -ne 0 ] \
-    && { rm -f "$(PREFIX)/mingw"; ln -s "$(PREFIX)/$(TARGET)" "$(PREFIX)/mingw" || exit $?; }
-  ( cd "$(<:D)/build" && $(RUN_VAR) make all-gcc 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make all-gcc' for the GCC build." 2>"$(STDERR_)" 1>&2; exit 1; }
-  ( cd "$(<:D)/build" && $(RUN_VAR) make install-gcc 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make install-gcc' for the GCC build." 2>"$(STDERR_)" 1>&2; exit 1; }
-  [ $(MINGW32_CROSS_TARGET) -ne 0 ] && { rm "$(PREFIX)/mingw" || exit $?; }
+  rm -f "$(PREFIX)/mingw" || exit $?
+  ln -s "$(PREFIX)/$(TARGET)" "$(PREFIX)/mingw" || exit $?
+  ( cd "$(<:D)/build" && $(RUN_VAR) make all-gcc 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'make all-gcc' for the GCC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(RUN_VAR) make install-gcc 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'make install-gcc' for the GCC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
+  rm "$(PREFIX)/mingw" || exit $?
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -396,7 +427,7 @@ explicit gcc.make ;
 rule make-gcc ( targets * : sources * : properties * )
 {
   local host = [ feature.get-values <intro-host> : $(properties) ] ;
-  local target = [ feature.get-values <intro-build> : $(properties) ] ;
+  local target = [ feature.get-values <intro-target> : $(properties) ] ;
   TARGET on $(targets) = $(target) ;
   local mingw32-cross-target = 0 ;
   if $(target) != $(host) {
@@ -418,10 +449,10 @@ actions make-gcc
   [ ! -f "$(<[1]:D)/build/Makefile" ] && exit 1
   [ $(MINGW32_CROSS_TARGET) -ne 0 ] \
     && { rm -f "$(PREFIX)/mingw"; ln -s "$(PREFIX)/$(TARGET)" "$(PREFIX)/mingw" || exit $?; }
-  ( cd "$(<:D)/build" && $(RUN_VAR) make 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make' for the GCC build." 2>"$(STDERR_)" 1>&2; exit 1; }
-  ( cd "$(<:D)/build" && $(RUN_VAR) make install 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make install' for the GCC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(RUN_VAR) make 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'make' for the GCC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(RUN_VAR) make install 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'make install' for the GCC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   [ $(MINGW32_CROSS_TARGET) -ne 0 ] && { rm "$(PREFIX)/mingw" || exit $?; }
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -458,7 +489,7 @@ actions test-gcc
   [ ! -f "$(>[1])" ] && exit 1
   # x=`"$(COMMAND)" $(VERSION) $(BUILD) $(HOST) $(ABI) "$(PREFIX)" $(LINK) $(CHECK)`
   # if [ $? -ne 0 ]; then
-  #   /bin/echo 'ERROR: post-installation test failed for the GCC build.' 2>"$(STDERR_)" 1>&2
+  #   /bin/echo 'ERROR: post-installation test failed for the GCC build.' 2>>"$(STDERR_)" 1>&2
   #   exit 1
   # fi
   # [ "$x" != 'yes' ] && exit 1
@@ -517,24 +548,16 @@ rule install-req ( properties * )
   }
 
   local version-cross-default = [ feature.get-values <gcc-version-cross-default> : $(properties) ] ;
-  if $(host) = $(build) && $(target) = $(host) {
-    if $(version-cross-default) != unspecified {
-      errors.error "ERROR: the property '<version-cross-default>' is specified for the GCC self-build." ;
+  if $(host) != $(build) {
+    if $(version-cross-default) = unspecified {
+      errors.error "ERROR: the property '<gcc-version-cross-default>' is not specified for the GCC cross-build." ;
     }
   }
   else {
-    if $(version-cross-default) = unspecified {
-      errors.error "ERROR: the property '<version-cross-default>' is not specified for the GCC cross-build." ;
+    if $(version-cross-default) != unspecified {
+      errors.error "ERROR: the property '<gcc-version-cross-default>$(version-cross-default)' is not valid for the GCC self-build." ;
     }
   }
-
-  local prefix = [ feature.get-values <intro-prefix> : $(properties) ] ;
-  if $(host) != $(build) {
-    if ! [ regex.match "^(/.+/$(host))$" : $(prefix) : 1 ] {
-      errors.error "ERROR: the property '<intro-prefix>$(prefix)' is not valid for the host-cross GCC build." ;
-    }
-  }
-  result = $(result)/<intro-prefix>$(prefix) ;
 
   local link = [ feature.get-values <intro-link> : $(properties) ] ;
   if $(link) != unspecified {
diff --git a/mpc/jamfile b/mpc/jamfile
--- a/mpc/jamfile
+++ b/mpc/jamfile
@@ -63,7 +63,7 @@ actions download-mpc
   rm -f "$(<)" || exit $?
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
     ( cd "$(TARBALL_GZ:D)" && wget --quiet --timestamping -- '$(URL)' ) \
-      || { echo "ERROR: failed to download the MPC tarball." 2>"$(STDOUT_)" 1>&2; exit 1; }
+      || { echo "ERROR: failed to download the MPC tarball." 2>>"$(STDOUT_)" 1>&2; exit 1; }
     [ ! -f "$(TARBALL_GZ)" ] && exit 1
   fi
   [ -e "$(<)" ] && exit 1
@@ -100,10 +100,10 @@ actions expand-mpc
     rm -rf "$(DEST_DIR)" || exit $?
     if [ -f "$(TARBALL_GZ)" ]; then
       tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the tarball for the MPC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the tarball for the MPC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
     elif [ -f "$(TARBALL_BZ2)" ]; then
       tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the tarball for the MPC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the tarball for the MPC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
     else
       exit 1
     fi
@@ -193,18 +193,17 @@ rule configure-mpc ( targets * : sources * : properties * )
   # Set the 'with-mpfr' option for the 'configure' script.
   OPTIONS on $(targets) += --with-mpfr=\"$(prefix)\" ;
 
-  RUN_VAR on $(targets) = [ run-var $(properties) ] ;
-
   STDOUT_ on $(targets) = [ feature.get-values <intro-stdout> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
+  RUN_VAR on $(targets) = [ run-var $(properties) ] ;
 }
 actions configure-mpc
 {
   rm -f "$(<)" || exit $?
   ( mkdir -p "$(<:D)/build" && { cd "$(<:D)/build" && rm -rf *; } ) || exit $?
   [ ! -f "$(CONFIGURE)" ] && exit 1
-  ( cd "$(<:D)/build" && $(CC) $(RUN_VAR) "$(CONFIGURE)" $(OPTIONS) 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'configure' for the MPC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(CC) $(RUN_VAR) "$(CONFIGURE)" $(OPTIONS) 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'configure' for the MPC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   [ ! -f "$(<:D)/build/Makefile" ] && exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -227,24 +226,24 @@ rule make-mpc ( targets * : sources * : properties * )
   }
   local prefix = [ feature.get-values <intro-prefix> : $(properties) ] ;
   local build = [ feature.get-values <intro-build> : $(properties) ] ;
-  RUN_VAR on $(targets) = [ run-var $(properties) ] ;
   CHECK on $(targets) = [ feature.get-values <intro-check> : $(properties) ] ;
   STDOUT_ on $(targets) = [ feature.get-values <intro-stdout> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
+  RUN_VAR on $(targets) = [ run-var $(properties) ] ;
 }
 actions make-mpc
 {
   rm -f "$(<)" || exit $?
   [ ! -f "$(>[1])" ] && exit 1
   [ ! -f "$(>[1]:D)/build/Makefile" ] && exit 1
-  ( cd "$(<:D)/build" && make 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make' for the MPC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(RUN_VAR) make 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'make' for the MPC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   if [ $(CHECK) = yes ]; then
-    ( cd "$(<:D)/build" && $(RUN_VAR) make check 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-      || { echo "ERROR: failed to 'make check' for the MPC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+    ( cd "$(<:D)/build" && $(RUN_VAR) make check 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+      || { echo "ERROR: failed to 'make check' for the MPC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   fi
-  ( cd "$(<:D)/build" && make install 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make install' for the MPC build." 2>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(RUN_VAR) make install 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'make install' for the MPC build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -280,7 +279,7 @@ actions test-mpc
   [ ! -f "$(>[1])" ] && exit 1
   result=`"$(COMMAND)" $(VERSION) $(BUILD) $(HOST) $(ABI) "$(PREFIX)" $(CHECK)`
   if [ $? -ne 0 ]; then
-    /bin/echo 'ERROR: post-installation test failed for the MPC build.' 2>"$(STDERR_)" 1>&2
+    /bin/echo 'ERROR: post-installation test failed for the MPC build.' 2>>"$(STDERR_)" 1>&2
     exit 1
   fi
   [ $(LINK) = static -a $result = shared ] && exit 1
diff --git a/mpfr/jamfile b/mpfr/jamfile
--- a/mpfr/jamfile
+++ b/mpfr/jamfile
@@ -4,6 +4,7 @@ import alias ;
 import errors ;
 import feature ;
 import make ;
+import regex ;
 
 path-constant THIS_DIR : . ;
 
@@ -63,7 +64,7 @@ actions download-mpfr
   rm -f "$(<)" || exit $?
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
     ( cd "$(TARBALL_BZ2:D)" && wget --quiet --timestamping -- '$(URL)' ) \
-      || { echo "ERROR: failed to download the MPFR tarball." 2>"$(STDOUT_)" 1>&2; exit 1; }
+      || { echo "ERROR: failed to download the MPFR tarball." 2>>"$(STDOUT_)" 1>&2; exit 1; }
     [ ! -f "$(TARBALL_BZ2)" ] && exit 1
   fi
   [ -e "$(<)" ] && exit 1
@@ -100,10 +101,10 @@ actions expand-mpfr
     rm -rf "$(DEST_DIR)" || exit $?
     if [ -f "$(TARBALL_GZ)" ]; then
       tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the tarball for the MPFR build." 2>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the tarball for the MPFR build." 2>>"$(STDERR_)" 1>&2; exit 1; }
     elif [ -f "$(TARBALL_BZ2)" ]; then
       tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the tarball for the MPFR build." 2>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the tarball for the MPFR build." 2>>"$(STDERR_)" 1>&2; exit 1; }
     else
       exit 1
     fi
@@ -111,6 +112,24 @@ actions expand-mpfr
   fi
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
+}
+
+
+rule run-var ( properties * )
+{
+  local result = ;
+  local build = [ feature.get-values <intro-build> : $(properties) ] ;
+  local prefix = [ feature.get-values <intro-prefix> : $(properties) ] ;
+  if [ regex.match "(-mingw32)$" : $(build) : 1 ] {
+    result = PATH=\"$(prefix)/bin\":$PATH ;
+  }
+  else if [ regex.match "(-cygwin)$" : $(build) : 1 ] {
+    result = PATH=\"$(prefix)/bin\":$PATH ;
+  }
+  else {
+    result = LD_LIBRARY_PATH=\"$(prefix)/lib\":$LD_LIBRARY_PATH ;
+  }
+  return $(result) ;
 }
 
 
@@ -174,14 +193,15 @@ rule configure-mpfr ( targets * : sources * : properties * )
 
   STDOUT_ on $(targets) = [ feature.get-values <intro-stdout> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
+  RUN_VAR on $(targets) = [ run-var $(properties) ] ;
 }
 actions configure-mpfr
 {
   rm -f "$(<)" || exit $?
   ( mkdir -p "$(<:D)/build" && { cd "$(<:D)/build" && rm -rf *; } ) || exit $?
   [ ! -f "$(CONFIGURE)" ] && exit 1
-  ( cd "$(<:D)/build" && $(CC) "$(CONFIGURE)" $(OPTIONS) 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'configure' for the MPFR build." 2>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(CC) $(RUN_VAR) "$(CONFIGURE)" $(OPTIONS) 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'configure' for the MPFR build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   [ ! -f "$(<:D)/build/Makefile" ] && exit 1
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
@@ -205,20 +225,21 @@ rule make-mpfr ( targets * : sources * : properties * )
   CHECK on $(targets) = [ feature.get-values <intro-check> : $(properties) ] ;
   STDOUT_ on $(targets) = [ feature.get-values <intro-stdout> : $(properties) ] ;
   STDERR_ on $(targets) = [ feature.get-values <intro-stderr> : $(properties) ] ;
+  RUN_VAR on $(targets) = [ run-var $(properties) ] ;
 }
 actions make-mpfr
 {
   rm -f "$(<)" || exit $?
   [ ! -f "$(>[1])" ] && exit 1
   [ ! -f "$(>[1]:D)/build/Makefile" ] && exit 1
-  ( cd "$(<:D)/build" && make 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make' for the MPFR build." 2>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(RUN_VAR) make 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'make' for the MPFR build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   if [ $(CHECK) = yes ]; then
-    ( cd "$(<:D)/build" && make check 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-      || { echo "ERROR: failed to 'make check' for the MPFR build." 2>"$(STDERR_)" 1>&2; exit 1; }
+    ( cd "$(<:D)/build" && $(RUN_VAR) make check 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+      || { echo "ERROR: failed to 'make check' for the MPFR build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   fi
-  ( cd "$(<:D)/build" && make install 1>"$(STDOUT_)" 2>"$(STDERR_)" ) \
-    || { echo "ERROR: failed to 'make install' for the MPFR build." 2>"$(STDERR_)" 1>&2; exit 1; }
+  ( cd "$(<:D)/build" && $(RUN_VAR) make install 1>>"$(STDOUT_)" 2>>"$(STDERR_)" ) \
+    || { echo "ERROR: failed to 'make install' for the MPFR build." 2>>"$(STDERR_)" 1>&2; exit 1; }
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -254,7 +275,7 @@ actions test-mpfr
   [ ! -f "$(>[1])" ] && exit 1
   result=`"$(COMMAND)" $(VERSION) $(BUILD) $(HOST) $(ABI) "$(PREFIX)" $(CHECK)`
   if [ $? -ne 0 ]; then
-    /bin/echo 'ERROR: post-installation test failed for the MPFR build.' 2>"$(STDERR_)" 1>&2
+    /bin/echo 'ERROR: post-installation test failed for the MPFR build.' 2>>"$(STDERR_)" 1>&2
     exit 1
   fi
   [ $(LINK) = static -a $result = shared ] && exit 1
