No change.

diff --git a/mpfr/jamfile b/mpfr/jamfile
--- a/mpfr/jamfile
+++ b/mpfr/jamfile
@@ -101,10 +101,10 @@ actions expand-mpfr
     rm -rf "$(DEST_DIR)" || exit $?
     if [ -f "$(TARBALL_GZ)" ]; then
       tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" \
-        || { echo "ERROR: failed to expand the tarball for the MPFR build." 2>>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the MPFR tarball." 2>>"$(STDERR_)" 1>&2; exit 1; }
     elif [ -f "$(TARBALL_BZ2)" ]; then
       tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" \
-        || { echo "ERROR: failed to expand the tarball for the MPFR build." 2>>"$(STDERR_)" 1>&2; exit 1; }
+        || { echo "ERROR: failed to expand the MPFR tarball." 2>>"$(STDERR_)" 1>&2; exit 1; }
     else
       exit 1
     fi
@@ -305,41 +305,34 @@ rule install-req ( properties * )
     errors.error "ERROR: the property '<intro-build>$(build)' is not valid." ;
   }
   tmp = [ SHELL "\"$(THIS_DIR)/config.sub\" $(build) | tr --delete '\n'" ] ;
-  if $(tmp) != $(build)
-  {
-    errors.error "ERROR: the given property '<intro-build>$(build)' is not canonical." ;
+  if $(tmp) != $(build) {
+    errors.error "ERROR: the property '<intro-build>$(build)' is not canonical." ;
   }
   result = $(result)/<intro-build>$(build) ;
 
   local host = [ feature.get-values <intro-host> : $(properties) ] ;
-  if $(host) = unspecified
-  {
+  if $(host) = unspecified {
     host = $(build) ;
   }
   tmp = [ SHELL "\"$(THIS_DIR)/config.sub\" $(host) | tr --delete '\n'" ] ;
-  if $(tmp) != $(host)
-  {
+  if $(tmp) != $(host) {
     errors.error "ERROR: the property '<intro-host>$(host)' is not canonical." ;
   }
   result = $(result)/<intro-host>$(host) ;
 
   local target = [ feature.get-values <intro-target> : $(properties) ] ;
-  if $(target) != unspecified
-  {
+  if $(target) != unspecified {
     errors.error "ERROR: the property '<intro-target>$(target)' is specified for MPFR build." ;
   }
 
   local link = [ feature.get-values <intro-link> : $(properties) ] ;
-  if $(link) = unspecified
-  {
+  if $(link) = unspecified {
     errors.error "ERROR: '<intro-link>' is not specified for the MPFR build." ;
   }
 
   local check = [ feature.get-values <intro-check> : $(properties) ] ;
-  if $(check) = unspecified
-  {
-    if $(build) = $(host)
-    {
+  if $(check) = unspecified {
+    if $(build) = $(host) {
       check = yes ;
     }
     else {
@@ -354,7 +347,7 @@ rule install-req ( properties * )
 }
 
 alias install
-  : # The source 'install-normalized' is introduced by the following indirect conditional requirements.
+  : # The source 'mpfr-test' is introduced by the conditional requirements.
   : <conditional>@install-req
   ;
 explicit install ;
