Build PPL and CLooG alongside during GCC bootstrap.

diff --git a/boost/jamfile b/boost/jamfile
--- a/boost/jamfile
+++ b/boost/jamfile
@@ -29,135 +29,40 @@ rule gcc-dep-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
+  assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
-  assert-specified   <icu4c>           : $(properties) ;
+  assert-unspecified <icu4c>           : $(properties) ;
   assert-unspecified <icu4c-hidden>    : $(properties) ;
-  assert-specified   <mpi>             : $(properties) ;
+  assert-unspecified <mpi>             : $(properties) ;
   assert-unspecified <mpi-hidden>      : $(properties) ;
-  #assert-specified   <openmpi>         : $(properties) ;
+  assert-unspecified <openmpi>         : $(properties) ;
   assert-unspecified <openmpi-hidden>  : $(properties) ;
-  assert-specified   <boost>           : $(properties) ;
+  assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
-  local result = <source>../gcc//install ;
   local multilib = [ feature.get-values <multilib-hidden> : $(properties) ] ;
-  result = $(result)/<multilib>$(multilib)/<multilib-hidden>unspecified ;
-  local gmp = [ feature.get-values <gmp-hidden> : $(properties) ] ;
-  result = $(result)/<gmp>$(gmp)/<gmp-hidden>unspecified ;
-  local mpfr = [ feature.get-values <mpfr-hidden> : $(properties) ] ;
-  result = $(result)/<mpfr>$(mpfr)/<mpfr-hidden>unspecified ;
-  local mpc = [ feature.get-values <mpc-hidden> : $(properties) ] ;
-  result = $(result)/<mpc>$(mpc)/<mpc-hidden>unspecified ;
-  local ppl = [ feature.get-values <ppl-hidden> : $(properties) ] ;
-  result = $(result)/<ppl>$(ppl)/<ppl-hidden>unspecified ;
-  local cloog = [ feature.get-values <cloog-hidden> : $(properties) ] ;
-  result = $(result)/<cloog>$(cloog)/<cloog-hidden>unspecified ;
-  result = $(result)/<icu4c>unspecified ;
-  result = $(result)/<mpi>unspecified ;
-  result = $(result)/<openmpi>unspecified ;
-  result = $(result)/<boost>unspecified ;
-  return $(result) ;
+  return <source>../gcc//install/<multilib>$(multilib)/<multilib-hidden>unspecified ;
 }
 
 alias gcc-dep : : <conditional>@gcc-dep-req ;
 explicit gcc-dep ;
 
 
-rule icu4c-dep-req ( properties * )
-{
-  assert-specified   <triplet>         : $(properties) ;
-  assert-unspecified <multilib>        : $(properties) ;
-  assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
-  assert-unspecified <binutils-hidden> : $(properties) ;
-  assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
-  assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
-  assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
-  assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
-  assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
-  assert-specified   <gcc>             : $(properties) ;
-  assert-unspecified <gcc-hidden>      : $(properties) ;
-  assert-specified   <icu4c>           : $(properties) ;
-  assert-unspecified <icu4c-hidden>    : $(properties) ;
-  assert-specified   <mpi>             : $(properties) ;
-  assert-unspecified <mpi-hidden>      : $(properties) ;
-  #assert-specified   <openmpi>         : $(properties) ;
-  assert-unspecified <openmpi-hidden>  : $(properties) ;
-  assert-specified   <boost>           : $(properties) ;
-  assert-unspecified <boost-hidden>    : $(properties) ;
-  local result = <source>../icu4c//install ;
-  result = $(result)/<mpi>unspecified ;
-  result = $(result)/<openmpi>unspecified ;
-  result = $(result)/<boost>unspecified ;
-  return $(result) ;
-}
-
-alias icu4c-dep : : <conditional>@icu4c-dep-req ;
-explicit icu4c-dep ;
-
-
-rule openmpi-dep-req ( properties * )
-{
-  assert-specified   <triplet>         : $(properties) ;
-  assert-unspecified <multilib>        : $(properties) ;
-  assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
-  assert-unspecified <binutils-hidden> : $(properties) ;
-  assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
-  assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
-  assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
-  assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
-  assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
-  assert-specified   <gcc>             : $(properties) ;
-  assert-unspecified <gcc-hidden>      : $(properties) ;
-  assert-specified   <icu4c>           : $(properties) ;
-  assert-unspecified <icu4c-hidden>    : $(properties) ;
-  assert-specified   <mpi>             : $(properties) ;
-  assert-unspecified <mpi-hidden>      : $(properties) ;
-  #assert-specified   <openmpi>         : $(properties) ;
-  assert-unspecified <openmpi-hidden>  : $(properties) ;
-  assert-specified   <boost>           : $(properties) ;
-  assert-unspecified <boost-hidden>    : $(properties) ;
-  local result ;
-  local mpi = [ feature.get-values <mpi> : $(properties) ] ;
-  if $(mpi) = openmpi {
-    result = <source>../openmpi//install ;
-    result = $(result)/<icu4c>unspecified ;
-    result = $(result)/<boost>unspecified ;
-  }
-  return $(result) ;
-}
-
-alias openmpi-dep : : <conditional>@openmpi-dep-req ;
-explicit openmpi-dep ;
-
-
 make make
-  : gcc-dep
-    icu4c-dep
-    openmpi-dep
+  : gcc-dep/<icu4c>unspecified/<mpi>unspecified/<openmpi>unspecified/<boost>unspecified
+    ../icu4c//install/<mpi>unspecified/<openmpi>unspecified/<boost>unspecified
+    ../openmpi//install/<icu4c>unspecified/<boost>unspecified
   : @make-boost
   ;
 explicit make ;
@@ -167,18 +72,18 @@ rule make-boost ( targets * : sources * : properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
+  assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-specified   <icu4c>           : $(properties) ;
@@ -200,64 +105,45 @@ rule make-boost ( targets * : sources * : properties * )
   local boost-root = $(PREFIX)/boost/$(version) ;
   BOOST_ROOT on $(targets) = $(boost-root) ;
 
-  local gcc-raw = [ feature.get-values <gcc> : $(properties) ] ;
-  GCC_RAW on $(targets) = $(gcc-raw) ;
-  local gcc ;
-  if [ regex.match "^([0123456789]+\\.[0123456789]+\\.[0123456789]+)$" : $(gcc-raw) : 1 ] {
-    gcc = $(gcc-raw) ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" ".0" ] ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+.0-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" "" ] ;
-  }
-  else {
-    errors.error "ERROR: an invalid GCC version." ;
-  }
-  if $(gcc) = $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += -sICU_PATH=\"$(PREFIX)\" ;
-  }
-  else {
-    OPTIONS on $(targets) += -sICU_PATH=\"$(PREFIX)/$(gcc)\" ;
-  }
+  local gcc = [ feature.get-values <gcc> : $(properties) ] ;
+  GCC on $(targets) = $(gcc) ;
 
+  OPTIONS on $(targets) += -sICU_PATH=\"$(PREFIX)/gcc-$(gcc)\" ;
+
+  OPTIONS on $(targets) += --stagedir=\"$(PREFIX)/gcc-$(gcc)\" ;
   OPTIONS on $(targets) += --build-type=complete ;
   OPTIONS on $(targets) += --layout=versioned ;
-
   OPTIONS on $(targets) += --without-mpi ;
 
-  if $(gcc) = $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += toolset=gcc ;
-  }
-  else {
-    OPTIONS on $(targets) += toolset=gcc-$(gcc) ;
-  }
+  local toolset-version = [ regex.replace $(gcc) "-" "_" ] ;
+  TOOLSET on $(targets) = gcc-$(toolset-version) ;
+
+  OPTIONS on $(targets) += toolset=gcc-$(toolset-version) ;
 
   OPTIONS on $(targets) += stage ;
-
-  CLEAN_UP_BIN_DIR on $(targets) = "( cd $(boost-root)/bin.v2 && rm -rf libs/*/build/gcc-$(gcc) )" ;
 }
 actions make-boost
 {
   rm -f "$(<)" || exit $?
   if [ ! -x "$(BOOST_ROOT)/b2" ]; then
-    /bin/echo "ERROR: Boost $(VERSION) not found ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: Boost $(VERSION) not found ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: Boost $(VERSION) not found (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: Boost $(VERSION) not found (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
-    ( cd "$(BOOST_ROOT)" && ./b2 -j$(CONCURRENCY) $(OPTIONS) >> "$(STREAM)" 2>&1 )
+    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=debug cxxflags="-std=c++0x" $(OPTIONS) >> "$(STREAM)" 2>&1 )
+    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=release cflags=-flto cxxflags="-std=c++0x" linkflags="-O3 -flto" $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) $(OPTIONS) )
+    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=debug cxxflags="-std=c++0x" $(OPTIONS) )
+    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=release cflags=-flto cxxflags="-std=c++0x" linkflags="-O3 -flto" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    /bin/echo "ERROR: failed to build Boost $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to build Boost $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to build Boost $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to build Boost $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
-  $(CLEAN_UP_BIN_DIR)
-  /bin/echo -n "Boost $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
+  ( cd "$(BOOST_ROOT)/bin.v2" && rm -rf libs/*/build/$(TOOLSET) )
+  echo -n "Boost $(VERSION) (GCC $(GCC), $(TRIPLET)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -268,18 +154,18 @@ rule install-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
+  assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-specified   <icu4c>           : $(properties) ;
diff --git a/clang/jamfile b/clang/jamfile
--- a/clang/jamfile
+++ b/clang/jamfile
@@ -29,18 +29,18 @@ rule gcc-dep-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
+  assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -51,20 +51,8 @@ rule gcc-dep-req ( properties * )
   assert-unspecified <openmpi-hidden>  : $(properties) ;
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
-  local result = <source>../gcc//install ;
   local multilib = [ feature.get-values <multilib-hidden> : $(properties) ] ;
-  result = $(result)/<multilib>$(multilib)/<multilib-hidden>unspecified ;
-  local gmp = [ feature.get-values <gmp-hidden> : $(properties) ] ;
-  result = $(result)/<gmp>$(gmp)/<gmp-hidden>unspecified ;
-  local mpfr = [ feature.get-values <mpfr-hidden> : $(properties) ] ;
-  result = $(result)/<mpfr>$(mpfr)/<mpfr-hidden>unspecified ;
-  local mpc = [ feature.get-values <mpc-hidden> : $(properties) ] ;
-  result = $(result)/<mpc>$(mpc)/<mpc-hidden>unspecified ;
-  local ppl = [ feature.get-values <ppl-hidden> : $(properties) ] ;
-  result = $(result)/<ppl>$(ppl)/<ppl-hidden>unspecified ;
-  local cloog = [ feature.get-values <cloog-hidden> : $(properties) ] ;
-  result = $(result)/<cloog>$(cloog)/<cloog-hidden>unspecified ;
-  return $(result) ;
+  return <source>../gcc//install/<multilib>$(multilib)/<multilib-hidden>unspecified ;
 }
 
 alias gcc-dep : : <conditional>@gcc-dep-req ;
@@ -82,18 +70,18 @@ rule make-clang ( targets * : sources * : properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
+  assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -127,26 +115,15 @@ rule make-clang ( targets * : sources * : properties * )
   OPTIONS on $(targets) += --host=$(triplet) ;
   OPTIONS on $(targets) += --target=$(triplet) ;
 
+  local gcc = [ feature.get-values <gcc> : $(properties) ] ;
+  GCC on $(targets) = $(gcc) ;
+
   # Set the '--prefix' option for the 'configure' script.
-  local gcc-raw = [ feature.get-values <gcc> : $(properties) ] ;
-  local gcc ;
-  if [ regex.match "^([0123456789]+\\.[0123456789]+\\.[0123456789]+)$" : $(gcc-raw) : 1 ] {
-    gcc = $(gcc-raw) ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" ".0" ] ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+.0-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" "" ] ;
-  }
-  else {
-    errors.error "ERROR: an invalid GCC version." ;
-  }
-  OPTIONS on $(targets) += --prefix=\"$(PREFIX)/$(gcc)\" ;
+  OPTIONS on $(targets) += --prefix=\"$(PREFIX)/gcc-$(gcc)\" ;
 
   if $(gcc) != $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += "--with-c-include-dirs=\"$(PREFIX)/$(gcc)/include:/usr/include\"" ;
-    OPTIONS on $(targets) += "--with-cxx-include-root=\"$(PREFIX)/$(gcc)/include/c++/$(gcc)\"" ;
+    OPTIONS on $(targets) += "--with-c-include-dirs=\"$(PREFIX)/gcc-$(gcc)/include:/usr/include\"" ;
+    OPTIONS on $(targets) += "--with-cxx-include-root=\"$(PREFIX)/gcc-$(gcc)/include/c++/\"`\"$(PREFIX)/gcc-$(gcc)/bin/g++\" -dumpversion`" ;
     OPTIONS on $(targets) += --with-cxx-include-arch=$(triplet) ;
     if $(triplet) = x86_64-unknown-linux-gnu || $(triplet) = x86_64-w64-mingw32 {
       OPTIONS on $(targets) += --with-cxx-include-32bit-dir=32 ;
@@ -154,43 +131,19 @@ rule make-clang ( targets * : sources * : properties * )
   }
 
   if $(gcc) != $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += CC="\"$(PREFIX)/$(gcc)/bin/gcc-wrapper\"" ;
-    OPTIONS on $(targets) += CXX="\"$(PREFIX)/$(gcc)/bin/g++-wrapper\"" ;
+    OPTIONS on $(targets) += CC="\"$(PREFIX)/gcc-$(gcc)/bin/gcc\"" ;
+    OPTIONS on $(targets) += CXX="\"$(PREFIX)/gcc-$(gcc)/bin/g++\"" ;
   }
 
-  SET_RUN_VARS on $(targets) = ;
-  if $(gcc) != $(GCC_BUILTIN) {
-    if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
-      SET_RUN_VARS on $(targets) = "PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"; export PATH" ;
-    }
-    else {
-      SET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
-    }
-  }
-
-  GCC_RAW on $(targets) = ;
-  if $(gcc) = $(GCC_BUILTIN) {
-    GCC_RAW on $(targets) = [ feature.get-values <toolset-gcc:version> : $(properties) ] ;
-  }
-  else {
-    GCC_RAW on $(targets) = $(gcc-raw) ;
-  }
-
-  local version-prefix = "$(PREFIX)/$(gcc)" ;
+  local version-prefix = "$(PREFIX)/gcc-$(gcc)" ;
   VERSION_PREFIX on $(targets) = $(version-prefix) ;
 
   ENV_DYN_LINK_VARS on $(targets) = ;
-  if $(gcc) != $(GCC_BUILTIN) {
-    if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
-      if $(gcc) != $(GCC_BUILTIN) {
-        ENV_DYN_LINK_VARS on $(targets) = "/usr/bin/env PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"" ;
-      }
-    }
-    else {
-      if $(version) != $(GCC_BUILTIN) {
-        ENV_DYN_LINK_VARS on $(targets) = "/usr/bin/env LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"" ;
-      }
-    }
+  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
+    ENV_DYN_LINK_VARS on $(targets) = "env PATH=\"$(PREFIX)/gcc-$(gcc)/bin${PATH:+:$PATH}\"" ;
+  }
+  else {
+    ENV_DYN_LINK_VARS on $(targets) = "env LD_LIBRARY_PATH=\"$(PREFIX)/gcc-$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"" ;
   }
 }
 actions make-clang
@@ -205,7 +158,7 @@ actions make-clang
     if [ $? -ne 0 ]; then
       ( cd "$(INTRO_ROOT_DIR)" && rm -rf llvm )
       echo "ERROR: failed to 'svn checkout' LLVM repository." 1>&2
-      /bin/echo -n "ERROR: failed to 'svn checkout' LLVM repository." | $(AWACS)
+      echo -n "ERROR: failed to 'svn checkout' LLVM repository." | $(AWACS)
       exit 1
     fi
     [ -d "$(LLVM_DIR)" ] || exit 1
@@ -222,7 +175,7 @@ actions make-clang
     if [ $? -ne 0 ]; then
       ( cd "$(INTRO_ROOT_DIR)/llvm/tools" && rm -rf clang )
       echo "ERROR: failed to 'svn checkout' Clang repository." 1>&2
-      /bin/echo -n "ERROR: failed to 'svn checkout' Clang repository." | $(AWACS)
+      echo -n "ERROR: failed to 'svn checkout' Clang repository." | $(AWACS)
       exit 1
     fi
     [ -d "$(CLANG_DIR)" ] || exit 1
@@ -234,7 +187,7 @@ actions make-clang
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'svn update' LLVM repository." 1>&2
-    /bin/echo -n "ERROR: failed to 'svn update' LLVM repository." | $(AWACS)
+    echo -n "ERROR: failed to 'svn update' LLVM repository." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -244,31 +197,31 @@ actions make-clang
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'svn update' Clang repository." 1>&2
-    /bin/echo -n "ERROR: failed to 'svn update' Clang repository." | $(AWACS)
+    echo -n "ERROR: failed to 'svn update' Clang repository." | $(AWACS)
     exit 1
   fi
-  llvm_rev=`( cd "$(LLVM_DIR)" && { LANG=C svn info || exit 1; } | { grep -E '^Revision: [[:digit:]]+$' || exit 1; } | { grep -oE '[[:digit:]]+$' || exit 1; } )`
+  llvm_rev=`( cd "$(LLVM_DIR)" && { env LANG=C svn info || exit 1; } | { grep -E '^Revision: [[:digit:]]+$' || exit 1; } | { grep -oE '[[:digit:]]+$' || exit 1; } )`
   [ $? -eq 0 ] || $?
-  mkdir -p "$(<:D)/build" || exit $?
+  { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit 1
   if [ -n "$(STREAM)" ]; then
-    ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) "$(CONFIGURE)" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'configure' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'configure' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'configure' LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'configure' LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   [ -f "$(<:D)/build/Makefile" ] || exit 1
   if [ -n "$(STREAM)" ]; then
-    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make' LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make' LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -277,28 +230,29 @@ actions make-clang
     ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) make check )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make check' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make check' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make check' LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make check' LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
-    ( cd "$(<:D)/build" && make install >> "$(STREAM)" 2>&1 )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) make install >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$(<:D)/build" && make install )
+    ( cd "$(<:D)/build" && $(ENV_DYN_LINK_VARS) make install )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make install' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make install' LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make install' LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make install' LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
-  install --mode=755 "$(INTRO_ROOT_DIR)/clang/clang++-wrapper" "$(VERSION_PREFIX)/bin"
-  if [ $? -ne 0 ]; then
-    echo "ERROR: failed to install the wrapper script for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to install the wrapper script for LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
-    exit 1
-  fi
-  /bin/echo -n "LLVM & Clang Rev.${llvm_rev} ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
+  #install --mode=755 "$(INTRO_ROOT_DIR)/clang/clang++-wrapper" "$(VERSION_PREFIX)/bin"
+  #if [ $? -ne 0 ]; then
+  #  echo "ERROR: failed to install the wrapper script for LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." 1>&2
+  #  echo -n "ERROR: failed to install the wrapper script for LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET))." | $(AWACS)
+  #  exit 1
+  #fi
+  ( cd "$(<:D)" && rm -rf build )
   [ -e "$(<)" ] && exit 1
+  echo -n "LLVM & Clang Rev.${llvm_rev} (GCC $(GCC), $(TRIPLET)) was successfully built." | $(AWACS)
   touch "$(<)"
 }
 
@@ -308,18 +262,18 @@ rule install-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
+  assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
diff --git a/gmp/jamfile b/gmp/jamfile
--- a/gmp/jamfile
+++ b/gmp/jamfile
@@ -29,18 +29,18 @@ rule gcc-dep-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
-  assert-specified   <gmp>             : $(properties) ;
+  assert-unspecified <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -51,18 +51,8 @@ rule gcc-dep-req ( properties * )
   assert-unspecified <openmpi-hidden>  : $(properties) ;
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
-  local result = <source>../gcc//install ;
   local multilib = [ feature.get-values <multilib-hidden> : $(properties) ] ;
-  result = $(result)/<multilib>$(multilib)/<multilib-hidden>unspecified ;
-  local mpfr = [ feature.get-values <mpfr-hidden> : $(properties) ] ;
-  result = $(result)/<mpfr>$(mpfr)/<mpfr-hidden>unspecified ;
-  local mpc = [ feature.get-values <mpc-hidden> : $(properties) ] ;
-  result = $(result)/<mpc>$(mpc)/<mpc-hidden>unspecified ;
-  local ppl = [ feature.get-values <ppl-hidden> : $(properties) ] ;
-  result = $(result)/<ppl>$(ppl)/<ppl-hidden>unspecified ;
-  local cloog = [ feature.get-values <cloog-hidden> : $(properties) ] ;
-  result = $(result)/<cloog>$(cloog)/<cloog-hidden>unspecified ;
-  return $(result) ;
+  return <source>../gcc//install/<multilib>$(multilib)/<multilib-hidden>unspecified ;
 }
 
 alias gcc-dep : : <conditional>@gcc-dep-req ;
@@ -116,7 +106,7 @@ actions download-gmp
     fi
     if [ $? -ne 0 ]; then
       echo "ERROR: failed to download GMP tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download GMP tarball." | $(AWACS)
+      echo -n "ERROR: failed to download GMP tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
@@ -191,7 +181,7 @@ actions expand-gmp
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to expand GMP tarball." 1>&2
-    /bin/echo -n "ERROR: failed to expand GMP tarball." | $(AWACS)
+    echo -n "ERROR: failed to expand GMP tarball." | $(AWACS)
     exit 1
   fi
   [ -d "$(DEST_DIR)" ] || exit 1
@@ -202,8 +192,8 @@ actions expand-gmp
 
 
 make make
-  : gcc-dep
-    expand/<triplet>unspecified/<multilib-hidden>unspecified/<binutils>unspecified/<mpfr-hidden>unspecified/<mpc-hidden>unspecified/<ppl-hidden>unspecified/<cloog-hidden>unspecified/<gcc>unspecified
+  : gcc-dep/<gmp>unspecified
+    expand/<triplet>unspecified/<multilib-hidden>unspecified/<gcc>unspecified
   : @make-gmp
   ;
 explicit make ;
@@ -213,18 +203,18 @@ rule make-gmp ( targets * : sources * : properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-specified   <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -251,28 +241,11 @@ rule make-gmp ( targets * : sources * : properties * )
   OPTIONS on $(targets) += --build=$(triplet) ;
   OPTIONS on $(targets) += --host=$(triplet) ;
 
+  local gcc = [ feature.get-values <gcc> : $(properties) ] ;
+  GCC on $(targets) = $(gcc) ;
+
   # Set the '--prefix' option for the 'configure' script.
-  local gcc-raw = [ feature.get-values <gcc> : $(properties) ] ;
-  GCC_RAW on $(targets) = $(gcc-raw) ;
-  local gcc ;
-  if [ regex.match "^([0123456789]+\\.[0123456789]+\\.[0123456789]+)$" : $(gcc-raw) : 1 ] {
-    gcc = $(gcc-raw) ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" ".0" ] ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+.0-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" "" ] ;
-  }
-  else {
-    errors.error "ERROR: an invalid GCC version." ;
-  }
-  if $(gcc) = $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += --prefix=\"$(PREFIX)\" ;
-  }
-  else {
-    OPTIONS on $(targets) += --prefix=\"$(PREFIX)/$(gcc)\" ;
-  }
+  OPTIONS on $(targets) += --prefix=\"$(PREFIX)/gcc-$(gcc)\" ;
 
   # Set the link variants for the 'configure' script.
   if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
@@ -285,26 +258,8 @@ rule make-gmp ( targets * : sources * : properties * )
   }
 
   if $(gcc) != $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += CC=\"$(PREFIX)/$(gcc)/bin/gcc-wrapper\" ;
-    OPTIONS on $(targets) += CXX=\"$(PREFIX)/$(gcc)/bin/g++-wrapper\" ;
-  }
-
-  SET_RUN_VARS on $(targets) = ;
-  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
-    if $(gcc) = $(GCC_BUILTIN) {
-      SET_RUN_VARS on $(targets) = "PATH=\"$(PREFIX)/bin${PATH:+:$PATH}\"; export PATH" ;
-    }
-    else {
-      SET_RUN_VARS on $(targets) = "PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"; export PATH" ;
-    }
-  }
-  else {
-    if $(gcc) = $(GCC_BUILTIN) {
-      SET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$(PREFIX)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
-    }
-    else {
-      SET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
-    }
+    OPTIONS on $(targets) += CC=\"$(PREFIX)/gcc-$(gcc)/bin/gcc\" ;
+    OPTIONS on $(targets) += CXX=\"$(PREFIX)/gcc-$(gcc)/bin/g++\" ;
   }
 }
 actions make-gmp
@@ -319,8 +274,8 @@ actions make-gmp
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'configure' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'configure' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'configure' GMP $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'configure' GMP $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   [ -f "$(<:D)/build/Makefile" ] || exit 1
@@ -330,8 +285,8 @@ actions make-gmp
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make' GMP $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make' GMP $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -340,8 +295,8 @@ actions make-gmp
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make check' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make check' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make check' GMP $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make check' GMP $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -350,12 +305,12 @@ actions make-gmp
     ( cd "$(<:D)/build" && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make install' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make install' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make install' GMP $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make install' GMP $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)" && rm -rf build )
-  /bin/echo -n "GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
+  echo -n "GMP $(VERSION) (GCC $(GCC), $(TRIPLET)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -366,18 +321,18 @@ rule install-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-specified   <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
diff --git a/mpc/jamfile b/mpc/jamfile
--- a/mpc/jamfile
+++ b/mpc/jamfile
@@ -24,43 +24,6 @@ rule assert-unspecified ( feature : properties * )
 }
 
 
-rule mpfr-dep-req ( properties * )
-{
-  assert-specified   <triplet>         : $(properties) ;
-  assert-unspecified <multilib>        : $(properties) ;
-  assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
-  assert-unspecified <binutils-hidden> : $(properties) ;
-  assert-specified   <gmp>             : $(properties) ;
-  assert-unspecified <gmp-hidden>      : $(properties) ;
-  assert-specified   <mpfr>            : $(properties) ;
-  assert-unspecified <mpfr-hidden>     : $(properties) ;
-  assert-specified   <mpc>             : $(properties) ;
-  assert-unspecified <mpc-hidden>      : $(properties) ;
-  assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
-  assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
-  assert-specified   <gcc>             : $(properties) ;
-  assert-unspecified <gcc-hidden>      : $(properties) ;
-  assert-unspecified <icu4c>           : $(properties) ;
-  assert-unspecified <icu4c-hidden>    : $(properties) ;
-  assert-unspecified <mpi>             : $(properties) ;
-  assert-unspecified <mpi-hidden>      : $(properties) ;
-  assert-unspecified <openmpi>         : $(properties) ;
-  assert-unspecified <openmpi-hidden>  : $(properties) ;
-  assert-unspecified <boost>           : $(properties) ;
-  assert-unspecified <boost-hidden>    : $(properties) ;
-  local result = <source>../mpfr//install ;
-  local mpc = [ feature.get-values <mpc> : $(properties) ] ;
-  result = $(result)/<mpc>unspecified/<mpc-hidden>$(mpc) ;
-  return $(result) ;
-}
-
-alias mpfr-dep : : <conditional>@mpfr-dep-req ;
-explicit mpfr-dep ;
-
-
 make download : : @download-mpc ;
 explicit download ;
 
@@ -108,7 +71,7 @@ actions download-mpc
     fi
     if [ $? -ne 0 ]; then
       echo "ERROR: failed to download MPC tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download MPC tarball." | $(AWACS)
+      echo -n "ERROR: failed to download MPC tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
@@ -183,7 +146,7 @@ actions expand-mpc
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to expand MPC tarball." 1>&2
-    /bin/echo -n "ERROR: failed to expand MPC tarball." | $(AWACS)
+    echo -n "ERROR: failed to expand MPC tarball." | $(AWACS)
     exit 1
   fi
   [ -d "$(DEST_DIR)" ] || exit 1
@@ -194,8 +157,8 @@ actions expand-mpc
 
 
 make make
-  : mpfr-dep
-    expand/<triplet>unspecified/<multilib-hidden>unspecified/<binutils>unspecified/<gmp>unspecified/<mpfr>unspecified/<ppl-hidden>unspecified/<cloog-hidden>unspecified/<gcc>unspecified
+  : ../mpfr//install/<mpc>unspecified
+    expand/<triplet>unspecified/<multilib-hidden>unspecified/<gmp>unspecified/<mpfr>unspecified/<gcc>unspecified
   : @make-mpc
   ;
 explicit make ;
@@ -205,7 +168,7 @@ rule make-mpc ( targets * : sources * : properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-specified   <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
@@ -214,9 +177,9 @@ rule make-mpc ( targets * : sources * : properties * )
   assert-specified   <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -243,28 +206,11 @@ rule make-mpc ( targets * : sources * : properties * )
   OPTIONS on $(targets) += --build=$(triplet) ;
   OPTIONS on $(targets) += --host=$(triplet) ;
 
+  local gcc = [ feature.get-values <gcc> : $(properties) ] ;
+  GCC on $(targets) = $(gcc) ;
+
   # Set the '--prefix' option for the 'configure' script.
-  local gcc-raw = [ feature.get-values <gcc> : $(properties) ] ;
-  GCC_RAW on $(targets) = $(gcc-raw) ;
-  local gcc ;
-  if [ regex.match "^([0123456789]+\\.[0123456789]+\\.[0123456789]+)$" : $(gcc-raw) : 1 ] {
-    gcc = $(gcc-raw) ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" ".0" ] ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+.0-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" "" ] ;
-  }
-  else {
-    errors.error "ERROR: an invalid GCC version." ;
-  }
-  if $(gcc) = $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += --prefix=\"$(PREFIX)\" ;
-  }
-  else {
-    OPTIONS on $(targets) += --prefix=\"$(PREFIX)/$(gcc)\" ;
-  }
+  OPTIONS on $(targets) += --prefix=\"$(PREFIX)/gcc-$(gcc)\" ;
 
   # Set the link variants for the 'configure' script.
   if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
@@ -276,36 +222,12 @@ rule make-mpc ( targets * : sources * : properties * )
     OPTIONS on $(targets) += --enable-shared ;
   }
 
-  if $(gcc) = $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += --with-gmp=\"$(PREFIX)\" ;
-    OPTIONS on $(targets) += --with-mpfr=\"$(PREFIX)\" ;
-  }
-  else {
-    OPTIONS on $(targets) += --with-gmp=\"$(PREFIX)/$(gcc)\" ;
-    OPTIONS on $(targets) += --with-mpfr=\"$(PREFIX)/$(gcc)\" ;
-  }
+  OPTIONS on $(targets) += --with-gmp=\"$(PREFIX)/gcc-$(gcc)\" ;
+  OPTIONS on $(targets) += --with-mpfr=\"$(PREFIX)/gcc-$(gcc)\" ;
 
-  if $(gcc) != $(GCC_BULITIN) {
-    OPTIONS on $(targets) += CC=\"$(PREFIX)/$(gcc)/bin/gcc-wrapper\" ;
-    OPTIONS on $(targets) += CXX=\"$(PREFIX)/$(gcc)/bin/g++-wrapper\" ;
-  }
-
-  SET_RUN_VARS on $(targets) = ;
-  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
-    if $(gcc) = $(GCC_BUILTIN) {
-      SET_RUN_VARS on $(targets) = "PATH=\"$(PREFIX)/bin${PATH:+:$PATH}\"; export PATH" ;
-    }
-    else {
-      SET_RUN_VARS on $(targets) = "PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"; export PATH" ;
-    }
-  }
-  else {
-    if $(gcc) = $(GCC_BUILTIN) {
-      SET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$(PREFIX)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
-    }
-    else {
-      SET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
-    }
+  if $(gcc) != $(GCC_BUILTIN) {
+    OPTIONS on $(targets) += CC=\"$(PREFIX)/gcc-$(gcc)/bin/gcc\" ;
+    OPTIONS on $(targets) += CXX=\"$(PREFIX)/gcc-$(gcc)/bin/g++\" ;
   }
 }
 actions make-mpc
@@ -320,8 +242,8 @@ actions make-mpc
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'configure' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'configure' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'configure' MPC $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'configure' MPC $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   [ -f "$(<:D)/build/Makefile" ] || exit 1
@@ -331,8 +253,8 @@ actions make-mpc
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make' MPC $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make' MPC $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -341,8 +263,8 @@ actions make-mpc
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make check' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make check' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make check' MPC $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make check' MPC $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -351,12 +273,12 @@ actions make-mpc
     ( cd "$(<:D)/build" && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make install' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make install' MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make install' MPC $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make install' MPC $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)" && rm -rf build )
-  /bin/echo -n "MPC $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
+  echo -n "MPC $(VERSION) (GCC $(GCC), $(TRIPLET)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -367,7 +289,7 @@ rule install-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-specified   <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
@@ -376,9 +298,9 @@ rule install-req ( properties * )
   assert-specified   <mpc>             : $(properties) ;
   assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
diff --git a/mpfr/jamfile b/mpfr/jamfile
--- a/mpfr/jamfile
+++ b/mpfr/jamfile
@@ -24,43 +24,6 @@ rule assert-unspecified ( feature : properties * )
 }
 
 
-rule gmp-dep-req ( properties * )
-{
-  assert-specified   <triplet>         : $(properties) ;
-  assert-unspecified <multilib>        : $(properties) ;
-  assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
-  assert-unspecified <binutils-hidden> : $(properties) ;
-  assert-specified   <gmp>             : $(properties) ;
-  assert-unspecified <gmp-hidden>      : $(properties) ;
-  assert-specified   <mpfr>            : $(properties) ;
-  assert-unspecified <mpfr-hidden>     : $(properties) ;
-  assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
-  assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
-  assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
-  assert-specified   <gcc>             : $(properties) ;
-  assert-unspecified <gcc-hidden>      : $(properties) ;
-  assert-unspecified <icu4c>           : $(properties) ;
-  assert-unspecified <icu4c-hidden>    : $(properties) ;
-  assert-unspecified <mpi>             : $(properties) ;
-  assert-unspecified <mpi-hidden>      : $(properties) ;
-  assert-unspecified <openmpi>         : $(properties) ;
-  assert-unspecified <openmpi-hidden>  : $(properties) ;
-  assert-unspecified <boost>           : $(properties) ;
-  assert-unspecified <boost-hidden>    : $(properties) ;
-  local result = <source>../gmp//install ;
-  local mpfr = [ feature.get-values <mpfr> : $(properties) ] ;
-  result = $(result)/<mpfr>unspecified/<mpfr-hidden>$(mpfr) ;
-  return $(result) ;
-}
-
-alias gmp-dep : : <conditional>@gmp-dep-req ;
-explicit gmp-dep ;
-
-
 make download : : @download-mpfr ;
 explicit download ;
 
@@ -108,7 +71,7 @@ actions download-mpfr
     fi
     if [ $? -ne 0 ]; then
       echo "ERROR: failed to download MPFR tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download MPFR tarball." | $(AWACS)
+      echo -n "ERROR: failed to download MPFR tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
@@ -183,7 +146,7 @@ actions expand-mpfr
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to expand MPFR tarball." 1>&2
-    /bin/echo -n "ERROR: failed to expand MPFR tarball." | $(AWACS)
+    echo -n "ERROR: failed to expand MPFR tarball." | $(AWACS)
     exit 1
   fi
   [ -d "$(DEST_DIR)" ] || exit 1
@@ -194,8 +157,8 @@ actions expand-mpfr
 
 
 make make
-  : gmp-dep
-    expand/<triplet>unspecified/<multilib-hidden>unspecified/<binutils>unspecified/<gmp>unspecified/<mpc-hidden>unspecified/<ppl-hidden>unspecified/<cloog-hidden>unspecified/<gcc>unspecified
+  : ../gmp//install/<mpfr>unspecified
+    expand/<triplet>unspecified/<multilib-hidden>unspecified/<gmp>unspecified/<gcc>unspecified
   : @make-mpfr
   ;
 explicit make ;
@@ -205,18 +168,18 @@ rule make-mpfr ( targets * : sources * : properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-specified   <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-specified   <mpfr>            : $(properties) ;
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -243,28 +206,11 @@ rule make-mpfr ( targets * : sources * : properties * )
   OPTIONS on $(targets) += --build=$(triplet) ;
   OPTIONS on $(targets) += --host=$(triplet) ;
 
+  local gcc = [ feature.get-values <gcc> : $(properties) ] ;
+  GCC on $(targets) = $(gcc) ;
+
   # Set the '--prefix' option for the 'configure' script.
-  local gcc-raw = [ feature.get-values <gcc> : $(properties) ] ;
-  GCC_RAW on $(targets) = $(gcc-raw) ;
-  local gcc ;
-  if [ regex.match "^([0123456789]+\\.[0123456789]+\\.[0123456789]+)$" : $(gcc-raw) : 1 ] {
-    gcc = $(gcc-raw) ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" ".0" ] ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+.0-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" "" ] ;
-  }
-  else {
-    errors.error "ERROR: an invalid GCC version." ;
-  }
-  if $(gcc) = $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += --prefix=\"$(PREFIX)\" ;
-  }
-  else {
-    OPTIONS on $(targets) += --prefix=\"$(PREFIX)/$(gcc)\" ;
-  }
+  OPTIONS on $(targets) += --prefix=\"$(PREFIX)/gcc-$(gcc)\" ;
 
   # Set the link variants for the 'configure' script.
   if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
@@ -276,34 +222,11 @@ rule make-mpfr ( targets * : sources * : properties * )
     OPTIONS on $(targets) += --enable-shared ;
   }
 
-  if $(gcc) = $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += --with-gmp=\"$(PREFIX)\" ;
-  }
-  else {
-    OPTIONS on $(targets) += --with-gmp=\"$(PREFIX)/$(gcc)\" ;
-  }
+  OPTIONS on $(targets) += --with-gmp=\"$(PREFIX)/gcc-$(gcc)\" ;
 
   if $(gcc) != $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += CC=\"$(PREFIX)/$(gcc)/bin/gcc-wrapper\" ;
-    OPTIONS on $(targets) += CXX=\"$(PREFIX)/$(gcc)/bin/g++-wrapper\" ;
-  }
-
-  SET_RUN_VARS on $(targets) = ;
-  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
-    if $(gcc) = $(GCC_BUILTIN) {
-      SET_RUN_VARS on $(targets) = "PATH=\"$(PREFIX)/bin${PATH:+:$PATH}\"; export PATH" ;
-    }
-    else {
-      SET_RUN_VARS on $(targets) = "PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"; export PATH" ;
-    }
-  }
-  else {
-    if $(gcc) = $(GCC_BUILTIN) {
-      SET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$(PREFIX)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
-    }
-    else {
-      SET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
-    }
+    OPTIONS on $(targets) += CC=\"$(PREFIX)/gcc-$(gcc)/bin/gcc\" ;
+    OPTIONS on $(targets) += CXX=\"$(PREFIX)/gcc-$(gcc)/bin/g++\" ;
   }
 }
 actions make-mpfr
@@ -318,8 +241,8 @@ actions make-mpfr
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'configure' MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'configure' MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'configure' MPFR $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'configure' MPFR $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   [ -f "$(<:D)/build/Makefile" ] || exit 1
@@ -329,8 +252,8 @@ actions make-mpfr
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make' MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make' MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make' MPFR $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make' MPFR $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -339,8 +262,8 @@ actions make-mpfr
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make check' MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make check' MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make check' MPFR $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make check' MPFR $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -349,12 +272,12 @@ actions make-mpfr
     ( cd "$(<:D)/build" && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make install' MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make install' MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make install' MPFR $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make install' MPFR $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)" && rm -rf build )
-  /bin/echo -n "MPFR $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
+  echo -n "MPFR $(VERSION) (GCC $(GCC), $(TRIPLET)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -365,18 +288,18 @@ rule install-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-specified   <gmp>             : $(properties) ;
   assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-specified   <mpfr>            : $(properties) ;
   assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
diff --git a/openmpi/jamfile b/openmpi/jamfile
--- a/openmpi/jamfile
+++ b/openmpi/jamfile
@@ -29,43 +29,30 @@ rule gcc-dep-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
+  assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
   assert-unspecified <icu4c-hidden>    : $(properties) ;
-  assert-specified   <mpi>             : $(properties) ;
+  assert-unspecified <mpi>             : $(properties) ;
   assert-unspecified <mpi-hidden>      : $(properties) ;
-  assert-specified   <openmpi>         : $(properties) ;
+  assert-unspecified <openmpi>         : $(properties) ;
   assert-unspecified <openmpi-hidden>  : $(properties) ;
   assert-unspecified <boost>           : $(properties) ;
   assert-unspecified <boost-hidden>    : $(properties) ;
-  local result = <source>../gcc//install ;
   local multilib = [ feature.get-values <multilib-hidden> : $(properties) ] ;
-  result = $(result)/<multilib>$(multilib)/<multilib-hidden>unspecified ;
-  local gmp = [ feature.get-values <gmp-hidden> : $(properties) ] ;
-  result = $(result)/<gmp>$(gmp)/<gmp-hidden>unspecified ;
-  local mpfr = [ feature.get-values <mpfr-hidden> : $(properties) ] ;
-  result = $(result)/<mpfr>$(mpfr)/<mpfr-hidden>unspecified ;
-  local mpc = [ feature.get-values <mpc-hidden> : $(properties) ] ;
-  result = $(result)/<mpc>$(mpc)/<mpc-hidden>unspecified ;
-  local ppl = [ feature.get-values <ppl-hidden> : $(properties) ] ;
-  result = $(result)/<ppl>$(ppl)/<ppl-hidden>unspecified ;
-  local cloog = [ feature.get-values <cloog-hidden> : $(properties) ] ;
-  result = $(result)/<cloog>$(cloog)/<cloog-hidden>unspecified ;
-  result = $(result)/<mpi>unspecified/<openmpi>unspecified ;
-  return $(result) ;
+  return <source>../gcc//install/<multilib>$(multilib)/<multilib-hidden>unspecified ;
 }
 
 alias gcc-dep : : <conditional>@gcc-dep-req ;
@@ -119,7 +106,7 @@ actions download-openmpi
     fi
     if [ $? -ne 0 ]; then
       echo "ERROR: failed to download Open MPI tarball." 1>&2
-      /bin/echo -n "ERROR: failed to download Open MPI tarball." | $(AWACS)
+      echo -n "ERROR: failed to download Open MPI tarball." | $(AWACS)
       exit 1
     fi
     [ -f "$(TARBALL_GZ)" -o -f "$(TARBALL_BZ2)" ] || exit 1
@@ -194,7 +181,7 @@ actions expand-openmpi
   fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to expand Open MPI tarball." 1>&2
-    /bin/echo -n "ERROR: failed to expand Open MPI tarball." | $(AWACS)
+    echo -n "ERROR: failed to expand Open MPI tarball." | $(AWACS)
     exit 1
   fi
   [ -d "$(DEST_DIR)" ] || exit 1
@@ -205,8 +192,8 @@ actions expand-openmpi
 
 
 make make
-  : gcc-dep
-    expand/<triplet>unspecified/<multilib-hidden>unspecified/<binutils>unspecified/<gmp-hidden>unspecified/<mpfr-hidden>unspecified/<mpc-hidden>unspecified/<ppl-hidden>unspecified/<cloog-hidden>unspecified/<gcc>unspecified/<mpi>unspecified
+  : gcc-dep/<mpi>unspecified/<openmpi>unspecified
+    expand/<triplet>unspecified/<multilib-hidden>unspecified/<gcc>unspecified/<mpi>unspecified
   : @make-openmpi
   ;
 explicit make ;
@@ -216,18 +203,18 @@ rule make-openmpi ( targets * : sources * : properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
+  assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
@@ -254,28 +241,11 @@ rule make-openmpi ( targets * : sources * : properties * )
   OPTIONS on $(targets) += --build=$(triplet) ;
   OPTIONS on $(targets) += --host=$(triplet) ;
 
+  local gcc = [ feature.get-values <gcc> : $(properties) ] ;
+  GCC on $(targets) = $(gcc) ;
+
   # Set the '--prefix' option for the 'configure' script.
-  local gcc-raw = [ feature.get-values <gcc> : $(properties) ] ;
-  GCC_RAW on $(targets) = $(gcc-raw) ;
-  local gcc ;
-  if [ regex.match "^([0123456789]+\\.[0123456789]+\\.[0123456789]+)$" : $(gcc-raw) : 1 ] {
-    gcc = $(gcc-raw) ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" ".0" ] ;
-  }
-  else if [ regex.match "^([0123456789]+\\.[0123456789]+.0-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789])$" : $(gcc-raw) : 1 ] {
-    gcc = [ regex.replace "$(gcc-raw)" "-RC-[0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789][0123456789]$" "" ] ;
-  }
-  else {
-    errors.error "ERROR: an invalid GCC version." ;
-  }
-  if $(gcc) = $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += --prefix=\"$(PREFIX)\" ;
-  }
-  else {
-    OPTIONS on $(targets) += --prefix=\"$(PREFIX)/$(gcc)\" ;
-  }
+  OPTIONS on $(targets) += --prefix=\"$(PREFIX)/gcc-$(gcc)\" ;
 
   OPTIONS on $(targets) += --disable-mpi-f77 ;
   OPTIONS on $(targets) += --disable-mpi-f90 ;
@@ -287,26 +257,8 @@ rule make-openmpi ( targets * : sources * : properties * )
   OPTIONS on $(targets) += --enable-mpi-threads ;
 
   if $(gcc) != $(GCC_BUILTIN) {
-    OPTIONS on $(targets) += CC=\"$(PREFIX)/$(gcc)/bin/gcc-wrapper\" ;
-    OPTIONS on $(targets) += CXX=\"$(PREFIX)/$(gcc)/bin/g++-wrapper\" ;
-  }
-
-  SET_RUN_VARS on $(targets) = ;
-  if $(triplet) = i686-pc-cygwin || $(triplet) = i686-w64-mingw32 || $(triplet) = x86_64-w64-mingw32 {
-    if $(gcc) = $(GCC_BUILTIN) {
-      SET_RUN_VARS on $(targets) = "PATH=\"$(PREFIX)/bin${PATH:+:$PATH}\"; export PATH" ;
-    }
-    else {
-      SET_RUN_VARS on $(targets) = "PATH=\"$(PREFIX)/$(gcc)/bin${PATH:+:$PATH}\"; export PATH" ;
-    }
-  }
-  else {
-    if $(gcc) = $(GCC_BUILTIN) {
-      SET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$(PREFIX)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
-    }
-    else {
-      SET_RUN_VARS on $(targets) = "LD_LIBRARY_PATH=\"$(PREFIX)/$(gcc)/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}\"; export LD_LIBRARY_PATH" ;
-    }
+    OPTIONS on $(targets) += CC=\"$(PREFIX)/gcc-$(gcc)/bin/gcc\" ;
+    OPTIONS on $(targets) += CXX=\"$(PREFIX)/gcc-$(gcc)/bin/g++\" ;
   }
 }
 actions make-openmpi
@@ -321,8 +273,8 @@ actions make-openmpi
     ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'configure' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'configure' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'configure' Open MPI $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'configure' Open MPI $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   [ -f "$(<:D)/build/Makefile" ] || exit 1
@@ -332,8 +284,8 @@ actions make-openmpi
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make' Open MPI $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make' Open MPI $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -342,8 +294,8 @@ actions make-openmpi
     ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make check' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make check' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make check' Open MPI $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make check' Open MPI $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   if [ -n "$(STREAM)" ]; then
@@ -352,12 +304,12 @@ actions make-openmpi
     ( cd "$(<:D)/build" && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make install' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
-    /bin/echo -n "ERROR: failed to 'make install' Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    echo "ERROR: failed to 'make install' Open MPI $(VERSION) (GCC $(GCC), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to 'make install' Open MPI $(VERSION) (GCC $(GCC), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
   ( cd "$(<:D)" && rm -rf build )
-  /bin/echo -n "Open MPI $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW)) was successfully built." | $(AWACS)
+  echo -n "Open MPI $(VERSION) (GCC $(GCC), $(TRIPLET)) was successfully built." | $(AWACS)
   [ -e "$(<)" ] && exit 1
   touch "$(<)"
 }
@@ -368,18 +320,18 @@ rule install-req ( properties * )
   assert-specified   <triplet>         : $(properties) ;
   assert-unspecified <multilib>        : $(properties) ;
   assert-specified   <multilib-hidden> : $(properties) ;
-  assert-specified   <binutils>        : $(properties) ;
+  assert-unspecified <binutils>        : $(properties) ;
   assert-unspecified <binutils-hidden> : $(properties) ;
   assert-unspecified <gmp>             : $(properties) ;
-  assert-specified   <gmp-hidden>      : $(properties) ;
+  assert-unspecified <gmp-hidden>      : $(properties) ;
   assert-unspecified <mpfr>            : $(properties) ;
-  assert-specified   <mpfr-hidden>     : $(properties) ;
+  assert-unspecified <mpfr-hidden>     : $(properties) ;
   assert-unspecified <mpc>             : $(properties) ;
-  assert-specified   <mpc-hidden>      : $(properties) ;
+  assert-unspecified <mpc-hidden>      : $(properties) ;
   assert-unspecified <ppl>             : $(properties) ;
-  assert-specified   <ppl-hidden>      : $(properties) ;
+  assert-unspecified <ppl-hidden>      : $(properties) ;
   assert-unspecified <cloog>           : $(properties) ;
-  assert-specified   <cloog-hidden>    : $(properties) ;
+  assert-unspecified <cloog-hidden>    : $(properties) ;
   assert-specified   <gcc>             : $(properties) ;
   assert-unspecified <gcc-hidden>      : $(properties) ;
   assert-unspecified <icu4c>           : $(properties) ;
