batch.sh: Batch build sometimes fails due to an accidental. I made the batch bulid script to retry if the first build attempt fails.
*/jamfile and user-config.jam:
`--prefix' for the built-in GCC is changed to `$(prefix)/local'.
Fixed some bugs.

gcc-prerequisites/jamfile and gcc/jamfile:
I made each GCC build to use pre-built GMP, MPFR and MPC.
Previously, they were built at the same time as each GCC build, by
creating `gmp', `mpfr', `mpc' symlinks in the GCC source trees.
However, it is difficult to control configuration
(environment variables) in the use of built compilers. Now, the
build process of GCC uses static libraries that are installed into
`gcc-prerequisites' directory in advance.
`gcc-prerequisites/jamfile' is the build script for such
prerequisites.

diff --git a/boost/jamfile b/boost/jamfile
--- a/boost/jamfile
+++ b/boost/jamfile
@@ -189,14 +189,18 @@ rule make-boost ( targets * : sources * : properties * )
 actions make-boost
 {
   rm -f "$(<)" || exit $?
-  [ -x "$(BOOST_ROOT)/b2" ] || exit $?
+  if [ ! -x "$(BOOST_ROOT)/b2" ]; then
+    /bin/echo "ERROR: Boost $(VERSION) not found ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo -n "ERROR: Boost $(VERSION) not found ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
+    exit 1
+  fi
   if [ -n "$(STREAM)" ]; then
     ( cd "$(BOOST_ROOT)" && ./b2 -j$(CONCURRENCY) $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
     ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to build Boost $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
+    /bin/echo "ERROR: failed to build Boost $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
     /bin/echo -n "ERROR: failed to build Boost $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
