Added multi-configuration support.
* .gitignore: Fixed `.gitignore` to ignore `objdir`.
* compilers.jam:
    * Removed `pushd` and `popd` because they are bash-specific builtins.
    * Fixed invocation of ICC `compilervars.sh`.
    * `Fixed bugs in calculation of triplets.
* jamroot:
    * Removed `unspecified` value from `<intro-address-model>` feature. The
      default value for the feature is the system default bits (e.g., `64`
      for `x86_64-*`, `32` for `i686-*`, and so on).
    * Added dependencies on the backend GCC for Clang.
    * Fixed typos.
* gcc/jamfile:
    * Removed `ln -s lib lib64` because the convention of library
      directories differs from distribution to distribution and `lib`
      directory cannot be assumed to be the directory for 64-bit libraries.
    * Added a new GCC mirror site in Japan.
* icc/jamfile: Added logfile output.
* template/x86_64-unknown-linux-gnu/gcc-wrapper:
    * Use `-###` (dry run) option to robustly detect whether the target is
      64-bit or 32-bit.
    * Added workaround for Debian multiarch. Because GCC without Debian
      patches cannot find by default libraries that reside in Debian
      multiarch directories, `-rpath-link` options to the directories are
      required for GCC (and an underlying linker) to correctly resolve
      indirect dependencies among shared libraries in link time.
* template/x86_64-unknown-linux-gnu/g++-wrapper:
    * Use `-###` (dry run) option to robustly detect whether the target is
      64-bit or 32-bit.
    * Added workaround for Debian multiarch. Because GCC without Debian
      patches cannot find by default libraries that reside in Debian
      multiarch directories, `-rpath-link` options to the directories are
      required for GCC (and an underlying linker) to correctly resolve
      indirect dependencies among shared libraries in link time.
* template/x86_64-unknown-linux-gnu/site-config.jam:
    * Added support for ICC.
    * Just tweaked quotations etc.
* template/x86_64-unknown-linux-gnu/user-config.jam: Added support for ICC.
* mpfr/jamfile: Added `--with-gmp` option.
* mpc/jamfile: Added `--with-mpfr` and `--with-gmp` options.
* isl/latest.sh: Modified to use the new repository of ISL.
* isl/jamfile:
    * Modified to use the new repository of ISL.
    * Added `--with-gmp-prefix` option.
* cloog/jamfile: Added `--with-isl-prefix` and `--with-gmp-prefix` options.
* icu4c/jamfile: Removed `--enable-threads` or `--disable-threads` from the
  command line options for ICU4C configure script because they are no longer
  valid in recent versions of ICU4C.
* openmpi/jamfile: Removed `<intro-address-model>unspecified` property.
* boost/jamfile:
    * Removed `<intro-address-model>unspecified` property.
    * Introduced dependencies on GMP and MPFR build processes because they
      may be used by Boost.Multiprecision as its backend.
    * Reduced build concurrency for the Boost.Thread test suite in order to
      allow more concurrency per a unit test.
    * Added support for ICC.
    * Added `ulimit` for the size of core files. Because many Boost test
      cases crash, core files should be prevented from occupying large
      portion of disk space.
    * Added `ulimit` for Boost test suite.
    * Added selections of suitable concurrency for Boost test suite.
    * Tweaked the limit on CPU time for Boost test suite, because the test
      suite for Boost.Algorithm and Boost.Thread takes more than 600
      seconds.
* boost/toolset.sh: Added support for ICC.
* valgrind/jamfile: Fixed a wrong value for `--with-mpicc` configure option.
* clang/jamfile:
    * Removed a workaround for a bug appeared in recent revisions.
    * Added support of extra clang tools repository.
* summary.sh:
    * Removed the column for `address-model=unspecified`.
    * Added rows for Boost.Atomic, Boost.Coroutine, Boost.Lockfree and
      Boost.Multiprecision.
* Fixed #8.
* Fixed #17.
* Fixed #24.

diff --git a/boost/jamfile b/boost/jamfile
--- a/boost/jamfile
+++ b/boost/jamfile
@@ -12,9 +12,10 @@ import "$(INTRO_ROOT_DIR)/compilers"
     is-icc
     get-compiler-description
     get-compiler-prefix
-    get-libdir
-    get-includedir
+    get-full-prefix
+    get-triplets
     get-environment-commands
+    get-logfile-path
     get-property-dump-commands
   ;
 
@@ -67,18 +68,15 @@ explicit openmpi-dep ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
-  local version = [ feature.get-values <boost-hidden> : $(properties) ] ;
-  version = [ regex.match "([0-9]+\\.[0-9]+)\\.[0-9]+" : "$(version)" : 1 ] ;
-  if ! "$(version)" {
-    errors.error "an internal error." ;
-  }
-  version = [ regex.replace "$(version)" "\\." "_" ] ;
-  return "<location>$(includedir)/boost-$(version)/boost" ;
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local libdir = "$(full-prefix)/lib" ;
+  return "<location>$(libdir)" ;
 }
 
-make version.hpp
+make boost.stage
   : compiler-dep
+    ../gmp//install
+    ../mpfr//install
     ../icu4c//install
     openmpi-dep
   : @install
@@ -92,7 +90,7 @@ make version.hpp
     $(USE_INSTRUCTION_SET)
     <conditional>@location-conditional
   ;
-explicit version.hpp ;
+explicit boost.stage ;
 
 rule install ( targets * : sources * : properties * )
 {
@@ -108,24 +106,44 @@ rule install ( targets * : sources * : properties * )
 
   local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
 
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local full-prefix-native = [ path.native "$(full-prefix)" ] ;
+  FULL_PREFIX on $(targets) = "$(full-prefix-native)" ;
+
+  ADDITIONAL_BUILD_OPTS on $(targets) = ;
+
+  ADDITIONAL_BUILD_OPTS on $(targets) += "--stagedir='$(full-prefix-native)'" ;
+
+  local triplets = [ get-triplets $(properties) ] ;
+  local build-triplet = "$(triplets[1])" ;
+  local host-triplet = "$(triplets[2])" ;
+
+  ADDITIONAL_BUILD_OPTS on $(targets) += "--build-type=minimal" ;
+  ADDITIONAL_BUILD_OPTS on $(targets) += "--layout=system" ;
+  ADDITIONAL_BUILD_OPTS on $(targets) += "--without-locale" ;
+  if "$(build-triplet)" = "x86_64-unknown-linux-gnu" && "$(host-triplet)" = "i686-pc-linux-gnu" {
+    ADDITIONAL_BUILD_OPTS on $(targets) += "--without-mpi" ;
+    ADDITIONAL_BUILD_OPTS on $(targets) += "--without-python" ;
+  }
+
+  local link = [ feature.get-values <link> : $(properties) ] ;
+  LINK on $(targets) = "$(link)" ;
+  if "$(link)" = "shared" {
+    ADDITIONAL_BUILD_OPTS on $(targets) += "--without-exception" ;
+  }
+
+  local threading = [ feature.get-values <threading> : $(properties) ] ;
+  THREADING on $(targets) = "$(threading)" ;
+  if "$(threading)" = "single" {
+    ADDITIONAL_BUILD_OPTS on $(targets) += "--without-locale" ;
+    ADDITIONAL_BUILD_OPTS on $(targets) += "--without-thread" ;
+    ADDITIONAL_BUILD_OPTS on $(targets) += "--without-wave" ;
+  }
+
   OPTIONS on $(targets) = ;
 
-  #OPTIONS on $(targets) += -sICU_PATH=\"$(compiler-prefix)\" ;
-
-  OPTIONS on $(targets) += "--prefix='$(compiler-prefix)'" ;
-
-  local libdir = [ get-libdir "$(PREFIX)" : $(properties) ] ;
-  local libdir-native = [ path.native "$(libdir)" ] ;
-  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
-
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
-  local includedir-native = [ path.native "$(includedir)" ] ;
-  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
-
-  OPTIONS on $(targets) += --build-type=complete ;
-  OPTIONS on $(targets) += --layout=versioned ;
-  OPTIONS on $(targets) += --without-locale ;
-  OPTIONS on $(targets) += --without-mpi ;
+  # The following environment variable is required for ICC to detect ICU4C correctly.
+  OPTIONS on $(targets) += "-sICU_PATH='$(full-prefix-native)'" ;
 
   if [ is-gcc "$(compiler)" ] {
     OPTIONS on $(targets) += "toolset=`'$(INTRO_ROOT_DIR)/boost/toolset.sh' '$(compiler-prefix)/bin/g++-wrapper'`" ;
@@ -133,56 +151,118 @@ rule install ( targets * : sources * : properties * )
   else if [ is-clang "$(compiler)" ] {
     OPTIONS on $(targets) += "toolset=`'$(INTRO_ROOT_DIR)/boost/toolset.sh' '$(compiler-prefix)/bin/clang++-wrapper'`" ;
   }
+  else if [ is-icc "$(compiler)" ] {
+    OPTIONS on $(targets) += "toolset=`'$(INTRO_ROOT_DIR)/boost/toolset.sh' '$(compiler-prefix)/bin/icpc-wrapper'`" ;
+  }
   else {
     errors.error "an internal error." ;
   }
 
-  local toolset = [ feature.get-values <toolset> : $(properties) ] ;
-
-  local std = [ feature.get-values <std> : $(properties) ] ;
-  OPTIONS on $(targets) += "std=$(std)" ;
-
   local variant = [ feature.get-values <variant> : $(properties) ] ;
   OPTIONS on $(targets) += "variant=$(variant)" ;
-  if "$(variant)" = "debug" {
-    switch "$(toolset)" {
-    case "gcc" :
-      # Do nothing.
-    case "clang" :
-      # Do nothing.
-    case "icc" :
+  switch "$(variant)" {
+  case "debug" :
+    if [ is-icc "$(compiler)" ] {
       OPTIONS on $(targets) += "cflags='-debug full'" ;
       OPTIONS on $(targets) += "linkflags='-debug full'" ;
-    case "*" :
-      errors.error "an internal error." ;
     }
+    OPTIONS on $(targets) += "linkflags=-rdynamic" ;
+  case "release" :
+    # Do nothing.
+  case "profile" :
+    OPTIONS on $(targets) += "linkflags=-rdynamic" ;
+  case "" :
+    errors.error "the value for `<variant>' is empty" ;
+  case "*" :
+    errors.error "<variant>$(variant): unknown property" ;
   }
+
+  OPTIONS on $(targets) += "link=$(link)" ;
 
   OPTIONS on $(targets) += "runtime-link=shared" ;
 
-  local threading = [ feature.get-values <threading> : $(properties) ] ;
   OPTIONS on $(targets) += "threading=$(threading)" ;
 
+  local address-model = [ feature.get-values "<intro-address-model>" : $(properties) ] ;
+  switch "$(address-model)" {
+  case "64" :
+    OPTIONS on $(targets) += "address-model=64" ;
+  case "32" :
+    OPTIONS on $(targets) += "address-model=32" ;
+  case "" :
+    errors.error "the value for `<intro-address-model>' is empty" ;
+  case "*" :
+    errors.error "`<intro-address-model>$(address-model)': unknown property" ;
+  }
+
   local instruction-set = [ feature.get-values <intro-instruction-set> : $(properties) ] ;
-  if "$(instruction-set)" != "unspecified" {
+  switch "$(instruction-set)" {
+  case "unspecified" :
+    # Do nothing.
+  case "native" :
     OPTIONS on $(targets) += "instruction-set=$(instruction-set)" ;
+    if [ is-icc "$(compiler)" ] {
+      OPTIONS on $(targets) += "cflags=-xHost" ;
+      OPTIONS on $(targets) += "linkflags=-xHost" ;
+    }
+  case "" :
+    errors.error "the value for `<instruction-set>' is empty" ;
+  case "*" :
+    errors.error "<instruction-set>$(instruction-set): unknown property" ;
+  }
+
+  local std = [ feature.get-values <std> : $(properties) ] ;
+  OPTIONS on $(targets) += "std=$(std)" ;
+  switch "$(std)" {
+  case "c++03" :
+    if [ is-gcc "$(compiler)" ] {
+      OPTIONS on $(targets) += "cxxflags='-std=c++03'" ;
+    }
+    else if [ is-clang "$(compiler)" ] {
+      OPTIONS on $(targets) += "cxxflags='-std=c++03'" ;
+    }
+    else if [ is-icc "$(compiler)" ] {
+      OPTIONS on $(targets) += "cxxflags='-strict-ansi -fno-math-errno'" ;
+    }
+    else {
+      errors.error "unknown compiler" ;
+    }
+  case "c++11" :
+    if [ is-gcc "$(compiler)" ] {
+      OPTIONS on $(targets) += "cxxflags='-std=c++0x'" ;
+    }
+    else if [ is-clang "$(compiler)" ] {
+      OPTIONS on $(targets) += "cxxflags='-std=c++11'" ;
+    }
+    else if [ is-icc "$(compiler)" ] {
+      OPTIONS on $(targets) += "cxxflags='-std=c++11'" ;
+    }
+    else {
+      errors.error "unknown compiler" ;
+    }
+  case "" :
+    errors.error "the value for `<std>' is empty" ;
+  case "*" :
+    errors.error "<std>$(std): unknown property" ;
   }
 
   local lto = [ feature.get-values <lto> : $(properties) ] ;
   OPTIONS on $(targets) += "lto=$(lto)" ;
   if "$(lto)" = "on" {
-    switch "$(toolset)" {
-    case "gcc" :
+    if [ is-gcc "$(compiler)" ] {
       OPTIONS on $(targets) += "cflags='-flto'" ;
       OPTIONS on $(targets) += "linkflags='-flto'" ;
-    case "clang" :
+    }
+    else if [ is-clang "$(compiler)" ] {
       OPTIONS on $(targets) += "cflags='-flto'" ;
       OPTIONS on $(targets) += "linkflags='-flto'" ;
-    case "icc" :
+    }
+    else if [ is-icc "$(compiler)" ] {
       OPTIONS on $(targets) += "cflags='-ipo'" ;
       OPTIONS on $(targets) += "linkflags='-ipo'" ;
-    case "*" :
-      errors.error "an internal error." ;
+    }
+    else {
+      errors.error "unknown compiler" ;
     }
 
     switch "$(variant)" {
@@ -192,76 +272,172 @@ rule install ( targets * : sources * : properties * )
       OPTIONS on $(targets) += "linkflags='-O3'" ;
     case "profile" :
       OPTIONS on $(targets) += "linkflags='-O3'" ;
+    case "" :
+      errors.error "the value for `<variant>' is empty" ;
     case "*" :
-      errors.error "an internal error." ;
+      errors.error "<variant>$(variant): unknown property" ;
     }
   }
 
   local memory-checker = [ feature.get-values <memory-checker> : $(properties) ] ;
   OPTIONS on $(targets) += "memory-checker=$(memory-checker)" ;
-  if "$(memory-checker)" = "on" {
-    switch "$(toolset)" {
-    case "gcc" :
+  switch "$(memory-checker)" {
+  case "off" :
+    # Do nothing.
+  case "on" :
+    if [ is-gcc "$(compiler)" ] {
       OPTIONS on $(targets) += "cflags='-fsanitize=address'" ;
       OPTIONS on $(targets) += "linkflags='-fsanitize=address'" ;
-    case "clang" :
-      OPTIONS on $(targets) += "cflags='-faddress-sanitizer'" ;
-      OPTIONS on $(targets) += "linkflags='-faddress-sanitizer'" ;
-    case "icc" :
-      OPTIONS on $(targets) += "cflags='-ftrapuv -check-pointers=rw -check-pointers-dangling=all -check-pointers-undimensioned'" ;
-      OPTIONS on $(targets) += "linkflags='-ftrapuv -check-pointers=rw -check-pointers-dangling=all -check-pointers-undimensioned'" ;
-    case "*" :
-      errors.error "an internal error." ;
     }
+    else if [ is-clang "$(compiler)" ] {
+      OPTIONS on $(targets) += "cflags='-fsanitize=address'" ;
+      OPTIONS on $(targets) += "linkflags='-fsanitize=address'" ;
+    }
+    else if [ is-icc "$(compiler)" ] {
+      OPTIONS on $(targets) += "cflags='-fp-speculation safe -ftrapuv -check-pointers=rw -check-pointers-dangling=all -check-pointers-undimensioned'" ;
+      OPTIONS on $(targets) += "linkflags='-fp-speculation safe -ftrapuv -check-pointers=rw -check-pointers-dangling=all -check-pointers-undimensioned'" ;
+    }
+    else {
+      errors.error "unknown compiler" ;
+    }
+  case "" :
+    errors.error "the value for `<memory-checker>' is empty" ;
+  case "*" :
+    errors.error "<memory-checker>$(memory-checker): unknown property" ;
   }
 
   local libstdcxx-debug-mode = [ feature.get-values <libstdc++-debug-mode> : $(properties) ] ;
   OPTIONS on $(targets) += "libstdc++-debug-mode=$(libstdcxx-debug-mode)" ;
 
-  # The following options are necessary for Boost.Regex to guess ICU4C location.
-  OPTIONS on $(targets) += "include='$(includedir-native)'" ;
-  OPTIONS on $(targets) += "library-path='$(libdir-native)'" ;
-
-  OPTIONS on $(targets) += "dll-path='$(libdir-native)'" ;
-
-  OPTIONS on $(targets) += "install" ;
-
-  # FIXME: Are `CPATH' and `LIBRARY_PATH' necessary despite explicitly specified `include' and `library-path'?
   local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  local logfile = [ get-logfile-path "boost" : "$(PREFIX)" : $(properties) ] ;
+  local logfile-native = [ path.native "$(logfile)" ] ;
+  LOGFILE on $(targets) = "$(logfile-native)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "$(logfile)" ] ;
 }
 actions install
 {
-  $(PROPERTY_DUMP_COMMANDS)
+  exit_with_error ()
+  {
+    echo "`LANG=C date`:ERROR: $1 (Boost $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "ERROR: $1 (Boost $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+    exit 1
+  }
+
+  mkdir -p `dirname '$(LOGFILE)'`
+  echo "`LANG=C date`:INFO: initiation of Boost build process" | tee '$(LOGFILE)' >> '$(STREAM)'
+
+$(ENVIRONMENT_COMMANDS)
+
+$(PROPERTY_DUMP_COMMANDS)
 
   if [ ! -x '$(BOOST_ROOT)/b2' ]; then
-    echo    "ERROR: Boost $(VERSION) not found ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: Boost $(VERSION) not found ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+    exit_with_error "\`$(BOOST_ROOT)/b2' is not found"
   fi
 
-  $(ENVIRONMENT_COMMANDS)
-
-  if [ -n '$(STREAM)' ]; then
-    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) $(OPTIONS) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) $(OPTIONS) )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to build Boost $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to build Boost $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: ./b2 -d+2 -j$(CONCURRENCY) $(ADDITIONAL_BUILD_OPTS:J= ) $(OPTIONS:J= ) stage" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(BOOST_ROOT)' && ./b2 -d+2 -j$(CONCURRENCY) $(ADDITIONAL_BUILD_OPTS) $(OPTIONS) stage >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error 'failed to build'
   fi
 
-  [ -f '$(<)' ] || exit 1
+  if [ '$(LINK)' = 'shared' ]; then
+    rm '$(FULL_PREFIX)/lib/libboost_test_exec_monitor.a' || exit_with_error "$(FULL_PREFIX)/lib/libboost_test_exec_monitor.a: could not delete"
+  fi
+
+  # Because some Boost test cases hang up on some environments, resource for
+  # processes shoud be limited in order for the processes to terminate in a
+  # reasonable length of time.
+  ulimit -St 1200
+  ulimit -Sm 2097152
+  # Because many Boost test cases crash, core files should be prevented from
+  # occupying large portion of disk space.
+  ulimit -Sc 0
+
+  get_clamped_concurrency ()
+  {
+    concurrency=$1
+    memory_per_concurrency=$2
+    if [ ! -f '/proc/meminfo' ]; then
+      exit 1
+    fi
+    mem=`grep -Eo '^MemFree:[[:space:]]+[[:digit:]]+[[:space:]]+kB' '/proc/meminfo'`
+    if [ $? -ne 0 ]; then
+      exit 1
+    fi
+    mem=`echo $mem | grep -Eo '[[:digit:]]+'`
+    con=`expr $mem / $memory_per_concurrency`
+    if [ $con -lt $concurrency ]; then
+      if [ $con -gt 0 ]; then
+        concurrency=$con
+      else
+        concurrency=1
+      fi
+    fi
+    return $concurrency
+  }
+
+  for i in '$(BOOST_ROOT)'/libs/*/test; do
+    libname=`echo -n "$i" | sed -e 's@$(BOOST_ROOT)/libs/\([^/]\{1,\}\)/test@\1@'`
+    if [ "$libname" = 'detail' ]; then
+      :
+    elif [ '$(LINK)' = 'shared' -a "$libname" = 'exception' ]; then
+      :
+    elif [ '$(THREADING)' = 'single' -a \( "$libname" = 'locale' -o "$libname" = 'thread' -o "$libname" = 'wave' \) ]; then
+      :
+    else
+      [ -d "$(BOOST_ROOT)/libs/$libname/test" ] || exit_with_error "\`$(BOOST_ROOT)/libs/$libname/test' is not a directory"
+      testdir="$(BOOST_ROOT)/libs/$libname/test"
+      if [ -f "$testdir/Jamfile.v2" -o -f "$testdir/Jamfile" ]; then
+        if [ -n '$(CONCURRENCY)' ]; then
+          concurrency=$(CONCURRENCY)
+        else
+          concurrency=1
+        fi
+        if [ "$libname" = 'multiprecision' ]; then
+          memory_per_concurrency=2097152
+        elif [ "$libname" = 'geometry' -o "$libname" = 'graph_parallel' -o "$libname" = 'intrusive' -o "$libname" = 'msm' -o "$libname" = 'range' -o "$libname" = 'spirit' -o "$libname" = 'xpressive' ]; then
+          memory_per_concurrency=1048576
+        else
+          memory_per_concurrency=524288
+        fi
+        get_clamped_concurrency $concurrency $memory_per_concurrency
+        concurrency=$?
+        logfile="`dirname '$(LOGFILE)'`/boost_$libname.txt"
+        echo "`LANG=C date`:INFO: initiation of tests for \`boost::$libname'" | tee "$logfile" >> '$(STREAM)'
+        echo "`LANG=C date`:INFO: concurrency=$concurrency" | tee -a "$logfile" >> '$(STREAM)'
+        echo "`LANG=C date`:COMMAND: cd \"$testdir\" && ../../../b2 -d+2 -j$concurrency $(OPTIONS:J= )" | tee -a "$logfile" >> '$(STREAM)'
+        tail --follow --lines=0 --sleep-interval=0.1 "$logfile" >> '$(STREAM)' &
+        ( cd "$testdir" && ../../../b2 -d+2 -j$concurrency $(OPTIONS) >> "$logfile" 2>&1 )
+        result=$?
+        kill -TERM $!
+        if [ $result -eq 0 ]; then
+          echo "`LANG=C date`:INFO: successful completion of tests for \`boost::$libname'" | tee -a "$logfile" >> '$(STREAM)'
+        else
+          echo "`LANG=C date`:ERROR: failed to test \`boost::$libname' (Boost $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a "$logfile" >> '$(STREAM)'
+          echo -n "ERROR: failed to test \`boost::$libname' (Boost $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+        fi
+      fi
+    fi
+  done
+
+  # Clean up `bin.v2' directory.
+  ( cd '$(BOOST_ROOT)' && rm -rf 'bin.v2' ) || exit_with_error "failed to clean up \`bin.v2' directory"
+
+  touch '$(<)' || exit_with_error 'failed to update the build target'
 
   echo -n "Boost $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built." | $(AWACS)
+  echo "`LANG=C date`:INFO: successful completion of Boost build process" | tee -a '$(LOGFILE)' >> '$(STREAM)'
   exit 0
 }
 
 
 
-alias install : version.hpp ;
+alias install : boost.stage ;
 explicit install ;
diff --git a/gmp/jamfile b/gmp/jamfile
--- a/gmp/jamfile
+++ b/gmp/jamfile
@@ -10,15 +10,14 @@ import "$(INTRO_ROOT_DIR)/compilers"
     is-clang
     is-icc
     get-compiler-description
-    get-compiler-prefix
-    get-libdir
-    get-includedir
+    get-full-prefix
     get-triplets
     get-cc
     get-cflags
     get-cxx
     get-cxxflags
     get-environment-commands
+    get-logfile-path
     get-property-dump-commands
   ;
 
@@ -60,11 +59,11 @@ rule download ( targets * : sources * : properties * )
   VERSION on $(targets) = "$(version)" ;
   URL on $(targets) = http://ftp.tsukuba.wide.ad.jp/software/gmp/gmp-$(version).tar.bz2 ;
   #URL on $(targets) = http://core.ring.gr.jp/pub/GNU/gmp/gmp-$(version).tar.bz2 ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions download
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<)' || exit 1
   if [ -n '$(STREAM)' ]; then
@@ -104,11 +103,11 @@ rule expand ( targets * : sources * : properties * )
 {
   local version = [ feature.get-values <gmp-hidden> : $(properties) ] ;
   VERSION on $(targets) = "$(version)" ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions expand
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<:D)' || exit 1
   [ -f '$(>)' ] || exit 1
@@ -147,7 +146,8 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local includedir = "$(full-prefix)/include" ;
   return "<location>$(includedir)" ;
 }
 
@@ -177,6 +177,7 @@ rule make-install ( targets * : sources * : properties * )
   local srcdir = "$(INTRO_ROOT_DIR)/gmp-$(version)" ;
   SRCDIR on $(targets) = [ path.native "$(srcdir)" ] ;
 
+  # Set the path to objdir.
   local objdir = "$(INTRO_ROOT_DIR)/objdir" ;
   local objdir-native = [ path.native "$(objdir)" ] ;
   OBJDIR on $(targets) = "$(objdir-native)" ;
@@ -184,21 +185,9 @@ rule make-install ( targets * : sources * : properties * )
   OPTIONS on $(targets) = ;
 
   # Set `--prefix' option for `configure' script.
-  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
-  local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
-  COMPILER_PREFIX on $(targets) += "$(compiler-prefix-native)" ;
-  OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
-
-  # Set `--libdir' option for `configure' script.
-  local libdir = [ get-libdir "$(PREFIX)" : $(properties) ] ;
-  local libdir-native = [ path.native "$(libdir)" ] ;
-  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
-
-  # Set `--includedir' option for `configure' script.
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
-  local includedir-native = [ path.native "$(includedir)" ] ;
-  INCLUDEDIR on $(targets) = "$(includedir-native)" ;
-  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local full-prefix-native = [ path.native "$(full-prefix)" ] ;
+  OPTIONS on $(targets) += "--prefix='$(full-prefix-native)'" ;
 
   # Set `--build' and `--host' options for `configure' script.
   local triplets = [ get-triplets $(properties) ] ;
@@ -210,37 +199,35 @@ rule make-install ( targets * : sources * : properties * )
   OPTIONS on $(targets) += "--host=$(host-triplet)" ;
 
   local variant = [ feature.get-values <variant> : $(properties) ] ;
-  if "$(variant)" = "debug" {
+  switch "$(variant)" {
+  case "debug" :
     OPTIONS on $(targets) += "--enable-assert" ;
-  }
-
-  if "$(variant)" = "profile" {
+  case "release" :
+    # Do nothing.
+  case "profile" :
     OPTIONS on $(targets) += "--enable-profiling=gprof" ;
+  case "" :
+    errors.error "the value for `<variant>' is empty" ;
+  case "*" :
+    errors.error "<variant>$(variant): unknown property" ;
   }
 
   OPTIONS on $(targets) += "--enable-cxx" ;
 
-  local memory-checker = [ feature.get-values <memory-checker> : $(properties) ] ;
-  local mudflap ;
-  if [ is-gcc "$(compiler)" ] && "$(memory-checker)" = "on" {
-    mudflap = "on" ;
-  }
-
   # Set the link variants for `configure' script.
-  if "$(mudflap)" = "on" {
+  local link = [ feature.get-values <link> : $(properties) ] ;
+  switch "$(link)" {
+  case "shared" :
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--disable-static" ;
+  case "static" :
     OPTIONS on $(targets) += "--disable-shared" ;
     OPTIONS on $(targets) += "--enable-static" ;
     OPTIONS on $(targets) += "--without-pic" ;
-  }
-  else {
-    if "$(host-triplet)" = "x86_64-w64-mingw32" || "$(host-triplet)" = "i686-w64-mingw32" || "$(host-triplet)" = "i686-pc-cygwin" {
-      OPTIONS on $(targets) += "--enable-shared" ;
-      OPTIONS on $(targets) += "--disable-static" ;
-    }
-    else {
-      OPTIONS on $(targets) += "--enable-shared" ;
-      OPTIONS on $(targets) += "--enable-static" ;
-    }
+  case "" :
+    errors.error "the value for `<link>' is empty" ;
+  case "*" :
+    errors.error "<link>$(link): unknown property" ;
   }
 
   local cc = [ get-cc "$(PREFIX)" : $(properties) ] ;
@@ -268,98 +255,92 @@ rule make-install ( targets * : sources * : properties * )
   local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  local logfile = [ get-logfile-path "gmp" : "$(PREFIX)" : $(properties) ] ;
+  local logfile-native = [ path.native "$(logfile)" ] ;
+  LOGFILE on $(targets) = "$(logfile-native)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "$(logfile)" ] ;
 }
 actions make-install
 {
-  $(PROPERTY_DUMP_COMMANDS)
+  exit_with_error ()
+  {
+    echo "`LANG=C date`:ERROR: $1 (GMP $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "ERROR: $1 (GMP $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+    exit 1
+  }
+
+  echo "`LANG=C date`:INFO: initiation of GMP build process" | tee '$(LOGFILE)' >> '$(STREAM)'
+
+$(ENVIRONMENT_COMMANDS)
+
+$(PROPERTY_DUMP_COMMANDS)
 
   # Restore the hacked configure script. See also `../gcc/jamfile'.
   if [ -e '$(SRCDIR)/real-configure' ]; then
-    [ ! -x '$(SRCDIR)/real-configure' ] && exit 1
-    mv -f '$(SRCDIR)/real-configure' '$(SRCDIR)/configure' || exit 1
+    [ -x '$(SRCDIR)/real-configure' ] || exit_with_error 'failed to restore the hacked script'
+    mv -f '$(SRCDIR)/real-configure' '$(SRCDIR)/configure' || exit_with_error 'failed to restore the hacked script'
   fi
 
-  [ -x '$(SRCDIR)/configure' ] || exit 1
-  [ -x '$(SRCDIR)/config.sub' ] || exit 1
-  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
-  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
+  [ -x '$(SRCDIR)/configure' ] || exit_with_error "\`$(SRCDIR)/configure' is not executable"
+  [ -x '$(SRCDIR)/config.sub' ] || exit_with_error "\`$(SRCDIR)/config.sub' is not executable"
+  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit_with_error "\`--build=$(BUILD_TRIPLET)' is not supported"
+  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit_with_error "\`--host=$(HOST_TRIPLET)' is not supported"
 
   # Clean up objdir `$(OBJDIR)'.
-  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
+  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit_with_error 'failed to clean up the old objdir'
 
-  $(ENVIRONMENT_COMMANDS)
+  echo "`LANG=C date`:INFO: @cflags: $(CFLAGS)" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  echo "`LANG=C date`:INFO: @cxxflags: $(CXXFLAGS)" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  ( cd '$(OBJDIR)' && echo -n '$(CFLAGS)' > cflags ) || exit_with_error 'failed to create @cflags'
+  ( cd '$(OBJDIR)' && echo -n '$(CXXFLAGS)' > cxxflags ) || exit_with_error 'failed to create @cxxflags'
 
-  ( cd '$(OBJDIR)' && echo -n '$(CFLAGS)' > cflags ) || exit 1
-  ( cd '$(OBJDIR)' && echo -n '$(CXXFLAGS)' > cxxflags ) || exit 1
-
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`configure' GMP $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`configure' GMP $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: ./configure $(OPTIONS:J= )" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`configure'"
   fi
 
   # Check the creation of `Makefile'.
-  [ -f '$(OBJDIR)/Makefile' ] || exit 1
+  [ -f '$(OBJDIR)/Makefile' ] || exit_with_error "failed to confirm the creation of \`Makefile'"
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make' GMP $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make' GMP $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make check' GMP $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make check' GMP $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make check" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make check'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make install >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make install )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make install' GMP $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make install' GMP $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make install" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make install >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make install'"
   fi
 
   # Clean up objdir `$(OBJDIR)'.
-  rm -rf '$(OBJDIR)' || exit 1
+  rm -rf '$(OBJDIR)' || exit_with_error 'failed to clean up the objdir'
 
-  # `gmp.h' is deployed to `(COMPILER_PREFIX)/include' even if `--includedir' is
-  # explicitly specified. So, hack is needed to deploy `gmp.h' to
-  # `(INCLUDEDIR)/gmp.h'.
-  # See also http://gmplib.org/list-archives/gmp-bugs/2009-March/001333.html.
-  if [ '$(INCLUDEDIR)' != '$(COMPILER_PREFIX)/include' ]; then
-    mv -f '$(COMPILER_PREFIX)/include/gmp.h' '$(INCLUDEDIR)'
-    if [ $? -ne 0 ]; then
-      echo    "ERROR: failed to install \`gmp.h' to \`$(INCLUDEDIR)' for GMP $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-      echo -n "ERROR: failed to install \`gmp.h' to \`$(INCLUDEDIR)' for GMP $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-      rm -f '$(COMPILER_PREFIX)/include/gmp.h'
-      exit 1
-    fi
-  fi
-
-  [ -f '$(<)' ] || exit 1
+  [ -f '$(<)' ] || exit_with_error 'failed to confirm the creation of the build target'
 
   echo -n 'GMP $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
+  echo "`LANG=C date`:INFO: successful completion of GMP build process" | tee -a '$(LOGFILE)' >> '$(STREAM)'
   exit 0
 }
 
diff --git a/icc/jamfile b/icc/jamfile
--- a/icc/jamfile
+++ b/icc/jamfile
@@ -4,9 +4,13 @@ import alias ;
 import errors ;
 import feature ;
 import make ;
+import path ;
 import "$(INTRO_ROOT_DIR)/compilers"
   : is-icc
+    get-backend-gcc
+    get-compiler-description
     get-frontend-version
+    get-compiler-prefix
     get-default-bindir
     get-property-dump-commands
   ;
@@ -47,46 +51,59 @@ explicit icpc-wrapper ;
 
 rule make-install ( targets * : sources * : properties * )
 {
-  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
+  local compiler = [ feature.get-values "<compiler>" : $(properties) ] ;
+  local backend-gcc = [ get-backend-gcc "$(compiler)" ] ;
+  local compiler-description = [ get-compiler-description "$(backend-gcc)" ] ;
+  COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
+
   local version = [ get-frontend-version "$(compiler)" ] ;
   VERSION on $(targets) = "$(version)" ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
+  local logfile = "$(compiler-prefix)/icc.txt" ;
+  local logfile-native = [ path.native "$(logfile)" ] ;
+  LOGFILE on $(targets) = "$(logfile-native)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "$(logfile)" ] ;
 }
 actions make-install
 {
-  $(PROPERTY_DUMP_COMMANDS)
+  exit_with_error ()
+  {
+    echo "`LANG=C date`:ERROR: $1 (ICC $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "ERROR: $1 (ICC $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+    exit 1
+  }
+
+  mkdir -p `dirname '$(LOGFILE)'`
+  echo "`LANG=C date`:INFO: initiation of ICC wrappers installation process" | tee '$(LOGFILE)' >> '$(STREAM)'
+
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -f '$(<:D)/icc-wrapper'
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to remove old \`$(<:D)/icc-wrapper'." 1>&2
-    echo -n "ERROR: failed to remove old \`$(<:D)/icc-wrapper'." | $(AWACS)
-    exit 1
+    exit_with_error "failed to remove old \`$(<:D)/icc-wrapper'"
   fi
 
   rm -f '$(<:D)/icpc-wrapper'
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to remove old \`$(<:D)/icpc-wrapper'." 1>&2
-    echo -n "ERROR: failed to remove old \`$(<:D)/icpc-wrapper'." | $(AWACS)
-    exit 1
+    exit_with_error "failed to remove old \`$(<:D)/icpc-wrapper'"
   fi
 
   install --mode=755 '$(INTRO_ROOT_DIR)/template/x86_64-unknown-linux-gnu/icc-wrapper' '$(<:D)'
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to install \`icc-wrapper' to \`$(<:D)'." 1>&2
-    echo -n "ERROR: failed to install \`icc-wrapper' to \`$(<:D)'." | $(AWACS)
-    exit 1
+    exit_with_error "failed to install \`icc-wrapper' to \`$(<:D)'"
   fi
 
   install --mode=755 '$(INTRO_ROOT_DIR)/template/x86_64-unknown-linux-gnu/icpc-wrapper' '$(<:D)'
   if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to install \`icpc-wrapper' to \`$(<:D)'." 1>&2
-    echo -n "ERROR: failed to install \`icpc-wrapper' to \`$(<:D)'." | $(AWACS)
-    exit 1
+    exit_with_error "failed to install \`icpc-wrapper' to \`$(<:D)'"
   fi
 
-  [ -f '$(<)' ] || exit 1
+  [ -f '$(<)' ] || exit_with_error 'failed to confirm the creation of the build target'
 
   echo -n 'Wrapper scripts for ICC $(VERSION) were successfully installed.' | $(AWACS)
+  echo "`LANG=C date`:INFO: successful completion of ICC wrappers installation process" | tee -a '$(LOGFILE)' >> '$(STREAM)'
   exit 0
 }
 
diff --git a/icu4c/jamfile b/icu4c/jamfile
--- a/icu4c/jamfile
+++ b/icu4c/jamfile
@@ -11,16 +11,14 @@ import "$(INTRO_ROOT_DIR)/compilers"
     is-clang
     is-icc
     get-compiler-description
-    get-compiler-prefix
-    get-bindir
-    get-libdir
-    get-includedir
+    get-full-prefix
     get-triplets
     get-cc
     get-cflags
     get-cxx
     get-cxxflags
     get-environment-commands
+    get-logfile-path
     get-property-dump-commands
   ;
 
@@ -63,11 +61,11 @@ rule download ( targets * : sources * : properties * )
   VERSION on $(targets) = "$(version)" ;
   local version-string = [ regex.replace "$(version)" "\\." "_" ] ;
   URL on $(targets) = http://download.icu-project.org/files/icu4c/$(version)/icu4c-$(version-string)-src.tgz ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions download
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<)' || exit 1
   if [ -n '$(STREAM)' ]; then
@@ -108,11 +106,11 @@ rule expand ( targets * : sources * : properties * )
 {
   local version = [ feature.get-values <icu4c-hidden> : $(properties) ] ;
   VERSION on $(targets) = "$(version)" ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions expand
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<:D)' || exit 1
   rm -rf '$(INTRO_ROOT_DIR)/icu' || exit 1
@@ -155,7 +153,8 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local includedir = "$(full-prefix)/include" ;
   return "<location>$(includedir)" ;
 }
 
@@ -175,7 +174,7 @@ explicit unicode/uchar.h ;
 rule make-install ( targets * : sources * : properties * )
 {
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local compiler-description = [ get-compiler-description $(compiler) ] ;
+  local compiler-description = [ get-compiler-description "$(compiler)" ] ;
   COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <icu4c> : $(properties) ] ;
@@ -185,6 +184,7 @@ rule make-install ( targets * : sources * : properties * )
   local srcdir = "$(INTRO_ROOT_DIR)/icu-$(version)" ;
   SRCDIR on $(targets) = [ path.native "$(srcdir)" ] ;
 
+  # Set the path to objdir.
   local objdir = "$(INTRO_ROOT_DIR)/objdir" ;
   local objdir-native = [ path.native "$(objdir)" ] ;
   OBJDIR on $(targets) = "$(objdir-native)" ;
@@ -201,6 +201,9 @@ rule make-install ( targets * : sources * : properties * )
   local triplets = [ get-triplets $(properties) ] ;
   local build-triplet = "$(triplets[1])" ;
   local host-triplet = "$(triplets[2])" ;
+  if "$(build-triplet)" = "x86_64-unknown-linux-gnu" && "$(host-triplet)" = "i686-pc-linux-gnu" {
+    build-triplet = "$(host-triplet)" ;
+  }
   BUILD_TRIPLET on $(targets) += "$(build-triplet)" ;
   HOST_TRIPLET on $(targets) += "$(host-triplet)" ;
 
@@ -226,24 +229,9 @@ rule make-install ( targets * : sources * : properties * )
   }
 
   # Set `--prefix' option for `configure' script.
-  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
-  local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
-  OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
-
-  # Set `--bindir' option for `configure' script.
-  local bindir = [ get-bindir "$(PREFIX)" : $(properties) ] ;
-  local bindir-native = [ path.native "$(bindir)" ] ;
-  OPTIONS on $(targets) += "--bindir='$(bindir-native)'" ;
-
-  # Set `--libdir' option for `configure' script.
-  local libdir = [ get-libdir "$(PREFIX)" : $(properties) ] ;
-  local libdir-native = [ path.native "$(libdir)" ] ;
-  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
-
-  # Set `--includedir' option for `configure' script.
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
-  local includedir-native = [ path.native "$(includedir)" ] ;
-  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local full-prefix-native = [ path.native "$(full-prefix)" ] ;
+  OPTIONS on $(targets) += "--prefix='$(full-prefix-native)'" ;
 
   # Set `--build' and `--host' options for `configure' script.
   OPTIONS on $(targets) += "--build=$(build-triplet)" ;
@@ -251,19 +239,19 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) += "--enable-strict" ;
 
-  OPTIONS on $(targets) += "--enable-shared" ;
-  OPTIONS on $(targets) += "--enable-static" ;
-
-  local threading = [ feature.get-values <threading> : $(properties) ] ;
-
-  if "$(threading)" = "single" {
-    OPTIONS on $(targets) += "--disable-threads" ;
-  }
-  else if "$(threading)" = "multi" {
-    OPTIONS on $(targets) += "--enable-threads" ;
-  }
-  else {
-    errors.error "an internal error." ;
+  # Set the link variants for `configure' script.
+  local link = [ feature.get-values <link> : $(properties) ] ;
+  switch "$(link)" {
+  case "shared" :
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--disable-static" ;
+  case "static" :
+    OPTIONS on $(targets) += "--disable-shared" ;
+    OPTIONS on $(targets) += "--enable-static" ;
+  case "" :
+    errors.error "the value for `<link>' is empty" ;
+  case "*" :
+    errors.error "<link>$(link): unknown property" ;
   }
 
   if "$(host-triplet)" = "x86_64-unknown-linux-gnu" || "$(host-triplet)" = "x86_64-w64-mingw32" {
@@ -307,89 +295,94 @@ rule make-install ( targets * : sources * : properties * )
   local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  local logfile = [ get-logfile-path "icu4c" : "$(PREFIX)" : $(properties) ] ;
+  local logfile-native = [ path.native "$(logfile)" ] ;
+  LOGFILE on $(targets) = "$(logfile-native)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "$(logfile)" ] ;
 }
 actions make-install
 {
-  $(PROPERTY_DUMP_COMMANDS)
+  exit_with_error ()
+  {
+    echo "`LANG=C date`:ERROR: $1 (ICU4C $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "ERROR: $1 (ICU4C $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+    exit 1
+  }
 
-  [ -x '$(SRCDIR)/source/runConfigureICU' ] || exit 1
-  chmod +x '$(SRCDIR)/source/config.sub' || exit 1
-  [ `'$(SRCDIR)/source/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
-  [ `'$(SRCDIR)/source/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
+  echo "`LANG=C date`:INFO: initiation of ICU4C build process" | tee '$(LOGFILE)' >> '$(STREAM)'
+
+$(ENVIRONMENT_COMMANDS)
+
+$(PROPERTY_DUMP_COMMANDS)
+
+  [ -x '$(SRCDIR)/source/runConfigureICU' ] || exit_with_error "\`$(SRCDIR)/source/runConfigureICU' is not executable"
+  chmod +x '$(SRCDIR)/source/config.sub' || exit_with_error "failed to make \`$(SRCDIR)/source/config.sub' executable"
+  [ `'$(SRCDIR)/source/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit_with_error "\`--build=$(BUILD_TRIPLET)' is not supported"
+  [ `'$(SRCDIR)/source/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit_with_error "\`--host=$(HOST_TRIPLET)' is not supported"
 
   # Clean up objdir `$(OBJDIR)'.
-  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
+  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit_with_error 'failed to clean up the old objdir'
 
-  $(ENVIRONMENT_COMMANDS)
+  echo "`LANG=C date`:INFO: @cflags: $(CFLAGS)" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  echo "`LANG=C date`:INFO: @cxxflags: $(CXXFLAGS)" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  ( cd '$(OBJDIR)' && echo -n '$(CFLAGS)' > cflags ) || exit_with_error 'failed to create @cflags'
+  ( cd '$(OBJDIR)' && echo -n '$(CXXFLAGS)' > cxxflags ) || exit_with_error 'failed to create @cxxflags'
 
-  ( cd '$(OBJDIR)' && echo -n '$(CFLAGS)' > cflags ) || exit 1
-  ( cd '$(OBJDIR)' && echo -n '$(CXXFLAGS)' > cxxflags ) || exit 1
-
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/source/runConfigureICU' $(OPTIONS) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/source/runConfigureICU' $(OPTIONS) )
-  fi
-  if [ $? -ne 0 ]; then
-    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR:$$: failed to \`runConfigureICU' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: source/runConfigureICU $(OPTIONS:J= )" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && '$(SRCDIR)/source/runConfigureICU' $(OPTIONS) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`runConfigureICU'"
   fi
 
   # Check the creation of `Makefile'.
-  [ -f '$(OBJDIR)/Makefile' ] || exit 1
+  [ -f '$(OBJDIR)/Makefile' ] || exit_with_error "failed to confirm the creation of \`Makefile'"
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
-  fi
-  if [ $? -ne 0 ]; then
-    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR:$$: failed to \`make' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    # `make check' of ICU4C does not support parallel build.
-    ( cd '$(OBJDIR)' && make check >> '$(STREAM)' 2>&1 )
-  else
-    # `make check' of ICU4C does not support parallel build.
-    ( cd '$(OBJDIR)' && make check )
-  fi
-  if [ $? -ne 0 ]; then
-    if uname | grep -Fq 'CYGWIN' && [ `echo $(VERSION) `x = 49.1.1x ]; then
-      echo    "WARNING: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-      echo -n "WARNING: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    else
-      mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-      echo    "ERROR:$$: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-      echo -n "ERROR:$$: failed to \`make check' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-      exit 1
-    fi
+  total_status=0
+
+  echo "`LANG=C date`:COMMAND: make check" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  # `make check' of ICU4C does not support parallel build.
+  ( cd '$(OBJDIR)' && make check >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    #exit_with_error "failed to \`make check'"
+    echo "`LANG=C date`:ERROR: failed to \`make check' (ICU4C $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "ERROR: failed to \`make check' (ICU4C $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+    total_status=1
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make install >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make install )
-  fi
-  if [ $? -ne 0 ]; then
-    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR:$$: failed to \`make install' ICU4C $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make install" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make install >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make install'"
   fi
 
-  # Clean up objdir `$(OBJDIR)'.
-  rm -rf '$(OBJDIR)' || exit 1
+  if [ $total_status -eq 0 ]; then
+    # Clean up objdir `$(OBJDIR)'.
+    rm -rf '$(OBJDIR)' || exit_with_error 'failed to clean up the objdir'
 
-  [ -f '$(<)' ] || exit 1
+    [ -f '$(<)' ] || exit_with_error 'failed to confirm the creation of the build target'
 
-  echo -n 'ICU4C $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
+    echo -n 'ICU4C $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
+    echo "`LANG=C date`:INFO: successful completion of ICU4C build process" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  fi
   exit 0
 }
 
diff --git a/isl/jamfile b/isl/jamfile
--- a/isl/jamfile
+++ b/isl/jamfile
@@ -10,15 +10,14 @@ import "$(INTRO_ROOT_DIR)/compilers"
     is-clang
     is-icc
     get-compiler-description
-    get-compiler-prefix
-    get-libdir
-    get-includedir
+    get-full-prefix
     get-triplets
     get-cc
     get-cflags
     get-cxx
     get-cxxflags
     get-environment-commands
+    get-logfile-path
     get-property-dump-commands
   ;
 
@@ -50,85 +49,42 @@ explicit compiler-dep ;
 
 
 for local version in $(ISL_VERSIONS) {
-  make "$(INTRO_ROOT_DIR)/isl-$(version).tar.bz2" : : @download ;
-  explicit "$(INTRO_ROOT_DIR)/isl-$(version).tar.bz2" ;
-}
-
-rule download ( targets * : sources * : properties * )
-{
-  local version = [ feature.get-values <isl-hidden> : $(properties) ] ;
-  VERSION on $(targets) = "$(version)" ;
-  URL on $(targets) = "ftp://ftp.linux.student.kuleuven.be/pub/people/skimo/isl/isl-$(version).tar.bz2" ;
-  #URL on $(targets) = "http://ftp.tsukuba.wide.ad.jp/software/gcc/infrastructure/isl-$(version).tar.bz2" ;
-  #URL on $(targets) = "http://www.ring.gr.jp/archives/lang/egcs/infrastructure/isl-$(version).tar.bz2" ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
-}
-actions download
-{
-  $(PROPERTY_DUMP_COMMANDS)
-
-  rm -rf '$(<)' || exit 1
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(<:D)' && wget -- '$(URL)' >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(<:D)' && wget --quiet -- '$(URL)' )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    'ERROR: failed to download isl $(VERSION) tarball.' 1>&2
-    echo -n 'ERROR: failed to download isl $(VERSION) tarball.' | $(AWACS)
-    rm -rf '$(<)'
-    exit 1
-  fi
-  [ -f '$(<)' ] || exit 1
-  exit 0
-}
-
-
-
-for local version in $(ISL_VERSIONS) {
-  # Use `ChangeLog' file as a target representing the completion of
-  # decompression action. It is suitable for the purpose because of the
-  # following reasons;
+  # Use `ChangeLog' file as a target representing the completion of export
+  # action. It is suitable for the purpose because of the following reasons;
   #
   #   - The name of this file is considered stable even if the version
   #     changes.
   #   - This file won't be modified during the build procedure.
   #
-  make "$(INTRO_ROOT_DIR)/isl-$(version)/ChangeLog"
-    : "$(INTRO_ROOT_DIR)/isl-$(version).tar.bz2"
-    : @expand
-    ;
+  make "$(INTRO_ROOT_DIR)/isl-$(version)/ChangeLog" : : @export ;
   explicit "$(INTRO_ROOT_DIR)/isl-$(version)/ChangeLog" ;
 }
 
-rule expand ( targets * : sources * : properties * )
+rule export ( targets * : sources * : properties * )
 {
   local version = [ feature.get-values <isl-hidden> : $(properties) ] ;
   VERSION on $(targets) = "$(version)" ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
-actions expand
+actions export
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<:D)' || exit 1
-  [ -f '$(>)' ] || exit 1
-  if [ -n '$(STREAM)' ]; then
-    tar xjvf '$(>)' --directory='$(INTRO_ROOT_DIR)' >> '$(STREAM)' 2>&1
-  else
-    tar xjf '$(>)' --directory='$(INTRO_ROOT_DIR)'
-  fi
+  ( cd '$(INTRO_ROOT_DIR)/isl-trunk' && git archive --prefix='isl-$(VERSION)/' 'isl-$(VERSION)' | tar -xv -C '$(INTRO_ROOT_DIR)' ) >> '$(STREAM)' 2>&1
   if [ $? -ne 0 ]; then
-    echo    'ERROR: failed to expand isl $(VERSION) tarball.' 1>&2
-    echo -n 'ERROR: failed to expand isl $(VERSION) tarball.' | $(AWACS)
+    echo    'ERROR: failed to export ISL $(VERSION) source tree.' 1>&2
+    echo -n 'ERROR: failed to export ISL $(VERSION) source tree.' | $(AWACS)
     rm -rf '$(<:D)'
     exit 1
   fi
-  # If the timestamp of the tarball's contents is restored, the modification
-  # time of the source directory could be older than the one of the tarball.
-  # Such behavior is not desirable because the decompression always happens.
-  # Therefore, `touch' is required.
-  touch --no-create '$(<)'
+  ( cd '$(INTRO_ROOT_DIR)/isl-$(VERSION)' && ./autogen.sh ) >> '$(STREAM)' 2>&1
+  if [ $? -ne 0 ]; then
+    echo    "ERROR: failed to execute \`$(INTRO_ROOT_DIR)/isl-$(VERSION)/autogen.sh'." 1>&2
+    echo -n "ERROR: failed to execute \`$(INTRO_ROOT_DIR)/isl-$(VERSION)/autogen.sh'." | $(AWACS)
+    rm -rf '$(<:D)'
+    exit 1
+  fi
   [ -f '$(<)' ] || exit 1
   exit 0
 }
@@ -148,7 +104,8 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local includedir = "$(full-prefix)/include" ;
   return "<location>$(includedir)" ;
 }
 
@@ -180,6 +137,7 @@ rule make-install ( targets * : sources * : properties * )
   local srcdir = "$(INTRO_ROOT_DIR)/isl-$(version)" ;
   SRCDIR on $(targets) = [ path.native "$(srcdir)" ] ;
 
+  # Set the path to objdir.
   local objdir = "$(INTRO_ROOT_DIR)/objdir" ;
   local objdir-native = [ path.native "$(objdir)" ] ;
   OBJDIR on $(targets) = "$(objdir-native)" ;
@@ -187,19 +145,9 @@ rule make-install ( targets * : sources * : properties * )
   OPTIONS on $(targets) = ;
 
   # Set `--prefix' option for `configure' script.
-  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
-  local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
-  OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
-
-  # Set `--libdir' option for `configure' script.
-  local libdir = [ get-libdir "$(PREFIX)" : $(properties) ] ;
-  local libdir-native = [ path.native "$(libdir)" ] ;
-  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
-
-  # Set `--includedir' option for `configure' script.
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
-  local includedir-native = [ path.native "$(includedir)" ] ;
-  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local full-prefix-native = [ path.native "$(full-prefix)" ] ;
+  OPTIONS on $(targets) += "--prefix='$(full-prefix-native)'" ;
 
   # Set `--build' and `--host' options for `configure' script.
   local triplets = [ get-triplets $(properties) ] ;
@@ -210,31 +158,29 @@ rule make-install ( targets * : sources * : properties * )
   OPTIONS on $(targets) += "--build=$(build-triplet)" ;
   OPTIONS on $(targets) += "--host=$(host-triplet)" ;
 
-  local memory-checker = [ feature.get-values <memory-checker> : $(properties) ] ;
-  local mudflap = "off" ;
-  if [ is-gcc "$(compiler)" ] && "$(memory-checker)" = "on" {
-    mudflap = "on" ;
-  }
-
   # Set the link variants for `configure' script.
-  if "$(mudflap)" = "on" {
-    # Mudflap does not seem to work with PIC.
+  local link = [ feature.get-values <link> : $(properties) ] ;
+  switch "$(link)" {
+  case "shared" :
+    OPTIONS on $(targets) += "--enable-shared" ;
+    OPTIONS on $(targets) += "--disable-static" ;
+  case "static" :
     OPTIONS on $(targets) += "--disable-shared" ;
     OPTIONS on $(targets) += "--enable-static" ;
     OPTIONS on $(targets) += "--without-pic" ;
-  }
-  else {
-    if "$(host-triplet)" = "x86_64-w64-mingw32" || "$(host-triplet)" = "i686-w64-mingw32" || "$(host-triplet)" = "i686-pc-cygwin" {
-      OPTIONS on $(targets) += "--enable-shared" ;
-      OPTIONS on $(targets) += "--disable-static" ;
-    }
-    else {
-      OPTIONS on $(targets) += "--enable-shared" ;
-      OPTIONS on $(targets) += "--enable-static" ;
-    }
+  case "" :
+    errors.error "the value for `<link>' is empty" ;
+  case "*" :
+    errors.error "<link>$(link): an unknown property" ;
   }
 
   OPTIONS on $(targets) += "--with-gmp=system" ;
+
+  # `--with-gmp-prefix` option is necessary for ISL to detect the correct
+  # location of GMP, even if `CPATH`, `LIBRARY_PATH` and `LD_LIBRARY_PATH`
+  # include the path to installed GMP headers and libraries. This seems due
+  # to old versions of `libtool`.
+  OPTIONS on $(targets) += "--with-gmp-prefix='$(full-prefix-native)'" ;
 
   # The following option does not work because Clang's ABI is unstable.
   #if [ is-clang "$(compiler)" ] {
@@ -301,88 +247,92 @@ rule make-install ( targets * : sources * : properties * )
   local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  local logfile = [ get-logfile-path "isl" : "$(PREFIX)" : $(properties) ] ;
+  local logfile-native = [ path.native "$(logfile)" ] ;
+  LOGFILE on $(targets) = "$(logfile-native)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "$(logfile)" ] ;
 }
 actions make-install
 {
-  $(PROPERTY_DUMP_COMMANDS)
+  exit_with_error ()
+  {
+    echo "`LANG=C date`:ERROR: $1 (ISL $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "ERROR: $1 (ISL $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+    exit 1
+  }
+
+  echo "`LANG=C date`:INFO: initiation of ISL build process" | tee '$(LOGFILE)' >> '$(STREAM)'
+
+$(ENVIRONMENT_COMMANDS)
+
+$(PROPERTY_DUMP_COMMANDS)
 
   # Restore the hacked configure script. See also `../gcc/jamfile'.
   if [ -e '$(SRCDIR)/real-configure' ]; then
-    [ ! -x '$(SRCDIR)/real-configure' ] && exit 1
-    mv -f '$(SRCDIR)/real-configure' '$(SRCDIR)/configure' || exit 1
+    [ -x '$(SRCDIR)/real-configure' ] || exit_with_error 'failed to restore the hacked script'
+    mv -f '$(SRCDIR)/real-configure' '$(SRCDIR)/configure' || exit_with_error 'failed to restore the hacked script'
   fi
 
-  [ -x '$(SRCDIR)/configure' ] || exit 1
-  [ -x '$(SRCDIR)/config.sub' ] || exit 1
-  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
-  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
+  [ -x '$(SRCDIR)/configure' ] || exit_with_error "\`$(SRCDIR)/configure' is not executable"
+  [ -x '$(SRCDIR)/config.sub' ] || exit_with_error "\`$(SRCDIR)/config.sub' is not executable"
+  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit_with_error "\`--build=$(BUILD_TRIPLET)' is not supported"
+  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit_with_error "\`--host=$(HOST_TRIPLET)' is not supported"
 
   # Clean up objdir `$(OBJDIR)'.
-  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
+  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit_with_error 'failed to clean up the old objdir'
 
-  $(ENVIRONMENT_COMMANDS)
+  echo "`LANG=C date`:INFO: @cflags: $(CFLAGS)" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  echo "`LANG=C date`:INFO: @cxxflags: $(CXXFLAGS)" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  ( cd '$(OBJDIR)' && echo -n '$(CFLAGS)' > cflags ) || exit_with_error 'failed to create @cflags'
+  ( cd '$(OBJDIR)' && echo -n '$(CXXFLAGS)' > cxxflags ) || exit_with_error 'failed to create @cxxflags'
 
-  ( cd '$(OBJDIR)' && echo -n '$(CFLAGS)' > cflags ) || exit 1
-  ( cd '$(OBJDIR)' && echo -n '$(CXXFLAGS)' > cxxflags ) || exit 1
-
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) )
-  fi
-  if [ $? -ne 0 ]; then
-    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`configure' isl $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR:$$: failed to \`configure' isl $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: ./configure $(OPTIONS:J= )" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`configure'"
   fi
 
   # Check the creation of `Makefile'.
-  [ -f '$(OBJDIR)/Makefile' ] || exit 1
+  [ -f '$(OBJDIR)/Makefile' ] || exit_with_error "failed to confirm the creation of \`Makefile'"
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
-  fi
-  if [ $? -ne 0 ]; then
-    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`make' isl $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR:$$: failed to \`make' isl $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check )
-  fi
-  if [ $? -ne 0 ]; then
-    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`make check' isl $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR:$$: failed to \`make check' isl $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make check" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make check'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make install >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make install )
-  fi
-  if [ $? -ne 0 ]; then
-    mv '$(OBJDIR)' "$(INTRO_ROOT_DIR)/objdir_$$"
-    echo    "ERROR:$$: failed to \`make install' isl $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR:$$: failed to \`make install' isl $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make install" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make install >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make install'"
   fi
 
   # Clean up objdir `$(OBJDIR)'.
-  rm -rf '$(OBJDIR)' || exit 1
+  rm -rf '$(OBJDIR)' || exit_with_error 'failed to clean up the objdir'
 
-  [ -f '$(<)' ] || exit 1
+  [ -f '$(<)' ] || exit_with_error 'failed to confirm the creation of the build target'
 
-  echo -n 'isl $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
+  echo -n 'ISL $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
+  echo "`LANG=C date`:INFO: successful completion of ISL build process" | tee -a '$(LOGFILE)' >> '$(STREAM)'
   exit 0
 }
 
diff --git a/openmpi/jamfile b/openmpi/jamfile
--- a/openmpi/jamfile
+++ b/openmpi/jamfile
@@ -12,14 +12,9 @@ import "$(INTRO_ROOT_DIR)/compilers"
     is-icc
     get-compiler-description
     get-compiler-prefix
-    get-default-bindir
-    get-default-libdir
-    get-default-includedir
     get-triplets
     get-cc
-    get-cflags
     get-cxx
-    get-cxxflags
     get-environment-commands
     get-property-dump-commands
   ;
@@ -60,11 +55,11 @@ rule download ( targets * : sources * : properties * )
   VERSION on $(targets) = "$(version)" ;
   local minor = [ regex.match "^([0-9]+\\.[0-9]+)(\\.[0-9]+)?$" : "$(version)" : 1 ] ;
   URL on $(targets) = http://www.open-mpi.org/software/ompi/v$(minor)/downloads/openmpi-$(version).tar.bz2 ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions download
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<)' || exit 1
   if [ -n '$(STREAM)' ]; then
@@ -102,11 +97,11 @@ rule expand ( targets * : sources * : properties * )
 {
   local version = [ feature.get-values <openmpi-hidden> : $(properties) ] ;
   VERSION on $(targets) = "$(version)" ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions expand
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<:D)' || exit 1
   [ -f '$(>)' ] || exit 1
@@ -145,7 +140,19 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-default-includedir "$(PREFIX)" : $(properties) ] ;
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
+  local address-model = [ feature.get-values "<intro-address-model>" : $(properties) ] ;
+  local includedir ;
+  switch "$(address-model)" {
+  case "64" :
+    includedir = "$(compiler-prefix)/address-model-64/include" ;
+  case "32" :
+    includedir = "$(compiler-prefix)/address-model-32/include" ;
+  case "" :
+    errors.error "the value for `<intro-address-model>' is empty" ;
+  case "*" :
+    errors.error "`<intro-address-model>$(address-model)': unknown property" ;
+  }
   return "<location>$(includedir)" ;
 }
 
@@ -175,30 +182,20 @@ rule make-install ( targets * : sources * : properties * )
   local srcdir = "$(INTRO_ROOT_DIR)/openmpi-$(version)" ;
   SRCDIR on $(targets) = [ path.native "$(srcdir)" ] ;
 
+  # Set the path to objdir.
   local objdir = "$(INTRO_ROOT_DIR)/objdir" ;
-  OBJDIR on $(targets) = [ path.native "$(objdir)" ] ;
+  local objdir-native = [ path.native "$(objdir)" ] ;
+  OBJDIR on $(targets) = "$(objdir-native)" ;
 
   OPTIONS on $(targets) = ;
 
-  # Set `--prefix' option for `configure' script.
   local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
-  local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
-  OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
 
-  # Set `--bindir' option for `configure' script.
-  local bindir = [ get-default-bindir "$(PREFIX)" : $(properties) ] ;
-  local bindir-native = [ path.native "$(bindir)" ] ;
-  OPTIONS on $(targets) += "--bindir='$(bindir-native)'" ;
+  local address-model = [ feature.get-values "<intro-address-model>" : $(properties) ] ;
 
-  # Set `--libdir' option for `configure' script.
-  local libdir = [ get-default-libdir "$(PREFIX)" : $(properties) ] ;
-  local libdir-native = [ path.native "$(libdir)" ] ;
-  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
-
-  # Set `--includedir' option for `configure' script.
-  local includedir = [ get-default-includedir "$(PREFIX)" : $(properties) ] ;
-  local includedir-native = [ path.native "$(includedir)" ] ;
-  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
+  local openmpi-prefix = "$(compiler-prefix)/address-model-$(address-model)" ;
+  local openmpi-prefix-native = [ path.native "$(openmpi-prefix)" ] ;
+  OPTIONS on $(targets) += "--prefix='$(openmpi-prefix-native)'" ;
 
   # Set `--build' and `--host' options for `configure' script.
   local triplets = [ get-triplets $(properties) ] ;
@@ -209,14 +206,24 @@ rule make-install ( targets * : sources * : properties * )
   OPTIONS on $(targets) += "--build=$(build-triplet)" ;
   OPTIONS on $(targets) += "--host=$(host-triplet)" ;
 
+  local variant = [ feature.get-values <variant> : $(properties) ] ;
+  if "$(variant)" != "release" {
+    errors.error "an internal error" ;
+  }
+
   OPTIONS on $(targets) += "--disable-mpi-f77" ;
   OPTIONS on $(targets) += "--disable-mpi-f90" ;
   OPTIONS on $(targets) += "--disable-mpi-cxx" ;
 
-  OPTIONS on $(targets) += "--enable-shared" ;
-  OPTIONS on $(targets) += "--enable-static" ;
+  local link = [ feature.get-values <link> : $(properties) ] ;
+  if "$(link)" != "shared" {
+    errors.error "an internal error" ;
+  }
 
-  OPTIONS on $(targets) += "--enable-mpi-thread-multiple" ;
+  local threading = [ feature.get-values <threading> : $(properties) ] ;
+  if "$(threading)" != "multi" {
+    errors.error "an internal error" ;
+  }
 
   # See https://github.com/Cryolite/intro/issues/12
   if [ is-clang "$(compiler)" ] {
@@ -227,96 +234,108 @@ rule make-install ( targets * : sources * : properties * )
   local cc-native = [ path.native "$(cc)" ] ;
   OPTIONS on $(targets) += "CC='$(cc-native)'" ;
 
-  #local cflags = [ get-cflags $(properties) ] ;
-  #if "$(cflags)" {
-  #  OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
-  #}
-
   local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
   local cxx-native = [ path.native "$(cxx)" ] ;
   OPTIONS on $(targets) += "CXX='$(cxx-native)'" ;
 
-  #local cxxflags = [ get-cxxflags $(properties) ] ;
-  #if "$(cxxflags)" {
-  #  OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
-  #}
+  switch "$(address-model)" {
+  case "64" :
+    OPTIONS on $(targets) += "CFLAGS='-m64'" ;
+    OPTIONS on $(targets) += "CXXFLAGS='-m64'" ;
+    OPTIONS on $(targets) += "LDFLAGS='-m64'" ;
+  case "32" :
+    OPTIONS on $(targets) += "CFLAGS='-m32'" ;
+    OPTIONS on $(targets) += "CXXFLAGS='-m32'" ;
+    OPTIONS on $(targets) += "LDFLAGS='-m32'" ;
+  case "" :
+    errors.error "the value for `<intro-address-model>' is empty" ;
+  case "*" :
+    errors.error "`<intro-address-model>$(address-model)': unknown property" ;
+  }
 
   local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  local logfile = "$(openmpi-prefix)/openmpi.txt" ;
+  local logfile-native = [ path.native "$(logfile)" ] ;
+  LOGFILE on $(targets) = "$(logfile-native)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "$(logfile)" ] ;
 }
 actions make-install
 {
-  $(PROPERTY_DUMP_COMMANDS)
+  exit_with_error ()
+  {
+    echo "`LANG=C date`:ERROR: $1 (Open MPI $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "ERROR: $1 (Open MPI $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+    exit 1
+  }
 
-  [ -x '$(SRCDIR)/configure' ] || exit 1
-  [ -x '$(SRCDIR)/config/config.sub' ] || exit 1
-  [ `'$(SRCDIR)/config/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
-  [ `'$(SRCDIR)/config/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
+  mkdir -p `dirname '$(LOGFILE)'`
+  echo "`LANG=C date`:INFO: initiation of Open MPI build process" | tee '$(LOGFILE)' >> '$(STREAM)'
+
+$(ENVIRONMENT_COMMANDS)
+
+$(PROPERTY_DUMP_COMMANDS)
+
+  [ -x '$(SRCDIR)/configure' ] || exit_with_error "\`$(SRCDIR)/configure' is not executable"
+  [ -x '$(SRCDIR)/config/config.sub' ] || exit_with_error "\`$(SRCDIR)/config/config.sub' is not executable"
+  [ `'$(SRCDIR)/config/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit_with_error "\`--build=$(BUILD_TRIPLET)' is not supported"
+  [ `'$(SRCDIR)/config/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit_with_error "\`--host=$(HOST_TRIPLET)' is not supported"
 
   # Clean up objdir `$(OBJDIR)'.
-  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
+  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit_with_error 'failed to clean up the old objdir'
 
-  $(ENVIRONMENT_COMMANDS)
-
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`configure' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`configure' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: ./configure $(OPTIONS:J= )" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`configure'"
   fi
 
   # Check the creation of `Makefile'.
-  [ -f '$(OBJDIR)/Makefile' ] || exit 1
+  [ -f '$(OBJDIR)/Makefile' ] || exit_with_error "failed to confirm the creation of \`Makefile'"
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make check' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make check' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make check" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make check'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make install >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make install )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make install' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make install' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make install" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make install >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make install'"
   fi
 
   # Clean up objdir `$(OBJDIR)'.
-  rm -rf '$(OBJDIR)' || exit 1
+  rm -rf '$(OBJDIR)' || exit_with_error 'failed to clean up the objdir'
 
-  [ -f '$(<)' ] || exit 1
+  [ -f '$(<)' ] || exit_with_error 'failed to confirm the creation of the build target'
 
   echo -n 'Open MPI $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
+  echo "`LANG=C date`:INFO: successful completion of Open MPI build process" | tee -a '$(LOGFILE)' >> '$(STREAM)'
   exit 0
 }
 
 
 
-alias install : "mpi.h/$(DEFAULT_COMPILER_PROPERTIES)" ;
+alias install : "mpi.h/$(ADDRESS_MODEL_SENSIBLE_DEFAULT_RELEASE_PROPERTIES)" ;
 explicit install ;
diff --git a/ppl/jamfile b/ppl/jamfile
--- a/ppl/jamfile
+++ b/ppl/jamfile
@@ -10,15 +10,14 @@ import "$(INTRO_ROOT_DIR)/compilers"
     is-clang
     is-icc
     get-compiler-description
-    get-compiler-prefix
-    get-libdir
-    get-includedir
+    get-full-prefix
     get-triplets
     get-cc
     get-cflags
     get-cxx
     get-cxxflags
     get-environment-commands
+    get-logfile-path
     get-property-dump-commands
   ;
 
@@ -57,11 +56,11 @@ rule download ( targets * : sources * : properties * )
   local version = [ feature.get-values <ppl-hidden> : $(properties) ] ;
   VERSION on $(targets) = "$(version)" ;
   URL on $(targets) = http://bugseng.com/products/ppl/download/ftp/releases/$(version)/ppl-$(version).tar.bz2 ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions download
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<)' || exit 1
   if [ -n '$(STREAM)' ]; then
@@ -99,11 +98,11 @@ rule expand ( targets * : sources * : properties * )
 {
   local version = [ feature.get-values <ppl-hidden> : $(properties) ] ;
   VERSION on $(targets) = "$(version)" ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions expand
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<:D)' || exit 1
   [ -f '$(>)' ] || exit 1
@@ -142,7 +141,8 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local includedir = "$(full-prefix)/include" ;
   return "<location>$(includedir)" ;
 }
 
@@ -174,25 +174,17 @@ rule make-install ( targets * : sources * : properties * )
   local srcdir = "$(INTRO_ROOT_DIR)/ppl-$(version)" ;
   SRCDIR on $(targets) = [ path.native "$(srcdir)" ] ;
 
+  # Set the path to objdir.
   local objdir = "$(INTRO_ROOT_DIR)/objdir" ;
-  OBJDIR on $(targets) = [ path.native "$(objdir)" ] ;
+  local objdir-native = [ path.native "$(objdir)" ] ;
+  OBJDIR on $(targets) = "$(objdir-native)" ;
 
   OPTIONS on $(targets) = ;
 
   # Set `--prefix' option for `configure' script.
-  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
-  local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
-  OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
-
-  # Set `--libdir' option for `configure' script.
-  local libdir = [ get-libdir "$(PREFIX)" : $(properties) ] ;
-  local libdir-native = [ path.native "$(libdir)" ] ;
-  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
-
-  # Set `--includedir' option for `configure' script.
-  local includedir = [ get-includedir "$(PREFIX)" : $(properties) ] ;
-  local includedir-native = [ path.native "$(includedir)" ] ;
-  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
+  local full-prefix = [ get-full-prefix "$(PREFIX)" : $(properties) ] ;
+  local full-prefix-native = [ path.native "$(full-prefix)" ] ;
+  OPTIONS on $(targets) += "--prefix='$(full-prefix-native)'" ;
 
   # Set `--build' and `--host' options for `configure' script.
   local triplets = [ get-triplets $(properties) ] ;
@@ -204,37 +196,44 @@ rule make-install ( targets * : sources * : properties * )
   OPTIONS on $(targets) += "--host=$(host-triplet)" ;
 
   local variant = [ feature.get-values <variant> : $(properties) ] ;
-  if "$(variant)" = "debug" {
+  switch "$(variant)" {
+  case "debug" :
     OPTIONS on $(targets) += "--enable-debugging" ;
     OPTIONS on $(targets) += "--enable-assertions" ;
     #OPTIONS on $(targets) += "--enable-more-assertions" ;
-  }
-  else if "$(variant)" = "release" {
+  case "release" :
     # Do nothing.
-  }
-  else if "$(variant)" = "profile" {
+  case "profile" :
     OPTIONS on $(targets) += "--enable-profiling" ;
-  }
-  else {
-    errors.error "an internal error." ;
+  case "" :
+    errors.error "the value for `<variant>' is empty" ;
+  case "*" :
+    errors.error "<variant>$(variant): unknown property" ;
   }
 
   #OPTIONS on $(targets) += "--enable-pch" ;
 
   # Set the link variants for `configure' script.
-  if "$(host-triplet)" = "x86_64-w64-mingw32" || "$(host-triplet)" = "i686-w64-mingw32" || "$(host-triplet)" = "i686-pc-cygwin" {
+  local link = [ feature.get-values <link> : $(properties) ] ;
+  switch "$(link)" {
+  case "shared" :
     OPTIONS on $(targets) += "--enable-shared" ;
     OPTIONS on $(targets) += "--disable-static" ;
-  }
-  else {
-    OPTIONS on $(targets) += "--enable-shared" ;
+  case "static" :
+    OPTIONS on $(targets) += "--disable-shared" ;
     OPTIONS on $(targets) += "--enable-static" ;
+    OPTIONS on $(targets) += "--without-pic" ;
+  case "" :
+    errors.error "the value for `<link>' is empty" ;
+  case "*" :
+    errors.error "<link>$(link): unknown property" ;
   }
 
   # The following options are necessary for `libtool' to guess the correct
   # include/library paths to installed GMP.
-  OPTIONS on $(targets) += "--with-gmp-include='$(includedir-native)'" ;
-  OPTIONS on $(targets) += "--with-gmp-lib='$(libdir-native)'" ;
+  #OPTIONS on $(targets) += "--with-gmp='$(full-prefix-native)'" ;
+  ##OPTIONS on $(targets) += "--with-gmp-include='$(full-prefix-native)/include'" ;
+  ##OPTIONS on $(targets) += "--with-gmp-lib='$(full-prefix-native)/lib'" ;
 
   local cc = [ get-cc "$(PREFIX)" : $(properties) ] ;
   local cc-native = [ path.native "$(cc)" ] ;
@@ -242,32 +241,31 @@ rule make-install ( targets * : sources * : properties * )
 
   local lto = [ feature.get-values <lto> : $(properties) ] ;
 
+  # C compiler options are `-DNDEBUG=1 -pedantic -std=c89 -Werror -pg -DPPL_PROFILING=1 -g -O2 -frounding-math CFLAGS -W -Wall'.
+  # `-pg -DPPL_PROFILING=1' is added iff `--enable-profiling' is specified.
   local cflags = [ get-cflags $(properties) ] ;
   if "$(cflags)" {
-    if "$(lto)" = "off" {
-      cflags = "$(cflags) -g" ;
+    if [ is-gcc "$(compiler)" ] && "$(lto)" = "on" {
+      # GCC's LTO is not compatible with `-g' option, so negates the preceding one.
+      cflags = "$(cflags) -g0" ;
     }
-    else if "$(lto)" = "on" {
-      # Do nothing.
-    }
-    else {
-      errors.error "an internal error." ;
-    }
-    cflags = "$(cflags) -frounding-math -Wall" ;
-    OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
+    cflags = "$(cflags) -frounding-math" ;
+    CFLAGS on $(targets) = "$(cflags)" ;
+    OPTIONS on $(targets) += "CFLAGS='@$(objdir-native)/cflags'" ;
   }
 
   local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
   local cxx-native = [ path.native "$(cxx)" ] ;
   OPTIONS on $(targets) += "--with-cxx='$(cxx-native)'" ;
 
-  # Default `CXXFLAGS' seems `-g -O2 -frounding-math -W -Wall'.
-  # When `--enable-profiling' is specified, `-pg -DPPL_PROFILING=1' is added to `CXXFLAGS'.
+  # C++ compiler options are `-pg -DPPL_PROFILING=1 -g -O2 -frounding-math CXXFLAGS -W -Wall'.
+  # `-pg -DPPL_PROFILING=1' is added iff `--enable-profiling' is specified.
   local cxxflags = [ get-cxxflags $(properties) ] ;
   if "$(cxxflags)" {
     # The build of PPL requires GNU extensions.
     local std = [ feature.get-values <std> : $(properties) ] ;
-    if "$(std)" = "c++03" {
+    switch "$(std)" {
+    case "c++03" :
       if [ is-clang "$(compiler)" ] {
         # Clang does not support `-std=gnu++03'.
         cxxflags = "$(cxxflags) -std=gnu++98" ;
@@ -275,111 +273,117 @@ rule make-install ( targets * : sources * : properties * )
       else {
         cxxflags = "$(cxxflags) -std=gnu++03" ;
       }
+    case "c++11" :
+      if [ is-gcc "$(compiler)" ] {
+        # GCC 4.6.x does not support `-std=gnu++11'.
+        cxxflags = "$(cxxflags) -std=gnu++0x" ;
+      }
+      else {
+        cxxflags = "$(cxxflags) -std=gnu++11" ;
+      }
+    case "" :
+      errors.error "the value for `<std>' is empty" ;
+    case "*" :
+      errors.error "<std>$(std): unknown property" ;
     }
-    else if "$(std)" = "c++11" {
-      cxxflags = "$(cxxflags) -std=gnu++0x" ;
+    if [ is-gcc "$(compiler)" ] && "$(lto)" = "on" {
+      # GCC's LTO is not compatible with `-g' option, so negates the preceding one.
+      cxxflags = "$(cxxflags) -g0" ;
     }
-    else {
-      error "`<std>$(std)' is not valid" ;
-    }
-    #cxxflags = "$(cxxflags) -pg -DPPL_PROFILING=1" ;
-    if "$(lto)" = "off" {
-      cxxflags = "$(cxxflags) -g" ;
-    }
-    else if "$(lto)" = "on" {
-      # Do nothing.
-    }
-    else {
-      errors.error "an internal error." ;
-    }
-    cxxflags = "$(cxxflags) -frounding-math -Wall" ;
-    OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
+    cxxflags = "$(cxxflags) -frounding-math" ;
+    CXXFLAGS on $(targets) = "$(cxxflags)" ;
+    OPTIONS on $(targets) += "CXXFLAGS='@$(objdir-native)/cxxflags'" ;
   }
 
   local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  local logfile = [ get-logfile-path "ppl" : "$(PREFIX)" : $(properties) ] ;
+  local logfile-native = [ path.native "$(logfile)" ] ;
+  LOGFILE on $(targets) = "$(logfile-native)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "$(logfile)" ] ;
 }
 actions make-install
 {
-  $(PROPERTY_DUMP_COMMANDS)
+  exit_with_error ()
+  {
+    echo "`LANG=C date`:ERROR: $1 (PPL $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "ERROR: $1 (PPL $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+    exit 1
+  }
+
+  echo "`LANG=C date`:INFO: initiation of PPL build process" | tee '$(LOGFILE)' >> '$(STREAM)'
+
+$(ENVIRONMENT_COMMANDS)
+
+$(PROPERTY_DUMP_COMMANDS)
 
   # Restore the hacked configure script. See also `../gcc/jamfile'.
   if [ -e '$(SRCDIR)/real-configure' ]; then
-    [ ! -x '$(SRCDIR)/real-configure' ] && exit 1
-    mv -f '$(SRCDIR)/real-configure' '$(SRCDIR)/configure' || exit 1
+    [ -x '$(SRCDIR)/real-configure' ] || exit_with_error 'failed to restore the hacked script'
+    mv -f '$(SRCDIR)/real-configure' '$(SRCDIR)/configure' || exit_with_error 'failed to restore the hacked script'
   fi
 
-  [ -x '$(SRCDIR)/configure' ] || exit 1
-  [ -x '$(SRCDIR)/config.sub' ] || exit 1
-  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
-  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
+  [ -x '$(SRCDIR)/configure' ] || exit_with_error "\`$(SRCDIR)/configure' is not executable"
+  [ -x '$(SRCDIR)/config.sub' ] || exit_with_error "\`$(SRCDIR)/config.sub' is not executable"
+  [ `'$(SRCDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit_with_error "\`--build=$(BUILD_TRIPLET)' is not supported"
+  [ `'$(SRCDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit_with_error "\`--host=$(HOST_TRIPLET)' is not supported"
 
   # Clean up objdir `$(OBJDIR)'.
-  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
+  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit_with_error 'failed to clean up the old objdir'
 
-  $(ENVIRONMENT_COMMANDS)
+  echo "`LANG=C date`:INFO: @cflags: $(CFLAGS)" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  echo "`LANG=C date`:INFO: @cxxflags: $(CXXFLAGS)" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  ( cd '$(OBJDIR)' && echo -n '$(CFLAGS)' > cflags ) || exit_with_error 'failed to create @cflags'
+  ( cd '$(OBJDIR)' && echo -n '$(CXXFLAGS)' > cxxflags ) || exit_with_error 'failed to create @cxxflags'
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`configure' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`configure' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: ./configure $(OPTIONS:J= )" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`configure'"
   fi
 
   # Check the creation of `Makefile'.
-  [ -f '$(OBJDIR)/Makefile' ] || exit 1
+  [ -f '$(OBJDIR)/Makefile' ] || exit_with_error "failed to confirm the creation of \`Makefile'"
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    # 0.12 can't run `make check'. See https://www.cs.unipr.it/mantis/view.php?id=350.
-    if [ $(VERSION) != 0.12 ]; then
-      ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(STREAM)' 2>&1 )
-    fi
-  else
-    # 0.12 can't run `make check'. See https://www.cs.unipr.it/mantis/view.php?id=350.
-    if [ $(VERSION) != 0.12 ]; then
-      ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check )
-    fi
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make check' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make check' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make check" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make check'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make install >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make install )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make install' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make install' PPL $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make install" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make install >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make install'"
   fi
 
   # Clean up objdir `$(OBJDIR)'.
-  rm -rf '$(OBJDIR)' || exit 1
+  rm -rf '$(OBJDIR)' || exit_with_error 'failed to clean up the objdir'
 
-  [ -f '$(<)' ] || exit 1
+  [ -f '$(<)' ] || exit_with_error 'failed to confirm the creation of the build target'
 
   echo -n 'PPL $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
+  echo "`LANG=C date`:INFO: successful completion of PPL build process" | tee -a '$(LOGFILE)' >> '$(STREAM)'
   exit 0
 }
 
diff --git a/template/x86_64-unknown-linux-gnu/g++-wrapper b/template/x86_64-unknown-linux-gnu/g++-wrapper
--- a/template/x86_64-unknown-linux-gnu/g++-wrapper
+++ b/template/x86_64-unknown-linux-gnu/g++-wrapper
@@ -1,85 +1,115 @@
 #!/usr/bin/env sh
 
-bits=
-is_link=1
-for arg in "$@"; do
-    if [ "${arg}" = '-m64' ]; then
-	if [ "${bits}" = '32' ]; then
-	    echo "${0}: error: both \`-m64' and \`-m32' cannot be specified simultaneously" 1>&2
-	    exit 1
-	fi
-	bits=64
-    fi
-    if [ "${arg}" = '-m32' ]; then
-	if [ "${bits}" = '64' ]; then
-	    echo "${0}: error: both \`-m64' and \`-m32' cannot be specified simultaneously" 1>&2
-	    exit 1
-	fi
-	bits=32
-    fi
-    if [ "${arg}" = '-fsyntax-only' -o "${arg}" = '-c' -o "${arg}" = '-M' -o "${arg}" = '-MM' -o "${arg}" = '-E' -o "${arg}" = '-S' ]; then
-	is_link=0
-    fi
-done
+bindir=`(cd \`dirname "$0"\`; pwd)`
 
-if false; then
-    mkdir -p "${HOME}/tmp"
-    if [ $is_link -eq 0 ]; then
-	echo "$@" > "${HOME}/tmp/cxx-compile.$$.log"
-    elif [ $is_link -eq 1 ]; then
-	echo "$@" > "${HOME}/tmp/cxx-link.$$.log"
-    else
-	echo "${0}: error: an internal error" 1>&2
-	exit 1
-    fi
-fi
+bits=0
+is_link=0
 
-if [ -z "${bits}" ]; then
-    if [ `uname --machine` = 'x86_64' ]; then
-	bits=64
-    elif [ `uname --machine` = 'x86' ]; then
-	bits=32
-    else
-	echo "${0}: error: unsupported architecture" 1>&2
-	exit 1
-    fi
-fi
-
-if [ -f /etc/debian_version ] && grep -Fq 'wheezy/sid' /etc/debian_version; then
-    if [ ${bits} -eq 64 ]; then
-	LIBRARY_PATH="/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu${LIBRARY_PATH:+:${LIBRARY_PATH}}"
-	export LIBRARY_PATH
-    elif [ ${bits} -eq 32 ]; then
-	:
-    else
-	echo "${0}: error: an internal error" 1>&2
-	exit 1
-    fi
-fi
-
-bindir=`(cd \`dirname "${0}"\`; pwd)`
-prefix=`dirname "${bindir}"`
-
-if [ ! -x "${bindir}/g++" ]; then
-  echo "${0}: error: \`${bindir}/g++': not found" 1>&2
+if [ ! -x "$bindir/g++" ]; then
+  echo "$0: error: \`$bindir/g++': not found" 1>&2
   exit 1
 fi
 
-ulimit -S -t 300
-ulimit -S -m 2097152
+dryrun=`"$bindir/g++" -### "$@" 2>&1`
 
-if [ ${is_link} -eq 0 ]; then
-    exec "${bindir}/g++" "$@"
-elif [ ${is_link} -eq 1 ]; then
-    if [ ${bits} -eq 64 ]; then
-	exec "${bindir}/g++" "$@" -Wl,"-rpath=${prefix}/lib64" -Wl,"-rpath=${prefix}/lib" -Wl,--enable-new-dtags
-    elif [ ${bits} -eq 32 ]; then
-	exec "${bindir}/g++" "$@" -Wl,"-rpath=${prefix}/lib32" -Wl,"-rpath=${prefix}/lib" -Wl,--enable-new-dtags
-    else
-	echo "${0}: error: an internal error" 1>&2
-	exit 1
+cc1plus_cl=`echo "$dryrun" | grep -F \`"$bindir/g++" -print-prog-name=cc1plus\``
+if [ -n "$cc1plus_cl" ]; then
+    if echo "$cc1plus_cl" | grep -Eq '[[:space:]]-m32[[:space:]]'; then
+        if [ $bits -eq 64 ]; then
+            echo "$0: error: failed to detect whether the target is 64-bit or 32-bit" 1>&2
+            exit 1
+        fi
+        bits=32
     fi
+    if echo "$cc1plus_cl" | grep -Evq '[[:space:]]-m32[[:space:]]'; then
+        if [ $bits -eq 32 ]; then
+            echo "$0: error: failed to detect whether the target is 64-bit or 32-bit" 1>&2
+            exit 1
+        fi
+        bits=64
+    fi
+fi
+
+as_cl=`echo "$dryrun" | grep -F \`"$bindir/g++" -print-prog-name=as\``
+if echo "$as_cl" | grep -Eq '[[:space:]]--64[[:space:]]'; then
+    if [ $bits -eq 32 ]; then
+        echo "$0: error: failed to detect whether the target is 64-bit or 32-bit" 1>&2
+        exit 1
+    fi
+    bits=64
+fi
+if echo "$as_cl" | grep -Eq '[[:space:]]--32[[:space:]]'; then
+    if [ $bits -eq 64 ]; then
+        echo "$0: error: failed to detect whether the target is 64-bit or 32-bit" 1>&2
+        exit 1
+    fi
+    bits=32
+fi
+
+collect2_cl=`echo "$dryrun" | grep -F \`"$bindir/g++" -print-prog-name=collect2\``
+if echo "$collect2_cl" | grep -Eq '[[:space:]]-m[[:space:]]+elf_x86_64[[:space:]]'; then
+    if [ $bits -eq 32 ]; then
+        echo "$0: error: failed to detect whether the target is 64-bit or 32-bit" 1>&2
+        exit 1
+    fi
+    bits=64
+    is_link=1
+fi
+if echo "$collect2_cl" | grep -Eq '[[:space:]]-m[[:space:]]+elf_i386[[:space:]]'; then
+    if [ $bits -eq 64 ]; then
+        echo "$0: error: failed to detect whether the target is 64-bit or 32-bit" 1>&2
+        exit 1
+    fi
+    bits=32
+    is_link=1
+fi
+
+if false; then
+    mkdir -p "$HOME/tmp"
+    if [ $is_link -eq 0 ]; then
+        echo "$@" > "$HOME/tmp/cxx-compile.$$.log"
+    elif [ $is_link -eq 1 ]; then
+        echo "$@" > "$HOME/tmp/cxx-link.$$.log"
+    else
+        echo "$0: error: an internal error" 1>&2
+        exit 1
+    fi
+fi
+
+if [ $is_link -eq 0 ]; then
+    exec "$bindir/g++" "$@"
+fi
+
+if [ $is_link -ne 1 ]; then
+    echo "$0: error: an internal error" 1>&2
+    exit 1
+fi
+
+if [ $bits -eq 0 ]; then
+    echo "$0: error: an internal error" 1>&2
+    exit 1
+fi
+
+if [ -f '/etc/debian_version' ] && grep -Fq 'wheezy/sid' '/etc/debian_version'; then
+    if [ $bits -eq 64 ]; then
+        LIBRARY_PATH="${LIBRARY_PATH:+${LIBRARY_PATH}:}/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu"
+        export LIBRARY_PATH
+        debian_multiarch_workaround_link_options="-Wl,-rpath-link=/usr/lib/x86_64-linux-gnu -Wl,-rpath-link=/lib/x86_64-linux-gnu"
+    elif [ $bits -eq 32 ]; then
+        :
+    else
+        echo "$0: error: an internal error" 1>&2
+        exit 1
+    fi
+fi
+
+prefix=`dirname "$bindir"`
+
+if [ $bits -eq 64 ]; then
+    exec "$bindir/g++" "$@" -Wl,"-rpath=$prefix/lib64" -Wl,"-rpath=$prefix/lib" $debian_multiarch_workaround_link_options -Wl,--enable-new-dtags
+elif [ $bits -eq 32 ]; then
+    exec "$bindir/g++" "$@" -Wl,"-rpath=$prefix/lib32" -Wl,"-rpath=$prefix/lib" -Wl,--enable-new-dtags
 else
-    echo "${0}: error: an internal error" 1>&2
+    echo "$0: error: an internal error" 1>&2
     exit 1
 fi
diff --git a/valgrind/jamfile b/valgrind/jamfile
--- a/valgrind/jamfile
+++ b/valgrind/jamfile
@@ -11,14 +11,9 @@ import "$(INTRO_ROOT_DIR)/compilers"
     is-icc
     get-compiler-description
     get-compiler-prefix
-    get-default-bindir
-    get-default-libdir
-    get-default-includedir
     get-triplets
     get-cc
-    get-cflags
     get-cxx
-    get-cxxflags
     get-environment-commands
     get-property-dump-commands
   ;
@@ -58,11 +53,11 @@ rule download ( targets * : sources * : properties * )
   local version = [ feature.get-values <valgrind-hidden> : $(properties) ] ;
   VERSION on $(targets) = "$(version)" ;
   URL on $(targets) = http://valgrind.org/downloads/valgrind-$(version).tar.bz2 ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions download
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<)' || exit 1
   if [ -n '$(STREAM)' ]; then
@@ -102,11 +97,11 @@ rule expand ( targets * : sources * : properties * )
 {
   local version = [ feature.get-values <valgrind-hidden> : $(properties) ] ;
   VERSION on $(targets) = "$(version)" ;
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions expand
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   rm -rf '$(<:D)' || exit 1
   [ -f '$(>)' ] || exit 1
@@ -143,11 +138,11 @@ if "$(VALGRIND)" = "trunk" {
 
 rule checkout-trunk ( targets * : sources * : properties * )
 {
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "/dev/null" ] ;
 }
 actions checkout-trunk
 {
-  $(PROPERTY_DUMP_COMMANDS)
+$(PROPERTY_DUMP_COMMANDS)
 
   if [ ! -f '$(INTRO_ROOT_DIR)/valgrind-trunk/README' ]; then
     if [ -n '$(STREAM)' ]; then
@@ -208,8 +203,8 @@ explicit srcdir ;
 
 rule location-conditional ( properties * )
 {
-  local includedir = [ get-default-includedir "$(PREFIX)" : $(properties) ] ;
-  return "<location>$(includedir)" ;
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(properties) ] ;
+  return "<location>$(compiler-prefix)/include" ;
 }
 
 make valgrind/valgrind.h
@@ -241,8 +236,10 @@ rule make-install ( targets * : sources * : properties * )
   local srcdir = "$(INTRO_ROOT_DIR)/valgrind-$(version)" ;
   SRCDIR on $(targets) = [ path.native "$(srcdir)" ] ;
 
+  # Set the path to objdir.
   local objdir = "$(INTRO_ROOT_DIR)/objdir" ;
-  OBJDIR on $(targets) = [ path.native "$(objdir)" ] ;
+  local objdir-native = [ path.native "$(objdir)" ] ;
+  OBJDIR on $(targets) = "$(objdir-native)" ;
 
   OPTIONS on $(targets) = ;
 
@@ -251,140 +248,125 @@ rule make-install ( targets * : sources * : properties * )
   local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
   OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
 
-  # Set `--bindir' option for `configure' script.
-  local bindir = [ get-default-bindir "$(PREFIX)" : $(properties) ] ;
-  local bindir-native = [ path.native "$(bindir)" ] ;
-  OPTIONS on $(targets) += "--bindir='$(bindir-native)'" ;
-
-  # Set `--libdir' option for `configure' script.
-  local libdir = [ get-default-libdir "$(PREFIX)" : $(properties) ] ;
-  local libdir-native = [ path.native "$(libdir)" ] ;
-  OPTIONS on $(targets) += "--libdir='$(libdir-native)'" ;
-
-  # Set `--includedir' option for `configure' script.
-  local includedir = [ get-default-includedir "$(PREFIX)" : $(properties) ] ;
-  local includedir-native = [ path.native "$(includedir)" ] ;
-  OPTIONS on $(targets) += "--includedir='$(includedir-native)'" ;
-
+  # Set `--build' and `--host' options for `configure' script.
   local triplets = [ get-triplets $(properties) ] ;
   local build-triplet = "$(triplets[1])" ;
   local host-triplet = "$(triplets[2])" ;
   BUILD_TRIPLET on $(targets) = "$(build-triplet)" ;
   HOST_TRIPLET on $(targets) = "$(host-triplet)" ;
 
-  # Set `--build' and `--host' options for `configure' script.
   OPTIONS on $(targets) += "--build=$(build-triplet)" ;
   OPTIONS on $(targets) += "--host=$(host-triplet)" ;
 
   OPTIONS on $(targets) += "--enable-tls" ;
 
-  OPTIONS on $(targets) += "--with-mpicc='$(compiler-prefix-native)/bin/mpicc'" ;
+  local address-model = [ feature.get-values "<intro-address-model>" : $(properties) ] ;
+  OPTIONS on $(targets) += "--with-mpicc='$(compiler-prefix-native)/address-model-$(address-model)/bin/mpicc'" ;
 
   local cc = [ get-cc "$(PREFIX)" : $(properties) ] ;
   local cc-native = [ path.native "$(cc)" ] ;
   OPTIONS on $(targets) += "CC='$(cc-native)'" ;
 
-  #local cflags = [ get-cflags $(properties) ] ;
-  #if "$(cflags)" {
-  #  OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
-  #}
-
   local cxx = [ get-cxx "$(PREFIX)" : $(properties) ] ;
   local cxx-native = [ path.native "$(cxx)" ] ;
   OPTIONS on $(targets) += "CXX='$(cxx-native)'" ;
 
-  #local cxxflags = [ get-cxxflags $(properties) ] ;
-  #if "$(cxxflags)" {
-  #  OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
-  #}
-
   local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) ] ;
   ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 
-  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) ] ;
+  local logfile = "$(compiler-prefix)/valgrind.txt" ;
+  local logfile-native = [ path.native "$(logfile)" ] ;
+  LOGFILE on $(targets) = "$(logfile-native)" ;
+
+  PROPERTY_DUMP_COMMANDS on $(targets) = [ get-property-dump-commands $(properties) : "$(STREAM)" : "$(logfile)" ] ;
 }
 actions make-install
 {
-  $(PROPERTY_DUMP_COMMANDS)
+  exit_with_error ()
+  {
+    echo "`LANG=C date`:ERROR: $1 (Valgrind $(VERSION), $(COMPILER_DESCRIPTION))" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "ERROR: $1 (Valgrind $(VERSION), $(COMPILER_DESCRIPTION))" | $(AWACS)
+    exit 1
+  }
+
+  mkdir -p `dirname '$(LOGFILE)'`
+  echo "`LANG=C date`:INFO: initiation of Valgrind build process" | tee '$(LOGFILE)' >> '$(STREAM)'
+
+$(ENVIRONMENT_COMMANDS)
+
+$(PROPERTY_DUMP_COMMANDS)
 
   # Clean up objdir `$(OBJDIR)'.
-  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
+  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit_with_error 'failed to clean up the old objdir'
 
   # Valgrind sources should compile in the `SRCDIR', not `OBJDIR' that is
   # different from `SRCDIR'. So, let's first copy all the contents of
   # `SRCDIR' to `OBJDIR'.
-  cp -rT '$(SRCDIR)' '$(OBJDIR)' || exit 1
+  cp -rT '$(SRCDIR)' '$(OBJDIR)' || exit_with_error 'failed to copy SRCDIR to OBJDIR'
 
-  [ -x '$(OBJDIR)/configure' ] || exit 1
-  [ -x '$(OBJDIR)/config.sub' ] || exit 1
-  [ `'$(OBJDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit 1
-  [ `'$(OBJDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit 1
+  [ -x '$(OBJDIR)/configure' ] || exit_with_error "\`$(OBJDIR)/configure' is not executable"
+  [ -x '$(OBJDIR)/config.sub' ] || exit_with_error "\`$(OBJDIR)/config.sub' is not executable"
+  [ `'$(OBJDIR)/config.sub' $(BUILD_TRIPLET)` = $(BUILD_TRIPLET) ] || exit_with_error "\`--build=$(BUILD_TRIPLET)' is not supported"
+  [ `'$(OBJDIR)/config.sub' $(HOST_TRIPLET)` = $(HOST_TRIPLET) ] || exit_with_error "\`--host=$(HOST_TRIPLET)' is not supported"
 
-  $(ENVIRONMENT_COMMANDS)
-
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && ./configure $(OPTIONS) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && ./configure $(OPTIONS) )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`configure' Valgrind $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`configure' Valgrind $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: ./configure $(OPTIONS:J= )" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && ./configure $(OPTIONS) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`configure'"
   fi
 
   # Check the creation of `Makefile'.
-  [ -f '$(OBJDIR)/Makefile' ] || exit 1
+  [ -f '$(OBJDIR)/Makefile' ] || exit_with_error "failed to confirm the creation of \`Makefile'"
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make' Valgrind $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make' Valgrind $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make check' Valgrind $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make check' Valgrind $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make check" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make check'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    ( cd '$(OBJDIR)' && make install >> '$(STREAM)' 2>&1 )
-  else
-    ( cd '$(OBJDIR)' && make install )
-  fi
-  if [ $? -ne 0 ]; then
-    echo    "ERROR: failed to \`make install' Valgrind $(VERSION) ($(COMPILER_DESCRIPTION))." 1>&2
-    echo -n "ERROR: failed to \`make install' Valgrind $(VERSION) ($(COMPILER_DESCRIPTION))." | $(AWACS)
-    exit 1
+  echo "`LANG=C date`:COMMAND: make install" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  ( cd '$(OBJDIR)' && make install >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    exit_with_error "failed to \`make install'"
   fi
 
-  if [ -n '$(STREAM)' ]; then
-    # Some tests might deadlock with GCC 4.8. Forces the deadlocked tests to be killed by `ulimit'.
-    ( cd '$(OBJDIR)' && ulimit -S -t 60 && ulimit -S -m 2097152 && make --jobs=$(CONCURRENCY) regtest 2>&1 | tee regtest.log >> '$(STREAM)' 2>&1 )
-  else
-    # Some tests might deadlock with GCC 4.8. Forces the deadlocked tests to be killed by `ulimit'.
-    ( cd '$(OBJDIR)' && ulimit -S -t 60 && ulimit -S -m 2097152 && make --jobs=$(CONCURRENCY) regtest 2>&1 | tee regtest.log )
+  echo "`LANG=C date`:COMMAND: make regtest" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+  tail --follow --lines=0 --sleep-interval=0.1 '$(LOGFILE)' >> '$(STREAM)' &
+  # Some tests might deadlock with GCC 4.8. Forces the deadlocked tests to be killed by `ulimit'.
+  ( cd '$(OBJDIR)' && ulimit -S -t 60 && ulimit -S -m 2097152 && make --jobs=$(CONCURRENCY) regtest 2>&1 | tee regtest.log >> '$(LOGFILE)' 2>&1 )
+  result=$?
+  kill -TERM $!
+  if [ $result -ne 0 ]; then
+    # `make regtest' usually fails, so they are treated as just information.
+    echo "`LANG=C date`:INFO:\`make regtest': `grep -Eo "^==.*==$" "$(OBJDIR)/regtest.log"`" | tee -a '$(LOGFILE)' >> '$(STREAM)'
+    echo -n "INFO:\`make regtest':" `grep -Eo "^==.*==$" "$(OBJDIR)/regtest.log"` | $(AWACS)
   fi
-  # `make regtest' usually fails, so they are treated as just information.
-  echo -n "INFO:\`make regtest':" `grep -Eo "^==.*==$" "$(OBJDIR)/regtest.log"` | $(AWACS)
 
   # Clean up objdir `$(OBJDIR)'.
-  rm -rf '$(OBJDIR)' || exit 1
+  rm -rf '$(OBJDIR)' || exit_with_error 'failed to clean up the objdir'
 
-  [ -f '$(<)' ] || exit 1
+  [ -f '$(<)' ] || exit_with_error 'failed to confirm the creation of the build target'
 
   echo -n 'Valgrind $(VERSION) ($(COMPILER_DESCRIPTION)) was successfully built.' | $(AWACS)
+  echo "`LANG=C date`:INFO: successful completion of Valgrind build process" | tee -a '$(LOGFILE)' >> '$(STREAM)'
   exit 0
 }
 
