Added support of i686-pc-cygwin.
To maintain the consistency between GCC versions and `hack-gcc-specs`
scripts, the build script uses the checksum of `gcc -dumpspecs` to identify
the corresponding `hack-gcc-specs`.

Explicitly prohibits `-fmudflap` and `-fmudflapth` options for GCC on
i686-pc-cygwin because they are not available on i686-pc-cygwin.

Added support of MPICH2 on i686-pc-cygwin.

Refactored `boost/toolset.sh`.

Added and modified `user-config.jam` and `site-config.jam` for
i686-pc-cygwin.

Fixed build script for Boost on i686-pc-cygwin.

Explicitly prohibits the build of Valgrind on i686-pc-cygwin.

diff --git a/boost/jamfile b/boost/jamfile
--- a/boost/jamfile
+++ b/boost/jamfile
@@ -86,12 +86,23 @@ for local compiler in $(COMPILERS)
       errors.error "an internal error." ;
     }
     local boost-abi-tag = [ regex.replace $(boost-abi-version) "\\." "_" ] ;
-    make "$(compiler-prefix)/lib/libboost_regex-$(compiler-abi-tag)-$(boost-abi-tag).so.$(boost)"
-      : compiler-dep/<icu4c>unspecified/<mpi>unspecified/<openmpi>unspecified/<boost>unspecified
-        ../icu4c//install/<mpi>unspecified/<openmpi>unspecified/<boost>unspecified
-        ../openmpi//install/<icu4c>unspecified/<boost>unspecified
-      : @install
-      ;
+    if $(OPENMPI)
+    {
+      make "$(compiler-prefix)/lib/libboost_regex-$(compiler-abi-tag)-$(boost-abi-tag).so.$(boost)"
+        : compiler-dep/<icu4c>unspecified/<mpi>unspecified/<openmpi>unspecified/<boost>unspecified
+          ../icu4c//install/<mpi>unspecified/<openmpi>unspecified/<boost>unspecified
+          ../openmpi//install/<icu4c>unspecified/<boost>unspecified
+        : @install
+        ;
+    }
+    else
+    {
+      make "$(compiler-prefix)/lib/libboost_regex-$(compiler-abi-tag)-$(boost-abi-tag).so.$(boost)"
+        : compiler-dep/<icu4c>unspecified/<mpi>unspecified/<openmpi>unspecified/<boost>unspecified
+          ../icu4c//install/<mpi>unspecified/<openmpi>unspecified/<boost>unspecified
+        : @install
+        ;
+    }
     explicit "$(compiler-prefix)/lib/libboost_regex-$(compiler-abi-tag)-$(boost-abi-tag).so.$(boost)" ;
   }
 }
@@ -162,9 +173,9 @@ rule install ( targets * : sources * : properties * )
     errors.error "an internal error." ;
   }
 
-  OPTIONS on $(targets) += "linkflags=-Wl,-rpath=\"$(compiler-prefix)/lib\"" ;
-
   OPTIONS on $(targets) += stage ;
+
+  CLEANUP_COMMAND on $(targets) = "rm -rf \"$(boost-root)/bin.v2/libs/*/build/`\"$(INTRO_ROOT_DIR)/boost/toolset.sh\" \"$(compiler-prefix)/bin/g++-wrapper\"`\"" ;
 }
 actions install
 {
@@ -174,34 +185,41 @@ actions install
     exit 1
   fi
 
+  result=0
+
   # Build debug version libraries.
   if [ -n "$(STREAM)" ]; then
-    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=debug cxxflags="-std=c++0x" $(OPTIONS) >> "$(STREAM)" 2>&1 )
+    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=debug runtime-link=shared cxxflags="-std=c++0x" $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=debug cxxflags="-std=c++0x" $(OPTIONS) )
+    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=debug runtime-link=shared cxxflags="-std=c++0x" $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to build Boost $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to build Boost $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
-    exit 1
+    echo "ERROR: failed to build Boost $(VERSION) (debug build) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to build Boost $(VERSION) (debug build) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    result=1
   fi
 
   # Build release version libraries with LTO options.
   if [ -n "$(STREAM)" ]; then
-    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=release cflags=-flto cxxflags="-std=c++0x" linkflags=-O3 linkflags=-flto $(OPTIONS) >> "$(STREAM)" 2>&1 )
+    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=release runtime-link=shared cflags=-flto cxxflags="-std=c++0x" linkflags=-O3 linkflags=-flto $(OPTIONS) >> "$(STREAM)" 2>&1 )
   else
-    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=release cflags=-flto cxxflags="-std=c++0x" linkflags=-O3 linkflags=-flto $(OPTIONS) )
+    ( cd "$(BOOST_ROOT)" && ./b2 -d+2 -j$(CONCURRENCY) variant=release runtime-link=shared cflags=-flto cxxflags="-std=c++0x" linkflags=-O3 linkflags=-flto $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to build Boost $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to build Boost $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo "ERROR: failed to build Boost $(VERSION) (release build with LTO support) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to build Boost $(VERSION) (release build with LTO support) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    result=1
+  fi
+
+  if [ $result -ne 0 ]; then
+    touch --no-create --date='2000/1/1' "$(<)"
     exit 1
   fi
 
   [ -x "$(<)" ] || exit 1
 
   # Clean up the build directory.
-  rm -rf "$(BOOST_ROOT)/bin.v2"
+  $(CLEANUP_COMMAND)
 
   echo -n "Boost $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built." | $(AWACS)
   exit 0
diff --git a/template/i686-pc-cygwin/gcc-wrapper b/template/i686-pc-cygwin/gcc-wrapper
--- a/template/i686-pc-cygwin/gcc-wrapper
+++ b/template/i686-pc-cygwin/gcc-wrapper
@@ -32,10 +32,10 @@ else
   exit 1
 fi
 
-if which "${bindir}/g++" 1>/dev/null 2>&1; then
+if which "${bindir}/gcc" 1>/dev/null 2>&1; then
   :
 else
-  echo "$0: error: ${bindir}/g++: command not found" 1>&2
+  echo "$0: error: ${bindir}/gcc: command not found" 1>&2
   exit 1
 fi
 
@@ -48,10 +48,10 @@ fi
 
 specs=`mktemp` || exit
 
-LD_LIBRARY_PATH="$LD_LIBRARY_PATH${LD_LIBRARY_PATH:+:}$libdir"
-export LD_LIBRARY_PATH
+PATH="$PATH${PATH:+:}$bindir"
+export PATH
 
-{ "${bindir}/hack-gcc-specs" > "$specs"; } && "${bindir}/g++" -specs="$specs" "$@" -Wl,-rpath="$libdir"
+{ "${bindir}/hack-gcc-specs" > "$specs"; } && "${bindir}/gcc" -specs="$specs" "$@"
 result=$?
 
 rm -f "$specs"
diff --git a/template/x86_64-unknown-linux-gnu/gcc-wrapper b/template/x86_64-unknown-linux-gnu/gcc-wrapper
--- a/template/x86_64-unknown-linux-gnu/gcc-wrapper
+++ b/template/x86_64-unknown-linux-gnu/gcc-wrapper
@@ -1,60 +1,57 @@
-#! /bin/sh
+#!/bin/sh
 
-if ! which dirname 1>/dev/null 2>&1; then
-  echo "$0: error: dirname: command not found" >&2
+if which dirname 1>/dev/null 2>&1; then
+  :
+else
+  echo "$0: error: dirname: command not found" 1>&2
   exit 1
 fi
 
-if ! which pwd 1>/dev/null 2>&1; then
-  echo "$0: error: pwd: command not found" >&2
+if which pwd 1>/dev/null 2>&1; then
+  :
+else
+  echo "$0: error: pwd: command not found" 1>&2
   exit 1
 fi
 
 bindir=`(cd \`dirname "$0"\`; pwd)`
 dir=`dirname "$bindir"`
-libdir="$dir/lib"
+libdir="${dir}/lib"
 
-if ! which uname 1>/dev/null 2>&1; then
-  echo "$0: error: uname: command not found" >&2
-  exit 1
-fi
-
-if ! which grep 1>/dev/null 2>&1; then
-  echo "$0: error: grep: command not found" >&2
-  exit 1
-fi
-
-if uname | grep -Fq 'Linux'; then
-  LD_LIBRARY_PATH="${LD_LIBRARY_PATH:+${LD_LIBRARY_PATH}:}$libdir"
-  export LD_LIBRARY_PATH
-elif uname | grep -Fq 'CYGWIN'; then
-  PATH="${PATH:+${PATH}:}$bindir"
-  export PATH
+if which mktemp 1>/dev/null 2>&1; then
+  :
 else
-  echo "$0: error: unknown system" >&2
+  echo "$0: error: mktemp: command not found" 1>&2
   exit 1
 fi
 
-if ! which mktemp 1>/dev/null 2>&1; then
-  echo "$0: error: mktemp: command not found" >&2
+if which "${bindir}/hack-gcc-specs" 1>/dev/null 2>&1; then
+  :
+else
+  echo "$0: error: ${bindir}/hack-gcc-specs: command not found" 1>&2
   exit 1
 fi
 
-if ! which "$bindir/hack-gcc-specs" >/dev/null 2>&1; then
-  echo "$0: error: $bindir/hack-gcc-specs: command not found" >&2
+if which "${bindir}/gcc" 1>/dev/null 2>&1; then
+  :
+else
+  echo "$0: error: ${bindir}/gcc: command not found" 1>&2
   exit 1
 fi
 
-if ! which "$bindir/g++" 1>/dev/null 2>&1; then
-  echo "$0: error: $bindir/g++: command not found" >&2
+if which rm 1>/dev/null 2>&1; then
+  :
+else
+  echo "$0: error: rm: command not found" 1>&2
   exit 1
 fi
 
 specs=`mktemp` || exit
 
-"$bindir/hack-gcc-specs" > "$specs" || exit
+LD_LIBRARY_PATH="$LD_LIBRARY_PATH${LD_LIBRARY_PATH:+:}$libdir"
+export LD_LIBRARY_PATH
 
-"$bindir/gcc" -specs="$specs" "$@" -Wl,-rpath="$libdir"
+{ "${bindir}/hack-gcc-specs" > "$specs"; } && "${bindir}/gcc" -specs="$specs" "$@" -Wl,-rpath="$libdir"
 result=$?
 
 rm -f "$specs"
diff --git a/template/x86_64-unknown-linux-gnu/hack-gcc-specs b/template/x86_64-unknown-linux-gnu/hack-gcc-specs
--- a/template/x86_64-unknown-linux-gnu/hack-gcc-specs
+++ b/template/x86_64-unknown-linux-gnu/hack-gcc-specs
@@ -1,10 +1,15 @@
-#! /bin/sh
+#!/bin/sh
 
-if ! which dirname 1>/dev/null 2>&1; then
+if which dirname 1>/dev/null 2>&1; then
+  :
+else
   echo "$0: error: dirname: command not found" >&2
   exit 1
 fi
-if ! which pwd 1>/dev/null 2>&1; then
+
+if which pwd 1>/dev/null 2>&1; then
+  :
+else
   echo "$0: error: pwd: command not found" >&2
   exit 1
 fi
@@ -12,14 +17,18 @@ fi
 bindir=`(cd \`dirname "$0"\`; pwd)`
 libdir="`dirname "$bindir"`/lib"
 
-if ! which "$bindir/g++-wrapper" 1>/dev/null 2>&1; then
-  echo "$0: error: $bindir/g++-wrapper: command not found" >&2
+if which "${bindir}/gcc" 1>/dev/null 2>&1; then
+  :
+else
+  echo "$0: error: ${bindir}/gcc: command not found" >&2
   exit 1
 fi
 
-specs=`"$bindir/gcc" -dumpspecs`
+specs=`"${bindir}/gcc" -dumpspecs`
 
-if ! which sed 1>/dev/null 2>&1; then
+if which sed 1>/dev/null 2>&1; then
+  :
+else
   echo "$0: error: sed: command not found" >&2
   exit 1
 fi
@@ -30,10 +39,13 @@ cpp_options_epilogue=`echo "$specs" | sed '1,/^\*cpp_options:$/d'`
 cpp_options=`echo "$cpp_options_epilogue" | sed '1q'`
 cpp_options_epilogue=`echo "$cpp_options_epilogue" | sed -n '2,$p'`
 
-if ! echo "$cpp_options" | grep -Fq ' %{f*} '; then
-  echo "$0: error: cannot hack GCC spec file" >&2
+if echo "$cpp_options" | grep -Fq ' %{f*} '; then
+  :
+else
+  echo "$0: error: cannot hack GCC spec file" 1>&2
   exit 1
 fi
+
 cpp_options=`echo "$cpp_options" | sed 's/ %{f\*} / %{f*} %{fmudflap:%{pthread:-fmudflapth}} /'`
 specs=`echo "$cpp_options_prologue
 $cpp_options
@@ -45,10 +57,13 @@ cpp_unique_options_epilogue=`echo "$specs" | sed '1,/^\*cpp_unique_options:$/d'`
 cpp_unique_options=`echo "$cpp_unique_options_epilogue" | sed '1q'`
 cpp_unique_options_epilogue=`echo "$cpp_unique_options_epilogue" | sed -n '2,$p'`
 
-if ! echo "$cpp_unique_options" | grep -Fq ' %{fmudflap:-D_MUDFLAP -include mf-runtime.h} '; then
-  echo "$0: error: cannot hack GCC spec file" >&2
+if echo "$cpp_unique_options" | grep -Fq ' %{fmudflap:-D_MUDFLAP -include mf-runtime.h} '; then
+  :
+else
+  echo "$0: error: cannot hack GCC spec file" 1>&2
   exit 1
 fi
+
 cpp_unique_options=`echo "$cpp_unique_options" \
                       | sed 's/ %{fmudflap:-D_MUDFLAP -include mf-runtime\.h} / %{fmudflap:-D_MUDFLAP %{pthread:-D_MUDFLAPTH} -include mf-runtime.h} /'`
 specs=`echo "$cpp_unique_options_prologue
@@ -61,10 +76,13 @@ cc1_options_epilogue=`echo "$specs" | sed '1,/^\*cc1_options:$/d'`
 cc1_options=`echo "$cc1_options_epilogue" | sed '1q'`
 cc1_options_epilogue=`echo "$cc1_options_epilogue" | sed -n '2,$p'`
 
-if ! echo "$cc1_options" | grep -Fq ' %{f*} '; then
-  echo "$0: error: cannot hack GCC spec file" >&2
+if echo "$cc1_options" | grep -Fq ' %{f*} '; then
+  :
+else
+  echo "$0: error: cannot hack GCC spec file" 1>&2
   exit 1
 fi
+
 cc1_options=`echo "$cc1_options" \
                | sed 's/\(.*\)/%{fmudflap|fmudflapth:%{fpic|fPIC:%e-fmudflap or -fmudflapth is not compatible with -fpic or -fPIC}} \1/' \
                | sed 's/ %{f\*} / %{f*} %{fmudflap:%{pthread:-fmudflapth}} /'`
@@ -78,10 +96,13 @@ mfwrap_epilogue=`echo "$specs" | sed '1,/^\*mfwrap:$/d'`
 mfwrap=`echo "$mfwrap_epilogue" | sed '1q'`
 mfwrap_epilogue=`echo "$mfwrap_epilogue" | sed -n '2,$p'`
 
-if ! echo "$mfwrap" | grep -Fq '%{fmudflapth: --wrap=pthread_create}'; then
-  echo "$0: error: cannot hack GCC spec file" >&2
+if echo "$mfwrap" | grep -Fq '%{fmudflapth: --wrap=pthread_create}'; then
+  :
+else
+  echo "$0: error: cannot hack GCC spec file" 1>&2
   exit 1
 fi
+
 mfwrap=`echo "$mfwrap" \
           | sed 's/%{fmudflapth: --wrap=pthread_create}/%{fmudflap:%{pthread: --wrap=pthread_create}} %{fmudflapth: --wrap=pthread_create}/'`
 specs=`echo "$mfwrap_prologue
@@ -94,14 +115,20 @@ link_command_epilogue=`echo "$specs" | sed '1,/^\*link_command:$/d'`
 link_command=`echo "$link_command_epilogue" | sed '1q'`
 link_command_epilogue=`echo "$link_command_epilogue" | sed -n '2,$p'`
 
-if ! echo "$link_command" | grep -Fq ' %(linker) '; then
-  echo "$0: error: cannot hack GCC spec file" >&2
+if echo "$link_command" | grep -Fq ' %(linker) '; then
+  :
+else
+  echo "$0: error: cannot hack GCC spec file" 1>&2
   exit 1
 fi
-if ! echo "$link_command" | grep -Fq ' %o '; then
-  echo "$0: error: cannot hack GCC spec file" >&2
+
+if echo "$link_command" | grep -Fq ' %o '; then
+  :
+else
+  echo "$0: error: cannot hack GCC spec file" 1>&2
   exit 1
 fi
+
 link_command=`echo "$link_command" \
                 | sed 's/ %o / %o %{fmudflap:%{!fmudflapth:%{pthread:-lmudflapth;:-lmudflap}}} %{fmudflapth:-lmudflapth} /'`
 specs=`echo "$link_command_prologue
