Added streaming output.

diff --git a/gmp/jamfile b/gmp/jamfile
--- a/gmp/jamfile
+++ b/gmp/jamfile
@@ -90,7 +90,11 @@ actions download-gmp
 {
   rm -f "$(<)" || exit $?
   if [ ! -f "$(TARBALL_GZ)" -a ! -f "$(TARBALL_BZ2)" ]; then
-    ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' )
+    if [ -n "$(STREAM)" ]; then
+      ( cd "$(TARBALL_BZ2:D)" && wget -- '$(URL)' >> "$(STREAM)" 2>&1 )
+    else
+      ( cd "$(TARBALL_BZ2:D)" && wget --quiet -- '$(URL)' )
+    fi
     if [ $? -ne 0 ]; then
       echo "ERROR: failed to download GMP tarball." 1>&2
       /bin/echo -n "ERROR: failed to download GMP tarball." | $(AWACS)
@@ -146,12 +150,21 @@ actions expand-gmp
   ( cd "$(INTRO_ROOT_DIR)" && rm -rf gmp-$(VERSION) ) || exit $?
   [ -e "$(INTRO_ROOT_DIR)/gmp-$(VERSION)" ] && exit 1
   if [ -f "$(TARBALL_GZ)" ]; then
-    tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" || { echo "ERROR: failed to expand GMP tarball." 1>&2; exit 1; }
+    if [ -n "$(STREAM)" ]; then
+      tar xzvf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)" >> "$(STREAM)" 2>&1
+    else
+      tar xzf "$(TARBALL_GZ)" -C "$(TARBALL_GZ:D)"
+    fi
   elif [ -f "$(TARBALL_BZ2)" ]; then
-    tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" || { echo "ERROR: failed to expand GMP tarball." 1>&2; exit 1; }
+    if [ -n "$(STREAM)" ]; then
+      tar xjvf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)" >> "$(STREAM)" 2>&1
+    else
+      tar xjf "$(TARBALL_BZ2)" -C "$(TARBALL_BZ2:D)"
+    fi
   else
     exit 1
   fi
+  [ $? -ne 0 ] && { echo "ERROR: failed to expand GMP tarball." 1>&2; exit 1; }
   [ -d "$(DEST_DIR)" ] || exit $?
   [ -x "$(DEST_DIR)/configure" ] || exit $?
   [ -e "$(<)" ] && exit 1
@@ -237,26 +250,42 @@ actions make-gmp
   [ `"$(CONFIGURE:D)/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit $?
   { mkdir -p "$(<:D)/build" && ( cd "$(<:D)/build" && rm -rf * ); } || exit $?
   $(SET_RUN_VARS)
-  ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
+  if [ -n "$(STREAM)" ]; then
+    ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) >> "$(STREAM)" 2>&1 )
+  else
+    ( cd "$(<:D)/build" && "$(CONFIGURE)" $(OPTIONS) )
+  fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'configure' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
     /bin/echo -n "ERROR: failed to 'configure' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
   [ -f "$(<:D)/build/Makefile" ] || exit $?
-  ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
+  if [ -n "$(STREAM)" ]; then
+    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+  else
+    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) )
+  fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'make' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
     /bin/echo -n "ERROR: failed to 'make' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
+  if [ -n "$(STREAM)" ]; then
+    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check >> "$(STREAM)" 2>&1 )
+  else
+    ( cd "$(<:D)/build" && make --jobs=$(CONCURRENCY) check )
+  fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'make check' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
     /bin/echo -n "ERROR: failed to 'make check' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
     exit 1
   fi
-  ( cd "$(<:D)/build" && make install )
+  if [ -n "$(STREAM)" ]; then
+    ( cd "$(<:D)/build" && make install >> "$(STREAM)" 2>&1 )
+  else
+    ( cd "$(<:D)/build" && make install )
+  fi
   if [ $? -ne 0 ]; then
     echo "ERROR: failed to 'make install' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." 1>&2
     /bin/echo -n "ERROR: failed to 'make install' GMP $(VERSION) ($(TRIPLET)-gcc-$(GCC_RAW))." | $(AWACS)
