Added multi-target/multi-binary support for Open MPI.

diff --git a/openmpi/jamfile b/openmpi/jamfile
--- a/openmpi/jamfile
+++ b/openmpi/jamfile
@@ -6,7 +6,19 @@ import feature ;
 import make ;
 import path ;
 import regex ;
-import "$(INTRO_ROOT_DIR)/compilers" ;
+import "$(INTRO_ROOT_DIR)/compilers"
+  : is-gcc
+    is-clang
+    get-compiler-description
+    get-compiler-prefix
+    get-libdir
+    get-includedir
+    get-cc
+    get-cflags
+    get-cxx
+    get-cxxflags
+    get-environment-commands
+  ;
 
 
 rule assert-specified ( feature : properties * )
@@ -42,11 +54,11 @@ rule compiler-dep-req ( properties * )
   local multitarget = [ feature.get-values <multitarget-hidden> : $(properties) ] ;
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
   local result ;
-  if [ "$(INTRO_ROOT_DIR)/compilers.is-gcc" $(compiler) ]
+  if [ is-gcc $(compiler) ]
   {
     result = <source>../gcc//install/<multitarget>$(multitarget)/<multitarget-hidden>unspecified ;
   }
-  else if [ "$(INTRO_ROOT_DIR)/compilers.is-clang" $(compiler) ]
+  else if [ is-clang $(compiler) ]
   {
     result = <source>../clang//install ;
   }
@@ -88,19 +100,19 @@ rule download ( targets * : sources * : properties * )
 }
 actions download
 {
-  rm -rf "$(<)" || exit 1
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(<:D)" && wget -- '$(URL)' >> "$(STREAM)" 2>&1 )
+  rm -rf '$(<)' || exit 1
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(<:D)' && wget -- '$(URL)' >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(<:D)" && wget --quiet -- '$(URL)' )
+    ( cd '$(<:D)' && wget --quiet -- '$(URL)' )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to download Open MPI $(VERSION) tarball." 1>&2
-    echo -n "ERROR: failed to download Open MPI $(VERSION) tarball." | $(AWACS)
-    rm -rf "$(<)"
+    echo    'ERROR: failed to download Open MPI $(VERSION) tarball.' 1>&2
+    echo -n 'ERROR: failed to download Open MPI $(VERSION) tarball.' | $(AWACS)
+    rm -rf '$(<)'
     exit 1
   fi
-  [ -f "$(<)" ] || exit 1
+  [ -f '$(<)' ] || exit 1
   exit 0
 }
 
@@ -145,25 +157,25 @@ rule expand ( targets * : sources * : properties * )
 }
 actions expand
 {
-  rm -rf "$(<:D)" || exit 1
-  [ -f "$(>)" ] || exit 1
-  if [ -n "$(STREAM)" ]; then
-    tar xjvf "$(>)" --directory="$(INTRO_ROOT_DIR)" >> "$(STREAM)" 2>&1
+  rm -rf '$(<:D)' || exit 1
+  [ -f '$(>)' ] || exit 1
+  if [ -n '$(STREAM)' ]; then
+    tar xjvf '$(>)' --directory='$(INTRO_ROOT_DIR)' >> '$(STREAM)' 2>&1
   else
-    tar xjf "$(>)" --directory="$(INTRO_ROOT_DIR)"
+    tar xjf '$(>)' --directory='$(INTRO_ROOT_DIR)'
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to expand Open MPI $(VERSION) tarball." 1>&2
-    echo -n "ERROR: failed to expand Open MPI $(VERSION) tarball." | $(AWACS)
-    rm -rf "$(<:D)"
+    echo    'ERROR: failed to expand Open MPI $(VERSION) tarball.' 1>&2
+    echo -n 'ERROR: failed to expand Open MPI $(VERSION) tarball.' | $(AWACS)
+    rm -rf '$(<:D)'
     exit 1
   fi
   # If the timestamp of the tarball's contents is restored, the modification
   # time of the source directory could be older than the one of the tarball.
   # Such behavior is not desirable because the decompression always happens.
   # Therefore, `touch' is required.
-  touch --no-create "$(<)"
-  [ -f "$(<)" ] || exit 1
+  touch --no-create '$(<)'
+  [ -f '$(<)' ] || exit 1
   exit 0
 }
 
@@ -190,17 +202,19 @@ explicit srcdir ;
 
 
 
-for local compiler in $(COMPILERS)
+rule location-conditional ( properties * )
 {
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  make "$(compiler-prefix)/include/mpi.h"
-    : compiler-dep/<mpi-backend>unspecified/<openmpi>unspecified
-      srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified/<mpi-backend>unspecified
-    : @make-install
-    ;
-  explicit "$(compiler-prefix)/include/mpi.h" ;
+  local includedir = [ get-includedir "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  return <location>"$(includedir)" ;
 }
+
+make mpi.h
+  : compiler-dep/<mpi-backend>unspecified/<openmpi>unspecified
+    srcdir/<triplet>unspecified/<multitarget-hidden>unspecified/<compiler>unspecified/<mpi-backend>unspecified
+  : @make-install
+  : <conditional>@location-conditional
+  ;
+explicit mpi.h ;
 
 rule make-install ( targets * : sources * : properties * )
 {
@@ -215,7 +229,7 @@ rule make-install ( targets * : sources * : properties * )
   assert-unspecified <openmpi-hidden>     : $(properties) ;
 
   local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local compiler-description = [ "$(INTRO_ROOT_DIR)/compilers.get-compiler-description" $(compiler) ] ;
+  local compiler-description = [ get-compiler-description $(compiler) ] ;
   COMPILER_DESCRIPTION on $(targets) = "$(compiler-description)" ;
 
   local version = [ feature.get-values <openmpi> : $(properties) ] ;
@@ -230,126 +244,123 @@ rule make-install ( targets * : sources * : properties * )
 
   OPTIONS on $(targets) = ;
 
-  # Set the '--build' and '--host' options for the 'configure' script.
+  # Set `--prefix' option for `configure' script.
+  local compiler-prefix = [ get-compiler-prefix "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  local compiler-prefix-native = [ path.native "$(compiler-prefix)" ] ;
+  OPTIONS on $(targets) += "--prefix='$(compiler-prefix-native)'" ;
+
+  # Set `--build' `--host' options for `configure' script.
   local triplet = [ feature.get-values <triplet> : $(properties) ] ;
   TRIPLET on $(targets) = $(triplet) ;
   OPTIONS on $(targets) += --build=$(triplet) ;
   OPTIONS on $(targets) += --host=$(triplet) ;
 
-  # Set the '--prefix' option for the 'configure' script.
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  OPTIONS on $(targets) += "--prefix=\"$(compiler-prefix)\"" ;
-
   OPTIONS on $(targets) += --disable-mpi-f77 ;
   OPTIONS on $(targets) += --disable-mpi-f90 ;
   OPTIONS on $(targets) += --disable-mpi-cxx ;
 
-  OPTIONS on $(targets) += --enable-static ;
   OPTIONS on $(targets) += --enable-shared ;
+  OPTIONS on $(targets) += --enable-static ;
 
-  OPTIONS on $(targets) += --enable-mpi-threads ;
+  OPTIONS on $(targets) += --enable-mpi-thread-multiple ;
 
   # See https://github.com/Cryolite/intro/issues/12
-  if [ "$(INTRO_ROOT_DIR)/compilers.is-clang" $(compiler) ]
+  if [ is-clang $(compiler) ]
   {
     OPTIONS on $(targets) += --disable-visibility ;
   }
 
-  local cc = [ "$(INTRO_ROOT_DIR)/compilers.cc" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
-  OPTIONS on $(targets) += "CC=\"$(cc)\"" ;
+  local cc = [ get-cc "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  cc = [ path.native "$(cc)" ] ;
+  OPTIONS on $(targets) += "CC='$(cc)'" ;
 
-  local cxx = [ "$(INTRO_ROOT_DIR)/compilers.cxx" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
-  OPTIONS on $(targets) += "CXX=\"$(cxx)\"" ;
+  #local cflags = [ get-cflags $(properties) ] ;
+  #if $(cflags)
+  #{
+  #  OPTIONS on $(targets) += "CFLAGS='$(cflags)'" ;
+  #}
 
-  PREPEND_SHARED_LIBRARY_PATH_VARIABLE_COMMAND on $(targets) = [ "$(INTRO_ROOT_DIR)/compilers.prepend-shared-library-path-variable-command" "$(PREFIX)" : $(compiler) : $(GCC_FOR_CLANG) ] ;
+  local cxx = [ get-cxx "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  cxx = [ path.native "$(cxx)" ] ;
+  OPTIONS on $(targets) += "CXX='$(cxx)'" ;
+
+  #local cxxflags = [ get-cxxflags $(properties) ] ;
+  #if $(cxxflags)
+  #{
+  #  OPTIONS on $(targets) += "CXXFLAGS='$(cxxflags)'" ;
+  #}
+
+  local environment-commands = [ get-environment-commands "$(PREFIX)" : $(properties) : $(GCC_FOR_CLANG) ] ;
+  ENVIRONMENT_COMMANDS on $(targets) = "$(environment-commands)" ;
 }
 actions make-install
 {
-  [ -x "$(SRCDIR)/configure" ] || exit 1
-  [ -x "$(SRCDIR)/config/config.sub" ] || exit 1
-  [ `"$(SRCDIR)/config/config.sub" $(TRIPLET)` = $(TRIPLET) ] || exit 1
+  [ -x '$(SRCDIR)/configure' ] || exit 1
+  [ -x '$(SRCDIR)/config/config.sub' ] || exit 1
+  [ `'$(SRCDIR)/config/config.sub' $(TRIPLET)` = $(TRIPLET) ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
-  { mkdir -p "$(OBJDIR)" && ( cd "$(OBJDIR)" && rm -rf * ); } || exit 1
+  { mkdir -p '$(OBJDIR)' && ( cd '$(OBJDIR)' && rm -rf * ); } || exit 1
 
-  $(PREPEND_SHARED_LIBRARY_PATH_VARIABLE_COMMAND)
+  $(ENVIRONMENT_COMMANDS)
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && "$(SRCDIR)/configure" $(OPTIONS) >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && "$(SRCDIR)/configure" $(OPTIONS) )
+    ( cd '$(OBJDIR)' && '$(SRCDIR)/configure' $(OPTIONS) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'configure' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'configure' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`configure' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to \`configure' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
 
   # Check the creation of `Makefile'.
-  [ -f "$(OBJDIR)/Makefile" ] || exit 1
+  [ -f '$(OBJDIR)/Makefile' ] || exit 1
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) )
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'make' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to \`make' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) check >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && make --jobs=$(CONCURRENCY) check )
+    ( cd '$(OBJDIR)' && make --jobs=$(CONCURRENCY) check )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make check' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'make check' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make check' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to \`make check' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
 
-  if [ -n "$(STREAM)" ]; then
-    ( cd "$(OBJDIR)" && make install >> "$(STREAM)" 2>&1 )
+  if [ -n '$(STREAM)' ]; then
+    ( cd '$(OBJDIR)' && make install >> '$(STREAM)' 2>&1 )
   else
-    ( cd "$(OBJDIR)" && make install )
+    ( cd '$(OBJDIR)' && make install )
   fi
   if [ $? -ne 0 ]; then
-    echo "ERROR: failed to 'make install' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
-    echo -n "ERROR: failed to 'make install' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
+    echo    "ERROR: failed to \`make install' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." 1>&2
+    echo -n "ERROR: failed to \`make install' Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET))." | $(AWACS)
     exit 1
   fi
 
-  [ -f "$(<)" ] || exit 1
+  [ -f '$(<)' ] || exit 1
 
   # Clean up objdir `$(OBJDIR)'.
-  rm -rf "$(OBJDIR)" || exit 1
+  rm -rf '$(OBJDIR)' || exit 1
 
-  echo -n "Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built." | $(AWACS)
+  echo -n 'Open MPI $(VERSION) ($(COMPILER_DESCRIPTION), $(TRIPLET)) was successfully built.' | $(AWACS)
   exit 0
 }
 
 
 
-rule install-req ( properties * )
-{
-  assert-specified   <triplet>            : $(properties) ;
-  assert-unspecified <multitarget>        : $(properties) ;
-  assert-specified   <multitarget-hidden> : $(properties) ;
-  assert-specified   <compiler>           : $(properties) ;
-  assert-unspecified <compiler-hidden>    : $(properties) ;
-  assert-specified   <mpi-backend>        : $(properties) ;
-  assert-unspecified <mpi-backend-hidden> : $(properties) ;
-  assert-specified   <openmpi>            : $(properties) ;
-  assert-unspecified <openmpi-hidden>     : $(properties) ;
-
-  local compiler = [ feature.get-values <compiler> : $(properties) ] ;
-  local prefix-leaf = [ "$(INTRO_ROOT_DIR)/compilers.get-prefix-leaf" $(compiler) : $(GCC_FOR_CLANG) ] ;
-  local compiler-prefix = "$(PREFIX)/$(prefix-leaf)" ;
-  return <source>"$(compiler-prefix)/include/mpi.h" ;
-}
-
-alias install : : <conditional>@install-req ;
+alias install : mpi.h/<std>c++03/<variant>release/<ssp>off/<mudflap>off/<address-sanitizer>off/<libstdc++-debug-mode>off ;
 explicit install ;
